### ISSUE TITLE
I think the page's description doesn't updated from the previous version. 

### ISSUE THREAD

**Issue by hien0024** [MicrosoftDocs/sql-docs#1263]
Hello.
I think [this page](https://docs.microsoft.com/en-us/sql/ssdt/walkthrough-author-custom-static-code-analysis-rule-assembly?view=sql-server-2017) is have not updated from the previous version.

The page is a tutorial for SQL Server 2017 and Visual Studio 2017 including SSDT, but it seems to be written for version 2013 or 2012.

For example, I think the following points are strange.
  1.In "Creating a Custom Code Analysis Rule for SQL Server", the page says "Click Browse and navigate to the C:\Program Files (x86)\MicrosoftSQL Server\120\SDK\Assemblies directory, select Microsoft.SqlServer.TransactSql.ScriptDom.dll, and the click OK.".
    But "Microsoft.SqlServer.TransactSql.ScriptDom.dll" doesn't exist in the directory. 
  2.There are examples of version 2013 and 2012 on the page but there is no example of version 2017.
  3.In "To Install the SampleRules Assembly", it says "When Visual Studio starts, it will identify any extensions in \Common7\IDE\Extensions\Microsoft\SQLDB\DAC\120\Extensions directory and subdirectories, and make them available for use.".
    But Visual Studio 2017 doesn't have the directory.
    
Let me apologize for my poor English.
Thank you.

**Comment by jzabroski** [comment]
@MightyPen I think the core issue here is that SQL Server and Visual Studio are not guaranteed to be released in lock-step, and there is no guarantee newer versions of Visual Studio will fully support working with older versions of SQL Server. For example, a project type for SQL Server 2012 might not exist in Visual Studio 2017.

**Comment by stevestein** [comment]
@hien0024 , @jzabroski Thanks for raising the issue here. Yes, this content has not yet been updated to match the latest versions of SSDT and Visual Studio.  The SSDT documentation is scheduled for a refresh sometime in 2019, but I can't commit to an actual date when this will happen.  An internal work item has been created to ensure this article is addressed at that time.  

If you need assistance, there's resources in the [Get Help section](https://docs.microsoft.com/en-us/sql/ssdt/download-sql-server-data-tools-ssdt?view=sql-server-2017#infotipmediainfo-tippng-get-help) that might point you in the right direction.

Thanks.

**Comment by hien0024** [comment]
@MightyPen , @jzabroski , @stevestein  Thank you for your courteous reply. I understood. I hope this content to be updated. I consult the site as you suggest.
Thank you.
