### ISSUE TITLE
Description of Merge function in "CLR User-Defined Aggregate - Invoking Functions" article

### ISSUE THREAD

**Issue by avchirkin** [MicrosoftDocs/sql-docs#1440]
Merge function of Example 1 looks like

```
public void Merge(Concatenate other)  
{  
      this.intermediateResult.Append(other.intermediateResult);  
}
```
, but Concatenate class has no public field (or property) with name "intermediateResult" - this field is private. May be, intermediateResult have to be a public property?

**Comment by MightyPen** [comment]
@avchirkin Hello Avchirkin, it is helpful for us to have a link to the article that the Issue is about.  I suspect this Issue 1440 is about the following article:
.
docs/relational-databases\clr-integration-database-objects-user-defined-functions\clr-user-defined-aggregate-invoking-functions.md
.
https://docs.microsoft.com/en-us/sql/relational-databases/clr-integration-database-objects-user-defined-functions/clr-user-defined-aggregate-invoking-functions?view=sql-server-2017
.
@rothja Hi Jason, you are the owner of this article.  Can you please process this Issue 1440.  (I took a quick look to see if I could handle this for you, but I could not even find the Concatenate class, not in any of the USING namespaces of the C# example.)

**Comment by avchirkin** [comment]
> @avchirkin Hello Avchirkin, it is helpful for us to have a link to the article that the Issue is about. I suspect this Issue 1440 is about the following article:
> .
> docs/relational-databases\clr-integration-database-objects-user-defined-functions\clr-user-defined-aggregate-invoking-functions.md
> .
> https://docs.microsoft.com/en-us/sql/relational-databases/clr-integration-database-objects-user-defined-functions/clr-user-defined-aggregate-invoking-functions?view=sql-server-2017
> .
> @rothja Hi Jason, you are the owner of this article. Can you please process this Issue 1440. (I took a quick look to see if I could handle this for you, but I could not even find the Concatenate class, not in any of the USING namespaces of the C# example.)

Yes, thanks a lot. I mean exactly the same article. Example 1, C# and VB, Merge method.

**Comment by avchirkin** [comment]
Thanks for the feedback. Glad to help!

**Comment by rothja** [comment]
@avchirkin Hi. I looked closer at the code example and see that we're in the Concatenate class and that the merge method takes another Concatenate object (other) and then tries to access the intermediateResult member which is private. It does seem like one solution would be to make that member public to resolve any errors. Did you run this code and get an error at the call to intermediateResult in the Merge method? Did you try to make the member public to resolve the problem? Thank you!

**Comment by avchirkin** [comment]
Thanks for feedback. There is no problem to make some fixes in this code to make it correct, I just want see the fixed version of article for everyone :) I found that invocation watching on code snippet, not after copy-paste to my solution, and just warned about potential problem.

**Comment by rothja** [comment]
@avchirkin Sorry for the delay. I going to make the Concatenate member public to resolve any potential issues now. I'm not able to test this immediately, but I assume that it will not be a problem as this is going from more restrictive to less restrictive. Thank you.
