### ISSUE TITLE
Login failed. The login is from an untrusted domain and cannot be used with Integrated authentication

### ISSUE THREAD

**Issue by eliassal** [MicrosoftDocs/sql-docs#1462]
I followed all instructions and I was able to add mydomain\mylogin to sql, in the step before last step, when I try to login through SSMS from my laptop, I get the following

TITLE: Connect to Server
------------------------------

Cannot connect to ubuntu17Sql.SALAM.NET.

------------------------------
ADDITIONAL INFORMATION:

Login failed. The login is from an untrusted domain and cannot be used with Integrated authentication. (Microsoft SQL Server, Error: 18452)

For help, click: http://go.microsoft.com/fwlink?ProdName=Microsoft%20SQL%20Server&EvtSrc=MSSQLServer&EvtID=18452&LinkId=20476

Thanks for your help

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffd6e9f1-17ab-7aea-818e-d2ab416e3891
* Version Independent ID: 3b789cdc-ca6c-4aca-ae01-b094926dbd7c
* Content: [Tutorial: Active Directory authentication for SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-active-directory-authentication?view=sql-server-2017)
* Content Source: [docs/linux/sql-server-linux-active-directory-authentication.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-active-directory-authentication.md)
* Product: **sql**
* GitHub Login: @meet-bhagdev
* Microsoft Alias: **meetb**

**Comment by MightyPen** [comment]
@rothja Jason, I am unsure whether this Issue 1462 indicates a Documentation bug, or whether it is more of a Support request issue?  After examining the article, I surmise that this Issue is probably focused on the following # particular H2 section, which contains two steps:
.
"Create AD-based logins in Transact-SQL"
.
https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-active-directory-authentication?view=sql-server-2017#createsqllogins 
.
Can you please work with the article owner== @meet-bhagdev to process this Issue as you two see fit.  Thank you.
CC: @eliassal

**Comment by rothja** [comment]
@eliassal Thanks for contacting us. I think Gene is right that this might need to be handled by a Microsoft Support case to troubleshoot fully. However, let me ask some subject matter experts here to see if they have any suggestions before we do that. Thank you for your patience on this.

**Comment by rothja** [comment]
@eliassal Thanks, again, for the question. I checked internally, and this is a generic error. It is really impossible to tell just from this error what might be happening. We hope to improve the error messages in the future to help with this. Unfortunately, I think your best option at this point is to contact Microsoft Technical Support to open a case and have them troubleshoot the steps with you. I apologize that the article did not get you up and running. If you *do* find that the article had some incorrect information that led to your problem, please circle back to me in this issue for us to investigate. Thank you!

**Comment by pszafer** [comment]
I have similar problem as author and logs are useless for this situation.
My OS is CentOS 7.
I can cross-login from linux joined domain with sssd via sqlcmd but cannot login from Windows machines.

I know that this issue is more about docs, but for me it is not clear if you shouldn't be using 
```
setspn -A MSSQLSvc/**<fully qualified domain name of host machine>**:**<tcp port>** DOMAIN\mssql
```
instead of
```
setspn -A MSSQLSvc/**<fully qualified domain name of host machine>**:**<tcp port>** mssql
```
other docs are pretty clear to use DOMAIN\user.
You could add desired output of commands as well.
I run setspn -A and spn is added to computer account. Don't know if it suppose to be like this or should it be added to user account DOMAIN\mssql.

Next thing, you run mssql-server service as local user mssql. Why not CONTOSO.COM\mssql?
Anyway, user of name mssql is mixed up a lot in this docs and if somebody has troubles running it is hard to find if it is configuration of server bug, domain config issue etc.

@rothja about Microsoft Technical Support, you mean to try contact here https://support.microsoft.com, yes? or do you have some other github issues?

**Comment by eliassal** [comment]
pszafer, this is becoming more and more confusing, every réponse in this thread adds a new complexity and confusion. Isn't there around an MS expert who can respond and let us know if it is valid or not? I can see a lot of MVPs, experts hanging around, doing webinars, conferences on "SQL on linux.......", even I came across a thread "SQL on linux setup best practices" where I also posted my question. 

@All, I followed instructions in the doc, so can you please say in 1 single word "Yes or Non" is it possible to connect using domain account, that is what I am looking for in order not to lose more time and receive unuseful responses

**Comment by pszafer** [comment]
@eliassal one thing I know. It is possible to connect using domain account. I have one installation which is working properly on other domain.
But if something is wrong, logs output are pointless... because logs in some way telling you that your joining steps were wrong, so you repeat those steps every time and you are confused, what is hostname of machine, what is local username of linux machine, what is domain account of mssql and in the end what is user@CONTOSO.COM ...

The best would be to create ansible/puppet role to join domain proper way for mssql-server.
