### ISSUE TITLE
Add PowerShell command to SQL Firewall doc

### ISSUE THREAD

**Issue by jzabroski** [MicrosoftDocs/sql-docs#1468]
`netsh.exe` is not portable to Linux, and so it would be ideal if we used a platform-agnostic tutorial.  Ideally, the firewall commands that ship as part of PowerShell would be portable to Linux - I'm actually not sure if they are since I am venturing into new territory myself here.

https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/install/configure-the-windows-firewall-to-allow-sql-server-access.md

This documentation is a forward from the SQL Server 2017 Setup executable, which generates the following message:

> ---------------------------
> Rule Check Result
> ---------------------------
> Rule "Windows Firewall" generated a warning.
> 
> The Windows Firewall is enabled. Make sure the appropriate ports are open to enable remote access. See the rules documentation at https://go.microsoft.com/fwlink/?LinkId=94001 for information about ports to open for each feature.
> ---------------------------
> OK   
> ---------------------------

LinkId=94001 forwards to https://docs.microsoft.com/en-us/sql/sql-server/install/configure-the-windows-firewall-to-allow-sql-server-access?view=sql-server-2017

**Comment by MightyPen** [comment]
@MashaMSFT Masha, as you are the owner of.....
docs/sql-server/install/configure-the-windows-firewall-to-allow-sql-server-access.md
.....would you please process this Issue 1468.
.
CC: @jzabroski

**Comment by MashaMSFT** [comment]
Hi @jzabroski , thanks for your suggestion! I've created an item to research this within our ticketing system: User Story [1418832](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1418832): SQL Setup | Add powershell option to opening firewall. Your idea definitely has merit, but I'll need to investigate the feasibility of using powershell or another tool that works with Linux. Since we're now tracking this internally, I'll proceed with closing out this Issue. However, please feel free to contact us if you have any additional information. Thanks again!

**Comment by jzabroski** [comment]
Thank you.

**Comment by MashaMSFT** [comment]
Hi @jzabroski , I've yet to find any cmdlet that will work on every distro of Linux. As such, I just added a note to the existing documentation pointing them to two different examples of opening the firewall in the linux doc set.  Thanks again for bringing this to our attention!

**Comment by MightyPen** [comment]
DevOps = 1418832 was marked as Completed on 2019/01/17.
Therefore, I am now finalizing the label for this Issue 1468, from -41- to -42-.
