### ISSUE TITLE
Update documentation to reflect that installation of mssql-server-extensibility package is not possible on a MSSQL Docker container

### ISSUE THREAD

**Issue by amanjeetsingh** [MicrosoftDocs/sql-docs#1488]
Hi 

I have been unable to install mssql-server-extensibility-java on MSSQL Docker container. Docker image details are as follows. 

mcr.microsoft.com/mssql/server               2019-CTP2.2-ubuntu 

As per documentation, one can install the package on Ubuntu by running the command 
sudo apt-get install mssql-server-extensibility-java

When I run the command, it fails with the following error:

`root@56dc52025056:/var/log# apt-get install -y mssql-server-extensibility-java
Reading package lists... Done
Building dependency tree
Reading state information... Done
mssql-server-extensibility-java is already the newest version (15.0.1200.24-2).
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
2 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up mssql-server-extensibility (15.0.1200.24-2) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline
Configuration file /lib/systemd/system/mssql-launchpadd.service is marked executable. Please remove executable permission bits. Proceeding anyway.
Failed to connect to bus: No such file or directory
dpkg: error processing package mssql-server-extensibility (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of mssql-server-extensibility-java:
 mssql-server-extensibility-java depends on mssql-server-extensibility; however:
  Package mssql-server-extensibility is not configured yet.

dpkg: error processing package mssql-server-extensibility-java (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 mssql-server-extensibility
 mssql-server-extensibility-java
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@56dc52025056:/var/log# echo $?
100
root@56dc52025056:/var/log#`

Seems like the installation fails because systemctl is not available. Upon checking the processes that are running on the container itself, we can see that PID 1 belongs to sqlservr process and not systemd. 

`root@56dc52025056:/var/log# ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0  2018 pts/0    00:00:01 /opt/mssql/bin/sqlservr
root         8     1  1  2018 pts/0    00:26:34 /opt/mssql/bin/sqlservr
root      8868     0  0 13:34 pts/1    00:00:00 bash
root      8979  8868  0 13:39 pts/1    00:00:00 ps -ef 
`

Can you please confirm that this is the issue that is preventing me from installing package on MSSQL container? 

Appreciate your help.

**Comment by MightyPen** [comment]
@amanjeetsingh Hi Amanjeet, You say "As per documentation": Can you please provide us with an exact link to the specific documentation article you have in mind, on
https://docs.microsoft.com/sql/<ARTICLE PATH FILENAME\>
.
If you can provide the link within the next several business days, remember to @ mention me (@ + MightyPen, as one 10 character string with no spaces), so that I receive a notification.
.
Without such a link, we who monitor this GitHub Issues webpage for repository 'sql-docs' (and 'sql-docs-pr') are unable to process this Issue 1488.
.
HELPFUL LINKS:

- [All the ways to get help](https://docs.microsoft.com/sql/sql-server/sql-server-get-help)
- [UserVoice - Suggestion to improve SQL Server?](https://feedback.azure.com/forums/908035-sql-server)
- [Setup and Upgrade -  MSDN Forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=sqlsetupandupgrade&filter=alltypes&sort=lastpostdesc)
- [SQL Server Data Tools - MSDN forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=ssdt&filter=alltypes&sort=lastpostdesc)
- [Transact-SQL - MSDN forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=transactsql)
- [SQL Server Security -  MSDN Forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=sqlsecurity&filter=alltypes&sort=lastpostdesc)
- [DBA Stack Exchange (tag sql-server) - ask SQL Server questions](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow (tag sql-server) - also has some answers about SQL development](https://stackoverflow.com/questions/tagged/sql-server) 
- [Reddit - general discussion about SQL Server](https://www.reddit.com/r/SQLServer/)
- [Microsoft SQL Server License Terms and Information](https://www.microsoft.com/download/details.aspx?id=39299)
- [Support options for business users](https://support.microsoft.com/gp/support-options-for-business)
- [Contact Microsoft](https://support.microsoft.com/gp/contactus81?Audience=Commercial)
- [Edit SQL Docs](https://aka.ms/editsqldocs)
- [SQL Docs Feedback](https://aka.ms/sqldocsfeedback)
- [SQL Docs Survey](https://aka.ms/sqldocsurvey)

**Comment by amanjeetsingh** [comment]
@MightyPen , my apologies for not mentioning the link. The documentation that I am referring to is https://docs.microsoft.com/en-us/sql/advanced-analytics/java/extension-java?view=sqlallproducts-allversions. 

The documentation talks about installing Java extensibility package on various variants of Linux. There are no errors in the documentation, and it works fine for Linux running on a standard VM. My question is that is there a limitation around installing/running Java extensibility package on Linux running inside a Docker container? If it's a known limitation, should we then update the documentation to reflect the same? 

Thanks

**Comment by MightyPen** [comment]
@HeidiSteen Hi Heidi,  As you are the owner of article 'advanced-analytics/java/extension-java.md',.....
Can you please assess this Issue 1488 (repo 'sql-docs').  Then update this Issue by entering a new Comment.  Remember to @ mention me so I am notified that an update has occurred.
If your assessment is that a documentation action should be implemented, please include in your Comment the ID number for the new PR, or the ID for a DevOps (MsEng) item to track the TODO work item.  Or in some cases, write that you will create the PR within a week or two, and add an additional Comment then.
Thanks.
GeneMi
CC: @amanjeetsingh

**Comment by HeidiSteen** [comment]
@amanjeetsingh I've asked the engineering team for assistance. @MightyPen we are waiting for their response.

**Comment by HeidiSteen** [comment]
@amanjeetsingh @MightyPen  I just learned there is a known issue related to docker installs and I've been asked to remove "Docker support" until a fix is published.  My apologies for the poor customer experience.  If you can try again in February, when the next CTP is released, it should work as expected.

**Comment by MightyPen** [comment]
@amanjeetsingh With Heidi's diagnosis given 16 minutes ago, this Issue 1488 has achieved its purpose of communication.  I will set the label to Fixed, in reference to the communication success.  Thank you for bringing this concern to our attention.  We can now Close this Issue.  However, if further communication on this Issue is needed, the @ mention technique remains available even after an Issue is closed.  Thanks again.
CC: @HeidiSteen

**Comment by MightyPen** [comment]
@HeidiSteen Hi Heidi, I am hereby testing my claim that @ notifications still work even after the Issue is Closed.  IF you do receive an email notification for this from the GitHub system, can you please simply Forward the notification email to me?  Thanks.  GeneMi
