### ISSUE TITLE
SSIS Enhanced Error Description Script - update

### ISSUE THREAD

**Issue by saaabbir** [MicrosoftDocs/sql-docs#1491]
Hi there,

I though I should share this. In my SSIS package there was a pk/fk constraint violation and I was getting ErrorColumn value as 0 (Zero). In that case the enhancement script doesn't work. So I made the below changes

```
public override void Input0_ProcessInputRow(Input0Buffer Row)
    {
        Row.ErrorDescription = this.ComponentMetaData.GetErrorDescription(Row.ErrorCode);

        var componentMetaData130 = this.ComponentMetaData as IDTSComponentMetaData130;
        if (componentMetaData130 != null)
        {
            if (Row.ErrorColumn == 0) //Checking if the ErrorColumn value is zero
            {
                Row.ColumnName = "Entire Row. Check PK FK constraints"; //Hardcoded error message
            }
            else
            {
                Row.ColumnName = componentMetaData130.GetIdentificationStringByID(Row.ErrorColumn);
            }
        }
    }
```

I tried to find out if there are any other unusual ErrorColumn value but no luck. Someone said in one of the forums that they got "-1" but again I couldn't find anything on the internet.

If you could incorporate the changes in the below link, I believe that will help loads of people from losing hair.

https://docs.microsoft.com/en-us/sql/integration-services/extending-packages-scripting-data-flow-script-component-examples/enhancing-an-error-output-with-the-script-component?view=sql-server-2017

**Comment by MightyPen** [comment]
PR 8659 fix for this is now merged into master, in internal private repo 'sql-docs-pr'.
.
@saaabbir Thank you very much for opening this Issue 1491, because the improvement you recommended will directly help other Microsoft customers.  I have implemented your suggestion in Pull Request 1491.  The fix should be visible by late Monday 2019/Jan/07 (give or take a day).
.
In the future, another option you can choose, instead of using the GitHub Issues UI, is to click the pencil icon on the Docs webpage to edit the article directly, which leads to the creation of "public repo PR".  Then our team can often merely click to approve the change for merge into master.  
.
Now that this Issue 1491 is fixed, I am closing this Issue.  Even when closed, the @ mention syntax can still be used to notify me if further communication about 1491 is needed.
Thanks again.
