### ISSUE TITLE
pcs support for sql linux docker

### ISSUE THREAD

**Issue by aqibsg** [MicrosoftDocs/sql-docs#1497]
Is there a way to start pcs daemon in the already existing sql server docker for linux?  I was trying to start a pacemaker cluster with with the docker image but got stuck when I reached the pcsd start service command.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b152444b-dfb8-5cbe-cf45-9830bd085a68
* Version Independent ID: 31719660-d4d0-7f63-efcc-846c822a63c2
* Content: [Get started with SQL Server containers on Docker (running SQL Server on Linux) - SQL Server](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-2017)
* Content Source: [docs/linux/quickstart-install-connect-docker.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-docker.md)
* Product: **sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by MightyPen** [comment]
@rothja Hi Jason,  Can you please process this Issue 1497, about PCS support for SQL Linux Docker.  I am unsure whether this Issue is a Documentation concern, or is a Support question that should perhaps be redirected (to User Voice or to where ever, per 'docs/includes/get-help-options.md').
CC: @aqibsg

**Comment by rothja** [comment]
@aqibsg Thanks for your question. I'm checking with others internally and will be back with you soon.

**Comment by vin-yu** [comment]
@aqibsg  - why do you want to start a pcs daemon inside of the SQL Server container image? Running multiple processes in a single container poses several challenges.

**Comment by aqibsg** [comment]
I was trying to make a high availability pacemaker cluster which uses pcs to allocate resources and setup cluster... so I need to start pcs inside the sql docker. Is there any way?
@vin-yu

**Comment by aqibsg** [comment]
@MightyPen , @rothja , @vin-yu 
Was there any way of suggestions for the above issue.

**Comment by rothja** [comment]
@aqibsg So sorry for the delay. I do not know of another approach. Let me check with one more person and I'll get back to you. If we can't find an answer, I'd suggest filing this as a feature request on user voice. I'll provide the link after I get back to you.

**Comment by rothja** [comment]
@aqibsg , One question: have you considered using Kubernetes rather than pcs for the HA solution in Docker? We have an article on this: https://docs.microsoft.com/en-us/sql/linux/tutorial-sql-server-containers-kubernetes?view=sql-server-2017. I checked internally and I don't think we've tested the pcs option or know whether it would be workable. Again, apologies for the long delay.

**Comment by rothja** [comment]
@aqibsg I don't think we have a good answer on this now other than to potentially try the kubernetes solution for this instead of pcs. But I know that might not be feasible for you. I have passed this request on to the product team as a feature request for future investigation and testing. I apologize that we don't have a better answer. Thanks for asking.
