### ISSUE TITLE
Table broken on page.

### ISSUE THREAD

**Issue by ElanHasson** [MicrosoftDocs/sql-docs#1554]
Table is broken near "The default value for REQUIRED_SYNCHRONIZED_SECONDARIES_TO_COMMIT is 0. The following table describes availability behavior." text

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a4e923b-784a-9931-d730-3031ff1b4049
* Version Independent ID: 310fbbc6-5116-c9b6-65a7-dd780a38a6df
* Content: [SQL Server Always On availability group deployment patterns - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-availability-group-ha?view=sql-server-2017#threeSynch)
* Content Source: [docs/linux/sql-server-linux-availability-group-ha.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-availability-group-ha.md)
* Product: **sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by MightyPen** [comment]
@ElanHasson Hello Elan, Good catch. We recently tightened the rules for our markdown source. Some of our documentation articles neglect to have a blank line immediately before and after each markdown table.  The table targeted by this Issue 1554 is one such instance of this problem.  It causes the Docs webpage to display raw markdown, instead of rendering an HTML table.
.
We are in the process of bulk fixing these via automation.  The automation run date has been delayed a bit because the preparation efforts have discovered some other problems in a subset of our tables, and those other problems must be fixed first.  This should all be fixed well before the end of January 2019.

**Comment by MightyPen** [comment]
@ElanHasson This Issue 1554 is now fixed, by our internal PR 8874.  (DevO 1429249)
Thank you for bringing this problem to our attention.  The same problem is now fixed for over 100 other tables too.
I am now Closing this Issue 1554.  However, the @ notification mechanism remains available regardless of whether an Issue is open or closed.

**Comment by ElanHasson** [comment]
Cool, thanks for the update :)

**Comment by MightyPen** [comment]
DevO = https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1429249
