### ISSUE TITLE
It would be nice to allow to display results in plain text

### ISSUE THREAD

**Issue by ArthurZ** [MicrosoftDocs/sql-docs#1559]
It would be nice to add an option to allow displaying results in text and not in grid. 
This is useful when one executes say `sp_helptext` to see a stored procedure body.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf7ad1cc-5659-1724-9ade-14859e2d469d
* Version Independent ID: 60d1da3a-3cbc-657c-e263-6fcefd918e23
* Content: [Use the Visual Studio Code mssql extension for SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-develop-use-vscode?view=sql-server-2017)
* Content Source: [docs/linux/sql-server-linux-develop-use-vscode.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-develop-use-vscode.md)
* Product: **sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by MightyPen** [comment]
@ArthurZ Hello Arthur,  Our GitHub Issues for documentation cannot provide the kind of response that this particular Issue seeks.  Documentation Issues are for things such as errors in the written documentation.
However, the following links are to resources that might be able to provide help in this case:

HELP LINKS:

- [All the ways to get help](https://docs.microsoft.com/sql/sql-server/sql-server-get-help)
- [UserVoice - Suggestion to improve SQL Server?](https://feedback.azure.com/forums/908035-sql-server)
- [Setup and Upgrade -  MSDN Forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=sqlsetupandupgrade&filter=alltypes&sort=lastpostdesc)
- [SQL Server Data Tools - MSDN forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=ssdt&filter=alltypes&sort=lastpostdesc)
- [Transact-SQL - MSDN forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=transactsql)
- [SQL Server Security -  MSDN Forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=sqlsecurity&filter=alltypes&sort=lastpostdesc)
- [DBA Stack Exchange (tag sql-server) - ask SQL Server questions](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow (tag sql-server) - also has some answers about SQL development](https://stackoverflow.com/questions/tagged/sql-server) 
- [Reddit - general discussion about SQL Server](https://www.reddit.com/r/SQLServer/)
- [Microsoft SQL Server License Terms and Information](https://www.microsoft.com/download/details.aspx?id=39299)
- [Support options for business users](https://support.microsoft.com/gp/support-options-for-business)
- [Contact Microsoft](https://support.microsoft.com/gp/contactus81?Audience=Commercial)
- [Edit SQL Docs](https://aka.ms/editsqldocs)
- [SQL Docs Feedback](https://aka.ms/sqldocsfeedback)
- [SQL Docs Survey](https://aka.ms/sqldocsurvey)

This Issue 1559 is now being closed.
However, if further communication about this Issue is needed, the @ notification syntax still works in closed Issues.
Thank you.
