### ISSUE TITLE
What is the difference between User installer and System Installer?

### ISSUE THREAD

**Issue by chanmmn** [MicrosoftDocs/sql-docs#1657]
What is the difference between User installer and System Installer? Can you explain it somewhere in the document?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 811ed1f4-1c78-aa1b-e752-307250ca8eb7
* Version Independent ID: f36629bf-b2e6-4993-7c77-32fa311ea942
* Content: [Download and install - Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/download?view=sql-server-2017)
* Content Source: [docs/azure-data-studio/download.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/download.md)
* Product: **sql**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by MightyPen** [comment]
@yualan HI Alan, the documentation article says a major difference between User vs System installers involves 'administrator privileges', but is there more we can say?:
_"User Installer (recommended)_ 
_The user installer is recommended because it does not require administrator privileges, which simplifies both installs and upgrades."._

For example, can we say that, after a User install, only that one user will have access to the installed tool? Is that a difference?  What else can be say?

Thanks. GeneMi  (SteveStein is on vacation).

**Comment by stevestein** [comment]
@chanmmn - Thanks for the suggestion. I updated the article with a little more info and link to the underlying Visual Studio Code explanation.

_The user installer is recommended because it does not require administrator privileges, which simplifies both installs and upgrades. The user installer does not require Administrator privileges as the location is under your user Local AppData (LOCALAPPDATA) folder. The user installer also provides a smoother background update experience. For more information, see [User setup for Windows](https://code.visualstudio.com/updates/v1_26#_user-setup-for-windows)._

**Comment by MaDnKount-r** [comment]
Ok. So let me get this straight. Sure the user install is more efficient for the install and upgrades. But there's no guarantee I'd be the only user with access to the download. Where as the system install perhaps has some sort of parameters that I can set into place. Am I getting this right?

**Comment by WilliamAntonRohm** [comment]
@MaDnKount-r -- thank you for your question.

@stevestein -- please look into this issue.

**Comment by WilliamAntonRohm** [comment]
@MaDnKount-r -- we are following up on this in your new Visual Studio issue MicrosoftDocs/visualstudio-docs/issues/5443.

**Comment by WilliamAntonRohm** [comment]
@MaDnKount-r -- thank you for your [followup question](https://github.com/MicrosoftDocs/sql-docs/issues/1657#issuecomment-640284273).  Apologies for the delay in responding.

@stevestein -- please look into this issue.

**Comment by stevestein** [comment]
@MaDnKount-r - Thanks for the feedback. I don't 100% understand the question. Can you clarify what the problem is you're encountering?


Thanks

**Comment by stevestein** [comment]
I'm going to go ahead and close this issue as there's nothing specific to add to the doc. Feel free to continue the conversation if needed.

Thanks!

**Comment by chr7** [comment]
I'm just asking myself what the difference is and would expect the document to answer the following: 
If the VSC system installer is used, what of VSC is shared among all users of the system and what is user specific (and stored in the user's home dir)? For example, can each user have his own plugins installed? Which settings are shared? Which are user specific?

**Comment by WilliamAntonRohm** [comment]
@chr7 -- thank you for your questions.  Please consider these resources:
- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/en-us/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server)
