### ISSUE TITLE
wget retrieval of .rpm file should also be included

### ISSUE THREAD

**Issue by PrometheusRising1** [MicrosoftDocs/sql-docs#1806]
Linux admins on a barebones restricted edge server will want to pull down the .rpm file with wget and add to a fileshare on a disconnected network.  Please include instructions on using wget and test to ensure that the links work for that purpose.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 811ed1f4-1c78-aa1b-e752-307250ca8eb7
* Version Independent ID: f36629bf-b2e6-4993-7c77-32fa311ea942
* Content: [Download and install - Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/download?view=sql-server-2017)
* Content Source: [docs/azure-data-studio/download.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/download.md)
* Product: **sql**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by PrometheusRising1** [comment]
Was able to find the direct link to the .rpm file by running wget -r once on the go.microsoft.com link.  There should be a way of listing direct copy links so that people can download directly.

**Comment by stevestein** [comment]
@PrometheusRising1  - Thanks for opening this issue/suggestion. This issue will be fixed in the documentation, although we cannot yet say when. We have created a new internal tracking number for this work item: 1504716. We are closing this Issue, and are letting the new item track this going forward. You will receive another notice after the internal item if completed. Thank you for submitting this Issue.

Looks like you already found it, but direct links are listed in the [Azure Data Studio repo](https://github.com/Microsoft/azuredatastudio/releases).

Thanks!
