### ISSUE TITLE
CREATE CREDENTIAL should mention gMSA

### ISSUE THREAD

**Issue by glatzert** [MicrosoftDocs/sql-docs#1819]
The Documentation on sql-docs/docs/t-sql/statements/create-credential-transact-sql.md 
should mention, if (and when yes, how) group Managed Service Accounts can be used here.

In fact all pages, which describe anything "credential" should mention, if groupManagedServiceAccounts are supported.

**Comment by MightyPen** [comment]
@VanMSFT Hi Van, Can you please process this Issue 1819.  Thanks.

**Comment by VanMSFT** [comment]
Hi @glatzert! Thank you for bringing up this issue! We will evaluate adding gMSA documentation, and will track this in our ticketing system: User Story [1487988](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1487988). Since we're now tracking this internally, I'll proceed with closing out this Issue. However, please feel free to contact us if you have any additional information. Thanks again!

**Comment by glatzert** [comment]
Thanks for taking care of it.
