### ISSUE TITLE
state_description is incorrect

### ISSUE THREAD

**Issue by MsSQLGirl** [MicrosoftDocs/sql-docs#1839]
Hello,

In the [documentation](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-os-buffer-pool-extension-configuration-transact-sql?view=sql-server-2017), the state_description mentions "1 = BUFFER POOL EXTENSION ENABLED". This should be changed to: "5 = BUFFER POOL EXTENSION ENABLED". 

Thank you!

**Comment by MightyPen** [comment]
@MsSQLGirl Hi Julie, This Issue 1839 is being fixed by PR 9701.
In the future, for anything small like this, you have the option of clicking the pencil icon, at the top-right of the Docs article, to generate a little PR yourself.  Then I can simply approve your PR.

PR fix:    https://github.com/MicrosoftDocs/sql-docs-pr/pull/9701 
Fixed, so now Closing this Issue 1839.

- [https://docs.microsoft.com/sql/relational-databases/system-dynamic-management-views/sys-dm-os-buffer-pool-extension-configuration-transact-sql](https://docs.microsoft.com/sql/relational-databases/system-dynamic-management-views/sys-dm-os-buffer-pool-extension-configuration-transact-sql)

- [sys.dm_os_buffer_pool_extension_configuration (Transact-SQL)](https://docs.microsoft.com/sql/relational-databases/system-dynamic-management-views/sys-dm-os-buffer-pool-extension-configuration-transact-sql)

- [The file in GitHub, private repo](https://github.com/MicrosoftDocs/sql-docs-pr/blob/live/docs/relational-databases/system-dynamic-management-views/sys-dm-os-buffer-pool-extension-configuration-transact-sql.md)

(ms.author = SteveStein, but I am going to spare Steve the interruption and fix this myself.)

Thanks.  GeneMi.  2019/03/30.
. .
