### ISSUE TITLE
Python script crashes 

### ISSUE THREAD

**Issue by CBrauer** [MicrosoftDocs/sql-docs#1853]
I'm trying to develop a machine language script using SQL Server 2017.
My code is:
```
EXEC sp_execute_external_script @language = N'Python',
@script = N'

import pandas as pd
import numpy as np
import csv
import collections as count
import xgboost as xgb
from sklearn import metrics
from sklearn.utils import shuffle

# df = pd.read_csv("https://raw.githubusercontent.com/CBrauer/CypressPoint.github.io/master/rocket.csv");
df_full = pd.read_csv("H:/HedgeTools/Notebooks/rocket.csv")
print("df_full:\n", df_full.head())

feature_names = ["BoxRatio", "Thrust", "Velocity", "OnBalRun", "vwapGain"]
response_name = ["Altitude"]
model_classify = shuffle(df_full)
print("model_classify:\n", model_classify.head())

train, valid, test = np.split(model_classify.sample(frac=1),
                              [int(.6*len(model_classify)),
                              int(.8*len(model_classify))])

X_train = train[feature_names].values
y_train = train[response_name].values.ravel()

X_valid = valid[feature_names].values
y_valid = valid[response_name].values.ravel()

X_test = test[feature_names].values
y_test = test[response_name].values.ravel()

print("Shape of datasets:")
print(" train shape....... ", X_train.shape, y_train.shape)
print(" validate shape.... ", X_valid.shape, y_valid.shape)
print(" test shape........ ", X_test.shape, y_test.shape)

count = pd.value_counts(y_test, sort = True)
goal_met = count[1]
goal_failed = count[0]
print("goal_met.......", goal_met)
print("goal_failed....", goal_failed)

imbalance_scale = int(goal_failed/goal_met)

best_model = xgb.XGBClassifier(n_estimators=1000,
                               max_depth = 19,
                               min_child_weight = 1.0,
                               subsample = 0.844367185738714,
                               max_delta_step=1,
                               scale_pos_weight=imbalance_scale,
                               random_state = 7)

# best_model.fit(X_train, y_train)
# predicted = best_model.predict(X_train)
# print(metrics.classification_report(y_train, predicted))
print("done.")
';

GO
```
If you uncomment the lines:
```
# best_model.fit(X_train, y_train)
# predicted = best_model.predict(X_train)
# print(metrics.classification_report(y_train, predicted))
```
You will see that a crash occurs in the fit method.

To reproduce the problem you will need to download the "rocket.csv" file from my GitHUb account.
See line 12

I hope this helps.
Charles

**Comment by MightyPen** [comment]
@CBrauer Hi Charles, Thank you for this inquiry.
This inquiry has been re-routed to here, new Issue 1853, where we handle **Documentation** errors / fixes / enhancements.
But this inquiry would be classified as a **Support** issue.

I will informally forward the content you put into this Issue 1853 to a couple people who might be able to help. If they do reply with helpful info, I will paste the info into here, and will @ notify you of the new info (@ works even after the Issue is Closed).

---

Beyond that, all I can do is offer the following list of links to various other sources of help and contacts:

- [All the ways to get help](https://docs.microsoft.com/sql/sql-server/sql-server-get-help)
- [UserVoice - Suggestion to improve SQL Server?](https://feedback.azure.com/forums/908035-sql-server)
- [Setup and Upgrade -  MSDN Forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=sqlsetupandupgrade&filter=alltypes&sort=lastpostdesc)
- [SQL Server Data Tools - MSDN forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=ssdt&filter=alltypes&sort=lastpostdesc)
- [Transact-SQL - MSDN forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=transactsql)
- [SQL Server Security -  MSDN Forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=sqlsecurity&filter=alltypes&sort=lastpostdesc)
- [DBA Stack Exchange (tag sql-server) - ask SQL Server questions](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow (tag sql-server) - also has some answers about SQL development](https://stackoverflow.com/questions/tagged/sql-server) 
- [Reddit - general discussion about SQL Server](https://www.reddit.com/r/SQLServer/)
- [Microsoft SQL Server License Terms and Information](https://www.microsoft.com/download/details.aspx?id=39299)
- [Support options for business users](https://support.microsoft.com/gp/support-options-for-business)
- [Contact Microsoft](https://support.microsoft.com/gp/contactus81?Audience=Commercial)
- [Edit SQL Docs](https://aka.ms/editsqldocs)
- [SQL Docs Feedback](https://aka.ms/sqldocsfeedback)
- [SQL Docs Survey](https://aka.ms/sqldocsurvey)

---

I am now Closing this Issue 1853.
Thank you.
