### ISSUE TITLE
Microsoft XML Core Services 4.0 Service Pack 3 is End of Life

### ISSUE THREAD

**Issue by rasane** [MicrosoftDocs/sql-docs#1888]
Your product lifecycle support shows this product is out of support -
https://support.microsoft.com/en-us/lifecycle/search?alpha=Microsoft%20XML%20Core%20Services.
Since SP3 is the only mentioned end of life on support page, it goes to reason that previous SPn are out of support as well. That page is dated 2014. Why then are you recommending use for SQL 2017? Did you wish to update the EOL on this product?
This is confusing product teams who have been using this product and were trying to move off - but you have resurrected it!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7193d6b-c4e6-71bd-5f68-bed2657af563
* Version Independent ID: dc17eb69-7b76-9302-5645-96bee7fa9fee
* Content: [SQLXML Is Not Installed in SQL Server - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/sqlxml/sqlxml-is-not-installed-in-sql-server?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/sqlxml/sqlxml-is-not-installed-in-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/sqlxml/sqlxml-is-not-installed-in-sql-server.md)
* Product: **sql**
* GitHub Login: @MightyPen
* Microsoft Alias: **genemi**

**Comment by julieMSFT** [comment]
@MightyPen Hi Gene, Please triage this issue.
CC:@rasane This Issue has been assigned to the article owner, who will triage this Issue. You will be notified again when the triage phase is completed.

**Comment by MightyPen** [comment]
@rasane Hello, This is the best answer I can give you:

- "Using SQLXML with SQL Server 2016 and Windows 10"
  - [https://social.msdn.microsoft.com/Forums/sqlserver/en-US/7c87f107-707b-4236-903b-2a60f703d117/using-sqlxml-with-sql-server-2016-and-windows-10?forum=sqlxml](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/7c87f107-707b-4236-903b-2a60f703d117/using-sqlxml-with-sql-server-2016-and-windows-10?forum=sqlxml)

OLEDB has been updated recently, and is actively being maintained. Apparently SQLXML would presumeably work on Windows 10 because OLEDB does.  I do not know of any backward incompatibility being introduced into OLEDB that would cause OLEDB to no longer interoperate with SQLXML. And nobody is making any changes to SQLXML, so SQLXML will not break its interoperability with OLEDB.

I can understand the confusion that you are bringing to our attention.  I will research this a bit further with one person here in Microsoft, in case more clarity can be had.
Thank you for inquiring.
I am now Closing this Issue 1888. However, the @ notification mechanism continues to work fine even in a Closed Issue, in case further communication is necessary.

. .

**Comment by rasane** [comment]
Thank you. 
You haven't said it explicitly, so can you confirm then that "SQLXML 4.0 SP1" is a **supported product** notwithstanding 

> Microsoft documentation oversight

 on: https://support.microsoft.com/en-us/lifecycle/search?alpha=Microsoft%20XML%20Core%20Services.

We share concerns of the [previous poster](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/7c87f107-707b-4236-903b-2a60f703d117/using-sqlxml-with-sql-server-2016-and-windows-10?forum=sqlxml), since this software is used in critical business application processes and support EOL is how we drive product updates.  

Based on this guidance we will continue using this product.
