### ISSUE TITLE
Error on Item D. Set PARAMETER_SNIFFING

### ISSUE THREAD

**Issue by asavioli** [MicrosoftDocs/sql-docs#1905]
The second phrase would be on SECONDARY database, not PRIMARY
"
This example sets PARAMETER_SNIFFING to OFF for a SECONDARY database in a geo-replication scenario.

SQL

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = OFF ;
"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40d08d20-a910-1226-c65d-408992ad871d
* Version Independent ID: 321ee79c-fc7e-513e-fecd-a38ab8e264c0
* Content: [ALTER DATABASE SCOPED CONFIGURATION (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-database-scoped-configuration-transact-sql?view=sql-server-2016#feedback)
* Content Source: [docs/t-sql/statements/alter-database-scoped-configuration-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/alter-database-scoped-configuration-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by MightyPen** [comment]
@asavioli Hello asavioli, Good catch. I have fixed this Issue 1905 by creating PR 1907.
https://github.com/MicrosoftDocs/sql-docs/pull/1907

In the future, when plausible, we encourage people to create the necessary PR directly, rather than creating an Issue. Simply click the "Edit" pencil icon at the top-right of the article, click the next pencil edit icon on the GitHub webpage, and type in the correction.  That enables you to make improvements in our master/public article, gives you credit for doing so, and spares our always way-too-busy staff from one more task  :-) 

Fixed. I am Closing this Issue 1905 now.
Thank you.

CC: @CarlRabeler
