### ISSUE TITLE
Why the function part can use number?

### ISSUE THREAD

**Issue by kind03** [MicrosoftDocs/sql-docs#1927]
[Enter feedback here]
What does this mean 
`SELECT ROUND(150.75, 0, 1);  `

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b61f3f8-eb79-944e-3241-e53dcaa294fa
* Version Independent ID: dd7552a3-5917-84e3-2746-cb3489fabaf5
* Content: [ROUND (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/round-transact-sql?view=sql-server-2017&viewFallbackFrom=sql-server-2014#feedback)
* Content Source: [docs/t-sql/functions/round-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/round-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MightyPen** [comment]
@MashaMSFT Hi Masha, At a brief glance, all I can glean about the third parameters is that.....
_**the numeric value of 1 for the third parameter seems to mean "truncate", rather than "round"**.....
.....per example C.  So in example C, the ".75" portion is chopped off, leaving nothing to round up or down regarding the 1's place-value unit.
IF instead the Select statement had been.....
`SELECT ROUND(150.75, 1,1);`
..... the result would have been "150.7", I presume, as the second parameter would mean Do not chop off the first digit after (to the right of) the decimal point.  So in both cases, the third parameter value of "1" means truncate (chop off), at the position indicated by the second parameter (I think).

The preceding explanations probably answer the specific question asked by @kind03, but overall the article seems lacking in its explanation of the third parameter.
Maybe 0=Round, 1=Truncate, but other values I dunno?

**Comment by MightyPen** [comment]
@kind03 Oh now I see. The article Does explain "function" parameter. 0=Round, and any other value means =Truncate.  Example C shows the nonZero value of "1" performing truncation.

The answer is now complete.
So I will Close this Issue 1927 now, as Fixed (answered).
Thank you for inquiring.

CC: @MashaMSFT
