### ISSUE TITLE
Confusion over "same" in Partition related text

### ISSUE THREAD

**Issue by DoyleJOfTexas** [MicrosoftDocs/sql-docs#1939]
[Enter feedback here]

"...columns in the tables are the same, because the partitions themselves can be joined"

I am unclear on what is meant by "same" ? Same in datatype? Same in Partition stored on?

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b7b22d6-0ccb-bda0-7ea6-dc4a7e4817c5
* Version Independent ID: 9039d0ef-8830-a67d-6cd0-b17ef2a78081
* Content: [Partitioned Tables and Indexes - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/partitions/partitioned-tables-and-indexes?view=sql-server-2017)
* Content Source: [docs/relational-databases/partitions/partitioned-tables-and-indexes.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/partitions/partitioned-tables-and-indexes.md)
* Product: **sql**
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by julieMSFT** [comment]
Hi @DoyleJOfTexas, 
thanks for bringing this to our attention! Let me look into this a bit further. Thanks!

**Comment by julieMSFT** [comment]
Hi @DoyleJOfTexas, Thank you for your question. "the same" is answered lower in the article in more detail.
"If you frequently run queries that involve an equi-join between two or more partitioned tables, their partitioning columns should be the same as the columns on which the tables are joined. Additionally, the tables, or their indexes, should be collocated. This means that they either use the same named partition function, or they use different ones that are essentially the same, in that they:
- Have the same number of parameters that are used for partitioning, and the corresponding parameters are the same data types.
- Define the same number of partitions.
- Define the same boundary values for partitions. In this way, the query optimizer can process the join faster, because the partitions themselves can be joined. If a query joins two tables that are not collocated or are not partitioned on the join field, the presence of partitions may actually slow down query processing instead of accelerate it." 

The columns that are used in an equi-join should have the same data type and the same partition scheme.

Please let me know if this helps to answer your question or if you have further questions.

**Comment by julieMSFT** [comment]
Hi @DoyleJOfTexas, I hope this answered your question. I will proceed with closing out this Git Issue, but please feel free to respond should you need anything further. Thanks!

**Comment by julieMSFT** [comment]
#10230
