### ISSUE TITLE
statement_start_offset

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/sql-docs#1947]
@uniqalex commented on [Wed Apr 17 2019](https://github.com/MicrosoftDocs/sql-docs.ru-ru/issues/47)

Hello.
I want to discuss  about statement_start_offset. Doc article says that it is number of characters, but in example D this parameter is devided by 2. 
If we talking about "number of characters" - it does no matter how many bytes is used for storing 1 character, coz we set NUMBER OF CHARACTERS! Not a number of bytes.
Can you explain me, what i cant understand this article moment?

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 785e6be1-0c51-7690-1eb6-c4c98c7c1133
* Version Independent ID: 79592f3b-ccff-06bd-eed8-08ab1bf74205
* Content: [sys.dm_exec_requests (Transact-SQL) - SQL Server](https://docs.microsoft.com/ru-ru/sql/relational-databases/system-dynamic-management-views/sys-dm-exec-requests-transact-sql?view=sql-server-2017)
* Content Source: [docs/relational-databases/system-dynamic-management-views/sys-dm-exec-requests-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs.ru-ru/blob/live/docs/relational-databases/system-dynamic-management-views/sys-dm-exec-requests-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by CeciAc** [comment]
Hi team, 
I'm moving this here because the user reports the explanation may be ambiguous
best regards

**Comment by rothja** [comment]
@CeciAc Thanks for the question. I'm going to have the author @stevestein look into this.

**Comment by srutzky** [comment]
@CeciAc and @uniqalex  (and others): regarding

> Doc article says that it is number of characters, but in example D this parameter is devided by 2.

`statement_start_offset` and `statement_end_offset` are the 0-based array index values for the starting and ending characters, respectively. Characters are stored as UTF-16, which is 2 bytes per code unit, so you _should_ only ever see even numbers (hence the need to `+1` for use in `SUBSTRING()` since T-SQL uses 1-based positions) as those are the first byte of ever 2-byte UTF-16 code unit.

I have no idea why they decided to return the exact physical index value rather than the character position (i.e. `index value / 2`) since the physical index value isn't usable without first dividing, and I can't think of any situation where an odd number would be returned as that would be a partial character, which is invalid. Perhaps there is a possible use case that might be exposed in the future that uses UTF-8 (which has characters that use 1 or 3 bytes), but who knows.

Either way, the values returned in each of these fields _are_ the "Number of characters into the currently executing batch or stored procedure..." _expressed in terms of bytes_ (or _starting byte positions_). Does that make sense?

**Comment by stevestein** [comment]
@srutzky - Thanks for providing an explanation. The example has been here for quite some time, and while I did verify that example D does still run successfully, I can't speak as to why the original approach was taken.

Thanks!
