### ISSUE TITLE
there's an error in the snippet

### ISSUE THREAD

**Issue by rbtlong-pitzer** [MicrosoftDocs/sql-docs#1959]
this line is missing a beginning quote

 @command = C:\clickme_scripts\SQL11\PostBOLReorg GetHsX.exe', 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05af7104-7302-6a57-6db9-6ddcafd95c75
* Version Independent ID: 455567cb-eda3-3b19-5217-6e4479523a1c
* Content: [Create a CmdExec Job Step - SQL Server](https://docs.microsoft.com/en-us/sql/ssms/agent/create-a-cmdexec-job-step?view=sql-server-2017#feedback)
* Content Source: [docs/ssms/agent/create-a-cmdexec-job-step.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/agent/create-a-cmdexec-job-step.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by rothja** [comment]
@rbtlong-pitzer Thank you for the feedback. Would you be interested in editing the article directly and submitting the fix to get attribution on the article? There is an edit button on each article and you become a contributor. Let us know. Otherwise @stevestein should be able to get this fixed. Thank you!

**Comment by stevestein** [comment]
@rbtlong-pitzer - Thanks for reporting this. Missing quote has been added in [PR 2108](https://github.com/MicrosoftDocs/sql-docs/pull/2108).

Thanks!
