### ISSUE TITLE
 Error converting data type NVARCHAR to BIGINT during ETL Process using Polybase

### ISSUE THREAD

**Issue by vijaysuram** [MicrosoftDocs/sql-docs#1960]
I am getting an error when I am trying to load data from Azure Blob Storage to Azure SQL Data warehouse.

I was able to create the EXTERNAL table successfully. Source and column mapping are fine but when I query SELECT * for the data, it throws me the below error.

Msg 107090, Level 16, State 1, Line 55
HdfsBridge::recordReaderFillBuffer - Unexpected error encountered filling record reader buffer: HadoopSqlException: Error converting data type NVARCHAR to BIGINT.
There are 42 columns with the same data type. Can you please explain me the solution for this? All my files in Blob storage are in .txt format, sample data is below.

id	source_id	root_account_id	account_id	enrollment_term_id	name
78530000000000077	77	78530000000000001	78530000000000010	78530000000000001	Employee training
78530000000000089	89	78530000000000001	78530000000000010	78530000000000001	SCORM TESTING

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7ac2fe2-31da-7db6-2d5f-5091022f41d2
* Version Independent ID: bbf07c2c-7006-7b94-f12f-800fa7bc67e4
* Content: [CREATE EXTERNAL TABLE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-external-table-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/statements/create-external-table-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-external-table-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by rothja** [comment]
@vijaysuram Thanks for the question. It is possible that this issue has to be investigated by Microsoft support and/or forums. But I want to make sure that the article is clear and that there isn't an issue with the instructions. I'm going to look into this to see if there is something wrong. I will be out of the office next week, so I apologize if there is a delay in my response.

**Comment by rothja** [comment]
@vijaysuram Hello. I have done some research on this, and I'm not sure why you are getting this error. At this time, it is unclear whether this is a product bug or documentation problem. I would suggest reaching out to Microsoft support or the forums with this question to troubleshoot, as these doc feedback issues are only used for corrections rather than deeper investigation. I did find one stack overflow issue with the same error that had to do with whitespace in the columns (https://stackoverflow.com/questions/41264655/sql-server-error-converting-data-type-nvarchar-to-bigint) but I'm not sure that this would apply in the PolyBase scenario. The only other suggestion I would have would be to possibly create a test table with only one column with the same data (maybe really small), and then add the other columns in gradually to see if you get the error. This is a brute force technique, but it might help you to narrow it down. I apologize I can't help more on this. 

At this time, I am going to close the issue, but feel free to reach out to me on this issue with any additional information or questions or comments. Thank you!

**Comment by mrunalvairagade** [comment]
CSV file that you have used might contain NULL as a string
