### ISSUE TITLE
No Trusted connection tutorial in this

### ISSUE THREAD

**Issue by mahidharguggilam** [MicrosoftDocs/sql-docs#1983]
How to use sqlcmd with trusted connection and when I use sqlcmd localhost -E -i xxxxx.sql file for running scripts, it is giving error:
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : SSPI Provider: No Kerberos credentials available (default cache: KEYRING:persistent:0).
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : Cannot generate SSPI context.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b543b57-f397-779d-6fe4-1bc2ecd3bdca
* Version Independent ID: e274a0f3-ec74-e809-f4d3-515782b29a92
* Content: [Get started with SQL Server on Red Hat Enterprise Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-red-hat?view=sql-server-2017#feedback)
* Content Source: [docs/linux/quickstart-install-connect-red-hat.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-red-hat.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by MashaMSFT** [comment]
Hi @mahidharguggilam , thank you for contacting Microsoft! Unfortunately, it sounds like you're running into an issue with the product itself, and this is actually just meant to discuss issues with the documentation. As such, your request is outside the scope of this medium. I would recommend checking this page to see what other options you have for getting support, such as engaging the community, or opening a ticket with our support team directly: https://docs.microsoft.com/en-us/sql/sql-server/sql-server-get-help?view=sql-server-2017#i-want-to-contact-microsoft-support

Sorry about that :( Please let me know if I could be of any other assistance? Thanks!

**Comment by rothja** [comment]
@mahidharguggilam Hello. As Masha said, this is probably best handled by support (from Microsoft or through forums). However, I would recommend that you look at this article: https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-active-directory-auth-overview?view=sql-server-2017. In order to do a trusted connection, you have to have fully setup active directory on linux. If you have already done this, then I would work with support to troubleshoot why it is not working. Thanks, again, for reaching out. And sorry that we cannot help on this git issue.
