### ISSUE TITLE
Release Notes for SSMS 16 and SSMS 17

### ISSUE THREAD

**Issue by dalekerr** [MicrosoftDocs/sql-docs#1992]
Where are answers to these questions clearly specified:
- what versions of Windows does SSMS 16 support?
- what versions of SQL Server does SSMS 16 support?
- what versions of Windows does SSMS 17 support?
- what versions of SQL Server does SSMS 17 support?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cac198c9-abf9-b7ae-0827-dac03ddf4ad6
* Version Independent ID: 9f2afe99-e7c3-726f-fa89-08fc1e4ed653
* Content: [Release notes for SQL Server Management Studio (SSMS) - SQL Server](https://docs.microsoft.com/en-us/sql/ssms/release-notes-ssms?view=sql-server-2017)
* Content Source: [docs/ssms/release-notes-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/release-notes-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by MashaMSFT** [comment]
Hi @dalekerr , thanks again for asking these clarifying questions! @stevestein , would you mind seeing if there's a way to update the SSMS documentation with more clarity revolving supportability? Thanks!

**Comment by stevestein** [comment]
@dalekerr - Because older versions of SSMS are no longer supported, that info is not available. Check out the [SQL Server Management Studio (SSMS) Support Policy](https://docs.microsoft.com/sql/ssms/support-policy) page. The only supported version of SSMS is the current version (today that's 18.0):

- [Supported SQL offerings](https://docs.microsoft.com/sql/ssms/download-sql-server-management-studio-ssms#supported-sql-offerings-ssms-180-ga)
- [Supported Operating systems](https://docs.microsoft.com/sql/ssms/download-sql-server-management-studio-ssms#supported-operating-systems-ssms-180-ga)

I'm going to go ahead and close this issue. Thanks!
