### ISSUE TITLE
Missing description of 'awaiting command' status

### ISSUE THREAD

**Issue by brettshearer** [MicrosoftDocs/sql-docs#2005]
As noted by Bob Dorr a few years back at :https://blogs.msdn.microsoft.com/bobsql/2017/06/09/sql-server-mysteries-the-case-of-the-suspended-awaiting-command-and-blocked-session/
Not all statuses are documented. Please update the documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 785e6be1-0c51-7690-1eb6-c4c98c7c1133
* Version Independent ID: 79592f3b-ccff-06bd-eed8-08ab1bf74205
* Content: [sys.dm_exec_requests (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-exec-requests-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/system-dynamic-management-views/sys-dm-exec-requests-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-dynamic-management-views/sys-dm-exec-requests-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by MashaMSFT** [comment]
Hi @brettshearer , thanks for bringing this to our attention! @stevestein , would you mind researching this further? Thanks!

**Comment by stevestein** [comment]
@brettshearer - Thank you for bringing up this issue! We opened an internal work item to update this article. To track this in our ticketing system we opened work item 1530308. Since we're now tracking this internally, I'll proceed with closing out this Issue. However, please feel free to contact us if you have any additional information. Thanks again!
