### ISSUE TITLE
Session_ID returns null - not documented

### ISSUE THREAD

**Issue by brettshearer** [MicrosoftDocs/sql-docs#2008]
THREADPOOL waits are appearing on my production server with null SESSION_ID and null EXEC_CONTEXT_ID, but columns are not documented as such.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 124c0a79-ddd4-7399-bfc5-ec2920931783
* Version Independent ID: 490a5d93-6b28-984c-6069-463a84ed3a8c
* Content: [sys.dm_os_waiting_tasks (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-os-waiting-tasks-transact-sql?view=sql-server-2017)
* Content Source: [docs/relational-databases/system-dynamic-management-views/sys-dm-os-waiting-tasks-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-dynamic-management-views/sys-dm-os-waiting-tasks-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by MashaMSFT** [comment]
Hi @brettshearer , thanks for contacting Microsoft! Sorry, would you mind clarifying what you mean by 'they're not documented as such'? Do you mean that there is no explanation for when the values of session_id and exec_context_id are null? Or did you mean something else? 

For what it's worth, threadpool waits are an indication that you're running out of worker threads. The most frequent cause of this issue is an improperly set max degree of parallelism - but there are many other things that can cause this as well. 

Having said that, if you're asking for assistance with the documentation, this is the right place - but if you're asking for assistance with this issue, unfortunately, that is outside the scope of this forum as this is just intended for documentation bugs. If you need further assistance with the threadpool waits, we'd recommend either reaching out to the community, or opening a ticket directly with Microsoft: https://docs.microsoft.com/en-us/sql/sql-server/sql-server-get-help?view=sql-server-2017.

Thanks!

**Comment by brettshearer** [comment]
The question is purely about documentation. Apologies for creating the confusion.
I am asking about the null SESSION_ID and null EXEC_CONTEXT_ID.
Normally columns would be marked nullable if they are allowed to be null.

**Comment by stevestein** [comment]
@brettshearer - Thanks for the feedback. For articles like this that describe Views (returned data) we don't typically call out if the underlying data allows Null values when being updated. Because these are simply views returning information, the potential to return Null values exist in pretty much every column.

I'm going to go ahead and close this one. 

Thanks!
