### ISSUE TITLE
Volumes for persistent data

### ISSUE THREAD

**Issue by jstafford5380** [MicrosoftDocs/sql-docs#2024]
It would be useful to document here which folders on the image I can mount to the host for persistent data, as other images have begun to do. for example `-v sql_data:/opt/sql/data`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b152444b-dfb8-5cbe-cf45-9830bd085a68
* Version Independent ID: 31719660-d4d0-7f63-efcc-846c822a63c2
* Content: [Get started with SQL Server containers on Docker (running SQL Server on Linux) - SQL Server](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-2017&pivots=cs1-bash)
* Content Source: [docs/linux/quickstart-install-connect-docker.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-docker.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by MikeRayMSFT** [comment]
@jstafford5380 - thank you for the submission. 

@rothja would you take a look at the recommendation?

**Comment by MikeRayMSFT** [comment]
Assigning to @rothja - 
@vin-yu would you be interested in taking a look?

**Comment by rothja** [comment]
@jstafford5380 @vin-yu Thanks for the question about persistent volumes with the sql server container. It is my understanding that you can mount any directory to a persistent volume and that the underlying work is done by Docker (i.e. SQL Server wouldn't need to be aware). Let me know if that is not your understanding or whether you ran into any issues mounting volumes in the past because of interactions between the container and persistent storage? Thank you!

**Comment by rothja** [comment]
@jstafford5380 I verified with the product team that mapping any volume should work and the interaction is up to Docker rather than something specific about the container. I'm going to close this Git Issue now, but if you have any other questions or feedback on this, please reach out to me, and I'll reopen it. Thank you!!

**Comment by grahambunce** [comment]
@rothja If you check the original question you'll notice it wasn't about whether you can do this, the question was that you should document this as it's a basic requirement needed for any kind of data persistence. What is the paths that should be mapped and can you provide an example in the documentation? I'm coming from Windows SQL Server and I have no idea where SQL Server linux stores it's database and log files.

**Comment by rothja** [comment]
@grahambunce I re-read the question and see your point. We talk about persisting data outside the container in a separate article [here](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-docker?view=sql-server-ver15#persist). We provide an example there too. I wonder if we should more clearly link to that section? Another thought would be to break this section out into its own article becuase it is important. We didn't put it in the quickstart, because we were keeping that as simple as possible just to try out the container. Thanks for the additional feedback!
