### ISSUE TITLE
No discussion of limitations to expression

### ISSUE THREAD

**Issue by ElmarJ** [MicrosoftDocs/sql-docs#2025]
Under "limitations", I would also expect a brief discussion of which expressions are allowed, even if everything is possible, particularly since MySQL's "Generated Columns" (same syntax) do have specific limitations (e.g. only deterministic and no subqueries allowed - see https://dev.mysql.com/doc/refman/5.7/en/create-table-generated-columns.html).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7155e90b-8b59-5029-6020-223ea44bac84
* Version Independent ID: 48027234-b139-14b5-b790-c65285664360
* Content: [Specify Computed Columns in a Table - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tables/specify-computed-columns-in-a-table?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/tables/specify-computed-columns-in-a-table.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/specify-computed-columns-in-a-table.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by MikeRayMSFT** [comment]
@ElmarJ - thank you for your suggestion.
We'll take a look.

**Comment by stevestein** [comment]
@ElmarJ - Thank you for bringing up this issue! We opened an internal work item to review and update this article. To track this in our ticketing system we opened work item 1530457. Since we're now tracking this internally, I'll proceed with closing out this Issue. However, please feel free to contact us if you have any additional information. Thanks again!
