### ISSUE TITLE
Variables IN OPENQUERY

### ISSUE THREAD

**Issue by markgmarkg** [MicrosoftDocs/sql-docs#2046]
Why OPENQUERY does not accept variables for its arguments?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36f32624-aca6-d742-899b-c5b0a0c8cec7
* Version Independent ID: 6ce3fbec-8a04-289e-412f-23c4b4b4bcf2
* Content: [OPENQUERY (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/openquery-transact-sql?view=sql-server-2017)
* Content Source: [docs/t-sql/functions/openquery-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/openquery-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @markgmarkg , thank you for contacting Microsoft and providing your feedback to our documentation! We'll need some time to look into this further. Depending on the complexity, the turnaround time for this may vary anywhere from a few business days to a few business weeks. We'll reply via comment should we need anything further in the meantime, and please feel free to do the same.

Thanks again for your submission, and hope you have a wonderful rest of your day!

**Comment by MashaMSFT** [comment]
Hi @markgmarkg , thanks again for submitting your question to Microsoft. The following blog explains why  OPENQUERY does not accept variables: https://blogs.msdn.microsoft.com/sqlsakthi/2011/05/08/best-performer-distributed-query-four-part-or-openquery-when-executing-linked-server-queries-in-sql-server/

OPENQUERY executes the specified pass-through query on the specified linked server. SQL Server sends pass-through queries as **uninterpreted query strings** to an OLE DB data source. That is, SQL won’t apply any kind of logic on the query and won’t try to estimate what that query would do, it would simply pass the specified query as it is to the target linked server.

As such, it's recommened to  build your variables in dynamic SQL with a linked server:  https://support.microsoft.com/en-us/help/314520/how-to-pass-a-variable-to-a-linked-server-query

I hope that helps and please let me know if we can be of further assistance. Otherwise, we'll proceed with closing out this Git Issue in a few business days. 

Thanks!
