### ISSUE TITLE
if partition_by_clause not specified

### ISSUE THREAD

**Issue by Haiming247** [MicrosoftDocs/sql-docs#2049]
If partition_by_clause not specified, the function treats all rows of the query result set as a single group. order_by_clause determines the logical order in which the operation is performed.

In the last example, STDEV(SalesAmountQuota) OVER (ORDER BY CalendarYear, CalendarQuarter) AS StdDeviation, no partition_by_clause is specified. All rows should be set as a single group. I'm wondering why the StdDeviation is different for each row?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9256cac5-f894-b0a9-ee1e-68280e0534b9
* Version Independent ID: 891adfb3-c657-dbd7-06f9-c7fd21a2ad6e
* Content: [STDEV (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/stdev-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/functions/stdev-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/stdev-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @Haiming247, thank you for contacting Microsoft and providing your feedback to our documentation! We'll need some time to look into this further. Depending on the complexity, the turnaround time for this may vary anywhere from a few business days to a few business weeks. We'll reply via comment should we need anything further in the meantime, and please feel free to do the same.

Thanks again for your submission, and hope you have a wonderful rest of your day!

**Comment by MashaMSFT** [comment]
Hi @Haiming247 , thank you for your patience as I researched this a bit further for you. It looks like this behavior is by design. 

If only ORDER BY is specified then the window frame is RANGE UNBOUNDED PRECEDING AND CURRENT ROW. So the first row (based on the ORDER BY clause) will include only that row, the 2nd row will include rows 1 & 2 and so on. PARTITION BY merely decides how to split the qualifying rows. Window frame is the important concept here to understand. Basically, all three queries below are same and 3rd one specifies all the optional clauses:

-- Uses AdventureWorks  
  
SELECT CalendarYear AS Year, CalendarQuarter AS Quarter, SalesAmountQuota AS SalesQuota,  
       **STDEV(SalesAmountQuota) OVER (ORDER BY CalendarYear, CalendarQuarter) AS StdDeviation**  
FROM dbo.FactSalesQuota  
WHERE EmployeeKey = 272  AND CalendarYear = 2012  
ORDER BY CalendarQuarter;

SELECT CalendarYear AS Year, CalendarQuarter AS Quarter, SalesAmountQuota AS SalesQuota,  
       **STDEV(SalesAmountQuota) OVER (ORDER BY CalendarYear, CalendarQuarter RANGE UNBOUNDED PRECEDING) AS StdDeviation**  
FROM dbo.FactSalesQuota  
WHERE EmployeeKey = 272  AND CalendarYear = 2012  
ORDER BY CalendarQuarter;

SELECT CalendarYear AS Year, CalendarQuarter AS Quarter, SalesAmountQuota AS SalesQuota,  
       **STDEV(SalesAmountQuota) OVER (ORDER BY CalendarYear, CalendarQuarter RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS StdDeviation**  
FROM dbo.FactSalesQuota  
WHERE EmployeeKey = 272  AND CalendarYear = 2012  
ORDER BY CalendarQuarter;
