### ISSUE TITLE
AbstractSqlServerExtensionExecutor source code not correct

### ISSUE THREAD

**Issue by nielsberglund** [MicrosoftDocs/sql-docs#2059]
The subheading AbstractSqlServerExtensionExecutor source code does not show the source for AbstractSqlServerExtensionExecutor but for AbstractSqlServerExtensionDataset.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cf79a33-34cc-b538-0d43-0855204e48a9
* Version Independent ID: b7a9dee6-9e40-8361-1db8-2784fb17229f
* Content: [SDK for Java extension - SQL Server Language Extensions - SQL Server](https://docs.microsoft.com/en-us/sql/advanced-analytics/java/java-sdk?view=sqlallproducts-allversions#abstractsqlserverextensionexecutor-source-code)
* Content Source: [docs/advanced-analytics/java/java-sdk.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/advanced-analytics/java/java-sdk.md)
* Product: **sql**
* Technology: **machine-learning**
* GitHub Login: @NelGson
* Microsoft Alias: **negust**

**Comment by stevestein** [comment]
@nielsberglund - thanks for the feedback! I've assigned this to the author @NelGson.  Thanks!

**Comment by NelGson** [comment]
I have already submitted a PR for this. Not sure what the status of that is. Hoppfully merged since I submitted it Sunday evening.

________________________________

**Comment by NelGson** [comment]
My changes are already merged. Issue resolved.

**Comment by MightyPen** [comment]
@NelGson Hello, What is the PR number that fixed this Issue 2059?  Thanks. (GeneMi)

I think it might have been #10114 ?

`https://github.com/MicrosoftDocs/sql-docs-pr/pull/10114/files`

It helps our auditing to have the Issue and the PR each contain a link to the other (or at least their respective numbers mentioned in each other).
Because I suspect PR 10114 is the corresponding PR for this Issue 2059, I am now Closing this Issue, and so notifying the original customer @nielsberglund .

Thank you for the prompt work you did to fix this Issue 2059.

CC: @stevestein Reminder Steve that a Writer must always be at least co-assigned to any given Issue.
fyi @dphansen 

Closing.
