### ISSUE TITLE
Using AD groups for authentication

### ISSUE THREAD

**Issue by EmileTenhagen** [MicrosoftDocs/sql-docs#2060]
When using AD-groups for authentication do not forget to change these to "Universal" instead of "Global" or "Local".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5785871a-0daf-16d7-6678-4285bbd28b6e
* Version Independent ID: c5587dc0-b731-67e1-0d2a-3225a10dd310
* Content: [Active Directory authentication for SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-active-directory-auth-overview?view=sql-server-2017)
* Content Source: [docs/linux/sql-server-linux-active-directory-auth-overview.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-active-directory-auth-overview.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by rothja** [comment]
@EmileTenhagen Thank you for your feedback on this article. Just to understand better, did you find that it did not work to have "global" or "local" groups for authentication with Linux? Is this a Linux-only issue in your understanding? Thank you for the additional information!

**Comment by EmileTenhagen** [comment]
@rothja The problem that I had was that Domain Local groups cannot be used within Linux SQL as soon as I changed the AD group to "Global" or "Universal" it worked within SQL. 
I could not find this information anywhere untill Puzzle_Chen mentioned this on the Microsoft MSDN Forum.
Perhaps this could be mentioned within the documentation of SQL on Linux as this is the information I used to set it up.

**Comment by rothja** [comment]
@EmileTenhagen Thanks for the additional information. I'll also run this by some of our Linux product team members before updating the docs. Thanks for pointing this out.

**Comment by rothja** [comment]
@EmileTenhagen We are investigating why Local does not work, but I will document this in the article for now. Thank you for bringing this to our attention!

**Comment by rothja** [comment]
@EmileTenhagen Thanks, again for bringing this to our attention. I have confirmed that this seems to be a bug or an unintentional behavior with AD groups. We have filed a work item to investigate, but for now we don't have a work around. If you can't use a non-local group, then you could consider opening up a support request with us to see if they can help figure out how to get this working. Otherwise, we will try to investigate further later and hopefully get this working. At this time, I am going to close the git issue, but I appreciate your feedback. Let me know if you have any other questions by replying to this thread and I'll help in any way I can. Thank you!!
