### ISSUE TITLE
Is usage of the SSIS "Table lock" checkbox desirable or not? when creating a new "OLE DB destination" component in SSIS.

### ISSUE THREAD

**Issue by foral66** [MicrosoftDocs/sql-docs#2067]
I am simply wondering: Is usage of the SSIS "Table lock" checkbox desirable or not? 
This checkbox is checked .. by default .. when creating a new "OLE DB destination" component in SSIS.
We have several SSIS processes running.
At certain times of the day, trying to just refresh the list of tables in SSMS for a database gives me message "Lock request time out period exceeded. (Microsoft SQL Server, Error: 1222)"
Am thinking this is related to this SSIS option ?
I will go with the default setting for now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f2c8c53-6371-b844-3b7b-8e93b8601683
* Version Independent ID: a5a62a2f-e91c-d2bd-e489-a612ea049b1a
* Content: [Prerequisites for Minimal Logging in Bulk Import - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/import-export/prerequisites-for-minimal-logging-in-bulk-import?view=sql-server-2017)
* Content Source: [docs/relational-databases/import-export/prerequisites-for-minimal-logging-in-bulk-import.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/import-export/prerequisites-for-minimal-logging-in-bulk-import.md)
* Product: **sql**
* Technology: **data-movement**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @foral66 , thanks for contacting Microsoft! Let me see if I'm understanding your issue correctly - 

1. You have a number of SSIS processes running, and you have the Allow Table Lock option enabled (since it's enabled by default). 
2. During the day, you are using Object Explorer in SQL Server Management Studio, expanding Databases > Tables, and when you do so,  you're seeing the error "Lock request timeout period exceeded"
3. You believe that the error is because your SSIS processes are running, and causing your tables to lock. 

Am I understanding correctly? 

I suppose you could try unchecking to box to see if that resolves the behavior. However, there may be other consequences for choosing that option, and there's a reason why it's checked by default. Since this form of contact is intended explicitly for issues with the documentation,  your best bet would be to engage the community, or open a support ticket directly with Microsoft. More information can be found here:  https://docs.microsoft.com/en-us/sql/sql-server/sql-server-get-help?view=sql-server-2017.

My apologies that the SQL docs team is unable to assist you further with your support issue. If you need any thing else from the content perspective, please let us know. Otherwise, we'll proceed with closing out this Git Issue in a few business days. 

Thanks again and hope you have a wonderful rest of your day!
