### ISSUE TITLE
Format AM/PM

### ISSUE THREAD

**Issue by CotivitiSuresh** [MicrosoftDocs/sql-docs#2114]
It would be great, if you could include an example for specifying AM and PM for time data type

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f019407-5787-6f54-1027-084e817b6b8e
* Version Independent ID: a92541d0-b63a-9603-2a1f-18e210be89e4
* Content: [FORMAT (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/format-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/functions/format-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/format-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by stevestein** [comment]
@CotivitiSuresh  - thanks for the feedback! I've assigned this to the author @MashaMSFT 

Thanks!

**Comment by MashaMSFT** [comment]
Hi @CotivitiSuresh ,

Thank you for contacting Microsoft and providing your feedback to our documentation! We'll need some time to look into this further. Depending on the complexity, the turnaround time for this may vary anywhere from a few business days to a few business weeks. We'll reply via comment should we need anything further in the meantime, and please feel free to do the same.

If you're suggesting a simple change to the documentation, it may be faster for you to submit the edit yourself via a Pull Request (PR). You can do so by following these steps:

1. Navigate to the page of interest
2. Select the "Edit" button at the top right of the page
3. Select the "Pencil" icon on the right
4. Modify the text within the text box in [markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) format
5. Name your file change and copy the link to your Git Issue into the "extended description" box
6. Select "Propose file change"
7. Select "Create pull request" on the 'Comparing changes' page
8. Select "Create pull request" on the 'Open a pull request' page
9. Wait for an author to review and approve the change request - this can take a bit depending on the complexity

Doing so will allow authors to directly add your text to the documentation. This also displays your github image on the page of authors, and list you as a contributor to the documentation.

Otherwise, we'll continue to research your suggestion, and get back to you as soon as we have more information for you.

Thanks again for your submission, and hope you have a wonderful rest of your day!

**Comment by MashaMSFT** [comment]
Hi @CotivitiSuresh , thanks again for contacting Microsoft! What type of AM / PM example are you hoping to see? 

The following T-SQL code shows the current time, so depending on when  you run it, it will show either AM or PM. 

```sql
SELECT FORMAT(SYSDATETIME(), N'hh:mm tt');
```
Is that what you were looking for, or were you hoping for a different type of example?

Thanks!

**Comment by MashaMSFT** [comment]
Hi @CotivitiSuresh , 

Thanks again for contacting Microsoft!  We've submitted a documentation change based on your suggestion, and it should be live by tomorrow. Please let us know if there is anything more we can do for you? If not, we'll proceed with closing out this Git Issue in a few business days.

Thanks again and hope you have a wonderful rest of your day!
