### ISSUE TITLE
SQL Server 2019 Linux connection from Web API / Web app using service name deployed on Kubernetes

### ISSUE THREAD

**Issue by NileshGule** [MicrosoftDocs/sql-docs#2117]
I have been using SQL Server 2017 Linux image for quite some time. I am able to deploy this to AKS cluster with **Statefulset** and a **service name** exposed via a **Service** object. I can then connect to the SQL Server instance using the service name from web API or frontend application. The complete working example of this can be found in the repo 
https://github.com/NileshGule/AKS-learning-series/tree/master/k8s/AKS

I upgraded to SQL Server 2019 Linux image. With the operator and the ag group deployment, I am able to create the database. However, I cannot access the database from the front end and Web API projects without giving in the loadbalancer IP address of the Availability Group primary service.

Is there any way to access the SQL Server 2019 using service discovery without specifying the IP address?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71553ef6-37d8-fbe4-fa56-98c13388efab
* Version Independent ID: f8073caa-f2bd-65b3-4968-ac9b87345872
* Content: [Manage a SQL Server Always On availability group Kubernetes - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-kubernetes-manage?view=sqlallproducts-allversions#feedback)
* Content Source: [docs/linux/sql-server-linux-kubernetes-manage.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-kubernetes-manage.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by VanMSFT** [comment]
Hello @NileshGule! Thank you for submitting this Issue. We appreciate you taking your time to go through our documentation and asking about managing SQL Server AG with AKS. Since this forum is specifically just for documentation issues, I suggest trying the following options to get your question answered:

- [UserVoice - Suggestion to improve SQL Server?](https://feedback.azure.com/forums/908035-sql-server)
- [Setup and Upgrade -  MSDN Forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=sqlsetupandupgrade&filter=alltypes&sort=lastpostdesc)
- [SQL Server Data Tools - MSDN forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=ssdt&filter=alltypes&sort=lastpostdesc)
- [Transact-SQL - MSDN forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=transactsql)
- [SQL Server Security -  MSDN Forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=sqlsecurity&filter=alltypes&sort=lastpostdesc)
- [DBA Stack Exchange (tag sql-server) - ask SQL Server questions](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow (tag sql-server) - also has some answers about SQL development](https://stackoverflow.com/questions/tagged/sql-server) 
- [Reddit - general discussion about SQL Server](https://www.reddit.com/r/SQLServer/)
- [Microsoft SQL Server License Terms and Information](https://www.microsoft.com/download/details.aspx?id=39299)
- [Support options for business users](https://support.microsoft.com/gp/support-options-for-business)
- [Contact Microsoft](https://support.microsoft.com/gp/contactus81?Audience=Commercial)
- [All the ways to get help](https://docs.microsoft.com/sql/sql-server/sql-server-get-help)

cc: @MikeRayMSFT

**Comment by NileshGule** [comment]
@MikeRayMSFT Thank you for the response. I will raise the query in other forums.

**Comment by MikeRayMSFT** [comment]
@SQLSourabh - I'm closing this issue at this time, because SQL Server 2019 is still preview. However, I'm including you so that you may review @NileshGule comment. Thank you.
