### ISSUE TITLE
bcp language

### ISSUE THREAD

**Issue by anon-acid** [MicrosoftDocs/sql-docs#2122]
On what parameters does the language of bcp text depend on? 

OS language of client machine?
OS language of SQL Server machine?
Language of SQL Server? 
Language of Native client?
Language of MsSqlCmdUtils?

Tried several combinations, Unable to find the logic on this. 

Example text : 
10 rows copied.
10 lignes copi�es.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86bd520a-7468-fd55-c357-b0f645a917ef
* Version Independent ID: 3dc9dee5-afcb-8287-4441-e84ff717186a
* Content: [bcp Utility - SQL Server](https://docs.microsoft.com/en-us/sql/tools/bcp-utility?view=sql-server-2017)
* Content Source: [docs/tools/bcp-utility.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/bcp-utility.md)
* Product: **sql**
* Technology: **tools-other**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by stevestein** [comment]
@anon-acid - Thanks for the feedback!

The answer is not so simple because it really depends on the specific situation. 

- Some messages come from SQL. In that case, the message is displayed in the locale of SQL server (i.e. bcp and sqlcmd simply relay the message)
- Likewise, messages coming from the driver (ODBC) are displayed based on the locale installed on the machine running sqlcmd/bcp (ODBC driver is available in multiple languages from https://www.microsoft.com/download/details.aspx?id=56567)
- Messages coming straight from bcp/sqlcmd downloaded from (https://docs.microsoft.com/en-us/sql/tools/bcp-utility) will likely be in English.
- Messages coming from bcp/sqlcmd installed with SQL will try to honor the current locale (they do come with localized resources): if the machine where SQL/bcp/sqlcmd is set to language X and SQL language X was installed (and the user doesn’t play with the codepage of the command line… etc… etc…), then the expectation is to see the bcp/sqlcmd messages in language X. If the OS language is changed to language Y (X <> Y), then the messages should default back to the language neutral (i.e. English)

Hope this helps!
Thanks!

**Comment by anon-acid** [comment]
Ok. 

It would be nice if there was a way to get the total number of rows copied from console output. 
Previously i was using regex to find "10 rows copied." But based on the given design, it should not be used.

Can you suggest any other way to achieve this? just from the console output.

**Comment by stevestein** [comment]
@anon-acid - Thanks  for the feedback. This area is for specific issues within the documentation. I'm going to go ahead and close this issue.

For product questions, support, and additional assistance, one of the following links may help:

- [All the ways to get help](https://docs.microsoft.com/sql/sql-server/sql-server-get-help)
- [UserVoice - Suggestion to improve SQL Server?](https://feedback.azure.com/forums/908035-sql-server)
- [Transact-SQL - MSDN forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=transactsql)
- [Support options for business users](https://support.microsoft.com/gp/support-options-for-business)
- [Contact Microsoft](https://support.microsoft.com/gp/contactus81?Audience=Commercial)


Thanks!

**Comment by pavisenthil3** [comment]
10 lignes copi�es.

Can someone suggest how can I get the out put in other languages(like the above)?

**Comment by pavisenthil3** [comment]
@stevestein / @anon-acid 

10 lignes copi�es.

Can someone suggest how can I get the out put in other languages(like the above) but not in english?

what combination i should use?

I installed sql server in japanese on a japanese OS but i got the bcp output in english(10 rows copied).

What I missed?
