### ISSUE TITLE
Wrong TYPE for EXTERNAL DATA SOURCE

### ISSUE THREAD

**Issue by aldelar** [MicrosoftDocs/sql-docs#2125]
CREATE EXTERNAL DATA SOURCE AzureStorage with (  
        TYPE = HADOOP,   
        LOCATION ='wasbs://&lt;blob_container_name&gt;@&lt;azure_storage_account_name&gt;.blob.core.windows.net',  
        CREDENTIAL = AzureStorageCredential  
);  

==&gt; TYPE SHOULD BE 'BLOB_STORAGE'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68376ebf-5749-2240-64b3-3d1edce00294
* Version Independent ID: 5615e4fd-fdef-954d-5c75-cac494ceab60
* Content: [PolyBase Transact-SQL reference - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/polybase/polybase-t-sql-objects?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/polybase/polybase-t-sql-objects.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/polybase/polybase-t-sql-objects.md)
* Product: **sql**
* Technology: **polybase**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by VanMSFT** [comment]
Thank you for contacting Microsoft and providing your feedback to our documentation! We'll need some time to look into this further. I'm assigning my colleague, Jason to take a look further. 

If you're suggesting a simple change to the documentation, it may be faster for you to submit the edit yourself via a Pull Request (PR). You can do so by following these steps: 
1. Navigate to the page of interest 
2. Select the "Edit" button at the top right of the page 
3. Select the "Pencil" icon on the right 
4. Modify the text within the text box within markdown format 
5. Name your file change and copy the link to your Git Issue into the "extended description" box 
6. Select "Propose file change" 
7. Select "Create pull request" on the 'Comparing changes' page 
8. Select "Create pull request" on the 'Open a pull request' page 
9. Wait for an author to review and approve the change request - this can take a bit depending on the complexity

Doing so will allow authors to directly add your text to the documentation. This also displays your github image on the page of authors, and lists you as a contributor to the article. 

Otherwise, we'll continue to research your suggestion, and get back to you as soon as we have more information for you.

Thanks again for your submission, and hope you have a wonderful rest of your day!

**Comment by aldelar** [comment]
I see the page applies to SQL Server, which may be confusing to users, since PolyBase is also available on Azure SQ Datawarehouse and DB.

The syntax for creating an external source to Blob Storage is different for SQL DW and SQL DB:
- SQL DW: HADOOP
- SQL DB: BLOB_STORAGE

Did not try on SQL Server, so the doc may be correct here, but overall it is confusing functionality since the same outcome is enabled with different syntax depending on the flavor of SQL.

**Comment by rothja** [comment]
@aldelar Thanks for contacting us on this. I'm going to take a look and see if I can update the page to make this correct / more clear.

**Comment by WilliamAntonRohm** [comment]
@rothja -- please process this aging issue 2125.

**Comment by rothja** [comment]
@WilliamAntonRohm @aldelar Sorry for the delay on this one. I'll try to get this fixed and closed out by the end of the week.

**Comment by WilliamAntonRohm** [comment]
@rothja I am looking into this issue 2125 today.

**Comment by WilliamAntonRohm** [comment]
@julieMSFT -- Julie, should this command apply to SQL DW?  Please add your answer here in Issue 2125. Thanks.

**Comment by WilliamAntonRohm** [comment]
@mzaman1 -- Murshed, should this command apply to APS PDW?  Please add your answer here in Issue 2125.  Thanks.

**Comment by mzaman1** [comment]
@WilliamAntonRohm for APS/PDW the type is Hadoop. APS has the capability to also read from blob storage but the type still is Hadoop. I feel like this is one of the pages that can benefit from having tabs for different products to clarify for the customer. Let me know if I can clarify anything else.

**Comment by msebolt** [comment]
@aldelar This issue has been resolved.

@mzaman1 Good idea, though this would be a separate issue marked as the need to replace current version markers.
