### ISSUE TITLE
index_name

### ISSUE THREAD

**Issue by sarafpradeep** [MicrosoftDocs/sql-docs#2126]
"index_name Is the name of the index. Index names must be unique within a table or view but do not have to be unique within a database. Index names must follow the rules of identifiers."

It would be nice to add - index_name is unique across schema. We cannot add same index name to two different tables under same schema. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13793c61-629f-f379-fcb7-e9178e4f5dce
* Version Independent ID: ced6efc1-1e34-f452-f995-b597e812c2f2
* Content: [CREATE INDEX (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-index-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/statements/create-index-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-index-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by VanMSFT** [comment]
Hello @sarafpradeep!

Thank you for contacting Microsoft and providing your feedback to our documentation! We'll need some time to look into this further. I'm assigning my colleague, Carl to take a look further. 

If you're suggesting a simple change to the documentation, it may be faster for you to submit the edit yourself via a Pull Request (PR). You can do so by following these steps: 
1. Navigate to the page of interest 
2. Select the "Edit" button at the top right of the page 
3. Select the "Pencil" icon on the right 
4. Modify the text within the text box within markdown format 
5. Name your file change and copy the link to your Git Issue into the "extended description" box 
6. Select "Propose file change" 
7. Select "Create pull request" on the 'Comparing changes' page 
8. Select "Create pull request" on the 'Open a pull request' page 
9. Wait for an author to review and approve the change request - this can take a bit depending on the complexity

Doing so will allow authors to directly add your text to the documentation. This also displays your github image on the page of authors, and lists you as a contributor to the article. 

Otherwise, we'll continue to research your suggestion, and get back to you as soon as we have more information for you.

Thanks again for your submission, and hope you have a wonderful rest of your day!

**Comment by sarafpradeep** [comment]
Same index name can be created on two different objects under same schema. thank you. I meant to address primary key.
