### ISSUE TITLE
Cannot mix different value types when inserting multiple rows to a bit column.

### ISSUE THREAD

**Issue by joseplar** [MicrosoftDocs/sql-docs#2129]
[When inserting several values at once, all the values need to be of one single data type. If it's one INSERT per VALUE then the data type can be either varchar for adding 'TRUE' or 'True' or int for any number where anything except 0 will be converted to 1.

This will work:
```
insert into boolTable
values
('1','int',1)
insert into boolTable
values
('0','int',0)
insert into boolTable
values
('TRUE','string','TRUE')
insert into boolTable
values
('FALSE','string','FALSE')
insert into boolTable
values
('True','string','True')
insert into boolTable
values
('False','string','False')
insert into boolTable
values
('NULL','null',NULL)
insert into boolTable
values
('0.34','float',0.34)
-----------
(1 row affected)
(1 row affected)
(1 row affected)
(1 row affected)
(1 row affected)
(1 row affected)
(1 row affected)
(1 row affected)
```

But this won't:
`insert into boolTable
values
('TRUE','string','TRUE'),
('FALSE','string','FALSE'),
('True','string','True'),
('False','string','False'),
('1','int',1),
('0','int',0),
('NULL','null',NULL),
('0.34','float',0.34)
Msg 8114, Level 16, State 5, Line 42
Error converting data type varchar to numeric.`
]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 019de197-9478-71e7-9618-7236a13027e6
* Version Independent ID: d9e87003-b94b-106d-af24-05916e4f9737
* Content: [bit (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/data-types/bit-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/data-types/bit-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/data-types/bit-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by VanMSFT** [comment]
Hello @joseplar! Thank you for contacting Microsoft and providing your feedback to our documentation! We'll need some time to look into this further. I'm assigning my colleague, Mike to take a look further.

**Comment by MikeRayMSFT** [comment]
Hi @joseplar - I've reproduced the behavior. I'm checking with our engineers. Thank you for the submission.

**Comment by pmasl** [comment]
Hi @joseplar 
This is actually by design. We can clarify the docs. I created a table like this (you didn't include yours so I assume it's similar to this): 

CREATE TABLE boolTable (c1 VARCHAR(10), c2 VARCHAR(10), c3 VARCHAR(10))
GO

Unlike other programming languages, the entire T-SQL statement is evaluated and parsed for execution as a single batch. 
As such, SQL Server must follow the rules of data type precedence when performing an implicit conversion for the same column in the same batch. 
For the same column to be inserted, SQL Server will need to convert all the data types to the data type that has the highest precedence if the conversion is possible at all (See data type precedence docs in https://docs.microsoft.com/en-us/sql/t-sql/data-types/data-type-precedence-transact-sql?view=sql-server-2017). Because the VARCHAR value ‘TRUE’ cannot be converted to int, we emit the expected conversion error.

Which is why the following works:

insert into boolTable 
values ('TRUE','string','TRUE'), 
('FALSE','string','FALSE'), 
('True','string','True'), 
('False','string','False'), 
('1','int','1'), 
('0','int','0'), 
('NULL','null',NULL), 
('0.34','float','0.34')
GO

But not:

insert into boolTable 
values ('TRUE','string','TRUE'), 
('FALSE','string','FALSE'), 
('True','string','True'), 
('False','string','False'), 
('1','int',1), 
('0','int',0), 
('NULL','null',NULL), 
('0.34','float',0.34)
GO

**Comment by MikeRayMSFT** [comment]
Thank you @pmasl

**Comment by joseplar** [comment]
Thanks, Ray, Van and Pedro.

I ran into the error while trying to fix a script a colleague created.
I had to provide a similar explanation as the one Pedro clearly detailed.

Now I have an email from experts, so it makes it a lot easier to explain.

Thanks again.

José Plá

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
