### ISSUE TITLE
Got "Setup Failed" during installation of Microsoft SQL Server Management Studio

### ISSUE THREAD

**Issue by traineedevops** [MicrosoftDocs/sql-docs#2142]
Got "Setup Failed" 
"The certificate was explicitly marked as untrusted by the user (0x800B0111)"
during installation of Microsoft SQL Server Management Studio

I have to say, I didn't change any certificates before installation and follow all provided instructions...
After I got this issue, I tryed to solve this with provided documentation: I didn't find any installed files or folders in Registry to delete.
Also, I got the same issue while installing older versions of Microsoft SQL Server Management Studio.
I cannot find any useful information what is the main problem :(

I have Windows 10 x64 OS. Added log file SSMS-Setup-ENU_20190515141847.log:
[SSMS-Setup-ENU_20190515141847.log](https://github.com/MicrosoftDocs/sql-docs/files/3182388/SSMS-Setup-ENU_20190515141847.log)

[SSMS-Setup-ENU_20190515141847.log](https://github.com/MicrosoftDocs/sql-docs/files/3182385/SSMS-Setup-ENU_20190515141847.log)

**Comment by VanMSFT** [comment]
Hello @traineedevops,

Thanks for contacting Microsoft!  From my understanding, the issue you're describing seems to be an issue with the product, is that correct? If so, unfortunately, this form of contact is intended explicitly for reporting issues with the documentation, and not for the product. To get further assistance with your issue, we'd recommend engaging the community, or opening a ticket with Microsoft Support. More information can be found here: https://docs.microsoft.com/en-us/sql/sql-server/sql-server-get-help?view=sql-server-2017.

If you're looking to provide suggestions or ideas for improvement for the product,  you can do so at https://aka.ms/sqlfeedback.

If I'm mistaken, and you're submitting feedback for the documentation, please reply to this comment to clarify further. Otherwise, we'll proceed with closing out this Git Issue within a few business days.

Our apologies that the SQL Docs team was unable to assist you further with your issue, but we appreciate you reaching out. Please let us know if there's anything more we can do for you.

Thanks again and hope you have a wonderful rest of your day!

**Comment by traineedevops** [comment]
Thank you for your reply !

Yes, really a have problem with product...
Thanks for links.
