### ISSUE TITLE
Minor point -- sys.server_triggers is not valid for Azure SQL Database

### ISSUE THREAD

**Issue by langstonj** [MicrosoftDocs/sql-docs#2145]
sys.server_triggers is not valid for Azure SQL Database.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6c6196a-41af-9c74-36ef-fcb6a4d28c27
* Version Independent ID: 72127529-08f8-5305-35d6-7ccd012a5862
* Content: [Manage Trigger Security - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/triggers/manage-trigger-security?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/triggers/manage-trigger-security.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/triggers/manage-trigger-security.md)
* Product: **sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by VanMSFT** [comment]
Hello @langstonj!

Thank you for contacting Microsoft and providing your feedback to our documentation! We'll need some time to look into this further. I'm assigning my colleague, Jason to take a look. 

If you're suggesting a simple change to the documentation, it may be faster for you to submit the edit yourself via a Pull Request (PR). You can do so by following these steps: 
1. Navigate to the page of interest 
2. Select the "Edit" button at the top right of the page 
3. Select the "Pencil" icon on the right 
4. Modify the text within the text box within markdown format 
5. Name your file change and copy the link to your Git Issue into the "extended description" box 
6. Select "Propose file change" 
7. Select "Create pull request" on the 'Comparing changes' page 
8. Select "Create pull request" on the 'Open a pull request' page 
9. Wait for an author to review and approve the change request - this can take a bit depending on the complexity

Doing so will allow authors to directly add your text to the documentation. This also displays your github image on the page of authors, and lists you as a contributor to the article. 

Otherwise, we'll continue to research your suggestion, and get back to you as soon as we have more information for you.

Thanks again for your submission, and hope you have a wonderful rest of your day!

**Comment by rothja** [comment]
@langstonj Thank you for pointing this out, and I'm really sorry for the delayed response. I'll get this corrected in the doc and then this git issue will automatically close. Thank you for the feedback.

**Comment by WilliamAntonRohm** [comment]
@rothja -- sys.server_triggers was not found on Azure when I tested it.

**Comment by WilliamAntonRohm** [comment]
@langstonj -- thank you for bringing this to our attention.  I have updated the documentation and it should be live by tomorrow.  

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
