### ISSUE TITLE
working with more complex Json (array of identical objects)

### ISSUE THREAD

**Issue by Houuse** [MicrosoftDocs/sql-docs#2146]
[Enter feedback here]
how to query an array of identical json objects every object has a diffirent value ?

consider the following json 
`{
 [
     {
	"info": {
		"type": 1,
		"address": {
			"town": "Bristol",
			"county": "Avon",
			"country": "England"
		},
		"tags": ["Sport", "Water polo"]
	},
	"type": "Basic"
    },
         {
	"info": {
		"type": 2,
		"address": {
			"town": "London",
			"county": "someCounty",
			"country": "England"
		},
		"tags": ["Sport", "Water polo"]
	},
	"type": "Basic"
    }
  ]
}`

for ex : how to query for all town names in the precceding json ?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28e8713d-8b6e-7e43-04cc-e2720891b56c
* Version Independent ID: d09b9ed6-4e55-7d18-b17f-88e17839074d
* Content: [JSON_VALUE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/json-value-transact-sql?view=sql-server-2017)
* Content Source: [docs/t-sql/functions/json-value-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/json-value-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @jovanpop-msft
* Microsoft Alias: **jovanpop**

**Comment by VanMSFT** [comment]
Hello @Houuse!

Thanks for contacting Microsoft!  From my understanding, you're requesting support on how to do something, is that correct? If so, unfortunately, this form of contact is intended explicitly for reporting issues with the documentation, and not for the product. To get further assistance with your issue, we'd recommend engaging the community, or opening a ticket with Microsoft Support. More information can be found here: https://docs.microsoft.com/en-us/sql/sql-server/sql-server-get-help?view=sql-server-2017.

If you're looking to provide suggestions or ideas for improvement for the product,  you can do so at https://aka.ms/sqlfeedback.

If I'm mistaken, and you're submitting feedback for the documentation, please reply to this comment to clarify further. Otherwise, we'll proceed with closing out this Git Issue within a few business days.

Our apologies that the SQL Docs team was unable to assist you further with your issue, but we appreciate you reaching out. Please let us know if there's anything more we can do for you.

Thanks again and hope you have a wonderful rest of your day!
