### ISSUE TITLE
Configuration Location

### ISSUE THREAD

**Issue by TsukeNoMe** [MicrosoftDocs/sql-docs#2148]
It would be great if someone was to think to mention where the generated ini would be located. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33aa7982-7edb-b858-7811-037a1d6d5bcc
* Version Independent ID: 683dcf24-4cb8-6eb7-f9bb-c916f3e85044
* Content: [Install SQL Server Using a Configuration File - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/install-windows/install-sql-server-using-a-configuration-file?view=sql-server-2017#feedback)
* Content Source: [docs/database-engine/install-windows/install-sql-server-using-a-configuration-file.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/install-windows/install-sql-server-using-a-configuration-file.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @TsukeNoMe , thanks for contacting Microsoft! We do not call out the path in the documentation as it may vary from installation to installation.  You can see the path where the file is generated from the GUI of the setup media, on the last "Ready to Install" page. 

We mention that here:
2. Follow the wizard through to the Ready to Install page. **The path to the configuration file is specified in the Ready to Install page in the configuration file path section.** For more information about how to install SQL Server, see Install SQL Server from the Installation Wizard (Setup).


For example, on my "Ready to install" page, you can see the path here: 
![image](https://user-images.githubusercontent.com/32783170/57872086-c50e0500-77bf-11e9-964b-08be85f5fae5.png)

This is the typical path, but since there may be cases where this is different, we don't want to unintentionally mislead customers, and instead, we just point to where the path is shown in their installation.

I hope that helps and please let me know if we can be of further assistance! If not, we'll proceed with closing out this Git Issue in a few business days.

Thanks!
