### ISSUE TITLE
Graphic does not display properly in Dark Theme

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/sql-docs#2152]
Similar to #1889, on https://docs.microsoft.com/en-us/sql/reporting-services/report-builder/generating-data-feeds-from-reports-report-builder-and-ssrs?view=sql-server-2017 the images of text do not render correctly in the dark theme (because of the transparent background?)

![image](https://user-images.githubusercontent.com/1297909/57885504-1090d500-77f9-11e9-95a2-0f6b58ef86d8.png)

**Comment by VanMSFT** [comment]
@nschonni - Thanks Nick! Yes, this is due to the image being saved with transparent background. We are looking into the issue and will provide a fix. Since we have a tracking work item for this, I will go ahead and close this Issue, but please feel free to let us know if you have any additional feedback. Thanks again for bringing this to our attention.

**Comment by nschonni** [comment]
OK, I might suggest converting these to Markdown/HTML tables in this particular case, since that should solve the theme issue
