### ISSUE TITLE
SSMS 18  query window refresh issue

### ISSUE THREAD

**Issue by jigarce** [MicrosoftDocs/sql-docs#2156]
Hi,

I have installed SSMS version 18 in windows 10 OS.

Please see below screenshot for more details

![image](https://user-images.githubusercontent.com/8125778/57905962-f2c57d80-7895-11e9-8263-80d3dd9bb4a7.png)

My issue is whenever I modify / open store procedure in new query window old query window is not showing its data properly until I scroll.

![image](https://user-images.githubusercontent.com/8125778/57906104-6f585c00-7896-11e9-9c9a-ac1db596f87d.png)

Red color text is another query window text.  

Very strange issue.

I have already installed SSMS 2 times

Regards,
jigar

**Comment by VanMSFT** [comment]
@jigarce - Hello Jigar!

Thanks for contacting Microsoft!  From my understanding, the issue you're describing seems to be an issue with the product, is that correct? If so, unfortunately, this form of contact is intended explicitly for reporting issues with the documentation, and not for the product. To get further assistance with your issue, we'd recommend engaging the community, or opening a ticket with Microsoft Support. More information can be found here: https://docs.microsoft.com/en-us/sql/sql-server/sql-server-get-help?view=sql-server-2017.

If you're looking to provide suggestions or ideas for improvement for the product,  you can do so at https://aka.ms/sqlfeedback.

If I'm mistaken, and you're submitting feedback for the documentation, please reply to this comment to clarify further. Otherwise, we'll proceed with closing out this Git Issue within a few business days.

Our apologies that the SQL Docs team was unable to assist you further with your issue, but we appreciate you reaching out. Please let us know if there's anything more we can do for you.

Thanks again and hope you have a wonderful rest of your day!

**Comment by p4lpsk** [comment]
I had the same problem. Found a temporary solution by using keyboard shortcut CTRL + TAB to switch between the tabs.

**Comment by jigarce** [comment]
Thanks buddy!
Its working!

**Comment by oppositive** [comment]
I had the same thing. Documentation says: Disable graphics hardware acceleration through Tools>Options.
[https://docs.microsoft.com/en-us/sql/ssms/release-notes-ssms?view=sql-server-2017]

**Comment by jigarce** [comment]
Its working thanks @oppositive

**Comment by joelangell** [comment]
Thanks @oppositive!

**Comment by blanchardc** [comment]
Thanks @oppositive!

**Comment by bcooper1970** [comment]
Thank you guys so much!  I have tolerated this problem for years but now it is fixed!!
