### ISSUE TITLE
Can't restore database

### ISSUE THREAD

**Issue by rockn4** [MicrosoftDocs/sql-docs#2157]
Ellipses to find BAK file to restore database just freezes (Not Responding). Using 18.0 against a 14.0.1000.169 server

**Comment by VanMSFT** [comment]
Hello @rockn4!

Thanks for contacting Microsoft!  From my understanding, the issue you're describing seems to be an issue with the product, is that correct? If so, unfortunately, this form of contact is intended explicitly for reporting issues with the documentation, and not for the product. To get further assistance with your issue, we'd recommend engaging the community, or opening a ticket with Microsoft Support. More information can be found here: https://docs.microsoft.com/en-us/sql/sql-server/sql-server-get-help?view=sql-server-2017.

If you're looking to provide suggestions or ideas for improvement for the product,  you can do so at https://aka.ms/sqlfeedback.

If I'm mistaken, and you're submitting feedback for the documentation, please reply to this comment to clarify further. Otherwise, we'll proceed with closing out this Git Issue within a few business days.

Our apologies that the SQL Docs team was unable to assist you further with your issue, but we appreciate you reaching out. Please let us know if there's anything more we can do for you.

Thanks again and hope you have a wonderful rest of your day!
