### ISSUE TITLE
Case insensitive wildacard range

### ISSUE THREAD

**Issue by jahav** [MicrosoftDocs/sql-docs#2183]
Beware that wildcard ranges are not behaving same as expanded range even in simple cases with collate use. The page notes that 'In range searches, the characters included in the range may vary depending on the sorting rules of the collation.', but it doesn't work properly even for a simple case:

-- db collation Czech_CI_AS
create table People (Id int identity, GivenName nvarchar(100));
insert into People (GivenName) values ('Adam'), ('Bob'), ('cecilia');

select * from People person where person.GivenName collate SQL_Latin1_General_CP1_CS_AS like '[A-C]%'; -- result: Adam, Bob, cecilia
select * from People person where person.GivenName collate SQL_Latin1_General_CP1_CS_AS like '[ABC]%'; -- result: Adam, Bob

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5353a04-2e20-ae05-2004-6fd8a19c440a
* Version Independent ID: 382b0acd-1e14-c7fd-bf92-c3e09ccdf4fa
* Content: [LIKE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/like-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/language-elements/like-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/language-elements/like-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by srutzky** [comment]
Hello @jahav . Actually, this is behaving correctly. The issue is simply a misunderstanding of how it should work, and an incomplete test that doesn't show the _complete_ behavior. To be clear, the pattern `[ABC]` is just a multi-character wildcard, it is not a "range". It works similar to an `IN` list in that it will try to match against `'A' OR 'B' OR 'C'`.

The `[A-C]` pattern _is_ a range that will try to match against anything between `'A' AND 'C'` (inclusive). So the question is: what characters are between `A` and `C`? Well, due to using a case-sensitive collation, the order of the character is:

1. a
1. A
1. b
1. B
1. c
1. C

As you can see, lowercase "a" is _outside_ of that range, and lowercase "c" is _inside_ of that range. Your test included "c", but not "a". If we add sample data for "a" and "C", then we will see this in action (the following example is based on your code at the top of this issue):

```sql
-- DROP TABLE dbo.People;
CREATE TABLE dbo.People (Id INT IDENTITY, GivenName NVARCHAR(100));
INSERT INTO dbo.People (GivenName) VALUES (N'Adam'), (N'Bob'), (N'cecilia'), (N'aaron'),
      (N'Charles');


SELECT *
FROM   dbo.People
ORDER BY [GivenName] COLLATE Latin1_General_100_CS_AS_SC;
-- result: aaron, Adam, Bob, cecilia, Charles

SELECT *
FROM   dbo.People person
WHERE  person.GivenName COLLATE Latin1_General_100_CS_AS_SC LIKE N'[A-C]%'
ORDER BY [GivenName] COLLATE Latin1_General_100_CS_AS_SC;
-- result: Adam, Bob, cecilia, Charles

SELECT *
FROM   dbo.People person
WHERE  person.GivenName COLLATE Latin1_General_100_CS_AS_SC LIKE N'[A-c]%'
ORDER BY [GivenName] COLLATE Latin1_General_100_CS_AS_SC;
-- result: Adam, Bob, cecilia

SELECT *
FROM   dbo.People person
WHERE  person.GivenName COLLATE Latin1_General_100_CS_AS_SC LIKE N'[a-c]%'
ORDER BY [GivenName] COLLATE Latin1_General_100_CS_AS_SC;
-- result: aaron, Adam, Bob, cecilia
```


Please note that:

1. When using `NVARCHAR` data, it is best to _always_ prefix string literals with an uppercase "N", even if all characters are standard ASCII.
1. It's best to _always_ specify a schema name--it cuts down on errors and increases performance. 
1. It's best to use the newest collation possible for the culture you need. The `SQL_*` collations are very out of date and are missing sort weights for many thousands of characters and hundreds of uppercase/lowercase mappings)

**Comment by jahav** [comment]
Thank you very much for a thorough answer. I get it now.

**Comment by srutzky** [comment]
@jahav You are quite welcome. Please keep in mind that when using case-sensitive collations, ordering is not guaranteed to be lowercase first. Some collations, at least most of the `SQL_*` collations (and only when using `VARCHAR` data), sort uppercase first:

```sql
SELECT tmp.col
FROM (VALUES ('a'), ('A'), ('b'), ('B')) tmp(col)
WHERE tmp.col > 'a' COLLATE SQL_Latin1_General_CP1_CS_AS
ORDER BY tmp.col COLLATE SQL_Latin1_General_CP1_CS_AS;
-- B, b

SELECT tmp.col
FROM (VALUES (N'a'), (N'A'), (N'b'), (N'B')) tmp(col)
WHERE tmp.col > N'a' COLLATE SQL_Latin1_General_CP1_CS_AS
ORDER BY tmp.col COLLATE SQL_Latin1_General_CP1_CS_AS;
-- A, b, B
```
