### ISSUE TITLE
Getting different answer while using PARSENAME

### ISSUE THREAD

**Issue by aksajith** [MicrosoftDocs/sql-docs#2204]
When i am trying the below query, getting different answers.
` DECLARE @num2 decimal(26,10) = 152.00685100
 SELECT PARSENAME(@num2,1)      --- Output  :   0068510000
 SELECT PARSENAME(cast(@num2 as DOUBLE PRECISION),1)     ---- Output  : 007`

what is the difference in these query. What is doing in depth.
I just try to convert to NVARCHAR/VARCHAR and try. that also getting different result

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e238279-e2e3-6b0c-dfc0-1fc6e7449df4
* Version Independent ID: 26fa833a-91d2-88d7-7840-4e71b41b2826
* Content: [PARSENAME (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/parsename-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/functions/parsename-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/parsename-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by srutzky** [comment]
@aksajith This issue has nothing to do with `PARSENAME`. You are passing in numbers to a function which accepts a string input parameter. The difference in what you are seeing is happening in the implicit conversion from the particular number type into `NVARCHAR`. You can see this more clearly if you remove `PARSENAME` and just do the conversion explicitly:

```sql
DECLARE @num3 decimal(26,10) = 152.00685100;

SELECT CONVERT(NVARCHAR(500), @num3), -- 152.0068510000
       CONVERT(NVARCHAR(500), CONVERT(FLOAT, @num3)), -- 152.007
       STR(@num3, 18, 10); --     152.0068510000
```

You might also want to check out the [STR](https://docs.microsoft.com/en-us/sql/t-sql/functions/str-transact-sql) built-in function, as it converts number types into `VARCHAR`.

Also, I highly recommend using `FLOAT` instead of the synonym `DOUBLE PRECISION` as a lot of people might not immediately know that "DOUBLE PRECISION" == `FLOAT`. In almost 20 years of using SQL Server, I have never once seen someone use `DOUBLE PRECISION` (not in code, or a book, blog post, article, forum, chat room, etc).

Take care, Solomon..


(cc @CarlRabeler and @MikeRayMSFT )

**Comment by MikeRayMSFT** [comment]
@aksajith thank you for the question.
@srutzky thank you for the response.
I'm checking to see if we can clarify this in the documentation a bit.

**Comment by srutzky** [comment]
@MikeRayMSFT You are welcome.
