### ISSUE TITLE
Where is the current version of the rolling patching process?

### ISSUE THREAD

**Issue by SharePointBlackBelt** [MicrosoftDocs/sql-docs#2222]
This document doesn't talk about how to patch SQL Server with no downtime (rolling patch), and the old document on this process (_https://support.microsoft.com/en-us/help/958734/sql-server-failover-cluster-rolling-patch-and-service-pack-process) only applies to SQL2008-2012. Please update to SQL2017.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65cbc801-7d70-e5ad-ad39-706f6158966c
* Version Independent ID: 49c90818-20ca-2f32-d378-22be6aaf3fbf
* Content: [Install SQL Server Servicing Updates - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/install-windows/install-sql-server-servicing-updates?view=sql-server-2017#feedback)
* Content Source: [docs/database-engine/install-windows/install-sql-server-servicing-updates.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/install-windows/install-sql-server-servicing-updates.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @SharePointBlackBelt , thanks for contacting Microsoft! Rolling upgrades for a failover cluster instance are covered in this doc:
https://docs.microsoft.com/en-us/sql/sql-server/failover-clusters/windows/upgrade-a-sql-server-failover-cluster-instance?view=sql-server-2017

Please let me know if this doesn't suit your needs? Otherwise we will proceed with closing out this Git Issue in a few business days. 

Thanks!
