### ISSUE TITLE
Constants SQL_TYPE_UTCDATETIME and SQL_TYPE_UTCTIME aren't declared anywhere

### ISSUE THREAD

**Issue by ryanmajidi** [MicrosoftDocs/sql-docs#2248]
**submitted to [site feedback issue #1508](https://github.com/MicrosoftDocs/feedback/issues/1508) by @lsmith999999 on 5/17**

The constants SQL_TYPE_UTCDATETIME and SQL_TYPE_UTCTIME are currently cited here:

SQL Data Types
https://docs.microsoft.com/en-us/sql/odbc/reference/appendixes/sql-data-types?view=sql-server-2017

But they're not declared in any header I can find, nor can I find any relevant info on them after extensive searching. Why are they documented?

**Comment by MightyPen** [comment]
`SQL_TYPE_UTCDATETIME` is mentioned in:
docs\odbc\reference\appendixes\sql-data-types.md

**Comment by MightyPen** [comment]
@David-Engel Hi David, Can you please let me know whether you have access to any info that might answer this question (Issue 2248) from @ryanmajidi .
Is there a .h file that mentions `SQL_TYPE_UTCDATETIME`, or that should?
Thanks.  GeneMi.

**Comment by David-Engel** [comment]
The referenced documentation page is for generic ODBC and not only SQL Server, hence there is the sentence "A given driver and data source do not necessarily support all the SQL data types that are defined in this appendix." as well as the Important Note "The tables throughout this appendix are only guidelines and show typically used names, ranges, and limits of SQL data types." I suspect the intention is that if a specific DBMS supports that type, it would use that name and define it in its own .h file. SQL Server doesn't support the interval types either, for example.

**Comment by lsmith999999** [comment]
Thanks for the feedback and I agree that this has nothing to do with SQL Server. I'm not even targeting SQL Server specifically, and never mentioned it. "ryanmajidi" moved my original post here and it's not even clear if "here" means SQL Server only.

Note that I'm working on generic C++ classes for ODBC and these two types are definitely problematic, notwithstanding any wish-washy caveats in the docs about "guidelines" (or whether a given data source supports a particular type). Generic code that deals with these constants including one of MSFT's own examples (I'd have to locate it again), ultimately needs to pass SQL_DESC_CONCISE_TYPE to function "SQLColAttribute()" to return one of the (ODBC) SQL Data Type constants described in the docs I referenced (a very common usage scenario anyway). The code then needs to convert that type to its corresponding C data type (see "C Data Types" here at this writing https://docs.microsoft.com/en-us/sql/odbc/reference/appendixes/c-data-types?view=sql-server-2017) in order to know how to work with it (typically using a large C/C++ switch statement or equivalent since there's no native MSFT function that does the conversion - the MSFT example I mentioned even shows such a function being called but then mysteriously neglects to show its code). The switch statement in that function would normally need to handle *all* SQL Data Types types mentioned in the docs, including the two I cited (the subject of this post). How can this be done though since those two constants aren't declared anywhere. The docs are presumably targeting all native ODBC types (the subject of these docs), not driver-specific types. Driver-specific types such as SQL_SS_TIMESTAMPOFFSET, SQL_SS_TIME2 and others in SQL Server have no place in these particular docs. Those are declared in their own custom header of course, which for SQL Server is <sqlncli.h> (as I'm sure you know). If SQL_TYPE_UTCDATETIME and SQL_TYPE_UTCTIMEIf are also driver-specific then they shouldn't be mentioned in a list that's describing the native types (since programmers will obviously expect to find all types mentioned there in the native ODBC headers).

The upshot is why include two outlier types that aren't present in any of the installed ODBC headers (why aren't they?), or any other (non-MSFT) implementation of ODBC I can find. There's virtually no mention of them anywhere on the web in fact (try searching for them), unless they're using a different name. From a developer's perspective it's very confusing so what should a programmer do, just ignore them? Obviously not. They're in your docs so anyone would expect to find them in the native ODBC headers. They're not there though so programmers are forced to research them to find out what's going on (and everyone's time is wasted, mine and yours). A brief blurb in the docs itself to clarify the situation (next to those two types) would have saved us all the trouble (or just remove those types altogether if they're not native types, or perhaps they once were but are now obsolete - otherwise it begs the question why they're not declared in one of the native ODBC headers). I still have no idea if these two types can actually occur in a real-world situation, and have no clean (proper) way to handle them if they are encountered (since there's no declared constant for them).

In any case, I realize you were just trying to explain the situation and I appreciate it. To be perfectly blunt however (and this isn't directed at you personally), MSFT does a lot of great work but the docs are far too often incomplete and/or misleading (frequently requiring significant follow-up work to unravel the details). Squishy explanations like "I suspect the intention ... <YourOpinionHere>" just doesn't cut it (respectfully). We're in a highly detailed field where documentation needs to be precise. For now I apparently have no choice but to ignore these two constants. Presumably they'll be rarely encountered in the real world.

Anyway. thanks for your help (appreciated).

**Comment by MightyPen** [comment]
@ryanmajidi Given the preceding answer and exchange, I am now Closing this Issue 2248.

Thank you for bringing this situation to our attention. We hope to hear from you again.

**Comment by MightyPen** [comment]
Oops, I meant to notify @lsmith999999 that Issue 2248 is now being closed.

CC: @David-Engel

**Comment by oneeyeman1** [comment]
It would be nice if there would be some generic define that will say "This is a generic SQL data types that can be implemented by any DBMS" and another one which will say "this one will be implemented by some".
But I guess MS cares only about SQL Server and not the standard....

**Comment by SpriggsySpriggs** [comment]
Closed but not resolved. Alright.
