### ISSUE TITLE
It is safer to specify realm in kvno command

### ISSUE THREAD

**Issue by c4milo** [MicrosoftDocs/sql-docs#2257]
Just in case `/etc/krb5.conf` doesn't have `CONTOSO.COM` set as `default_realm` realm. 

```
kinit user@CONTOSO.COM
kvno MSSQLSvc/**<fully qualified domain name of host machine>**:**<tcp port>**@CONTOSO.COM
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffd6e9f1-17ab-7aea-818e-d2ab416e3891
* Version Independent ID: 3b789cdc-ca6c-4aca-ae01-b094926dbd7c
* Content: [Tutorial: Use AD authentication for SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-active-directory-authentication?view=sql-server-2017)
* Content Source: [docs/linux/sql-server-linux-active-directory-authentication.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-active-directory-authentication.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @Dylan-MSFT
* Microsoft Alias: **Dylan.Gray**

**Comment by MightyPen** [comment]
Hi @Dylan-MSFT , This sql-docs/docs/**linux/** Issue 2257 might be a documentation enhancement suggestion.  If so, please consider whether to edit in the enhancement.

CC: @MikeRayMSFT @rothja (because both of these Writers also work under docs/linux/).

**Comment by MikeRayMSFT** [comment]
@vin-yu - would you have a moment to review this?

**Comment by Dylan-MSFT** [comment]
Since we call out adding default_realm to /etc/krb5.conf in the instructions for joining a machine to the domain, does it make sense to not do this as it will catch that problem? If they don't have the default_realm value, they will have other problems with SQL. Would it make more sense to leave it this way but add a warning saying if no domain is added, then they should check krb5.conf? @tejasaks who wrote the docs

**Comment by c4milo** [comment]
>  Would it make more sense to leave it this way but add a warning saying if no domain is added, then they should check krb5.conf?

Make sense. Although, further down, in other examples the realm is being explicitly set too. For example https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-active-directory-authentication?view=sql-server-2017#spn, step 3.

**Comment by Dylan-MSFT** [comment]
> Although, further down, in other examples the realm is being explicitly set too
Yes, whatever we do, it should be consistent throughout the docs

**Comment by tejasaks** [comment]
I agree with making it consistent so we can add the @CONTOSO.COM in kvno command as suggested by c4milo. I also agree with Dylan that since we explicitly suggest/require customer to add default_realm in the (Join SQL Server on a Linux host to an Active Directory domain) page, we should add a Note suggesting that they ensure it has been done and point them to the AD join page.

**Comment by MikeRayMSFT** [comment]
@tejasaks - is that note similar to what the article says at: [Join SQL Server host to AD domain](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-active-directory-authentication?view=sql-server-2017#join)? Specifically: 
>You must join your SQL Server Linux host with an Active Directory domain controller. For information on how to join an active directory domain, see [Join SQL Server on a Linux host to an Active Directory domain.](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-active-directory-join-domain?view=sql-server-2017)

If it makes sense, I'd rather not repeat it. I'd simply move it to where it's more appropriate.

I'm updating the kvno command.

**Comment by MikeRayMSFT** [comment]
The initial request has been answered with PR 10664. Closing issue.
