### ISSUE TITLE
A SEARCHABLE Transact-SQL Reference Manual Please!

### ISSUE THREAD

**Issue by rlhane** [MicrosoftDocs/sql-docs#2267]
I don't want to attack the people who wrote this particular page but... This reference keeps getting worse and worse instead of better and better.  (1) The title in the topic list at left named "Transact-SQL (T-SQL)" Cannot be selected.  (2) It can never be the "top" so that search results do not include a flood of completely irrelevant results.  (3) Choosing the topic directly below the topic title of the same name sends you to this reasonably meaningless page in a different place in the topic hierarchy that does not give you reasonable access to the T-SQL topics, only links to other references!  (4) just try as an obvious example, searching for CONVERT, a T-sql function name. CROSS JOIN? FULL OUTER JOIN?   Ridiculous.  (5) You can't make ANY of the topics at left sticky or bookmark it, such as the "Functions" category.  None of them.  Every time I want to find something I have to wade through the topics and subtopics and subtopics because (a) this page has no direct links to its subtopics, (b) subtopics can't be bookmarked, and (c) entering search text in "Filter by title" is worthless. Hey, I guess it could be worse.  At least stuff a pile of links in here to the subtopics of Transact-SQL please.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c90a9561-bef5-25e8-e672-ed0d4493a383
* Version Independent ID: 16c705c1-55be-d339-8326-51d57cb0fd69
* Content: [Transact-SQL Reference (Database Engine) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/language-reference?view=sql-server-2017)
* Content Source: [docs/t-sql/language-reference.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/language-reference.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by RegexPro** [comment]
There's a lot of issues and (shared) frustrations noted in your comment.  In the meantime, I've found that Bing does a very good job of delivering the page I'm looking for when I search for 'tsql <my topic | page>'.

For me, the biggest pain point is the inaccuracy of the search/filter bar.  If that can be resolved, the need to navigate manually would be 95% gone, and any bugs or design limitations in the topic tree would be far less frustrating.

The fundamental flaw with the search/filter bar is its lack of scope.  Aside from unsociable bad breath, it does not prefer search results for the current page's branch of the topic tree.  I think users expect that when they are already detailed into 'Docs/SQL/Reference/Transact-SQL (T-SQL) Reference', the results will be- if not strictly scoped to the current branch- then at least sorted from current branch to root.  If a user needs to broaden the search, links to each root level are already close-by.
![image](https://user-images.githubusercontent.com/36213797/59631372-7e803300-90fc-11e9-905c-ca39ce62affd.png)

In the example below, I'd like the results sorted as:
a. Page scope- the leaves within _./Queries_ (result #34)
b. Search box scope- other branches of _./Reference/Transact-SQL (T-SQL) Reference_ (result #33)
c. Larger scope (by special dispensation or algorithm?)- other branches of _./Reference_ when it makes sense
![image](https://user-images.githubusercontent.com/36213797/59632075-2e09d500-90fe-11e9-8669-8519056da0c7.png)

I would also like to have preference for full string matches over partial string matches, and start-of-string matches over any-position matches.

Finally, a picky comment- the 'filter by title' text is misleading, because the filter is an ephemeral search results overlay, not a true filter of the topic tree.  I typically don't want to filter the topic tree anyway; I want to traverse it.

Thanks for considering!  FYI, docs.Microsoft.com is streets ahead of Oracle and other developer reference sites.  Thank you for all the careful thought and investment you've put into such a tremendous product!

**Comment by rlhane** [comment]
MightyPen is DEAD ON. _Please consider his suggestions_ for making this huge investment in documentation, especially this Transact-SQL Reference, the useful tool it should and could be.

**Comment by MightyPen** [comment]
@sudeepku Hi Sudeep, Last week this Issue 2267 had screenshots added to explain suggestions for how the TOC Search textbox feature might be changed.  The screenshots build on the points made by the original poster.
You may like to consider these ideas.

@rlhane @RegexPro

I am now Closing this Issue 2267, as a successful Issue. These ideas are interesting, and they have been communicated to the proper people within Microsoft.
Thank you for submitting this interesting Issue. We hope to hear from you again.
The @ notification mechanism continues to work even after an item is Closed, in case further communication is needed.

CC: @MashaMSFT

**Comment by MightyPen** [comment]
Related: 
- AzBoards > CeApex > Engineering > 92405
