### ISSUE TITLE
VIEW DATABASE STATE permission on Azure SQL Database

### ISSUE THREAD

**Issue by tbolon** [MicrosoftDocs/sql-docs#2272]
This documentation states that : "On SQL Database, requires the VIEW DATABASE STATE permission in the database.".

But trying to use that view with a dbo contained user on my Azure SQL Database results in an error : "Msg 300, Level 14, State 1, Line 6 VIEW SERVER STATE permission was denied on object 'server', database 'master'."

So, it seems this view requires VIEW SERVER STATE on SQL Database, which is not clearly indicated in the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5953bdd-7283-0051-aadb-fb84ecb8bb37
* Version Independent ID: e36d75e3-caf1-ccd9-4cc1-43c58139205c
* Content: [sys.dm_fts_active_catalogs (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-fts-active-catalogs-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/system-dynamic-management-views/sys-dm-fts-active-catalogs-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-dynamic-management-views/sys-dm-fts-active-catalogs-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @pmasl
* Microsoft Alias: **pelopes**

**Comment by MightyPen** [comment]
@pmasl Hi Pedro, Can you clarify the permissions need here in Issue 2272, for Azure SQL Database, between:
- VIEW DATABASE STATE
- VIEW SERVER STATE

Maybe an Edit/Update to the article is needed too.

CC: @stevestein @VanMSFT

**Comment by tbolon** [comment]
Maybe (if not present) add a link to the sys.fulltext_catalogs help page which can be used without the VIEW SERVER STATE permission?

**Comment by pmasl** [comment]
Apologies for the delayed reply. There is no VIEW SERVER STATE permission on Azure SQL DB, so this is a bug. Adding @joesackmsft as the owner for Azure SQL DB for comment.

**Comment by WilliamAntonRohm** [comment]
@joesackmsft -- please look into this aging issue 2272.

@stevestein, @VanMSFT -- please consider a documentation update.

**Comment by VanMSFT** [comment]
Hi @tbolon, thank you for bringing this issue to our attention. Since this DMV is scoped for the server level, it requires the VIEW SERVER STATE permission on the server when using SQL Database Standard or Basic Tiers. Since you are not able to grant this permission to users in the **master** database, only server admins are able to query server level DMVs.

On Premium Tiers, you would be able to grant VIEW DATABASE STATE permissions to the contained user in the scoped database, and run server or database level scoped DMVs on that database.

@stevestein  - Please close https://github.com/MicrosoftDocs/sql-docs-pr/pull/10970. We had the proper wording to address this in the past, but it was removed. I'll look to add it back in via another PR.

**Comment by VanMSFT** [comment]
https://github.com/MicrosoftDocs/sql-docs-pr/pull/11064

**Comment by VanMSFT** [comment]
Docs should go live soon with changes to permission. Closing.
