### ISSUE TITLE
Cant tell which way the difference goes from this page

### ISSUE THREAD

**Issue by MP7373** [MicrosoftDocs/sql-docs#2280]
This is a simple function and there is a page of documentation and I've been looking at I for 5 minutes and still don't know if DATEDIFF(day, '2007-05-06 12:10:09', '2007-05-05 12:10:09') will return -1 or 1. The RETURN value section should say something like "Returns startdate - endate" or "Returns enddate - startdate" or "Returns the absolute value of startdate - enddate" in the first arguments units. Instead it only lists a bunch of edge cases and doesn't tell you what the function actually does.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 340056a9-0593-4289-7b72-601ae718b05f
* Version Independent ID: 1db8e288-8068-be96-b2f2-c8a2fe5a857a
* Content: [DATEDIFF (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/datediff-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/functions/datediff-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/datediff-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by MightyPen** [comment]
Fixing this Issue 2280 by using PR 10577.
https://github.com/MicrosoftDocs/sql-docs-pr/pull/10577

@MikeRayMSFT hi Mike, I am fixing this Issue 2280 for you. There is no further work for you here. Welcome.

**Comment by MightyPen** [comment]
PR 10578 manually undid the changes of 10577, probably to avoid Merge Conflicts.

@MikeRayMSFT Mike, I must reAssign this Issue 2280 from me to you. Between you or Pedro, one of you should add clarification equivalent to what I added (in 10577) under H2 Return value. The customer, @MP7373 , has a valid point.  Thanks, G.

**Comment by MikeRayMSFT** [comment]
@pmasl  - as you know we rolled back the initial changes, and would appreciate your input on the customer issue.

**Comment by WilliamAntonRohm** [comment]
@MikeRayMSFT -- please review the duplicated changes in https://github.com/MicrosoftDocs/sql-docs-pr/pull/11115

cc:  @pmasl

**Comment by pmasl** [comment]
Do not merge the PR. Most of the PR is code embellishment, but introduces docs formatting errors (code syntax is NOT marked as tsql because its not executable, like examples are) and the additional comments added are extraneous.

I’ve slightly reworded some of the content in PR 11116 and merging those. Also found that datediff_big already had the docs formatting error that I’m reverting too.

Thanks

Pedro Lopes

[cid:image002.png@01D53D73.73521430]<http://twitter.com/SQLPedro>    [cid:image004.jpg@01D53D73.73521430] <http://linkedin.com/in/pedroazevedolopes>

Need a way to keep indexes and statistics healthy? Check out AdaptiveIndexDefrag<http://aka.ms/AdaptiveIndexDefrag>!
Check your SQL Server for known best practices and performance issues with BPCheck<http://aka.ms/BPCheck>.
Learn T-SQL Querying book: aka.ms/LearnTSQLQuerying<https://aka.ms/LearnTSQLQuerying>
Follow the Tiger Team on Twitter: @mssqltiger<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftwitter.com%2Fmssqltiger&data=02%7C01%7CPedro.Lopes%40microsoft.com%7Cc37a192ec20e4e1def0808d491979277%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636293527558948856&sdata=Qs7kO%2Bxm1zK0a1WVphfCDZXjhyHTdVmS0QBHJb8tgOw%3D&reserved=0> | Blog: aka.ms/sqlserverteam<http://aka.ms/sqlserverteam>

**Comment by pmasl** [comment]
Addressed in PR #11116. This can be closed

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
