### ISSUE TITLE
LocalDB Start/Stop?

### ISSUE THREAD

**Issue by Chaz6** [MicrosoftDocs/sql-docs#2321]
It would be useful to explain why a LocalDB needs to be started and stopped. SQLite on the other hand does not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80ae2735-1406-baf7-df41-5f2b930c132a
* Version Independent ID: 99241f21-4b3a-5a5d-1257-38ed9d5be434
* Content: [SqlLocalDB Utility - SQL Server](https://docs.microsoft.com/en-us/sql/tools/sqllocaldb-utility?view=sql-server-2017#feedback)
* Content Source: [docs/tools/sqllocaldb-utility.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/sqllocaldb-utility.md)
* Product: **sql**
* Technology: **tools-other**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by stevestein** [comment]
@Chaz6 - Thanks for raising this issue!

There's no single reason to stop a LocalDB, and there's no requirement that you ever stop it. Because it's designed for small-scale applications and may not need to be running full time, you may, for example, want to stop the db to free up resources.

I'm going to go ahead and close this one. Thanks!
