### ISSUE TITLE
CREATE USER FROM EXTERNAL PROVIDER by Service Principal

### ISSUE THREAD

**Issue by alexmbaker** [MicrosoftDocs/sql-docs#2323]
I am using an Azure Active Directory Service Principal to authenticate with an Azure SQL Database.  Everything works as I would expect except when I try to add an Azure AD user to the database using a script similar to: 

CREATE USER [bob@contoso.com] FROM EXTERNAL PROVIDER;

I can run the script without issue however the Service Principal returns Error 33134, Severity 16, Message "Principal 'bob@contoso.com' could not be found at this time. Please try again later."

I can think of a couple of reasons for this however I think the most likely cause being the Service Principal not having been granted a required permission.  

Could you include details in this document of the Azure AD permissions required to successfully execute a CREATE USER .... FROM EXTERNAL PROVIDER statement.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65ba42b4-26ac-259a-5f2a-4c96e00f1645
* Version Independent ID: b5d8007e-38e2-b99f-7fd8-975d9bd390b7
* Content: [CREATE USER (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-user-transact-sql?view=sql-server-2017)
* Content Source: [docs/t-sql/statements/create-user-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-user-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by msebolt** [comment]
Hi @alexmbaker, thank you for the feedback!

This issue has been addressed on the [forums](https://social.msdn.microsoft.com/Forums/en-US/84d9448e-ad26-4b29-9500-f473f96da128/azure-ad-authentication-on-azure-sql-unable-to-create-users-from-external-provider-in-db?forum=WindowsAzureAD) and via [blog post](https://blogs.msdn.microsoft.com/sqldw/2017/07/28/adding-ad-users-and-security-groups-to-azure-sql-data-warehouse/).

Please comment if either of these posts answers your questions.

**Comment by alexmbaker** [comment]
@msebolt while the links you have provided do cover a similar area of functionality they do not discuss the specific use case.  Consider this script:
``` SQL
CREATE USER [alex.baker@dhhs.vic.gov.au] FROM EXTERNAL PROVIDER
```
When I execute this script against my Azure SQL database it works exactly as expected.  

The issues arise with this scenario:

* I create a service principal in the Azure Active Directory
* Create a group in the Azure AD - lets say 'sql-admins' and
** Add myself to the group
** Add the service principal to the group
* Make the group the Azure AD administrator of my Azure SQL Server

Again, if I connect to an Azure SQL database on my server I can run the script above successfully

Things go wrong when I:

* Obtain a SQL Server access token for the service principal
* Using the access token connect to the SQL Database - (so far so good I can issue DDL and DML scripts)
* When I run the script above then I encounter the issue I reported.

We have been experimenting today and have found that adding the service principal to the built in Azure AD Role [Directory Readers](https://docs.microsoft.com/en-us/azure/active-directory/users-groups-roles/directory-assign-admin-roles#directory-readers) resolves the issue.  What I don't know is if this is the Microsoft recommended approach?  Should we perhaps be granting the service principal an API Permission to the Microsoft Graph or Azure Active Directory API?

**Comment by VanMSFT** [comment]
Hi @alexmbaker - You should not have to add the user to the AAD role Directory Readers. Our Product Team is looking to fix this issue in the next month. I hope that helps.

**Comment by VanMSFT** [comment]
Closing this for now. Our Product Team is already working on a fix, and we'll update the documentation when it's ready. Please let us know if there are any further concerns.

**Comment by michaelsync** [comment]
@VanMSFT 

Does it fix?  

I have a similar issue but different error. 

I can execute this script `CREATE USER [AAD-UserGroup] FROM EXTERNAL PROVIDER` using my AAD user but I got the following error when I execute it with the service principle. 

> that access between first-party applications must be handled via preauthorization

According to this page https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/sql-database/sql-database-aad-authentication-configure.md, it recommended using the user instead of the service principle. I am not sure if it's a limitation or a bug.

**Comment by VanMSFT** [comment]
Hi @michaelsync - We currently don't allow service principals to create users in SQL DB. We will update the documentation when this feature is available. Thanks!

**Comment by alexmbaker** [comment]
Simply create a group in your Azure active directory, add the service principal to the group.  
Now create the database user from the group and you have what you need.


Alex Baker



On Fri, Mar 6, 2020 at 6:56 AM +1100, "Van To" <notifications@github.com> wrote:












Hi @michaelsync - We currently don't allow service principals to create users in SQL DB. We will update the documentation when this feature is available. Thanks!

**Comment by Rookian** [comment]
> Hi @michaelsync - We currently don't allow service principals to create users in SQL DB. We will update the documentation when this feature is available. Thanks!

Hi @VanMSFT we are also effected by this issue. Is there any news regarding this topic? Is there a schedule for beeing able to use `Service Principal` in order to create `Managed Identity` based SQL users?

**Comment by Rookian** [comment]
> @msebolt while the links you have provided do cover a similar area of functionality they do not discuss the specific use case. Consider this script:
> 
> ```sql
> CREATE USER [alex.baker@dhhs.vic.gov.au] FROM EXTERNAL PROVIDER
> ```
> 
> When I execute this script against my Azure SQL database it works exactly as expected.
> 
> The issues arise with this scenario:
> 
> * I create a service principal in the Azure Active Directory
> * Create a group in the Azure AD - lets say 'sql-admins' and
>   ** Add myself to the group
>   ** Add the service principal to the group
> * Make the group the Azure AD administrator of my Azure SQL Server
> 
> Again, if I connect to an Azure SQL database on my server I can run the script above successfully
> 
> Things go wrong when I:
> 
> * Obtain a SQL Server access token for the service principal
> * Using the access token connect to the SQL Database - (so far so good I can issue DDL and DML scripts)
> * When I run the script above then I encounter the issue I reported.
> 
> We have been experimenting today and have found that adding the service principal to the built in Azure AD Role [Directory Readers](https://docs.microsoft.com/en-us/azure/active-directory/users-groups-roles/directory-assign-admin-roles#directory-readers) resolves the issue. What I don't know is if this is the Microsoft recommended approach? Should we perhaps be granting the service principal an API Permission to the Microsoft Graph or Azure Active Directory API?

Did you use `Azure.Identity` or the old `Microsoft.Azure.Services.AppAuthentication`? I tried your solution (assigning Directory Readers) with `Azure.Identity` without success.

**Comment by VanMSFT** [comment]
Hi @alexmbaker and @Rookian - There will be a tutorial coming out on this in the next week or so. This is going in preview, but @alexmbaker had it right. 

1. Assign a server identity to the Azure SQL logical server
   - `Set-AzSqlServer -ResourceGroupName <resource group> -ServerName <Server name> -AssignIdentity`
2. Grant the **Directory Readers** permissions to the server identity.

**Comment by Rookian** [comment]
Hi @VanMSFT!
We have continued to research the topic and propose the following alternative solution.
We ask Microsoft kindly to verify the solution described below and to inform whether this is an approperiate solution.

**Proposed solution**  
A service principal is configured to create various resources in a subscription.
This service principal has to be assigned to the `Directory Readers` role in the AAD in order to determine the Application Id for a Managed Identity in the context of the deployment process.

The configured “Managed Identity” of the Azure App Service can be registered on the respective Azure SQL database with the following command.

```sql
CREATE USER [{managedIdentityName}] WITH SID={applicationSid}, TYPE=E
```

The SID (`applicationSid`) passed in the SQL statement is now resolved by the deployment process and is accepted by the SQL Server without verification. You can use the .NET Core library `Microsoft.Azure.Management.Graph.RBAC.Fluent` to obtain the Application Id for an AAD registered application (Managed Identity). 

```csharp
var principal = await Az.GraphApi.ServicePrincipals.GetByNameAsync(managedIdentityName);
var applicationId = Guid.Parse(principal.ApplicationId);
var applicationSid = FormatSqlByteLiteral(applicationId.ToByteArray());

private static string FormatSqlByteLiteral(byte[] bytes)
{
    var stringBuilder = new StringBuilder();
    stringBuilder.Append("0x");
    foreach (var @byte in bytes)
    {
        if (@byte < 16)
        {
            stringBuilder.Append("0");
        }
        stringBuilder.Append(Convert.ToString(@byte, 16));
    }
    return stringBuilder.ToString();
}
```

After that, authorization roles (e.g. `db_datareader`, `db_datawriter`, `db_ddladmin`) can now be assigned to the assigned Managed Identity.

```sql
ALTER ROLE {role} ADD MEMBER [{managedIdentityName}];
``` 

**Conclusion**  
The Azure App Service can now access the previously authorized Azure SQL database in the context of its Managed Identity.

**Regarding your proposed solution of using SQL Server Managed Identity and assign it the `Directory Readers` role**
Please keep in mind that a lot of companies out there have very strict regulations when it comes to Azure AD administration. Your proposed solution has two possible approaches
#1 Grant Service Principal permission to assign Azure AD roles in order to assign `Directory Readers` role to SQL Server Managed Identity. This is a security nightmare, because now the Service Principal could assign e.g. `Global administrator` or other roles. 
#2 Manually assigning `Directory Readers` role by an Azure AD admin after SQL Server is provisioned. (error-prone and cumbersome)

**Comment by valx** [comment]
Hi all,
I am working with a very similar scenario as @Rookian (Thanks for posting it!), and his solution seems to work for us.

I am working with user groups (instead of individual users) and programming in Python, so I used the following code:
- using MS Graph REST API to get user SID
`
    resource = "https://graph.microsoft.com/"
    authority_url = (parameters['authorityHostUrl'] + '/' +
                    parameters['tenant'])
    context = adal.AuthenticationContext(
        authority_url, api_version=None
        )
    token = context.acquire_token_with_client_credentials(
        resource,
        parameters['clientId'],
        parameters['clientSecret'])
    accessToken = token["accessToken"]

    result = requests.get(
        (f'{resource}v1.0/groups/?$filter=startswith(displayName,\'{prefix}\')'
         f'&$select=id,securityIdentifier,displayName'),
        headers={'Authorization': accessToken})
` 

And I wrote the following function to convert the SID from the format returned from MS Graph into the one used in SQL Servers (I couldn't find any documentation, so I have reverse engineered this function)
`
def convert_graphSid_to_sqlSid(g_sid):
    """
    converts a string representing a users/groups Security ID (SID) in Azure Graphs 
    into a string representing SID for Azure SQL server users/groups.
    The ouput is a 16 bytes Hex representation of the last 4 10-digits-blocks of the graph SID

    Example:
    input g_sid: 'S-2-24-2-1232761456-456137123-1234432456-1235122456'
    output s_sid: '0x70727A49A319301BC8F1934918799E49'
    """

    # split the g_sid by '-' and take the last 4 elements
    l_g_sid = g_sid.split('-')[4:]

    # for each 10 digit string block: convert string to int, convert int to byte,
    # convert the bytes to their hexadecimal representation.
    # Byteorder is "little": the most significant byte is at the end of the byte array
    s_sid = ''.join(map(lambda x: int(x).to_bytes(4,'little').hex().upper(), l_g_sid))
    s_sid = '0x' + s_sid
    
    return s_sid
`

finally the SQL code to create SQL user associated to the AD user groups:
`
CREATE USER [user-group-name]  WITH SID=0x70727A49A319301BC8F1934918799E49, TYPE=X;
`

**Comment by TroyWitthoeft** [comment]
> Hi @alexmbaker and @Rookian - There will be a tutorial coming out on this in the next week or so. This is going in preview, but @alexmbaker had it right.
> 
> 1. Assign a server identity to the Azure SQL logical server
>    
>    * `Set-AzSqlServer -ResourceGroupName <resource group> -ServerName <Server name> -AssignIdentity`
> 2. Grant the **Directory Readers** permissions to the server identity.

@VanMSFT  Do we have a link to the tutorial?

**Comment by VanMSFT** [comment]
@TroyWitthoeft - Yes, that is the new tutorial.

**Comment by GithubMirek** [comment]
Please be aware that:
SID and TYPE represent an undocumented, unsupported and unsecured commands and will be removed in the near future.
For  proper solution please review  the main docs indicated below
https://docs.microsoft.com/en-us/azure/azure-sql/database/authentication-aad-service-principal
https://docs.microsoft.com/en-us/azure/azure-sql/database/authentication-aad-service-principal-tutorial
https://docs.microsoft.com/en-us/azure/azure-sql/database/authentication-aad-directory-readers-role
https://docs.microsoft.com/en-us/azure/azure-sql/database/authentication-aad-directory-readers-role-tutorial
Mirek Sztajno, Senior PM, Azure SQL

**Comment by robdmoore** [comment]
Hi @GithubMirek,

A bit of feedback on that point.

Context: You want to fully automate the end to end of an environment (including SQL Database as one component) and you are doing this from a DevOps deployment pipeline running as an Azure AD Service Account.

If you want to create access for Azure AD users to access the database (say a service principal for a web app) as part of this automation then, per the links above, you need to grant Directory Readers access to the service principal of the SQL Server. While it's a bit complex to set up, it can be automated (I've created some PowerShell that does it).

The feedback I want to provide is:

* Access to grant that kind of privilege (Privileged Roles Administrator) is a very high privilege so in most security conscious environments you won't want to grant that to the Service Principal
* You can absolutely make use of the role-assignable group technique mentioned in the third link above to create a group that gives members Directory Reader access and then give the automation service principal access to add the sql server service principal to that group, but this functionality requires Azure AD Premium, which not all environments will have
* If you can't do the above 2 options then you are forced to use the SID approach mentioned above. While it's not formally documented, it does work and the result of it (as far as I can tell) is the same as calling CREATE USER FROM EXTERNAL.

If there is a future plan to remove the ability for the SID option to work then I'd humbly request that you consider one or more of:

* Allowing the use of role-assignable groups in non Azure AD Premium
* Allowing for an Azure SQL Database to be created with Directory Readers role automatically assigned (maybe via an Azure Resource Manager flag?) so you don't have to go through hoops to allow it to happen
* Allowing for a call to CREATE USER FROM EXTERNAL call to receive the object ID (users/groups) or application ID (service principals) so that it can be called from a normal SQL user or an Azure AD service principal where the sql server principal doesn't have Directory Reader role
  * My thinking here is that in the automation we have the object ID / application ID of the principals being granted so it's actually better to just give that to the SQL database to identify the user anyway rather than rely on it looking up a name and converting to an object ID (which is, as far as I can tell, the only reason it needs Directory Reader in the first place).

Happy to jump on a Teams call to talk in more detail if that's helpful. I'm in GMT+8 (Perth, Australia) timezone.

Thanks

Rob

**Comment by GithubMirek** [comment]
We plan to add a T-SQL syntax CREATE USER [name ] FROM EXTERNAL PROVIDER WITH OBJECT_ID= ' ObjectID’ 
The Object  ID will be verified in AAD if present there. The name can be aad_name or any name unique in the sys.database_principals.

**Comment by robdmoore** [comment]
Cool! Will that call require the sql server principal to have Directory Reader role though?

**Comment by mkosieradzki** [comment]
Looks awesome! Is there any ETA?

**Comment by jason-swissre** [comment]
> We plan to add a T-SQL syntax CREATE USER [name ] FROM EXTERNAL PROVIDER WITH OBJECT_ID= ' ObjectID’
> The Object ID will be verified in AAD if present there. The name can be aad_name or any name unique in the sys.database_principals.
> Thanks,
> Mirek

Hi, is this feature being tracked somewhere public or is this issue the correct place to watch?  If the latter, why is this issue closed?

**Comment by VanMSFT** [comment]
Hi @jason-swissre - This is tracked internally. Unfortunately, we can't promise any timelines

**Comment by jason-swissre** [comment]
That's fair but please have someone post here when it changes as those of us who can't wait are relying on the deprecated behavior until your solution is finished.

**Comment by Rookian** [comment]
> Hi @jason-swissre - This is tracked internally. Unfortunately, we can't promise any timelines

@VanMSFT @GithubMirek Are there any news relating to your proposed solution?
We would like to avoid the creation of separate Azure AD groups (with Directory reader role) as a workaround.

```sql
CREATE USER [name] FROM EXTERNAL PROVIDER WITH OBJECT_ID= 'ObjectID’
```

**Comment by VanMSFT** [comment]
Hi @Rookian - The feature has not been released for public preview.

**Comment by Rookian** [comment]
> Hi @Rookian - The feature has not been released for public preview.

But has it been under development?

**Comment by VanMSFT** [comment]
Hi @Rookian - We appreciate the question, but unfortunately, we can't provide product roadmaps in our documentation

**Comment by TroyWitthoeft** [comment]
@VanMSFT - No comment eh?  I hear ya... wink wink.  
@Rookian - I don't work for MS, but from all the comments above by @GithubMirek and others that do, I think it's safe to say they plan on introducing this feature.  Just no set dates.

**Comment by MichelZ** [comment]
Which can really mean anything in Microsoft land. We're working on it and it's very close (3 months) to release. 
OR
It's somewhere in a system, and maybe with a lot of luck we get to it in 10 years.

Really not useful unfortunately.

**Comment by ilmax** [comment]
this `FROM EXTERNAL PROVIDER WITH OBJECT_ID...` works today in azure sql apparently

**Comment by Rookian** [comment]
> this `FROM EXTERNAL PROVIDER WITH OBJECT_ID...` works today in azure sql apparently

Any official news about that @VanMSFT and @GithubMirek?

**Comment by HiroyukiSakoh** [comment]
Why was the document description deleted once added?
https://github.com/MicrosoftDocs/sql-docs/commits/live/docs/t-sql/statements/create-user-transact-sql.md
@VanMSFT

**Comment by VanMSFT** [comment]
@HiroyukiSakoh - It's not ready to be supported.

**Comment by HiroyukiSakoh** [comment]
I tried the new syntax `FROM EXTERNAL PROVIDER WITH OBJECT_ID=` today.
The role of directory leader was still required.

What has changed compared to `FROM EXTERNAL PROVIDER`?

I just want to grant access to WebApps Managed ID without directory reader.
So I still have to continue to use `WITH SID=, Type=E`...

**Comment by VanMSFT** [comment]
@HiroyukiSakoh - If you can't grant the Directory Readers role, you will still need to give proper permissions to the server/instance identity documented here: https://docs.microsoft.com/en-us/azure/azure-sql/database/authentication-azure-ad-user-assigned-managed-identity#permissions

The new syntax is not yet supported, and even if it is, won't remove restrictions on providing the necessary permissions.

**Comment by HiroyukiSakoh** [comment]
@VanMSFT 
When operating a subscription on my customer's AAD tenant,I am a guest user and it is very difficult to request a directory role(or permission).

I want to add a user with AAD authentication for a SQL database,even if the guest user only has the contributor role for subscriptions.

I am now using the `SID Type=E` command to create resources and users in ARMTemplate as in this example and it is working well.
https://gist.github.com/HiroyukiSakoh/0e84bab0a0adc21082d8fac03cb71d0b


https://github.com/MicrosoftDocs/sql-docs/issues/2323#issuecomment-719003520
This comment says it will be removed in the near future.
Please do not remove the way to add AAD authenticated users in SQL databases without AAD role(or permission) assignments.

I have never needed directory roles at all with KeyVault or any other Azure service.
Why do only SQL databases need directory roles(or permission)?

**Comment by VanMSFT** [comment]
@HiroyukiSakoh - The role/permissions are necessary for the server/instance identity to read from AAD.  The user adding principals to the database doesn't need those permissions, but you can reason why a server identity would need it.

Unfortunately, I can't comment on any future releases, and don't have that information as well. The Docs team is only responsible for documentation issues, and you're asking about product questions.

**Comment by WilliamAntonRohm** [comment]
@All -- please add and then upvote this issue here:
- [SQL Server feedback](http://aka.ms/sqlfeedback)

**Comment by chwunder** [comment]
> Hi all, I am working with a very similar scenario as @Rookian (Thanks for posting it!), and his solution seems to work for us.
> 
> I am working with user groups (instead of individual users) and programming in Python, so I used the following code:
> 
> 1. Get user SID using MS Graph REST API:
> 
> ```python
>     prefix = "user-group-name" # user group name (or prefix of the name)
>     resource = "https://graph.microsoft.com/"
>     authority_url = (parameters['authorityHostUrl'] + '/' +
>                     parameters['tenant'])
>     context = adal.AuthenticationContext(
>         authority_url, api_version=None
>         )
>     token = context.acquire_token_with_client_credentials(
>         resource,
>         parameters['clientId'],
>         parameters['clientSecret'])
>     accessToken = token["accessToken"]
> 
>     result = requests.get(
>         (f'{resource}v1.0/groups/?$filter=startswith(displayName,\'{prefix}\')'
>          f'&$select=id,securityIdentifier,displayName'),
>         headers={'Authorization': accessToken})
> ```
> 
> The SID can be extracted from the `result` json.
> 
> 2. convert the SID from the format returned from MS Graph into the one used in SQL Servers.
>    I wrote the following function for the conversion (I couldn't find any documentation, so I have reverse engineered this function).
> 
> ```python
> def convert_graphSid_to_sqlSid(g_sid):
>     """
>     converts a string representing a users/groups Security ID (SID) in Azure Graphs 
>     into a string representing SID for Azure SQL server users/groups.
>     The output is a 16 bytes Hex representation of the last 4 10-digits-blocks of the graph SID
> 
>     Example:
>     input g_sid: 'S-2-24-2-1232761456-456137123-1234432456-1235122456'
>     output s_sid: '0x70727A49A319301BC8F1934918799E49'
>     """
> 
>     # split the g_sid by '-' and take the last 4 elements
>     l_g_sid = g_sid.split('-')[4:]
> 
>     # for each 10 digit string block: convert string to int, convert int to byte,
>     # convert the bytes to their hexadecimal representation.
>     # Byteorder is "little": the most significant byte is at the end of the byte array
>     s_sid = ''.join(map(lambda x: int(x).to_bytes(4,'little').hex().upper(), l_g_sid))
>     s_sid = '0x' + s_sid
>     
>     return s_sid
> ```
> 
> 3. Finally the SQL code to create SQL user associated to the AD user groups:
> 
> ```sql
> CREATE USER [user-group-name]  WITH SID=0x70727A49A319301BC8F1934918799E49, TYPE=X;
> ```

I have actually done exactly the same thing, but for me users try to authenticate using their AAD credentials will still get this error: Login failed for user '<token-identified principal>'. (.Net SqlClient Data Provider)

I have a Service Principal having the directory reader permissions but I have used this one just to create the sql server as well as the sql database. Neither a User assigned managed Identity nor a System assigned managed Identity are in place. Now we are using pyodbc to connect to this database using the service principal and try to create this command: CREATE USER xxxx FROM EXTERNAL PROVIDER; which fails with the error message: no graph permissions / directory reader. 

As i understood the workaround from valx you can do this without granting any permissions to neither the UAMI, SAMI nor the Service Principal, you just need a user or SP beforehand to transform the SID into a HEX and running the statement cCREATE USER [USERGROUP] WITH SID=0x72C47B3D97403C4E9663338B6C711111, TYPE=X; .... to get it to work. I did all of this but my users are still not able to authenticate using their AAD credentials ... any ideas?

**Comment by jason-swissre** [comment]
Any update on this issue?  What ever change is made, we will need to be able to add AD users without having any additional permissions from what we have now.  If the SQL server has to have access to AAD, that's fine and expected but not clients trying to add external users.

**Comment by darootler** [comment]
Hi all,

you mentioned the workaround for the „CREAT
E USER“. Thanks for that.

But whats the workaround for „CREATE LOGIN“?

Regards
Richard

**Comment by syedhamjath** [comment]
People thought that SID and Graph API permission wow is difficult. Guess what, it became unpredictable now. 

Let me explain, its possible to have two Identity with same name so without OBJECT ID parameter no one can be sure what is being added in Azure SQL database.

I just checked Azure SQL db, it doesn't have these options (OBJECT ID and SID) with external provider. Now what will happen if I had two user assigned identity with same name with graph API permission to AZ SQL's identity and run CREATE SQL USER statement. Which one will be selected? I can't use OBJECT ID in Azure SQL database  because there is no option described in documentation.

I wasted lot of time today and finally found out this thread, I can't wait to see this thing grow complicated.

In fact this should be marked as bug for Azure SQL db or missing docs.

**Comment by BenjaminAbt** [comment]
It's now been another year where we still don't have an end to end solution for Azure SQL DevOps.

We are still waiting for
> We plan to add a T-SQL syntax CREATE USER [name ] FROM EXTERNAL PROVIDER WITH OBJECT_ID= ' ObjectID’
which is a statement from 2021.

It would be nice if there was some information on what happens next. Or information that there will be no official, secure solution.
Thanks, Ben.

**Comment by VanMSFT** [comment]
Hi @BenjaminAbt - Unfortunately, we cannot discuss feature releases here. I'm sorry for the inconvenience.

**Comment by alexmbaker** [comment]
@BenjaminAbt you can create the user using the existing construct

``` SQL
CREATE USER [name] WITH TYPE=?, SID=0x....,
```

TYPE should be `X` for a Group and `E` for other user types (Service Principal or standard user)
SID is the binary representation of the GUID and depends on the user type:

* For users and groups, it is the ObjectID from Entra
* For a Service Principal / Managed Identity you should use the 'ApplicationId'

To cast a string to the binary SID:

``` SQL
SELECT CAST(CAST('guid as string' AS uniqueidentifier) AS varbinary(85))
```
if you are building some dynamic SQL then you can get the SQL literal for the binary data

```
SELECT CONVERT(varchar(34), @binary_value,1)
```

**Comment by ilmax** [comment]
> Hi @BenjaminAbt - Unfortunately, we cannot discuss feature releases here. I'm sorry for the inconvenience.

This is such a disappointing answer. I'm not sure what's the purpose of being so secretative. I can somehow understand that MS may want to keep new/ground breaking functionalities hidden to the public till release date, but I don't see the point in keeping those quality of life improvements secret to your paying customers.

More and more Azure teams are sharing what they're working on and what's theyr future plans is, not sure what the SQL team has to hide here.

**Comment by BenjaminAbt** [comment]
> @BenjaminAbt you can create the user using the existing construct

Thank you, but I am aware of all this for years. In my case, together with my colleague, I have implemented a "much better" solution for us and our customers, which works "better" for E2E with both managed identities and federation [E2E DevOps for Azure SQL with Managed Identities](https://philippbauknecht.medium.com/e2e-devops-for-azure-sql-with-managed-identities-f2231c7e964c)
"Better" because we have more control here and we don't need any "weird" scripts, which are unfortunately a no-go for many companies.

For them the current solution with Type=E etc feels like unsupported patchwork. Microsoft is pushing more and more for Managed Identity on the one hand - which is right - and always insists on a clean security solution for databases in the WAF (all database services) and there is almost no secure E2E DevOps solution in any Microsoft DB product.
This has been frustrating for years, we have constant discussions over and over - and nothing happens.

**Comment by justin-mellor** [comment]
Hi @VanMSFT and @GithubMirek 
This discussion has been ongoing for a while now, but I have a scenario that has not been discussed and I want to understand what the current suggestion would be from Microsoft.

I am trying to create an Azure Managed Application using the Publisher Managed security model.
This means that when a customer installs the application they have no access to the resources, and we as publisher have ownership of the resource group. However we are in a different Entra ID tenant.

The managed application consists of an Azure Sql Database, and an App Service.
I would like to grant the App Service access to the database using a Managed Identity (as opposed to SQL authentication) however this is where the problem comes

Because the Managed Identities (either System or User Assigned) would exist in the Customers Tenant, the SQL Server requires configuration with an Entra ID that is part of the customer's tenant, and requires Directory.Read permission, even though it doesn't need access to anything that is not part of the Managed Application. As the publisher I cannot see how I can then configure this access.

Working with Azure Key Vault has similar challenges, but there you can configure the access via the ARM template and delegatedManagedIdentityResourceId, whereas with SQL Server you have to call SQL commands and seem stuck.

What is the recommended way to publish an Azure Managed Application and deploy an App Service and an Azure Sql Database and configure security between the two?

**Comment by VanMSFT** [comment]
Hi @justin-mellor - I don't have the best answers for you as this is not a help forum for the product, only documentation issues. However, see the following and if it can apply to your scenario. https://learn.microsoft.com/en-us/azure/azure-sql/database/authentication-aad-guest-users?view=azuresql

Please utilize the feedback for the product, or contact Microsoft Support for additional assistance.

![image](https://github.com/MicrosoftDocs/sql-docs/assets/40007119/5614a702-24e2-4faa-883d-d7ff33a0ebf5)

**Comment by justin-mellor** [comment]
> Hi @justin-mellor - I don't have the best answers for you as this is not a help forum for the product, only documentation issues. However, see the following and if it can apply to your scenario. https://learn.microsoft.com/en-us/azure/azure-sql/database/authentication-aad-guest-users?view=azuresql

Thanks. I have raised a support ticket.

**Comment by tameikal-msft** [comment]
Hi, to share an update, the Object_ID syntax for the CREATE USER/LOGIN T-SQL query is currently supported and has been released into public preview as of February 2024. For more information on this supportability feature see: 

https://learn.microsoft.com/en-us/azure/azure-sql/database/authentication-microsoft-entra-create-users-with-nonunique-names?view=azuresql

**Comment by varg-praedico** [comment]
Any plans to support adding logins by SID similar to CREATE USER [{managedIdentityName}] WITH SID={applicationSid}, TYPE=E ?

**Comment by VanMSFT** [comment]
Hi @varg-praedico - Unfortunately, we can't discuss any future plans for support here.

**Comment by redoz** [comment]
@VanMSFT Is there any information on whether `CREATE USER [xyz] WITH SID={sid}, TYPE=E/X ` will continue to work of if this is expected to be phased out at some point?

**Comment by VanMSFT** [comment]
Hi @redoz - I appreciate the question, but the Docs team doesn't have insight into future supportability or deprecation, until it's communicated by the Product Team.
