### ISSUE TITLE
Add a space between an and on in the paragraph below

### ISSUE THREAD

**Issue by ManojNair** [MicrosoftDocs/sql-docs#2326]
While this article does not cover availability options external to SQL Server, such as those provided by virtualization, everything discussed here applies to SQL Server installations inside a guest virtual machine whether in the public cloud or hosted by anon premises hypervisor server.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76208061-3c5d-758a-6704-dd7f546d5545
* Version Independent ID: 6ea99630-2750-17b2-b64b-b6fa8464e1dc
* Content: [Disaster recovery for SQL Server - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/sql-server-business-continuity-dr?view=sql-server-2017#feedback)
* Content Source: [docs/database-engine/sql-server-business-continuity-dr.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/sql-server-business-continuity-dr.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @ManojNair,

Thank you for contacting Microsoft and providing your feedback to our documentation! 

If you're suggesting a simple change to the documentation, it may be faster for you to submit the edit yourself via a Pull Request (PR). You can do so by following these steps:

1. Navigate to the page of interest
2. Select the "Edit" button at the top right of the page
3. Select the "Pencil" icon on the right
4. Modify the text within the text box in [markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) format
5. Name your file change and copy the link to your Git Issue into the "extended description" box
6. Select "Propose file change"
7. Select "Create pull request" on the 'Comparing changes' page
8. Select "Create pull request" on the 'Open a pull request' page
9. Wait for an author to review and approve the change request - this can take a bit depending on the complexity

Doing so will allow authors to directly add your text to the documentation. This also displays your github image on the page of authors, and list you as a contributor to the documentation.

Otherwise, we would be happy to make this change for you :) 

Thanks again for your submission, and hope you have a wonderful rest of your day!

**Comment by msebolt** [comment]
@ManojNair Thank you for the feedback!  This issue appears to have been resolved.

Please comment below if there are any further questions.
