### ISSUE TITLE
Sections in wrong order

### ISSUE THREAD

**Issue by cbailiss** [MicrosoftDocs/sql-docs#2334]
Surely the database permissions at the subscriber should be set before creating the subscription?
The order described in this page results in a "Unable to Connect Error".  
This clears after a few minutes, but is confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0086945e-a60b-31ed-9445-160fed6ea1f1
* Version Independent ID: 2dcdbf33-d5af-b766-dd5c-f477c8b441b7
* Content: [Tutorial: Configure replication between two fully connected servers (transactional) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/replication/tutorial-replicating-data-between-continuously-connected-servers?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/replication/tutorial-replicating-data-between-continuously-connected-servers.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/replication/tutorial-replicating-data-between-continuously-connected-servers.md)
* Product: **sql**
* Technology: **replication**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @cbailiss , 

Thanks for contacting Microsoft! This actually seems to be a gap in this documentation: https://docs.microsoft.com/en-us/sql/relational-databases/replication/tutorial-preparing-the-server-for-replication?view=sql-server-2017#create-windows-accounts-for-replication

I've created a work item on my end to address this - due to the complexity it may take a few business days to a few business weeks to get it addressed. Thanks for bringing this to our attention!

**Comment by WilliamAntonRohm** [comment]
@MashaMSFT -- please add a link to your work item.  When you create a work item, please close the related issue.

cc:  @MightyPen

**Comment by MashaMSFT** [comment]
User Story [1558194](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1558194).

**Comment by MashaMSFT** [comment]
Hi @cbailiss, I've reviewed the tutorial once more; actually it is impossible to create the permissions for the subscriber before the subscription is created. This is because we need the subscriber database to set the permissions, and that's only created at the time of the subscription. As such, I'll need to roll back the changes previously. I'm not sure why you would be getting a connection error, or why it would clear after some time, but I don't believe it's a permissions issue. 

Thanks!
Masha from the SQL Docs team
