### ISSUE TITLE
Detach/Attach consideration

### ISSUE THREAD

**Issue by aminechafai** [MicrosoftDocs/sql-docs#2372]
Since scenario 2 above will cause a down time, isn't better to use the detach/attach method instead of backup/restore?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93aae7da-b3c2-a0df-cdac-2ea7dd3adc82
* Version Independent ID: aed47ec8-1a51-b2b7-c6ed-dd82061cb23c
* Content: [Upgrade SQL Server instances running on Windows Server 2008/2008 R2/2012 clusters - SQL Server Always On](https://docs.microsoft.com/en-us/sql/sql-server/failover-clusters/windows/upgrade-sql-server-failover-cluster-instance-2008-2012?view=sql-server-2016#feedback)
* Content Source: [docs/sql-server/failover-clusters/windows/upgrade-sql-server-failover-cluster-instance-2008-2012.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/failover-clusters/windows/upgrade-sql-server-failover-cluster-instance-2008-2012.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @aminechafai , thanks for contacting Microsoft! Actually, restoring a backup rather than detaching is the safer method, and allows for an easier rollback path. What if, for some reason, you can no longer attach the database? At least, if you take a back up and restore, you can easily go back if necessary. 

I hope that helps and please let me know if we can be of further assistance! If not, we'll proceed with closing out this Git Issue in a few business days. 

Thanks and hope you have a wonderful rest of your day!

**Comment by WilliamAntonRohm** [comment]
@MashaMSFT -- thank for your replying, I have assigned this issue to you.  Going forward, please assign such issues to yourself.
