### ISSUE TITLE
New features link is wrong

### ISSUE THREAD

**Issue by rgwood** [MicrosoftDocs/sql-docs#2375]
Specifically this bit: "For information about the new features in In-Memory OLTP, see Columnstore indexes - what's new"

The linked page lists new features for columnstore indexes, nearly all of which are not related to in-memory OLTP. I'm guessing this was supposed to link somewhere else.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 494b3bdc-5dc6-66a0-3c01-ab53f76539fc
* Version Independent ID: 22627b4b-4877-6aa5-933b-8010e07487a4
* Content: [In-Memory OLTP (In-Memory Optimization) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/in-memory-oltp/in-memory-oltp-in-memory-optimization?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/in-memory-oltp/in-memory-oltp-in-memory-optimization.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/in-memory-oltp/in-memory-oltp-in-memory-optimization.md)
* Product: **sql**
* Technology: **in-memory-oltp**
* GitHub Login: @MightyPen
* Microsoft Alias: **genemi**

**Comment by MightyPen** [comment]
@rgwood Fixed, by private repo PR #10773.  The fix should be live on Docs website by late Tuesday June/25.
Thank you for submitting this Issue 2375. We hope to hear from you again.

I am now Closing this Issue 2375.
The @ notification mechanism continues to work even after an item is Closed, in case further communication is needed.

A very effective option that many customers like is to edit our documentation directly through a Pull Request (PR), instead of describing the fix in an Issue. If you are ever interested, you can click the Edit-pencil icon at the top-right on the article's webpage, and then click the pencil icon on the GitHub webpage.
