### ISSUE TITLE
Config provided for SQL authentication through Node.js is wrong

### ISSUE THREAD

**Issue by marcusteh1238** [MicrosoftDocs/sql-docs#2389]
sql-docs/docs/connect/node-js/step-3-proof-of-concept-connecting-to-sql-using-node-js.md
In the above document, the config is written as
```javascript
var config = {  
        userName: 'yourusername',  
        password: 'yourpassword',  
        server: 'yourserver.database.windows.net',  
        // If you are on Microsoft Azure, you need this:  
        options: {encrypt: true, database: 'AdventureWorks'}  
    };  
```
where it should be like
```javascript
var config = 
{
    authentication: {
        options: {
            userName: 'userName', // update me
            password: 'password' // update me
        },
        type: 'default'
    },
    server: 'your_server.database.windows.net', // update me
    options:
    {
        database: 'your_database', //update me
        encrypt: true
    }
}
```
like in the doc provided for [Azure.](https://docs.microsoft.com/en-sg/azure/sql-database/sql-database-connect-query-nodejs)

**Comment by MightyPen** [comment]
@David-Engel Hi David, Do you know someone who works with Node.js enough who can assess whether this customer suggestion is something we want to implement in our Docs documentation?

**Comment by David-Engel** [comment]
@MightyPen The customer is correct. Tedious changed config options last year and deprecated the old ones, which were subsequently removed earlier this year. I'll submit a PR for the doc change.

**Comment by David-Engel** [comment]
PR #2585 created.

**Comment by MightyPen** [comment]
@marcusteh1238 The fix for the outdated Node.js code, that you brought to our attention here with Issue 2389, is presently being built (PR 11187).  The fix should be live on Docs before the sun sets this evening.

- https://github.com/MicrosoftDocs/sql-docs-pr/pull/11187

Thank you very much for bringing the the problem of this outdated code to our attention. We are very glad to fix these types of problems.

I am now Closing this Issue 2389 as fixed. We hope to hear from you again.

@David-Engel Thanks so much for your help with this.


 . .
