### ISSUE TITLE
Clarification required for Step 3.1 -- non-leaf level calculations log base (e or 10?)

### ISSUE THREAD

**Issue by swbhartims** [MicrosoftDocs/sql-docs#2404]
Calculate the number of non-leaf levels in the index:

Non-leaf Levels = 1 + log( Index_Rows_Per_Page) (Num_Leaf_Pages / Index_Rows_Per_Page)

It is unclear if the base is 10 or e.
Please refactor this line to indicate this value.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acd0f89f-5bd7-5332-fbb5-2c362d9da599
* Version Independent ID: 78e1a2f9-2aa1-06a8-ff64-21cfe75b2540
* Content: [Estimate the Size of a Nonclustered Index - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/databases/estimate-the-size-of-a-nonclustered-index?view=sql-server-2017#step-3-calculate-the-space-used-to-store-index-information-in-the-non-leaf-levels)
* Content Source: [docs/relational-databases/databases/estimate-the-size-of-a-nonclustered-index.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/databases/estimate-the-size-of-a-nonclustered-index.md)
* Product: **sql**
* Technology: **supportability**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@kfarlee -- Kevin, can you please determine the base for this logarithm, is it 10 or e?

**Comment by WilliamAntonRohm** [comment]
@kfarlee -- Kevin, please look into this aging issue 2404.

**Comment by WilliamAntonRohm** [comment]
@CarlRabeler -- can you help get this issue 2404 processed?  Thank you.

**Comment by CarlRabeler** [comment]
what makes you suggest that the base is not 10 ?
@swbhartims

**Comment by RobAshton-IM** [comment]
The answer is "Neither".

The calculation requires the logarithm to the base of Index_Rows_Per_Page, not base 10 or base e because of how a B*-tree handles the fan-out between the levels of the tree.

However, I would argue that the calculation given is more complex than it needs to be, apologies in advance for the maths about to be thrown around!

It can be shown using simple logarithmic identities (happy to provide a rudimentary proof if needed) that the calculation in the document can be simplified to:
Log[Index_Rows_Per_Page](Num_Leaf_Pages)

Note that I'm defining the base of the logarithm within the square brackets and the value whose logarithm is to be calculated within the ellipses for clarity here.

If you absolutely have to have the calculation in base-10 (perhaps because you don't have a calculator that can do arbitrary-base logarithm calculations), another logarithmic identity allows us to transform the simplified form I gave above to base-10:
Log[10](Num_Leaf_Pages) / Log[10](Index_Rows_Per_Page)

Hope that helps!

**Comment by swbhartims** [comment]
@CarlRabeler - I brought up this request as it is not clear what base must be chosen - either `e` or `10`. An educated guess would make me assume that it is to the base 10. However, I would appreciate if the instructions included this specification as well.

**Comment by swbhartims** [comment]
@RobAshton-IM Thanks for the clarification :)
Would the documentation be updated to reflect this?

**Comment by RobAshton-IM** [comment]
@swbhartims I've taken a fork of the page as I have noticed a few typos and copy-paste errors between the sections that I was planning on submitting issues and PR's for myself, happy to include a fix for this issue if no-one else gets to it before me :)

**Comment by swbhartims** [comment]
@RobAshton-IM Thank you so much 👍

**Comment by CarlRabeler** [comment]
@kfarlee can you review please

**Comment by CarlRabeler** [comment]
@RobAshton-IM Hi Rob - have you made any progress in updating the page? Thanks, Carl

**Comment by rothja** [comment]
@RobAshton-IM Thanks, again, for your input. Did you create an update to the page? Let me know how we can help. @CarlRabeler is out of the office for the next few weeks, but I will take over this and help out as needed. @swbhartims Thanks for your question and your patience as we look into the right next steps.

**Comment by RobAshton-IM** [comment]
@rothja Hi Jason, I'm having a ton of issues with GitHub Desktop at work, so I'm probably going to end up doing this at home I think. I'm going to spend some time over the weekend on it, so watch this space :)

**Comment by rothja** [comment]
As @RobAshton-IM has provided an answer and is working on the suggested doc updates, I am going to close this issue. @swbhartims Thank you for your feedback, and please accept my apologies for any delay in our response on this. I hope we can make this more clear going forward. Thank you!!

**Comment by swbhartims** [comment]
Thanks @rothja  :)
