### ISSUE TITLE
Ownership chain?

### ISSUE THREAD

**Issue by ibTnJohn** [MicrosoftDocs/sql-docs#2417]
We discovered that in a stored proc, Update Statistics will not execute unless the caller or "execute as" user has Alter Table, even if the ownership chain is not broken.  We did not see that explicitly spelled out in documentation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e28c075d-4756-d41f-7ef2-56bee48deaf1
* Version Independent ID: 3df1db03-f7a7-fa1b-d064-04ec36b1f882
* Content: [Update Statistics - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/statistics/update-statistics?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/statistics/update-statistics.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/statistics/update-statistics.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by srutzky** [comment]
Hi there, @ibTnJohn . What you are experiencing is the expected behavior. This is due to ownership chaining only implying permissions for `SELECT`, `INSERT`, `UPDATE`, `DELETE`, `MERGE`, and `EXEC(UTE)` statements. Hence you would run into the same situation if you were trying to issue `TRUNCATE TABLE` on a table having the same owner as the owner of the stored procedure.

To address this security issue, it is preferred that you use [Module Signing](https://modulesigning.info/) instead of Impersonation (i.e. `EXECUTE AS`). To understand why, I wrote a detailed post here:

[PLEASE, Please, please Stop Using Impersonation, TRUSTWORTHY, and Cross-DB Ownership Chaining](https://sqlquantumleap.com/2017/12/30/please-please-please-stop-using-impersonation-execute-as/)

For a step-by-step walk-through on how to easily fix your issue using Module Signing, please see:

[Safely and Easily Use High-Level Permissions Without Granting Them to Anyone: Database-level](https://sqlquantumleap.com/2018/03/05/safely-and-easily-use-high-level-permissions-without-granting-them-to-anyone-database-level/)

All you need to do is make sure to assign the correct permission under "Step 6" in "Setup for Test 2", which could be adding the signature-based User to the "database_owner" fixed database Role.

Take care,
Solomon..

**Comment by MightyPen** [comment]
@srutzky Thank you very much for your in-depth answer.

@julieMSFT Julie, fyi you might want to consider whether to edit the article based on some of this information.

@ibTnJohn 
Thank you for submitting this Issue. We hope to hear from you again. 
The @ notification mechanism continues to work even after an item is Closed, in case further communication is needed.

**Comment by srutzky** [comment]
@ibTnJohn (and others): Actually, I just noticed that I recently answered a related question on DBA.StackExchange, and that scenario required an additional step (the server-level piece) as it required giving permissions within `[tempdb]`. However, the extra step seems to be required only due to the use of the `WITH ROWCOUNT` clause. If you are not using that, then you might could get away with the simpler method that I mentioned in my comment above. Please take a look:

[What permissions are required for UPDATE STATISTICS #table WITH ROWCOUNT = xxx?](https://dba.stackexchange.com/a/239279/30859)

Take care,
Solomon..
https://SqlQuantumLeap.com/

**Comment by ibTnJohn** [comment]
@srutzky I actually have referenced your Module Signing post in the past -- and thank you for your detailed answer here.  My main reason for posting was that I do not recall seeing in any documentation this nugget from your response: "This is due to ownership chaining only implying permissions for SELECT, INSERT, UPDATE, DELETE, MERGE, and EXEC(UTE) statements."   I have noted that behavior and that it is consistent, but when asked "Why?" have not found a reference.  Now, I'll use your post. :-)

@julieMSFT, perhaps any enhancement would better fit on the Ownership Chaining page to indicate the limitations of what specific permissions will chain.

Thanks,
John

**Comment by srutzky** [comment]
@ibTnJohn:

You are quite welcome. And I'm glad that my Module Signing post(s) has been helpful 😺 .

>  I do not recall seeing in any documentation this nugget from your response: "This is due to ownership chaining only implying permissions for SELECT, INSERT, UPDATE, DELETE, MERGE, and EXEC(UTE) statements." I have noted that behavior and that it is consistent, but when asked "Why?" have not found a reference.

Really? I could have sworn that I read it somewhere and didn't just infer it from observed behavior. I will take a look to see if I can find it.

**Comment by ibTnJohn** [comment]
@srutzky  A Safari search shows It's in a few MSPress books (Itzik Ben-Gan is so thorough) and I see it on RedGate's site -- now that I made my search very specific.  But I don't see it in the MS documentation.  I could be missing it, or maybe it used to be there. Again, thanks for your help.

**Comment by srutzky** [comment]
@ibTnJohn: the info must have been on an old MSDN or TechNet page that is no longer accessible. I found it here:

[SQL Server: Exploring Cross-Database Ownership Chaining](https://social.technet.microsoft.com/wiki/contents/articles/52875.sql-server-exploring-cross-database-ownership-chaining.aspx#Limitations)

That page was created not even 60 days ago, yet the "Limitations" section contains the following:

> Cross-database ownership chaining had below limitations.  
>   
> * Cross-Database ownership chaining allows only to object permissions, operations such as SELECT, UPDATE, DELETE, INSERT and EXECUTE but for any other operation beyond this like DDL statements or statements like TRUNCATE TABLE, etc. SQL server will always be checking permissions on underlying objects too, that means user must have granted the permissions needed on underlying objects explicitly.  
> * Cross-database ownership chaining does not work in cases where dynamically created SQL statements are executed in stored procedures. On statements that run dynamically through EXECUTE or sp_executesql, SQL Server checks permissions in the security context of the user who executed the procedure instead of the procedure owner. As a result, Dynamic SQL breaking the ownership-chain and users must have permissions on all objects that are directly referenced by dynamically executed statements.

I remember reading both of those years ago. The Dynamic SQL piece I can still find in current documentation. But the ownership-chaining part I can't find. I think it was a SQL Server 2000 document. It wouldn't have mentioned `MERGE`. I threw that in there because it's DML and that's part of what Ownership Chaining handles.

I do find it strange that it's so hard to find documentation on such a foundational behavior of the system. Of course, the overall lack of thorough documentation on this topic is why I created https://ModuleSigning.Info/ in the first place :-). Here are two pages that would benefit from (and are natural fits for) some additional explanation of Ownership Chaining:

* "Ownership Chains" and "Procedural Code and Ownership Chaining" sections of [Authorization and Permissions in SQL Server](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql/authorization-and-permissions-in-sql-server#ownership-chains)
* "Summary of the Permission Check Algorithm" section of [Permissions (Database Engine)](https://docs.microsoft.com/en-us/sql/relational-databases/security/permissions-database-engine#_algorithm)

I don't have time at the moment to do this update. Also, it would be great to confirm this behavior with a developer that can review the code, making sure that the rest of us didn't miss something in our educated guesses.
