### ISSUE TITLE
How does docs.ms rendering for GH Markdown?

### ISSUE THREAD

**Issue by mikejwhitty** [MicrosoftDocs/sql-docs#2422]
I came across the page: [HASHBYTES (Transact-SQL)](https://docs.microsoft.com/en-us/sql/t-sql/functions/hashbytes-transact-sql?view=sql-server-2017)

I noticed some odd formatting around the description of parameters (particularly the _@input_ bit) so I thought I'd try and do my bit to fix it.

so I went to the md file at: https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/hashbytes-transact-sql.md

But looking at lines 43 and 44 of that file:

```
 **@input**  
 Specifies a variable containing the data to be hashed. **@input** is **varchar**, **nvarchar**, or **varbinary**.  
```

and how that renders in GH itself, the same problem isn't apparent, so I don't know how to change the file to "fix" the issue I see with it on the docs.ms site.

Is there a way to see what the page will look like on the site when proposing changes?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e193d722-8726-b83f-f642-2881b36503f1
* Version Independent ID: f01a8a7e-c5ce-8ccf-9054-b518f37619a9
* Content: [How to Contribute to SQL Server Documentation - SQL Server](https://docs.microsoft.com/en-gb/sql/sql-server/sql-server-docs-contribute?view=sql-server-2017)
* Content Source: [docs/sql-server/sql-server-docs-contribute.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/sql-server-docs-contribute.md)
* Product: **sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by MightyPen** [comment]
@mikejwhitty Thank you so much for bringing this formatting Issue 2422 to our attention.  We have cleaned up several articles that have a similar problem (leftover from an automated conversion to markdown).
Normally I would love to encourage you to create a Pull Request to fix this, as you volunteered. But this is a tricky case, partly because the editing system we offer does Not provide good feedback to you on the ultimate rendering of the formatting changes you would be trying. So in this case I think it is best if I do the edit.  Darn, because we love it when customers improve our documentation with PRs they create.

I will put my PR number in here, for audit trail.

**Comment by MightyPen** [comment]
Fixed by 10898.
https://github.com/MicrosoftDocs/sql-docs-pr/pull/10898

@mikejwhitty I am now Closing this fixed Issue 2422. 
The @ notification mechanism continues to work even after an item is Closed, in case further communication is needed. 
Thank you for submitting this Issue. We hope to hear from you again.
