### ISSUE TITLE
What about the .NDF file?

### ISSUE THREAD

**Issue by ShawnPOWER** [MicrosoftDocs/sql-docs#2436]
I don't see any mention here of the .NDF file(s). Should the .NDF file(s) also move along with the .MDF and .LDF of the TempDB to a new location? Or should they be left behind on the OS drive?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9423e4-0573-7564-3f58-2a8df9a11d9f
* Version Independent ID: 5b88aa32-b6f7-e8eb-806f-fd331ed43133
* Content: [Move System Databases - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/databases/move-system-databases?view=sql-server-2017)
* Content Source: [docs/relational-databases/databases/move-system-databases.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/databases/move-system-databases.md)
* Product: **sql**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by msebolt** [comment]
@ShawnPOWER Thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation.

Please refer to the following for product support:

- [UserVoice - Suggestion to improve SQL Server?](https://feedback.azure.com/forums/908035-sql-server) 

- [Setup and Upgrade -  MSDN Forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=sqlsetupandupgrade&filter=alltypes&sort=lastpostdesc) 

- [Transact-SQL - MSDN forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=transactsql) 

- [DBA Stack Exchange (tag sql-server) - ask SQL Server questions](https://dba.stackexchange.com/questions/tagged/sql-server)

**Comment by ShawnPOWER** [comment]
@msebolt The documentation doesn't mention what to do with the .NDF files. This question is specifically related to the documentation and not the product itself. I apologize if that wasn't clear.

**Comment by stevestein** [comment]
@ShawnPOWER - Thanks for raising this issue. Yes, if you use an .ndf file it should move with the other files as it's just another data file.

**Comment by ShawnPOWER** [comment]
I appreciate it @stevestein, makes total sense.
