### ISSUE TITLE
Import data disabled in SSMS18.1

### ISSUE THREAD

**Issue by pantonis** [MicrosoftDocs/sql-docs#2444]
Tasks => Import data option is disabled in SSMS 18.1

**Comment by MightyPen** [comment]
@pantonis Hello, yes unfortunately we have received several reports from customers that SSMS 18.1 has some problems. The Development team is focused on fixing these problems, and it hopes to release an updated version of SSMS in the near future.

I am Closing this Issue 2444. The @ notification mechanism continues to work even after an item is Closed, in case further communication is needed.
Thank you for submitting this Issue. We hope to hear from you again.

CC: @markingmyname

**Comment by pantonis** [comment]
@MightyPen Thanks for your reply.
Any workaround on this until bug is fixed?

**Comment by MightyPen** [comment]
@pantonis No work-around that I know of off the top of my head.
I often presume that the SSMS UI just builds Transact-SQL commands that a human can writer on his/her own, and could then submit through a plain Query pane in the SSMS UI, or through osql.exe.

I am just wildly speculating, but I wonder whether the problem you encountered is because the Object Explorer in SSMS 18.1 is building or submitting the T-SQL incorrectly.  If incorrectly, then perhaps writing the proper T-SQL by hand, and directing the T-SQL through the proper connection to the proper target - might provide a work-around.  I have not researched this situation in detail, and I am just guessing.
Thanks.
