### ISSUE TITLE
Didactics

### ISSUE THREAD

**Issue by NicoBoey** [MicrosoftDocs/sql-docs#2459]
It is confusing to start a tutorial about hierarchyid by 'flattening' an existing hierarchical table first, in order to explain how to get from the flattened table to a hierarchical table.
IMHO it would be better to start from a script that creates and populates a 'flat' table, and then explain how to get to a hierarchical table.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51ed423e-1352-12c5-5666-34f9861863e8
* Version Independent ID: f542c2e1-e65e-ded8-e103-1441e9eb7277
* Content: [Lesson 1: Converting a Table to a Hierarchical Structure - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tables/lesson-1-converting-a-table-to-a-hierarchical-structure?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/tables/lesson-1-converting-a-table-to-a-hierarchical-structure.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/lesson-1-converting-a-table-to-a-hierarchical-structure.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MightyPen** [comment]
@msebolt Hi Matthew, If you decide a change is important enough here, you might consider ending the article's use of AdventureWorks2017 entirely. There may be other options too.

**Comment by MashaMSFT** [comment]
Hi @NicoBoey , 

Thank you for contacting Microsoft and providing your feedback to our documentation! We'll need some time to look into this further. Depending on the complexity, the turnaround time for this may vary anywhere from a few business days to a few business weeks. We'll reply via comment should we need anything further in the meantime, and please feel free to do the same.

If you're suggesting a simple change to the documentation, it may be faster for you to submit the edit yourself via a Pull Request (PR). You can do so by following these steps:

1. Navigate to the page of interest
2. Select the "Edit" button at the top right of the page
3. Select the "Pencil" icon on the right
4. Modify the text within the text box in [markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) format
5. Name your file change and copy the link to your Git Issue into the "extended description" box
6. Select "Propose file change"
7. Select "Create pull request" on the 'Comparing changes' page
8. Select "Create pull request" on the 'Open a pull request' page
9. Wait for an author to review and approve the change request - this can take a bit depending on the complexity

Doing so will allow authors to directly add your text to the documentation. This also displays your github image on the page of authors, and list you as a contributor to the documentation.

Otherwise, we'll continue to research your suggestion, and get back to you as soon as we have more information for you.

Thanks again for your submission, and hope you have a wonderful rest of your day!
Masha from SQL Docs team

**Comment by MikeRayMSFT** [comment]
Hi @NicoBoey - Thank you for your comment. I agree that if the document began with a flattened table, instead of flattening a hierarchical table, it could simplify the tutorial. We are not currently planning to update the tutorial, but your point is valid.

Thank you.
