### ISSUE TITLE
SSMS 18 temp table select statement does not return data in order

### ISSUE THREAD

**Issue by chandansj** [MicrosoftDocs/sql-docs#2491]
Hi,
I am not getting the ordered data which used to work in older version.

for eg: Student table:
                                  Id Name
                                   1  xyz
                                   2  abc
                                   3  yax
select Id, Name into #temp from student
select *from #temp 

will return data 

Id Name
2   abc
1   xyz
3  yax

**Comment by msebolt** [comment]
@chandansj Thank you for the feedback.

Since this is product-related, please post the issue in the [SQL Server forums](https://social.msdn.microsoft.com/Forums/sqlserver/home?category=sqlserver).

In the meantime, please refer to [ORDER BY](https://docs.microsoft.com/sql/t-sql/queries/select-order-by-clause-transact-sql] to order your queries.
