### ISSUE TITLE
Specify a default collation

### ISSUE THREAD

**Issue by HairyDrumroll** [MicrosoftDocs/sql-docs#2524]
Someone has gone to the trouble of adding a note to say "Instead of changing the default collation of an instance of SQL Server, you can specify a default collation for each new database you create."
It would be useful to include a link or text explaining how to do this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ca70403-237f-0160-7d1f-5817e40b5d25
* Version Independent ID: 9993116a-bcec-e054-1cbe-82c3ad603ef6
* Content: [Set or Change the Server Collation - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/collations/set-or-change-the-server-collation?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/collations/set-or-change-the-server-collation.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/collations/set-or-change-the-server-collation.md)
* Product: **sql**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by stevestein** [comment]
@CarlRabeler - can you provide additional info on this?

**Comment by CarlRabeler** [comment]
you can set the collation for a new database in a managed instance - see https://docs.microsoft.com/en-us/sql/relational-databases/collations/set-or-change-the-database-collation

**Comment by HairyDrumroll** [comment]
But what about the default collation for new databases on a SQL Server. That is what the note is referring to, but there is no instruction or link to instructions on how to do this.

**Comment by WilliamAntonRohm** [comment]
@HairyDrumroll -- if I understand you correctly, the information you are looking for is in [this related article](https://docs.microsoft.com/en-us/sql/relational-databases/collations/set-or-change-the-database-collation?view=sql-server-2017).

I will update that Note to include a link the related article.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by srutzky** [comment]
@HairyDrumroll (and @WilliamAntonRohm , @CarlRabeler , and @stevestein ):

I believe the following note (that is the subject of this issue):

> Instead of changing the default collation of an instance of SQL Server, you can specify a default collation for each new database you create

is recommending that you can do the following:

```sql
CREATE DATABASE [BobsHouseOfDatas] COLLATE Latin1_General_100_CI_AS_SC;
```

That creates the database with a "default" collation of `Latin1_General_100_CI_AS_SC`.

There is no way to change the default collation used to create databases (i.e. `CREATE DATABASE...` _without_ the `COLLATE` clause) because that is the collation of the `[model]` database, which is a system database, and you cannot change the collation of system DBs.

Of course, if you want / need to change the collation of the entire instance (including all DBs), I have that documented here:

[Changing the Collation of the SQL Server Instance, the Databases, and All Columns in All User Databases: What Could Possibly Go Wrong?](https://sqlquantumleap.com/2018/06/11/changing-the-collation-of-the-instance-and-all-columns-across-all-user-databases-what-could-possibly-go-wrong/)

Take care,
Solomon...
https://SqlQuantumLift.com/
https://SqlQuantumLeap.com/
https://SQLsharp.com/

**Comment by HairyDrumroll** [comment]
Thanks @srutzky, that is information that would be useful to include in the documentation.

**Comment by srutzky** [comment]
Hello @HairyDrumroll (and @WilliamAntonRohm , @CarlRabeler , and @stevestein ): I just submitted PR #4747 to address this issue (as well as Issue #4103 ). I clarified that note to explicitly state using the `COLLATE` clause of the `CREATE DATABASE` and `ALTER DATABASE` statements. I also included a link to: [Set or Change the Database Collation](https://docs.microsoft.com/en-us/sql/relational-databases/collations/set-or-change-the-database-collation) .

Of course, there is a caveat to that advice: changing the database collations to be different than the server-level collation greatly increases the chances of running into collation conflicts in temporary tables (when JOINing on string columns). Such errors are easily avoidable by simply specifying the `COLLATE` clause for the relevant column(s) in the `CREATE TABLE` statement that creates the temporary table. In cases where the collation is known ahead of time, specify the desired collation. In cases where the collation should be the same as the database's default collation but the database's default collation might not be known ahead of time (i.e. the code can be installed in various databases each having a different collation; for example, 3rd party software typically behaves this way), specify `DATABASE_DEFAULT`.



Take care,
Solomon...
https://SqlQuantumLift.com/
https://SqlQuantumLeap.com/
https://SQLsharp.com/
