### ISSUE TITLE
AND operator do now work as expected with OPENJSON()

### ISSUE THREAD

**Issue by ableji** [MicrosoftDocs/sql-docs#2536]
This query execute successfully

```
Select *
From Users
CROSS APPLY OPENJSON(Codes, '$') X
WHERE 1111 IN (x.value) 
```

> "Codes" column is varchar and contains json array like this :
> ["1111","2222","3333"]

when I append an **AND** operator to the query

```
Select *
From Users
CROSS APPLY OPENJSON(Codes, '$') X
WHERE 1111 IN (x.value) 
And 2222 IN (x.value))
```
it returns nothing/empty result.

but its ok with OR operator and return some data.

I wana know whats wrong with AND operator ?
and is there any better way to write this query ?

**Comment by msebolt** [comment]
@ableji Thank you for the question.

The **CROSS APPLY** will flatten your JSON data and then when you try to apply the **AND** to a single column of data, it returns nothing because both `1111` and `2222` are in separate rows.  You should instead use the **OR**.

Observe this when you run the first part of your statement:

```
Select *
From Users
CROSS APPLY OPENJSON(Codes, '$') X
```

...and note the flattened nature of the JSON values.  Moving forward you should design your **AND**, **OR**, etc. filters based on querying this table.

If you there are any further issues please comment below.
