### ISSUE TITLE
offset, row, rows?

### ISSUE THREAD

**Issue by orastarter** [MicrosoftDocs/sql-docs#2543]
Hi, according this article https://docs.microsoft.com/en-us/sql/t-sql/queries/select-order-by-clause-transact-sql?view=sql-server-2017 i don't see "offset", "row", "rows" etc in this list. Is it correct? Are they also keywords?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f79ec4df-5309-60fc-1c20-f32b219fb9b9
* Version Independent ID: 6ee85c34-9a2c-e007-dcda-fb6016b98119
* Content: [Reserved Keywords (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/reserved-keywords-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/language-elements/reserved-keywords-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/language-elements/reserved-keywords-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by rothja** [comment]
@orastarter Thanks for the question. I can see from the article why we would think that these should be listed as reserved keywords. But they don't quite behave the same. Note the qualification "Although it is syntactically possible to use SQL Server reserved keywords as identifiers and object names in Transact-SQL scripts, you can do this only by using delimited identifiers." So you can't do this:

```sql
SELECT 'hi' as coalesce
```

But you can run these queries successfully:

```sql
SELECT 'hi' as row
SELECT 'hi' as rows
SELECT 'hi' as offset
```

So although they are used in these statements, I don't think they are treated in the same class as reserved keywords in T-SQL. Let me know if this makes sense, because I agree with you that it seems like maybe they should be reserved in the same way. Thank you!

**Comment by rothja** [comment]
@orastarter I'm going to close this issue, but please feel free to continue the conversation. Thanks, again!

**Comment by rothja** [comment]
#please-close

**Comment by rothja** [comment]
#please-close

**Comment by orastarter** [comment]
Thank you, rothja. Why does this work `SELECT 'hi' as int`? INT is reserved keyword.

**Comment by rothja** [comment]
@orastarter To be honest, I'm not sure why this would work. I'm guessing it has to do with how the parser works that they allow this. But I think for the same reasons that this works, it is not listed on the list of terms to avoid as "reserved words". Sorry I can't provide a better answer than that. Thanks!
