### ISSUE TITLE
Incorrect code snippet

### ISSUE THREAD

**Issue by jacob-displayr** [MicrosoftDocs/sql-docs#2573]
The snippet:
SELECT 'language_id' AS "LCID" FROM sys.fulltext_index_columns; 
doesn't work when run. It should be:
SELECT language_id AS "LCID" FROM sys.fulltext_index_columns;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b1f8df8-6e72-0cf8-1f0c-4b5a609d680a
* Version Independent ID: 33fe7c44-6a47-4729-eab6-e9455f31b1f2
* Content: [Configure and Manage Word Breakers and Stemmers for Search - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/search/configure-and-manage-word-breakers-and-stemmers-for-search?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/search/configure-and-manage-word-breakers-and-stemmers-for-search.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/search/configure-and-manage-word-breakers-and-stemmers-for-search.md)
* Product: **sql**
* Technology: **search**
* GitHub Login: @pmasl
* Microsoft Alias: **pelopes**

**Comment by pmasl** [comment]
Will get it fixed. Thanks

**Comment by MightyPen** [comment]
Thanks Pedro. (Issue 2573)

@jacob-displayr Hi Jacob, just as an fyi, a very effective option that many customers like is to edit our documentation directly through a Pull Request (PR), instead of describing the fix in an Issue. If you are ever interested, you can click the Edit-pencil icon at the top-right on the article's webpage, and then click the pencil icon on the GitHub webpage.

Pedro is planning on creating a PR to fix this Issue.

Thank you.
 . .

**Comment by pmasl** [comment]
Please close, it's fixed now

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
