### ISSUE TITLE
Slight typo

### ISSUE THREAD

**Issue by aawood** [MicrosoftDocs/sql-docs#2574]
In 'Limiting the number of rows returned' section E 'Running multiple queries in a single transaction', the third comment in the example has a small typo. It reads "-- Beging the transaction"; the first word should be "Begin".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e30064c-9e16-640d-19ce-4b62c4cee65b
* Version Independent ID: 7f1a98a5-81c8-6b04-c216-ffdf81d31cce
* Content: [ORDER BY Clause (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/queries/select-order-by-clause-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/queries/select-order-by-clause-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/queries/select-order-by-clause-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by MightyPen** [comment]
@aawood Hello Adrian,  This issue 2574 is being fixed by PR 11168.  The fix should be visible in 24 hours.
Thank you for bringing this error to our attention.

A very effective option that many customers like is to - edit our documentation directly through a Pull Request (PR), instead of describing the fix in an Issue. If you are ever interested, you can click the Edit-pencil icon at the top-right on the article's webpage, and then click the pencil icon on the GitHub webpage.

Thank you for submitting this Issue. We hope to hear from you again.
I am now closing this fixed issue.
The @ notification mechanism continues to work even after an item is Closed, in case further communication is needed.
