### ISSUE TITLE
Secret must be entire query string of SAS

### ISSUE THREAD

**Issue by CastleArg** [MicrosoftDocs/sql-docs#2579]
The current example implies just the 'sig' query param is needed. 
In fact the entire query string including expiry dates etc is needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b7a6124-86bc-bd57-88c6-7c4334c49cd5
* Version Independent ID: 1598c673-fb85-3cf7-4ff9-8fdc0e384c68
* Content: [Examples of Bulk Access to Data in Azure Blob Storage - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/import-export/examples-of-bulk-access-to-data-in-azure-blob-storage?view=sql-server-2017)
* Content Source: [docs/relational-databases/import-export/examples-of-bulk-access-to-data-in-azure-blob-storage.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/import-export/examples-of-bulk-access-to-data-in-azure-blob-storage.md)
* Product: **sql**
* Technology: **data-movement**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MightyPen** [comment]
@MashaMSFT Hi Masha, Can you please process this Issue 2579. CastleArg believes a code example is incorrect.

**Comment by MashaMSFT** [comment]
Hi @CastleArg , 

Thank you for contacting Microsoft and providing your feedback to our documentation! We'll need some time to look into this further. Depending on the complexity, the turnaround time for this may vary anywhere from a few business days to a few business weeks. We'll reply via comment should we need anything further in the meantime, and please feel free to do the same.

If you're suggesting a simple change to the documentation, it may be faster for you to submit the edit yourself via a Pull Request (PR). You can do so by following these steps:

1. Navigate to the page of interest
2. Select the "Edit" button at the top right of the page
3. Select the "Pencil" icon on the right
4. Modify the text within the text box in [markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) format
5. Name your file change and copy the link to your Git Issue into the "extended description" box
6. Select "Propose file change"
7. Select "Create pull request" on the 'Comparing changes' page
8. Select "Create pull request" on the 'Open a pull request' page
9. Wait for an author to review and approve the change request - this can take a bit depending on the complexity

Doing so will allow authors to directly add your text to the documentation. This also displays your github image on the page of authors, and list you as a contributor to the documentation.

Otherwise, we'll continue to research your suggestion, and get back to you as soon as we have more information for you.

Thanks again for your submission, and hope you have a wonderful rest of your day!
Masha from SQL Docs team

**Comment by MashaMSFT** [comment]
Hi @CastleArg , Thanks again for contacting Microsoft!  We've submitted a documentation change based on your suggestion, and it should be live at this point. Please let us know if there is anything more we can do for you? If not, we'll proceed with closing out this Git Issue in a few business days.

Thanks again and hope you have a great weekend!
Masha from SQL Docs team
