### ISSUE TITLE
How will i know if this command works on SQL 2008?

### ISSUE THREAD

**Issue by sansmash** [MicrosoftDocs/sql-docs#2580]
Earlier there use to be part on the header it was showing the versions it is compatible with. In this case, CONCAT command is not supported in SQL 2008. 
Please help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a6598dc-e3b2-c92a-0be0-759ba1d21d61
* Version Independent ID: b978a25d-36ea-00cb-9a8e-90e8fa3c6f70
* Content: [CONCAT (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/concat-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/functions/concat-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/concat-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by MightyPen** [comment]
@sansmash Hello Sandeep, The "Applies To" line that you are referring to is supposed to list _Product_ information only. It was recently edited/updated to remove the improper version info (about 2008). It should not also list _Version_ information within Product, because.....

..... Please notice the _Versioning_ dropdown list, that is at the top-left of the article, and is just above the Table of Contents. The Versioning dropdown contains both Product and Version info.
In the attached screenshot image, we see a list of products, and that "SQL Server" is currently selected in the Product column.
For the selected product, we see its associated list of version in the second column, labeled Version. These are the only Product+Version combinations that this particular article _might_ apply to. To know whether the article applies to say '2016', you would click the '2016' value under Version: then if the article applies to '2016', the Product+Version across the top of the dropdown list would change to "SQL Server 2016".

The documentation for SQL Server 2008 is available on Docs at our archive location _previous-versions/sql/_ :
- `https://docs.microsoft.com/previous-versions/sql/`

---

Thank you for inquiring with this Issue 2580. We hope all our customers play with the Versioning dropdown to understand what it does. Tell all your friends about it!  :-) 
We hope to hear from you again.

I am now closing this Issue 2580.
The @ notification mechanism continues to work even after an item is Closed, in case further communication is needed.

**Comment by sansmash** [comment]
@MightyPen Hi Gene, I've already checked the versioning drop down. But whenever i click on 'older' version of SQL Server, it throws an error like "The requested page is not available for SQL Server previous versions. You have been redirected to the newest product version this page is available for."
Is it because documentation is incomplete.? 

This is important to me because, i needed to make sure my scripts are fully compatible with SQL 2008. It would be really helpful if i'm able to know if the command supports on not!

**Comment by MightyPen** [comment]
@sansmash The 'older' version, under SQL Server, is an attempt by us to make it easier to learn about the existence of previous-versions/sql/. But maybe 'older' is not working very well in practice.

The bottom line is - use the previous-versions/sql/ web address for learn about SQL 2008.

This is the second article in our main TOC:

- `https://docs.microsoft.com/sql/toc/previous-versions-sql-server`

**Comment by sansmash** [comment]
Thanks Gene.

**Comment by nickolay** [comment]
Here are the links to "String Functions (Transact-SQL)" located by browsing the previous-versions/sql/ documentation for versions 2008-2012: [2012](https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2012/ms181984%28v%3dsql.110%29), [2008R2](https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2008-r2/ms181984%28v%3dsql.105%29), [2008](https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2008/ms181984%28v%3dsql.100%29). The 2012 page is the first one to include CONCAT.

[Here's a stackoverflow question that confirms that it's been introduced in 2012](https://stackoverflow.com/a/10550343/1026).
