### ISSUE TITLE
UNION introduction/synopsis needs to state that the final result set from UNION will contain distinct rows 

### ISSUE THREAD

**Issue by ShayanZafar** [MicrosoftDocs/sql-docs#2589]
The main introduction/synopsis should mention the fact that the final result set of a UNION will reconcile duplicate rows returned in each query with only distinct values

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f0be71d-df4c-6e45-3fec-557b3da486b0
* Version Independent ID: a92cbde6-cb56-c585-334d-875c8efb4fdb
* Content: [UNION (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/set-operators-union-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/t-sql/language-elements/set-operators-union-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/language-elements/set-operators-union-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by MightyPen** [comment]
@ShayanZafar Hello Shayan, We have just now fixed with Issue #2589, with our private repo PR #11245 .

Thank you for bringing this shortcoming to our attention. We hope to hear from you again.

Closing 2589 now.

Customers like you have the option of directly editing Microsoft's documentation article, to fix or update as you see fit.  We then review the proposed change, and hopefully we approve the update to go live.
To do this, you click the "Edit"-pencil icon near the upperRight on the Docs webpage, and then click the pencil on the GitHub webpage. This enables you to edit, and to then click to create a Pull Request that contains your update. We then see that PR. It is just a nice option.
