### ISSUE TITLE
-g option

### ISSUE THREAD

**Issue by yang-jiayi** [MicrosoftDocs/sql-docs#2596]
hey.
https://docs.microsoft.com/en-us/sql/tools/sqlservr-application?view=sql-server-2017

Is the -g option supported by the latest SQL Server?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7952b332-8f4c-4ee9-6916-e9da4cd61002
* Version Independent ID: 9a2a20ee-e340-2488-9a7e-1b1cbf001e9c
* Content: [Database Engine Service Startup Options - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/database-engine-service-startup-options?view=sql-server-2017&fbclid=IwAR3aHsr-XJmKAwm-jS_wzpjoFT_A_iJQykTcMVoo0rPPrhpddMnBI33McpU)
* Content Source: [docs/database-engine/configure-windows/database-engine-service-startup-options.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/database-engine-service-startup-options.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by MightyPen** [comment]
(This Issue 2596 seems closely related to #2601
`https://github.com/MicrosoftDocs/sql-docs/issues/2596`
)

**Comment by msebolt** [comment]
@MikeRayMSFT Should this be forwarded to engineering?

Running `sqlservr.exe /?` lists the `-g` startup option and allows its use, but nowhere is it mentioned in the startup messaging.

**Comment by MikeRayMSFT** [comment]
@yang-jiayi  - I believe it doesn't apply to 64-bit applications, but I'm double checking. It appears there are several related places to update. I will confirm. Thanks for raising the issue.

**Comment by MikeRayMSFT** [comment]
@yang-jiayi - thank you for submitting this. We're submitting an update to remove this inoperable parameter from the options. We'll explain that it was supported through 2014.

**Comment by yang-jiayi** [comment]
@MikeRayMSFT 
Thanks for help!

**Comment by ry0uta** [comment]
I use a translation service. I am sorry if my English is not correct.
I am the author of https://github.com/MicrosoftDocs/sql-docs/issues/2601

Thank you for correcting the document. Japanese documents do not seem to be fixed yet, but I believe that they will be fixed in the future.

As I wrote in https://github.com/MicrosoftDocs/sql-docs/issues/2601, The 2017 version of the following documents have descriptions based on -g (memory_to_reserve).

https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/server-memory-server-configuration-options?view=sql-server-2017#setting-the-memory-options-manually

https://docs.microsoft.com/en-us/sql/relational-databases/memory-management-architecture-guide?view=sql-server-2017#changes-to-memory_to_reserve-starting-with-

It should be clear how these contents should be considered in SQL Server 2017.
