### ISSUE TITLE
Failed to start session: An exception occurred while executing a Transact-SQL statement or batch.

### ISSUE THREAD

**Issue by alexr-degreed** [MicrosoftDocs/sql-docs#2604]
I am currently getting this error trying to run the sql profiler in Azure Data Studio:

Failed to start session: An exception occurred while executing a Transact-SQL statement or batch.

AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] (node:17012) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 Failed to start session: An exception occurred while executing a Transact-SQL statement or batch.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ddbdcc5-661b-427d-7080-902c4611f739
* Version Independent ID: 3cf010c2-45ef-b58a-4091-c79c3e67cfef
* Content: [SQL Server Profiler extension - Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/sql-server-profiler-extension?view=sql-server-2017)
* Content Source: [docs/azure-data-studio/sql-server-profiler-extension.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/sql-server-profiler-extension.md)
* Product: **sql**
* Technology: **azure-data-studio**
* GitHub Login: @yualan
* Microsoft Alias: **alayu**

**Comment by WilliamAntonRohm** [comment]
@alexr-degreed -- Alex, thank you for your feedback.  This seems like a support issue rather than an issue with the documentation itself.

Please consider looking into the following support resources:

- [SQL Server Data Tools - MSDN forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=ssdt&filter=alltypes&sort=lastpostdesc)
- [Transact-SQL - MSDN forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=transactsql)
- [DBA Stack Exchange (tag sql-server) - ask SQL Server questions](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow (tag sql-server) - also has some answers about SQL development](https://stackoverflow.com/questions/tagged/sql-server) 
- [Support options for business users](https://support.microsoft.com/gp/support-options-for-business)

**Comment by WilliamAntonRohm** [comment]
@yualan -- Alan, fyi.
