### ISSUE TITLE
More contextual information required

### ISSUE THREAD

**Issue by dmacko** [MicrosoftDocs/sql-docs#2611]
Many of these parameters have different behaviours depending on the replication environment in which the merge agent is being run - for example, if web synchronisation is being used, then -DownloadGenerationsPerBatch does not appear to do anything.

Maybe it would be worthwhile to have a page for each merge replication type (pull, push, and pull+websync?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a4be28a-07d1-8bba-568b-05656ee20bbb
* Version Independent ID: 92aa0abd-658e-a6a3-612b-df4816619441
* Content: [Replication Merge Agent - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/replication/agents/replication-merge-agent?view=sql-server-2017)
* Content Source: [docs/relational-databases/replication/agents/replication-merge-agent.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/replication/agents/replication-merge-agent.md)
* Product: **sql**
* Technology: **replication**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @dmacko,

Thank you for contacting Microsoft and providing your feedback to our documentation! We'll need some time to look into this further. Depending on the complexity, the turnaround time for this may vary anywhere from a few business days to a few business weeks. We'll reply via comment should we need anything further in the meantime, and please feel free to do the same.

Thanks again for your submission, and hope you have a wonderful rest of your day!
Masha from SQL Docs team

**Comment by MashaMSFT** [comment]
Hi @dmacko , 

Thanks again for reaching out! My concern with splitting these articles would be a disparate experience for customers that may contribute to confusion rather than alleviating it. Especially because there aren't many differences between the parameters depending on the replication type. 

In fact, would you mind providing more information about why you think that parameter does nothing?

Thanks!
Masha from the SQL Docs team

**Comment by dmacko** [comment]
Hi Masha, thanks for your reply.

I think you're right about that the confusion problem - It would make things a bit complicated if there's only one page for the other agents, and multiple pages for the merge agent.

With regards to my comments about the parameter not doing anything under web synchronisation - I had some issues some time ago with a subscriber (using web sync) that hadn't replicated in a while - It was replicating, but it was doing so quite slowly. When I tried re-running the merge agent using different values for the download parameters, I did not observe any changes in the msmerge_history table or in the performance.

I might be wrong about that parameter's behaviour - it would be nice to have some further clarity in the documentation about how the merge agent behaves, especially under web synchronisation.

Thanks,
-Daniel

**Comment by MashaMSFT** [comment]
Hi @dmacko, just wanted to provide you with a quick update and let you know I'm still looking into this :) Thanks!

- Masha from the SQL Docs team

**Comment by MashaMSFT** [comment]
Hi @dmacko,

Thanks again for providing your suggestion to improve our docs! I have opened an item in our internal tracking system around adding clarity for the merge agent parameters. For bookkeeping purposes, I will close out this Git Issue, but I will update you once the changes have been made. Due to the complexity, it may take some time for us to publish these changes. 

In the meantime, please feel free to reach out via comment should you need anything.

Thanks again and hope you have a great weekend!
Masha from the SQL Docs team
