### ISSUE TITLE
not able to download the exe file for SSMS

### ISSUE THREAD

**Issue by AJAnujsharma** [MicrosoftDocs/sql-docs#2612]
Hi Team,
When we try to download the .exe file its downloads and once 528mb is downloaded it again restart the downloading process from 0 mb, I have tried this several times in different networks but the issue persists.

Anuj

**Comment by msebolt** [comment]
@AJAnujsharma Thank you for the feedback.

Can you provide the specific link as reference?

**Comment by msebolt** [comment]
Please comment below if there are any further issues.

**Comment by AJAnujsharma** [comment]
Hi @msebolt , Aplogy for the delayed response 

Below is the link where i was finding the issue while downloading ssms 

https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017

**Comment by msebolt** [comment]
Hi @AJAnujsharma Thank you for the link and sorry for your difficulties.

I'm guessing this is a network issue since I can download from my machine.  

Another option is to try [downloading previous versions](https://docs.microsoft.com/en-us/sql/ssms/release-notes-ssms?view=sql-server-2017#download-ssms-180) from different locations.  In particular, [version 2008](https://www.microsoft.com/en-us/download/details.aspx?id=7593) is under 200 MB.
