### ISSUE TITLE
<backup_device> missing URL

### ISSUE THREAD

**Issue by gmassari-88** [MicrosoftDocs/sql-docs#2613]
Maybe it's not supported but I'm able to `RESTORE HEADERONLY FROM URL`  successfully - if it actually is supported then the page is missing this info :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9e8a50f-dd56-7b9e-58a8-7842710f9d1e
* Version Independent ID: d1d3e45f-f441-95ce-34a3-38faeebc0da6
* Content: [RESTORE HEADERONLY (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/restore-statements-headeronly-transact-sql?view=sql-server-2016#feedback)
* Content Source: [docs/t-sql/statements/restore-statements-headeronly-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/restore-statements-headeronly-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by MashaMSFT** [comment]
Hi @gmassari-88, 

Thank you for contacting Microsoft and providing your feedback to our documentation! We'll need some time to look into this further. Depending on the complexity, the turnaround time for this may vary anywhere from a few business days to a few business weeks. We'll reply via comment should we need anything further in the meantime, and please feel free to do the same.

If you're suggesting a simple change to the documentation, it may be faster for you to submit the edit yourself via a Pull Request (PR). You can do so by following these steps:

1. Navigate to the page of interest
2. Select the "Edit" button at the top right of the page
3. Select the "Pencil" icon on the right
4. Modify the text within the text box in [markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) format
5. Name your file change and copy the link to your Git Issue into the "extended description" box
6. Select "Propose file change"
7. Select "Create pull request" on the 'Comparing changes' page
8. Select "Create pull request" on the 'Open a pull request' page
9. Wait for an author to review and approve the change request - this can take a bit depending on the complexity

Doing so will allow authors to directly add your text to the documentation. This also displays your github image on the page of authors, and list you as a contributor to the documentation.

Otherwise, we'll continue to research your suggestion, and get back to you as soon as we have more information for you.

Thanks again for your submission, and hope you have a wonderful rest of your day!
Masha from SQL Docs team

**Comment by MashaMSFT** [comment]
Hi @gmassari-88 , thanks again for bringing this to our attention! Restore from URL is supported starting with SQL Server 2012 SP1 CU2, and it looks like this is a gap in our documentation. Thanks for noticing! We're working on getting some documentation published but it make take a bit. We're going to close this Issue in the meantime, but we are working on it :) I will update you once the changes have gone live. Please feel free to reach out should you need anything in the meantime.

Thanks again and hope you have a wonderful rest of your day!
Masha from the SQL Docs team
