### ISSUE TITLE
关于 SQL Server SSRS 函数表达式文章 内容错误 #1771

### ISSUE THREAD

**Issue by ryanmajidi** [MicrosoftDocs/sql-docs#2619]
**Submitted to [site feedback](https://github.com/MicrosoftDocs/feedback/issues/1771) by @chaoxiaole**

在 地址为 https://docs.microsoft.com/zh-cn/sql/reporting-services/report-design/expression-examples-report-builder-and-ssrs?view=sql-server-2014

文章中 关于 lookup函数表达式感觉有错误。
原文如下：
=Lookup(Fields!PID.Value, Fields!ProductID.Value, Fields.ProductName.Value, "Product")
个人感觉是否应该是：
=Lookup(Fields!PID.Value, Fields!ProductID.Value, Fields!ProductName.Value, "Product")

一个关于！的小问题。
如果指出的问题不对，请谅解，刚刚开始学习。

**Comment by MightyPen** [comment]
Issue #2619. 

- [https://docs.microsoft.com/en-us/sql/reporting-services/report-design/expression-examples-report-builder-and-ssrs?view=sql-server-201**6**](https://docs.microsoft.com/en-us/sql/reporting-services/report-design/expression-examples-report-builder-and-ssrs?view=sql-server-2016)
  - _TITLE:_  "Expression Examples (Report Builder and SSRS)"
  - _ms.author GitHub name is_ 'markingmyname' (probably not really MaggieMSFT).
  - Same link, with `?view=sql-server-2014`, should very likely receive the same fix by you as -201**6**, if either is fixed.  See under **docs/2014/reporting-services/**..... .
Both .md files (with same filename but slightly different directory paths) should be fixed in the same one PR.

_Customer 'chaoxiaole' says:_
There is an error in the article about the lookup function expression.
The original text is as follows:
`=Lookup(Fields!PID.Value, Fields!ProductID.Value, Fields.ProductName.Value, "Product")`
But that seems wrong, and correct would likely use another `!`, before `ProductName`:
`=Lookup(Fields!PID.Value, Fields!ProductID.Value, Fields!ProductName.Value, "Product")`

**Comment by MightyPen** [comment]
Being fixed by PR 11295:

- https://github.com/MicrosoftDocs/sql-docs-pr/pull/11295

**Comment by MightyPen** [comment]
@chaoxiaole Hello, Thank you for reporting this documentation error to us. The fix will be live within 24 hours.
Thank you for submitting this Issue #2619 (Issue #1771). We hope to hear from you again.
I am now Closing this Issue 2619, as fixed.
