### ISSUE TITLE
Can we have pictures and images in the tutorial?

### ISSUE THREAD

**Issue by chanmmn** [MicrosoftDocs/sql-docs#2654]
The page such as https://docs.microsoft.com/en-us/sql/integration-services/lesson-1-2-adding-and-configuring-a-flat-file-connection-manager?view=sql-server-2017 and https://docs.microsoft.com/en-us/sql/integration-services/lesson-1-6-adding-and-configuring-the-lookup-transformations?view=sql-server-2017 can be better understand with pictures in them. I have actually tried to capture and upload the pictures to the media folder, but I have no enough permission to do so. Maybe the content owner should consider that. 
This is more like a request than an issue.

**Comment by MightyPen** [comment]
@rothja Hi Jason, Janine Zhang is nominally the owner of these docs/integration-services/ articles, but your team might be the only team that will consider making these kinds of documentation enhancements (such as Add Screenshot Images)?  Or ask Janine.
Each of these articles is popular, with lots of pageviews.

If due to your team's heavy workload, your team does not have the resources to make these enhancements, then please briefly mention that and then close this Issue #2654 .
Thanks. G

cc: @janinezhang

**Comment by janinezhang** [comment]
While your request is reasonable, for existing SSIS customers this document does provide sufficient steps to follow, and I don't have bandwidth to enhance this doc.

**Comment by MightyPen** [comment]
@chanmmn This Issue #2654 suggests a documentation enhancement, by the addition of screenshots.
This is a reasonable idea. However, there are reasons why we sometimes need to avoid screenshots or minimize our use of screenshots. Screenshots go out of date, and maintaining them all may not be plausible given the huge amount of work we already have.

For now, we have decided not to add screenshots to this article.

I am now Closing this Issue. The @ notification mechanism continues to work even after an item is Closed, in case further communication is needed.

Thank you for submitting this Issue. We hope to hear from you again.

cc: @janinezhang
