### ISSUE TITLE
Extended Events

### ISSUE THREAD

**Issue by keeyu2** [MicrosoftDocs/sql-docs#2667]
1. Creating a new session and clicking on Events.  SSMS locks up. 
2.  Uninstalled and Reinstalled SSMS 18.2 and doesn't work
3. I have to end task.

**Comment by MightyPen** [comment]
@markingmyname Hi Mark, Is there a lingering problem from the SSMS 18.1 fix?

@keeyu2 Hi Kenny, I suspect the event session would be created fine if you installed SSMS 18.0 (although I cannot be sure).  Anyway, I am passing your Issue #2667 along to the SSMS team.  Thank you for bringing this to our attention.

**Comment by markingmyname** [comment]
@keeyu2,

I was able to reproduce this issue with 18.1.  If I can reproduce this also with 18.2, then I will engage our engineering team to take a look at this issue.

Thank you for your patience.

**Comment by markingmyname** [comment]
@keeyu2,

I can reproduce this even with 18.2.

I will move forward with engaging our engineering team.

Thank you.

**Comment by markingmyname** [comment]
@keeyu2,

The engineering team is aware of this issue and are in the process of correcting it.  Unfortunately, I do not have an ETA on the bug fix release. However, you can visit [UserVoice](https://feedback.azure.com/forums/908035-sql-server) to see how often this issue is affecting other users and submit a vote to help elevate its importance. 

I hope this helps.

Thank you.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) site.
