### ISSUE TITLE
bcp Unicode Character encoding format not specified

### ISSUE THREAD

**Issue by simon-biber** [MicrosoftDocs/sql-docs#2710]
The article doesn't specify which Unicode encoding is used for Unicode character format. Is it UTF-8, UTF-16-BE, UTF-16-LE or UTF-32? Is there a way to choose among these?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24585fc4-f2c4-ed59-0d18-9e8f3a9f2fc0
* Version Independent ID: f6c4db9b-efe4-6cbf-637f-bf2a40c0501e
* Content: [Use Unicode Character Format to Import or Export Data (SQL Server) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/import-export/use-unicode-character-format-to-import-or-export-data-sql-server?view=sql-server-2017)
* Content Source: [docs/relational-databases/import-export/use-unicode-character-format-to-import-or-export-data-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/import-export/use-unicode-character-format-to-import-or-export-data-sql-server.md)
* Product: **sql**
* Technology: **data-movement**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @simon-biber ,

Thank you for contacting Microsoft and providing your feedback to our documentation! We'll need some time to look into this further. Depending on the complexity, the turnaround time for this may vary anywhere from a few business days to a few business weeks. We'll reply via comment should we need anything further in the meantime, and please feel free to do the same.

Otherwise, we'll continue to research your suggestion, and get back to you as soon as we have more information for you.

Thanks again for your submission!
Masha from SQL Docs team

**Comment by MashaMSFT** [comment]
Hi @simon-biber , thanks again for reaching out! The encoding is actually specified in the BCP command itself, and this is why it's not mentioned in this doc. Please see [bcp utility](https://docs.microsoft.com/en-us/sql/tools/bcp-utility?view=sql-server-2017#C) for more information.

I hope that helps and please let us know if we can be of further assistance :) If not, we'll proceed with closing out this Git issue in a few business days.

Thanks!
Masha from the SQL Docs team

**Comment by dawidi** [comment]
The format BCP expects when importing with -w seems to be UTF-16 LE (also called UCS-2 LE) with a BOM, same as the .NET encoding "1200" - at least that's what worked for me.
As far as I can tell, whenever Microsoft docs speak of "Unicode" without naming the exact encoding, that is what they mean, because Windows internally uses that exclusively.
