### ISSUE TITLE
Do we have multi level partitioning ?

### ISSUE THREAD

**Issue by AJAnujsharma** [MicrosoftDocs/sql-docs#2721]
Do we have any concept like SUBPARTITION ?

**Comment by WilliamAntonRohm** [comment]
@AJAnujsharma Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.

**Comment by AJAnujsharma** [comment]
I'm working on SQL DW - which has data around 16bn i have used a partitioned already but i wanted another partitoned or to get a clear picture multilevel partitioning or Subpartitioning. Is it possible in SQL Server ?

**Comment by msebolt** [comment]
@AJAnujsharma Are you referring to external or internal partitioning?  

Each has its own way to design "multi-level".

For external drives, see [maximum capacity specifications](https://docs.microsoft.com/sql/sql-server/maximum-capacity-specifications-for-sql-server?view=sql-server-ver15#DAC) which states up to 50 instances per computer.  With multi-level support you can customize instances per partition (i.e. backup instances would be installed on slower partitions, etc.).

Otherwise with internal partitioning, see [Partitioned tables and indexes](https://docs.microsoft.com/sql/relational-databases/partitions/partitioned-tables-and-indexes?view=sql-server-2017).  This is more about data optimizing large tables and is currently limited to 1000 partitions per table.  Using indexes can add another layer to this design, see [Table and index organization](https://docs.microsoft.com/previous-versions/sql/sql-server-2008/ms189051%28v%3dsql.100%29).

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
