### ISSUE TITLE
Consistency Issue

### ISSUE THREAD

**Issue by ma17961363** [MicrosoftDocs/sql-docs#2755]
I have problem with MS SQL Always On Availability. Suppose the connection between primary and secondary replica is broken. The client inserts data to the primary database (replication cannot be done because of disconnection) that committed. Then the connection between client and primary database is disconnected. Now the client should be connected to the secondary database but it has not the last inserted data by the client. How does this problem can be solved?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c5b4585-159a-6472-140f-8e9439222ab7
* Version Independent ID: 03a14cb4-5589-1156-5a4e-938665968ebb
* Content: [Overview of Always On Availability Groups - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/overview-of-always-on-availability-groups-sql-server?view=sql-server-2017)
* Content Source: [docs/database-engine/availability-groups/windows/overview-of-always-on-availability-groups-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/overview-of-always-on-availability-groups-sql-server.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @ma17961363 , thanks for contacting Microsoft! I'm not sure I understand the scenario you're describing. If the connection is broken between the primary and secondary replica, then how is the client connecting to the secondary replica? 

Thanks!
Masha from the SQL Docs team

**Comment by ma17961363** [comment]
Hi @MashaMSFT, thanks for the reply. In the mentioned scenario, it is supposed the connection problem is between primary and secondary not secondary and client.

**Comment by MashaMSFT** [comment]
Hi @ma17961363 , just to make sure I understand correctly.. 
1. The secondary replica disconnected, meaning that changes from the primary did not make it over to the secondary
2. The connection between the two replicas was fixed
3. The client is _manually_ connecting to the secondary replica expecting changes from the primary to be on the secondary, but the secondary has not yet caught up

Is that correct?

Thanks!
Masha from the SQL Docs team

**Comment by ma17961363** [comment]
Hi @MashaMSFT, yes exactly but I supposed there is one replica (secondary) server.

1. The primary has a connection problem with the replica.
2. The primary and client do not have any problem to reach each other.
3. The primary has got a connection problem now and the client no longer can connect to it.
4. The client is manually connecting to the replica (secondary server) expecting changes from the primary to be on the secondary, but the secondary has not yet caught up.

Thank you.

**Comment by MashaMSFT** [comment]
Hi @ma17961363 , thank you for patience as I researched this for you! 

This is an expected limitation of the availability group infrastructure. If there is a disconnection between the primary and secondary replica, then changes will not propagate, and therefore data will not be synchronized. This is documented here: https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/active-secondaries-readable-secondary-replicas-always-on-availability-groups?view=sql-server-2017#DataLatency  and here: https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/availability-modes-always-on-availability-groups?view=sql-server-2017#SyncCommitAvMode 

Unfortunately, we cannot guarantee data accuracy on the secondary replica until there is a healthy connection between the two replicas, and even then, there may be a slight discrepancy between the visible data on the primary and the secondary, depending on network latency and the speed of the redo thread on the secondary replica. Just because a change has been hardened on the secondary replica (which is what's necessary for the commit to go through on the primary), it doesn't mean that change has been redone yet, so that's where you might see that delay.

I hope that helps and please let me know if we can be of further assistance? If not, I will proceed with closing out this Git Issue in a few business days.

Thanks!
Masha from the SQL Docs team

**Comment by ma17961363** [comment]
Thanks @MashaMSFT. It helped completely.
