### ISSUE TITLE
procedure "sp_add_log_shipping_secondary_primary"

### ISSUE THREAD

**Issue by gayazshaik** [MicrosoftDocs/sql-docs#2776]
when we follow above mentioned syntax, by default database is getting restored as stand by mode, any option to ensure database does not go onto stand by mode using this procedure or is there any other procedure using script?

Error message:
 Error: This backup cannot be restored using WITH STANDBY because a database upgrade is needed. Reissue the RESTORE without WITH STANDBY.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0506789-33c5-6ea6-dfa2-87b1feb563d0
* Version Independent ID: fba4f3d4-5995-476a-112c-854af08a978d
* Content: [sp_add_log_shipping_secondary_primary (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-add-log-shipping-secondary-primary-transact-sql?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/system-stored-procedures/sp-add-log-shipping-secondary-primary-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-stored-procedures/sp-add-log-shipping-secondary-primary-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by msebolt** [comment]
@gayazshaik  Thank you for the question.

From the following [StackOverflow post](https://dba.stackexchange.com/questions/55072/this-backup-cannot-be-restored-using-with-standby-because-a-database-upgrade-is) this occurs when the databases are not the same version.

This issue has been moved to the [SQL Server forums](https://feedback.azure.com/forums/908035-sql-server/suggestions/38422945-sp-add-log-shipping-secondary-primary-has-with-sta).

**Comment by msebolt** [comment]
There is nothing further that can be done with the documentation.

Please direct feedback to the link posted above.
