### ISSUE TITLE
Page "Integration Services Backward Compatibility" inconsistent

### ISSUE THREAD

**Issue by abbgrade** [MicrosoftDocs/sql-docs#2792]
The page "Integration Services Backward Compatibility" looks wrong.
The same content is delivered for 2016, 2017 and 2019. The headings contain 2016 and the paragraphs 2017.

https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/integration-services/integration-services-backward-compatibility.md

**Comment by WilliamAntonRohm** [comment]
@abbgrade -- Steffen, thank you for your feedback.  I am looking into this issue.

**Comment by abbgrade** [comment]
It's the same for Reporting Services (https://docs.microsoft.com/de-de/sql/reporting-services/reporting-services-backward-compatibility?view=sql-server-2017)

**Comment by abbgrade** [comment]
And here https://docs.microsoft.com/de-de/sql/reporting-services/discontinued-functionality-to-sql-server-reporting-services-in-sql-server?view=sql-server-2014#bkmk_rc0 for 2012 to 2014.

**Comment by abbgrade** [comment]
The page https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2012/cc707784(v%3dsql.110) lists two breaking changes for SQL Server 2012 but https://docs.microsoft.com/en-us/sql/database-engine/breaking-changes-to-database-engine-features-in-sql-server-2016?view=sql-server-2014#Denali has a lot of other breaking changes for 2012.

**Comment by rothja** [comment]
@chugugrace You're the current owner of this content. I believe what happened is that the INCLUDE files are being used for the product name. the ssCurrent INCLUDE in the article defaulted to the latest version but it resulted in the text not making sense. I would recommend taking out the includes and having static strings for the SQL Server product names in this article. Otherwise the meaning will be very confusing. #reassign:chugugrace

**Comment by craigg-msft** [comment]
@chugugrace . also sending email as a reminder

**Comment by chugugrace** [comment]
Fixed in PR: https://github.com/MicrosoftDocs/sql-docs-pr/pull/17493
