### ISSUE TITLE
Description for SQL_BIGINT is (completely) wrong

### ISSUE THREAD

**Issue by lsmith999999** [MicrosoftDocs/sql-docs#2804]
See https://docs.microsoft.com/en-us/sql/odbc/reference/appendixes/transfer-octet-length?view=sql-server-2017. The "Transfer Octet Length" seen here for SQL_BIGINT is an [unsigned] __int64 on Windows, and therefore always 8 bytes. It's not a character string in this context (as the latter link currently describes it). A call to "SQLColAttribute() for instance, passing SQL_DESC_OCTET_LENGTH for the "FieldIdentifier" arg, confirms this (as would be expected).

**Comment by rothja** [comment]
@lsmith999999 Thank you for your feedback. We apologize for the delayed response. @MightyPen could you take a look at this feeedback and let me know if you're the right person to help? Thank you!

**Comment by MightyPen** [comment]
@lsmith999999 Hello, The fix for this Issue #2804 is now merged into our master branch.  The fix will appear on our live Docs website within 24 hours.
Thank you for submitting this Issue. We hope to hear from you again.
I am now Closing this Issue, as fixed.

- `https://github.com/MicrosoftDocs/sql-docs-pr/pull/12673`

cc: @rothja 
 . .
