### ISSUE TITLE
TABLOCK

### ISSUE THREAD

**Issue by stevethresh** [MicrosoftDocs/sql-docs#2893]
Which API do you use to enable TABLOCK?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 769b52a9-d98c-7848-6140-3de5e33076ef
* Version Independent ID: 6f17664b-b940-2244-03e7-8abb75eaaeda
* Content: [Managing Bulk Copy Batch Sizes - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/native-client-odbc-bulk-copy-operations/managing-bulk-copy-batch-sizes?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/native-client-odbc-bulk-copy-operations/managing-bulk-copy-batch-sizes.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/native-client-odbc-bulk-copy-operations/managing-bulk-copy-batch-sizes.md)
* Product: **sql**
* Technology: **native-client**
* GitHub Login: @MightyPen
* Microsoft Alias: **genemi**

**Comment by MightyPen** [comment]
@David-Engel Hi David, Do you know the "API" that a program can use to "enable TABLOCK"?

I gather that having the program simply issue a T-SQL statement to gain the table lock is insufficient, perhaps because the lock would belong to another session?

@stevethresh Hello Steve, we have begun to process your new Issue #2893. Thanks.

**Comment by stevethresh** [comment]
Found it! Call bcp_control() and use the BCPHINTS option. https://stackoverflow.com/questions/57690444/howto-specify-tablock-with-the-odbc-api
