### ISSUE TITLE
In picture EKH with AKV - master ou user database? 

### ISSUE THREAD

**Issue by EikisteinS** [MicrosoftDocs/sql-docs#2921]
Can you confirm whether in the picture that compares EKH (traditional) and EKH with AKV, the bottom right green (SQL Server instance) is indeed to be master database and not user database?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8a49313-385a-3f77-5468-f6b5c631adcb
* Version Independent ID: 913fde38-b0c6-6abc-1a7f-69ae976a9c30
* Content: [Extensible Key Management Using Azure Key Vault (SQL Server) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/extensible-key-management-using-azure-key-vault-sql-server?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/security/encryption/extensible-key-management-using-azure-key-vault-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/extensible-key-management-using-azure-key-vault-sql-server.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @aliceku
* Microsoft Alias: **aliceku**

**Comment by rothja** [comment]
@EikisteinS Thank you for the question and apologies for the delayed response. I am reaching out internally to see if there is someone that can respond to this issue. Thank you!

**Comment by hugobarona** [comment]
Hi there. I noticed exactly the same as @EikisteinS, and i would say it is the user database and not the master database, since this key is stored in the database user, since it is the only database with access to the external EKM/HSM module, as stated here - https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/extensible-key-management-ekm?view=sql-server-ver15.

"SQL Server Extensible Key Management enables the encryption keys that protect the database files to be stored in an off-box device such as a smartcard, USB device, or EKM/HSM module. This also enables data protection from database administrators (except members of the sysadmin group). Data can be encrypted by using encryption keys that only the database user has access to on the external EKM/HSM module."

**Comment by rothja** [comment]
@jaszymas, I believe you're the new owner of this content. Can you take a look? Thank you! #reassign:jaszymas

**Comment by SgtSpamCan** [comment]
@rothja Wondering if this will be definitively answered for documentations sake, as in an Azure Sql environment one does not want to depend on a Master database.

**Comment by rothja** [comment]
@SgtSpamCan Larry, thanks for the ping. I don't have a definitive answer, but I'm following up internally. Thanks for your patience.

**Comment by VanMSFT** [comment]
@EikisteinS @hugobarona @SgtSpamCan - Hi all, we've confirmed with the Product Team who verified that the diagram is indeed correct. The DEK resides in the master database. Please let us know if you have any concerns. Thanks!
