### ISSUE TITLE
Suggestion: call input range disparity between CHAR() and NCHAR()

### ISSUE THREAD

**Issue by perennialmind** [MicrosoftDocs/sql-docs#2922]
Given that the `NCHAR` function was extended to support non-BMP/supplementary codepoints with adequate storage for UTF-16 surrogate pairs, changing the return type to`NVARCHAR(2)`, one might reasonably expect the `CHAR` function to likewise support UTF-8 collations by returning `VARCHAR(4)`. As this is not the case, please consider updating the "non-European character set" note which references the legacy `Shift_JIS` "double-byte" case to include mention of modern multi-byte UTF-8 and the effective input range 0-127.

Also, please consider adding an example showing how one may safely produce multibyte `VARCHAR(4)` from a given codepoint when the default collation is not a _UTF8 variant. In other words, rather than saying "it won't work", show a workaround.

Assuming effective collation is SQL_Latin1_General_CP1_CI_AS:
```
SELECT CHAR(9834) COLLATE Japanese_CI_AI -- NULL
SELECT CONVERT(CHAR(2), NCHAR(9834)) COLLATE Japanese_CI_AI -- ?
SELECT CONVERT(CHAR(2), NCHAR(9834) COLLATE Japanese_CI_AI) -- ♪

SELECT CHAR(9835) COLLATE Latin1_General_100_CI_AI_UTF8 -- NULL
SELECT CONVERT(VARCHAR(4), NCHAR(9835)) COLLATE Latin1_General_100_CI_AI_UTF8 -- ?
SELECT CONVERT(VARCHAR(4), NCHAR(9835) COLLATE Latin1_General_100_CI_AI_UTF8) -- ♫
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8cf272b-3e28-160e-7e32-cf824766f87a
* Version Independent ID: cb16a55b-c7c3-8e5a-7b1e-9fb8d16cedc2
* Content: [CHAR (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/char-transact-sql?view=sql-server-2017)
* Content Source: [docs/t-sql/functions/char-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/char-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by srutzky** [comment]
@perennialmind Yes, this is a confusion caused by the current wording of the doc. Please see the UTF-8 specific feedback I opened because this behavior wasn't more obvious and not well documented:

[UTF-8 in SQL 2019: CHAR() function broken in databases with "_UTF8" default Collation](https://feedback.azure.com/forums/908035-sql-server/suggestions/35587813-utf-8-in-sql-2019-char-function-broken-in-datab)

Also, minor note regarding terminology: there are no such things as "surrogate characters". There are surrogate _code points_ which can be used in combination in the UTF-16 encoding scheme to produce _supplementary_ characters. But, the surrogate code points individually have no meaning and can never produce a "character", per se. (Sorry, I know that's a bit nit-picky, but I have been seeing the term "surrogate character(s)" in quite a few places lately so I thought I would clarify before the usage becomes too common (hopefully)).

**Comment by perennialmind** [comment]
@srutzky Thank for calling that out. I was thinking of "surrogate pairs", as amended.

As for the uservoice suggestion: I wholeheartedly agree that extending parity to CHAR() would be ideal. (I chimed in on that on back in January). Absent that sensible change, our best bet is to be precise and advertise the rough edges.

**Comment by srutzky** [comment]
@perennialmind / @xemed-ahope : No problem. And thanks for your input on that FeedBack item. I now see the connection between the usernames and the avatar.

I see that you updated the main post here, but also that you used "supplementary characters" in your comment on that FeedBack item. I think that "supplementary characters" is more accurate than "surrogate pairs" because technically speaking, creating supplementary characters from surrogate pairs had already been supported:

```sql
SELECT NCHAR(0xD83D) + NCHAR(0xDE08) AS [Surrogate Pair], -- Works regardless of DB collation.
       NCHAR(0x1F608) AS [Code Point (Hex)],    -- NULL if DB collation is not Supplementary-
       NCHAR(128520) AS [Code Point (Decimal)]; -- Character aware ("_SC" or "_140" in name).

/*
Surrogate Pair     Code Point (Hex)     Code Point (Decimal)
😈                😈                   😈
*/
```

The change that you are referring to regarding `NCHAR()`  is the ability to create a supplementary character using the actual code point (which is 0x10000 / 65536 through 0x10FFFF / 1114111, whereas previously 0xFFFF  / 65535 was the highest code point one could specify).

Again, I don't mean to be overly nit-picky. I just want to make sure that even if you already understand all of this, many readers will not and I want to reduce the wide-spread misunderstanding related to Unicode and encodings in general 😺 .

But yes, I completely agree that ideally `CHAR()` would be updated to support multi-byte output such that DBCS and UTF-8 collations would produce valid output for all valid input within those 8-bit encodings. And, if that can't happen, then at least be clear in the documentation regarding the precise behavior and limitations of the `CHAR()` function.

Take care,
Solomon...
https://SqlQuantumLeap.com/

**Comment by perennialmind** [comment]
@srutzky : Comments like yours have value for posterity, preserving clarifications and perspectives, and for me personally, just not. It wouldn't occur to individually address and fabricate surrogate code units with a UTF-16 type. I tend to forget that `NCHAR` was a UCS2 type until relatively recently. That's exactly the sort of intermixing of abstractions that's prohibited for DBCS character sets with `CHAR()`. I'm a bit surprised it's accepted under _SC collations!

Lately, I've been trying to avoid the term "character" in favor of "code unit", "code point", and "grapheme cluster". I think I need to be more careful with "surrogate" as well! I'll amend the issue description again.

**Comment by MikeRayMSFT** [comment]
@perennialmind - I'm working to validate https://github.com/MicrosoftDocs/sql-docs/pull/2925 - also reviewing this content. Thanks for the spirited discussion.

**Comment by MikeRayMSFT** [comment]
@pmasl - this is related to https://github.com/MicrosoftDocs/sql-docs/pull/2925/files - thanks.

**Comment by MikeRayMSFT** [comment]
@perennialmind - per discussion with @pmasl, you may submit this request as a product feature request through [user voice](https://feedback.azure.com/forums/908035-sql-server/).

Thank you.
