### ISSUE TITLE
Index/Table wording swap

### ISSUE THREAD

**Issue by calabast** [MicrosoftDocs/sql-docs#2958]
In the opening paragraph, the last sentence says "...an index on a memory-optimized index differs..."  

I believe it should read "...an index on a memory-optimized table differs..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a9c5960-23d2-409d-1899-9bd8e079c217
* Version Independent ID: 5626e74a-6059-ab65-5564-cf18208f0038
* Content: [Indexes for Memory-Optimized Tables - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/in-memory-oltp/indexes-for-memory-optimized-tables?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/in-memory-oltp/indexes-for-memory-optimized-tables.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/in-memory-oltp/indexes-for-memory-optimized-tables.md)
* Product: **sql**
* Technology: **in-memory-oltp**
* GitHub Login: @MightyPen
* Microsoft Alias: **genemi**

**Comment by MightyPen** [comment]
@calabast Hello, The fix for this Issue #2958 will be merged in tomorrow, with private repo #12018.

- `https://github.com/MicrosoftDocs/sql-docs-pr/pull/12018`

Thank you for submitting this Issue. We hope to hear from you again.

By the way, customers like you have the option of directly editing Microsoft's documentation article, to fix or update as you see fit.  We then review the proposed change, and hopefully we approve the update to go live.
To do this, you click the "Edit"-pencil icon near the upperRight on the Docs webpage, and then click the pencil on the GitHub webpage. This enables you to edit, and to then click to create a Pull Request that contains your update. We then see that PR. It is just a nice option.

**Comment by MightyPen** [comment]
Oops, closing now.
