### ISSUE TITLE
AdventureWorks Installation and configuration

### ISSUE THREAD

**Issue by rootsmusic** [MicrosoftDocs/sql-docs#2959]
Under the section ["Install to Azure SQL Database"](https://docs.microsoft.com/en-us/sql/samples/adventureworks-install-configure?view=sql-server-2017#install-to-azure-sql-database), please add instructions for other sample versions (which are still used by some courseware).

**Comment by MashaMSFT** [comment]
Hi @rootsmusic,  thanks again for reaching out, and I appreciate the link to the courseware, it helps clarify. 

Let me take a minute to explain - there are three editions of the AdventureWorks database: OLTP, Data warehouse, and LT. The LT is just a pared down version of the OLTP database, with a number of objects removed.

You may be able to get away with running the OLTP courseware examples against the LT database,  but you'll need the DW database for the DW workload. It looks like the courses come with VMs that you can use for your testing: 10985C-MIA-DC and 10985C-MIA-SQL virtual machines

Since the AdventureWorks databases were initially intended for on-premises, it will take some additional steps to get them into the cloud. You can use the [backup and restore](https://docs.microsoft.com/en-us/sql/relational-databases/tutorial-sql-server-backup-and-restore-to-azure-blob-storage-service?view=sql-server-2017) to blog storage method, or maybe migrate it using the [Azure Database Migration service](https://docs.microsoft.com/en-us/azure/dms/).

I have created an internal work item ([1599582](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1599582)) to add some information to the existing documentation for getting these sample databases up into Azure. Additionally, I have submitted a request to the PG to make these sample databases available.

I hope that helps and please let us know if we can be of further assistance? If not, I will proceed with closing out this Git Issue in a few business days.

Thanks!
Masha from the SQL Docs team

**Comment by rootsmusic** [comment]
> I have submitted a request to the PG to make these sample databases available.

Yes Masha, you may close this case.  I opened [issue #572](https://github.com/microsoft/sql-server-samples/issues/572) to suggest making SQL sample databases readily accessible to data connections, without everyone needing to install individual instances.

Besides courseware, recent publications from MS Press (e.g. [p.5](https://www.microsoftpressstore.com/content/images/9781509308040/samplepages/9781509308040_Sample.pdf)) still use the non-LT editions of AdventureWorks.  (This issue was created because it took me a while to realize that Azure doesn't support creating a SQL Database from .bak files.  Eventually, the MSDN forums helped me with how to [install to SQL Server](https://docs.microsoft.com/en-us/sql/samples/adventureworks-install-configure?view=sql-server-2017#install-to-sql-server) on-premises.)

**Comment by MashaMSFT** [comment]
Hi @rootsmusic, I was doing some additional research and realized that when you deploy an Azure Data Warehouse, the sample database available is the AdventureWorks DW edition :) So you can use that for the courseware, and try the LT database for the other part of the course. 

![image](https://user-images.githubusercontent.com/32783170/65090192-16e2b980-d971-11e9-97e3-49e06287763a.png)


Hope that helps!
Masha from the SQL Docs team
