### ISSUE TITLE
SQLXML 4.0 SP1 and MSXML

### ISSUE THREAD

**Issue by sandys21** [MicrosoftDocs/sql-docs#3020]
On this page, it has been mentioned that SQLXML uses MSXML 6.0, whereas the installation document of SqlXml 4.0 Service Pack 1 (SP1) at https://www.microsoft.com/en-us/download/details.aspx?id=30403 mentions that SQLXml has a dependency on MSXML version 4.0 SP2. This version of MSXML is included with the download.

Please let me know the current version of MSXML that SQLXML 4.0 SP1 needs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 518df43a-f11e-84f8-d227-31c888b538b8
* Version Independent ID: 8892df79-4e69-47e2-6901-3e6ed9d93b9a
* Content: [What's New in SQLXML 4.0 SP1 - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/sqlxml/what-s-new-in-sqlxml-4-0-sp1?view=sql-server-2017)
* Content Source: [docs/relational-databases/sqlxml/what-s-new-in-sqlxml-4-0-sp1.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/sqlxml/what-s-new-in-sqlxml-4-0-sp1.md)
* Product: **sql**
* Technology: **xml**
* GitHub Login: @MightyPen
* Microsoft Alias: **genemi**

**Comment by msebolt** [comment]
@sandys21 Thank you for the question.

Assigning this to the author for further clarification.

**Comment by rothja** [comment]
@sandys21 I apologize for the delay on this answer. I have not had a chance to look into this dependency question. However, since the download you obtained came with a specific version of MSXML, I would use that version. If you want to use the 6.0 version, I assume that would work per the article, but you would have to test it. However, I apologize for the confusion between the article and the download, and thank you for reporting it. At this time, I assume you got it working with the version that came with the download, and I will close this git issue. If that is not the case, please let me know! Thank you! #reassign:rothja
