### ISSUE TITLE
Does this need correction?

### ISSUE THREAD

**Issue by dawoodjee** [MicrosoftDocs/sql-docs#3043]
The link to Configure IIS refers to to SSMS:

SQL Server Management Studio: Configure IIS for Web Synchronization

I think there might be a mistake

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd4250e7-f6ac-470a-208f-fcf30da67b91
* Version Independent ID: c5533837-b491-8802-1eaf-cfa1e72a3f5c
* Content: [Configure Web Synchronization - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/replication/configure-web-synchronization?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/replication/configure-web-synchronization.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/replication/configure-web-synchronization.md)
* Product: **sql**
* Technology: **replication**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @dawoodjee, thank  you so much for your feedback! I have created an internal work item [1605936](https://mseng.visualstudio.com/TechnicalContent/SQL/_dashboards/SQL/e6c08d9e-8daa-49bc-92c4-b65995f06307) to review this tutorial for opportunities for improvement. 

Since we're tracking this work internally, I will close out this Git Issue, but please feel free to reach out should you need anything further from us in the meantime. 

And thank you, once more, for caring about our documentation and helping us improve it :) 
Masha from the SQL Docs team
