### ISSUE TITLE
The tutorials are jumbled

### ISSUE THREAD

**Issue by dawoodjee** [MicrosoftDocs/sql-docs#3044]
All the tutorials are very long and cross-reference each other in a way which can be quite confusing. Its quite frustrating. 

For example:

Between configure Web Synchronization (not 10 minutes) and Configure IIS for Web Synchronization (this article). The link Configure IIS for Web Synchronization is placed before Publication Configuration but the second sentence says the Publication agent must be enabled:

 "You perform this step after you enable a publication for Web synchronization."

This is confusing for first time users. Additionally, I think that these tutorials can be simplified further.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13046ce7-e06c-ffaa-59b8-c6dc0ecdebd8
* Version Independent ID: 81ca8e84-2d41-2159-4bfb-5f7f6990a398
* Content: [Configure IIS for Web Synchronization - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/replication/configure-iis-for-web-synchronization?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/replication/configure-iis-for-web-synchronization.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/replication/configure-iis-for-web-synchronization.md)
* Product: **sql**
* Technology: **replication**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @dawoodjee, thank  you so much for your feedback! I have created an internal work item [1605936](https://mseng.visualstudio.com/TechnicalContent/SQL/_dashboards/SQL/e6c08d9e-8daa-49bc-92c4-b65995f06307) to review this tutorial for opportunities for improvement. 

Since we're tracking this work internally, I will close out this Git Issue, but please feel free to reach out should you need anything further from us in the meantime. 

And thank you, once more, for caring about our documentation and helping us improve it :) 
Masha from the SQL Docs team
