### ISSUE TITLE
database drop-down list

### ISSUE THREAD

**Issue by peeryw** [MicrosoftDocs/sql-docs#3083]
You tell us to change to TutorialDB and that we can just append the new code to the end of the code we already have. Issue is that the first line refers to "master" so the appended code will not create a table in the TutorialDB

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eda8bfc9-3c56-6087-891b-aaa6ddcad7f9
* Version Independent ID: 634bf829-a9d8-7c00-96a9-645d99b7ca62
* Content: [Connect to and query a SQL Server instance by using SQL Server Management Studio (SSMS) - SQL Server](https://docs.microsoft.com/en-us/sql/ssms/tutorials/connect-query-sql-server?view=sql-server-ver15#feedback)
* Content Source: [docs/ssms/tutorials/connect-query-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/tutorials/connect-query-sql-server.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @peeryw, thank you for contacting Microsoft! I've modified the text to provide more clarity and it should be live by tomorrow. Please let us know if we can  be of further assistance? Otherwise, I will proceed with closing out this Git Issue in a few business days.

Thanks and hope you have a wonderful rest of your day!
Masha from the SQL Docs team
