### ISSUE TITLE
Hybrid Buffer Pool and 'enlightenment'

### ISSUE THREAD

**Issue by karldodd** [MicrosoftDocs/sql-docs#3112]
A bit confused about the difference between Hybrid Buffer Pool and 'enlightenment'. Are they two different things? 

I read a quite good article (http://nedotter.com/archive/2019/06/sql-2019-pmem-enlightenment-and-the-hybrid-buffer-pool/) which tells HBP and enlightenment are different. It says HBP is just PMEM extension of normal buffer pool and enlightment is putting data file on PMEM. Is this right? If yes, the doc page here should probably be clearer and not confuse the two concepts (especially the sentence 'The mechanism to copy the file from the PMEM device to DRAM is direct memory-mapped I/O (MMIO) and is also referred to as the enlightenment of data files within SQL Server.').

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85310dff-ada2-9b02-f8ac-758ca538be6c
* Version Independent ID: dec86687-bdc5-6c69-b4be-d6179fefd5bf
* Content: [Hybrid Buffer Pool - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/hybrid-buffer-pool?view=sqlallproducts-allversions#feedback)
* Content Source: [docs/database-engine/configure-windows/hybrid-buffer-pool.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/hybrid-buffer-pool.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @briancarrig
* Microsoft Alias: **brcarrig**

**Comment by WilliamAntonRohm** [comment]
@karldodd -- thank you for your feedback.

@briancarrig -- please look into updating the documentation.

cc: @MightyPen

**Comment by rothja** [comment]
@karldodd Thanks, again for this questions. I'm looking into this further, and I appreciate your patience.

**Comment by karldodd** [comment]
@rothja Thanks. SQL2019 seems very close to GA, so maybe we need to get this clear before the release :)

Another question related to the issue is, whether we can put data files (not buffer pool cached pages) directly on PMEM device. Since it is not easy to get a machine with PMEM today, it is hard for users to test and find out. More T-SQL samples here in the doc would help a lot.

**Comment by briancarrig** [comment]
I agree this feature needs additional clarification and I am working to address shortly. Both Data and Log File Enlightenment and Hybrid Buffer Pool make use of a DAX (Direct Access) enabled file system (like NTFS or XFS) and require database files to be on byte addressable storage such as PMEM. The clean cached index leaf pages in the Hybrid Buffer Pool will be on the PMEM module with the data files without consuming any additional capacity (memory mapping). I understand the difficulty in obtaining such modules for testing purposes and we are exploring some options to present in this space. I worked with Ned on his blog post so will seek to address any discrepancies there too. Can you advise what kind of additional T-SQL examples would be helpful? I will be happy to work on getting them added.

**Comment by karldodd** [comment]
>  Can you advise what kind of additional T-SQL examples would be helpful?

@briancarrig Thanks for your help. Hybrid Buffer Pool is something transparent, so I guess examples are not necessary. But for 'enlightenment', if my imagination is correct, maybe we can add some T-SQL to show how to actually put a data file or file group on PMEM device (e.g. in a `create database` statement? ).

Looking forward to the doc update and examples.

**Comment by briancarrig** [comment]
> @briancarrig Thanks a lot for your help.
> 
> > Both Data and Log File Enlightenment and Hybrid Buffer Pool make use of a DAX (Direct Access) enabled file system (like NTFS or XFS) and require database files to be on byte addressable storage such as PMEM.
> 
> Sorry but still a bit confused.. Let me put my question this way: (1) Can a database file live on a regular normal hard drive and some of its cache pages go to PMEM part in the Hybrid Buffer Pool? (2) Can a database file itself (not cache page) live on PMEM directly?
> 
> > Can you advise what kind of additional T-SQL examples would be helpful?
> 
> Hybrid Buffer Pool is something transparent, so I guess examples are not necessary. But for 'enlightenment', if my understanding is correct, maybe we can add some T-SQL to show how to actually put a data file or file group on PMEM device (e.g. in a `create database` statement? ).
> 
> Looking forward to the doc update and examples.

I fear we failed to enlighten with the concept of enlightenment :-) I will attempt to clarify more in my next PR (landing tomorrow hopefully). The normal file I/O used for copying pages from disk to the DRAM buffer pool and writing them back out again gets replaced with interactions with a memory mapped file. The buffer pool continues to behave as it normally has, only when you enable Hybrid Buffer Pool do we expand the buffer pool scope to include PMEM.

1) No this is not possible currently although I am intrigued by the suggestion and would love to hear more about scenarios. Perhaps you could add a feedback item to https://aka.ms/sqlfeedback to explore more? It would be good to find out why PMEM might be more useful in this scenario than DRAM.
2) Yes, you store data files on the PMEM storage device file system. The files can be accessed through regular file APIs for the OS. Once you enable Hybrid Buffer Pool, on start up SQL Server requests a memory map of the file and can interact with this mapped file using memory functions as though it was a region of DRAM. This way it avoids making regular file API calls which traverse the kernel stack. Instead of block I/O calls to read from the device and copying pages to DRAM to associate buffer pool objects with a data page, the same buffer pool object can be associated with a region in the memory mapped file.

I can certainly add T-SQL to demonstrate but essentially the T-SQL will be no different than creating database files on normal block storage.

**Comment by rothja** [comment]
@briancarrig Thanks for the detailed explanations. Did you get a chance to update the explanation in the article? Thanks!

@karldodd Thank you for your questions. I believe that Brian has answered them and he either has (or plans to) update the content to clarify. We appreciate you asking so we can make the docs better. I am going to close now, but please feel free to respond on this thread with any more clarification you need on this question. Thank you!
