### ISSUE TITLE
Pratice Examples

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/sql-docs#3120]
Hi team, I'm moving this issue from https://github.com/MicrosoftDocs/sql-docs.pt-br/issues/26.

Please check it. Thanks!!

Notes from @leoTotvs

> This page should contain practices examples, like the most of docs.microsoft pages.
> 
> Below is a practical example, so that character matching starts with a letter between a and z, using LIKE or PATINDEX :
> DECLARE @string AS VARCHAR(100) = 'T1904';
> 
> SELECT @string AS STRING, CASE WHEN @string LIKE '[A-Z]%' THEN 'MATCH' ELSE 'NOT MATCH' END AS TESTING_MATCH_LIKE
> 
> SELECT @string AS STRING, CASE WHEN patindex('[A-Z]%',@string) > 0 THEN 'MATCH' ELSE 'NOT MATCH' END AS TESTING_MATCH_PATINDEX

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9027fbf7-358e-f42f-91e3-5dd316bd68a1
* Version Independent ID: 8751863c-1c8f-fe89-11be-e66ebc8416fa
* Content: [Search Text with Regular Expressions - SQL Server](https://docs.microsoft.com/en-us/sql/ssms/scripting/search-text-with-regular-expressions?view=sql-server-2017#feedback)
* Content Source: [docs/ssms/scripting/search-text-with-regular-expressions.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/scripting/search-text-with-regular-expressions.md)
* Product: **sql**
* Technology: **scripting**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by leoTotvs** [comment]
Thanks to received my suggestions. 
I hope this help the microsoft community and their users.

**Comment by msebolt** [comment]
@leoTotvs You're welcome, assigning this to the author now.

**Comment by markingmyname** [comment]
@lichasu,

Are you suggesting we add the "examples" you are listing in the article?

If so, we do appreciate it, I just want to make sure I understand your request.

**Comment by cawrites** [comment]
@leoTotvs thank you for contacting Microsoft. If you can respond to the question from the author we would appreciate it.

**Comment by leoTotvs** [comment]
Hi! In my initial suggestion, I suggested inserting some examples on the page [Search text with regular expressions](https://docs.microsoft.com/pt-br/sql/ssms/scripting/search-text-with-regular-expressions?view=sql-server-2017), because there is only documentation, with no example of how to use it.

To collaborate I wrote some practical examples that I did to understand how to use and exemplify the use. Examples, which are in [issue 26](https://github.com/MicrosoftDocs/sql-docs.pt-br/issues/26):

Character matching starts with a letter between a and z, using LIKE or PATINDEX :

DECLARE @string AS VARCHAR(100) = 'T1904';

SELECT @string AS STRING, CASE WHEN @string LIKE '[A-Z]%' THEN 'MATCH' ELSE 'NOT MATCH' END AS TESTING_MATCH_LIKE

SELECT @string AS STRING, CASE WHEN patindex('[A-Z]%',@string) > 0 THEN 'MATCH' ELSE 'NOT MATCH' END AS TESTING_MATCH_PATINDEX

**Comment by rothja** [comment]
@leoTotvs Thanks for the examples. I am going to test them out and look to add them to the article. #reassign:rothja

**Comment by rothja** [comment]
@leoTotvs Leo, I ran your examples and they definitely work great. But I don't think they would belong on the [Search Text with Regular Expressions](https://docs.microsoft.com/en-us/sql/ssms/scripting/search-text-with-regular-expressions). The syntax here is specifically with the find and replace dialog of SSMS. However, your suggestion to provide examples is a good one, and we are looking into it. I'm also looking to see if the information on this page about SSMS is still accurate with the most recent versions of SSMS. So, thank you very much for the suggestions. I am going to close the issue, but there may be examples added in the future as we continue to look at improving the content. Thank you!!
