### ISSUE TITLE
ALTER TABLE (Transact-SQL): "The requested page is not available for SQL Server 2014. You have been redirected to the newest product version this page is available for."

### ISSUE THREAD

**Issue by Bart76** [MicrosoftDocs/sql-docs#3239]
"The requested page is not available for SQL Server 2014. You have been redirected to the newest product version this page is available for."

WTF!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abcca5d2-d433-96cc-930e-4de020c5785d
* Version Independent ID: fde147ff-b157-502c-276a-d3a2bf9bb3c7
* Content: [ALTER TABLE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-table-transact-sql?view=sql-server-2017&viewFallbackFrom=sql-server-2014#feedback)
* Content Source: [docs/t-sql/statements/alter-table-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/alter-table-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by WilliamAntonRohm** [comment]
@Bart76 -- thank you for your feedback.  That article applies to "SQL Server 2014 (12.x) through SQL Server 2017" and is also valid for SQL Server 2109 Preview.

Are you looking for documentation specific to SQL Server 2014?

**Comment by Bart76** [comment]
Yes, I needed some specific documentation for SQL Server 2014. I was looking at the ALTER TABLE's syntax for disk-based tables and on this page, I saw that it should support `ALTER TABLE [tablename] DROP CONSTRAINT IF EXISTS [constraintname];`. It works fine on SQL Server 2017 (and perhaps also on SQL Server 2016), but I am sure it doesn't work on SQL Server 2014. I tested it and it failed with error message "Incorrect syntax near the keyword 'IF'." So it seems that this documentation does not apply to SQL Server 2014.

**Comment by WilliamAntonRohm** [comment]
@Bart76 -- thank you for clarifying.

@CarlRabeler -- please look into this issue 3239.

**Comment by rothja** [comment]
@Bart76 I apologize for the confusion and the delay. @CarlRabeler is out of the office, so I will reassign this issue to myself. #reassign:rothja . It does seem from your tests that this is not available in 2014, and we should indicate this in the article. Also, you make a good point that if this is the only article for ALTER TABLE that it should not say that it is not available for 2014 but should clarify when certain features are introduced. We do not always do that well. Let me do a litttle research and try to get back to you. However, I would say that your tests (if they worked in later versions) seem to prove that it is a feature that was introduced later. Thanks for your patience.

**Comment by rothja** [comment]
@Bart76 I apologize for the long delay. The SQL Server Transact-SQL reference is not currently available online, which is why this error occurs when you switch back to 2014. However, we know this is not a great experience. We are considering trying to make this available online again, but it will take some time. However, there is a work around to find the older reference content. You can install the offline books for 2014, which includes the older reference content. We updated this article to show how: [SQL Server offline help and Help Viewer](https://docs.microsoft.com/en-us/sql/sql-server/sql-server-help-installation). I apologize for this experience, and we will be trying to improve it in the future. Thank you!
