### ISSUE TITLE
Error in Syntax ? 

### ISSUE THREAD

**Issue by luomoyuyi** [MicrosoftDocs/sql-docs#3240]
is "OPTION &lt;query_hint&gt; " optional ? 
And for the &lt;query_hint&gt; clause,  is 
"&lt;query_hint&gt; ::=
    {
        MAXDOP 
    }
"
correct ? 
How about the statement : 
"CREATE TABLE [wwi].[fact_Purchase]
WITH
( 
    DISTRIBUTION = HASH([Purchase Key]),
    CLUSTERED COLUMNSTORE INDEX
)
AS
SELECT * FROM [ext].[fact_Purchase]
OPTION (LABEL = 'CTAS : Load [wwi].[fact_Purchase]')
;
"
Is it of correct syntax ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d789618-4d39-1977-a4f3-520308f4f675
* Version Independent ID: a4e034e8-fc72-dd9b-c575-1ef81528c5cd
* Content: [CREATE TABLE AS SELECT (Azure SQL Data Warehouse) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-table-as-select-azure-sql-data-warehouse?view=azure-sqldw-latest#feedback)
* Content Source: [docs/t-sql/statements/create-table-as-select-azure-sql-data-warehouse.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-table-as-select-azure-sql-data-warehouse.md)
* Service: **sql-data-warehouse**
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by WilliamAntonRohm** [comment]
@luomoyuyi -- Yanzhe, thank you for your feedback.  It appears you have an issue with your algorithm or implementation, rather than with the documentation itself.  You may find an answer here:

- [Transact-SQL - MSDN forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=transactsql)
- [Reddit - general discussion about SQL Server](https://www.reddit.com/r/SQLServer/)

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
