### ISSUE TITLE
SQL Express at Subscriber

### ISSUE THREAD

**Issue by git-sw** [MicrosoftDocs/sql-docs#3318]
Near the start of the article under "Prerequisites" it states "At the subscriber server (destination), install any edition of SQL Server, except for SQL Server Compact. The publication that's created in this tutorial does not support SQL Server Compact"

Near the end of the article under "Synchronize the subscription to the merge publication" it states "1. Connect to the subscriber in SQL Server Management Studio.
2. Make sure that the SQL Server Agent is running..."

How can I use SQL Express as the Subscriber given that SQL Express doesn't include SQL Agent?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16df2747-32ea-b464-e92c-535f6d2a788c
* Version Independent ID: f50b285e-9a62-8823-c207-3b31ce6d4e7e
* Content: [Tutorial: Configure replication between a server and mobile clients (merge) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/replication/tutorial-replicating-data-with-mobile-clients?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/replication/tutorial-replicating-data-with-mobile-clients.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/replication/tutorial-replicating-data-with-mobile-clients.md)
* Product: **sql**
* Technology: **replication**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@git-sw -- thank you for your feedback.

@MashaMSFT -- please look into this question.

**Comment by MashaMSFT** [comment]
Hi @git-sw , thank you so much for your feedback! Okay so, if the distributor is on the publisher, and you've configured a push subscription, then you don't have to run any agent at the subscriber as the agents run on the publisher and distributor (which may or may not be one and the same). 

However, having said that, you've pointed out a gap in our documentation because we explicitly create a pull subscription, and the agent is running at the subscriber - so you're right, the subscriber cannot be SQL Server Express, because the SQL Agent does not come with the Express version. 

I've submitted a documentation change to update the requirements to clarify this and it should be live tomorrow.

Thank you for making our documentation better! Please let us know if there is anything else we may assist you with? Otherwise we will proceed with closing out this Git Issue in a few business days :)

Thanks!
Masha from the SQL Docs team

**Comment by git-sw** [comment]
Hi @MashaMSFT, thank you very much for your prompt response! A tutorial explaining a push subscription would be great! I feel this is probably more fitting for "mobile clients" which may not be running a "full" version of SQL.

**Comment by MashaMSFT** [comment]
Hi @git-sw, thanks for sharing that feedback as well -  you're right, I can see how having a push subscription tutorial would be beneficial. I've updated the existing article to modify the requirements stating that SQL Express is not supported for the subscriber, so at least the article is no longer misleading. 

However, I have also created an internal work item ([1616831](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1616831)) to consider either rewriting the existing tutorial, or adding another one that addresses the push scenario. 

Thanks again for helping us improve our documentation! :) 

I will close out this Git Issue for now, but please feel free to reach out should you need anything further.

Thanks!
Masha from the SQL Docs team
