### ISSUE TITLE
SQL query does not give information about ghost records

### ISSUE THREAD

**Issue by micheleTahay** [MicrosoftDocs/sql-docs#3383]
As tested on a 2016 version, the sql statement above does not give information in the ghost_record_count column. You need to set your 'mode' for dm_db_index_physical_stats on at least 'SAMPLED' to gather that data. When 'mode' is null, then it defaults to 'LIMITED'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a868d47-f2ae-14f0-b303-ae6794a16ad6
* Version Independent ID: 5d79057a-959f-73ef-6829-9111a9a98b39
* Content: [Ghost cleanup process guide - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/ghost-record-cleanup-process-guide?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/ghost-record-cleanup-process-guide.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/ghost-record-cleanup-process-guide.md)
* Product: **sql**
* Technology: **supportability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @micheleTajay, thanks for bringing this to our attention! Let me investigate this further :) Please note, this process may take a a while, depending on the complexity.

Thanks!
Masha from the SQL Docs team

**Comment by MashaMSFT** [comment]
Hi @micheleTahay, you were right, the last column should be sampled :) I have processed this change and it should be live later today. Please let us know if there is anything else we can assist you with? Otherwise, we will proceed with closing out this Git Issue in a few business days. 

Thanks again for making our docs better, and hope you have a wonderful rest of your day!
Masha from the SQL Docs team
