### ISSUE TITLE
Fillfactor is not supported on Azure SQL?

### ISSUE THREAD

**Issue by kazshi** [MicrosoftDocs/sql-docs#3401]
Looks like we can set fillfactor to Azure SQL DB index table using T-SQL, but the fillfactor option is omitted in generated script using Generate Scripts command and Azure SQL is not included in "Applies to" in this page.  Does it mean Fillfactor is not supported on Azure SQL?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0652001f-415e-b992-094e-452993f482f2
* Version Independent ID: ce78ead1-4075-af11-a05d-17d9b14faaad
* Content: [ | Microsoft Docs - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-table-index-option-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/statements/alter-table-index-option-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/alter-table-index-option-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by msebolt** [comment]
@kazshi  Thank you for the question, assigning this to the author for review.

**Comment by rothja** [comment]
@kazshi Thanks for the question. Unfortunately, @CarlRabeler is out of the office at this time. @stevestein could you please help look into this question? Thank you! #reassign:stevestein

**Comment by stevestein** [comment]
@kazshi - the entire article applies to Azure SQL Database. The individual parameters specify the SQL Server versions because a few parameters weren't supported until SQL Server 2014.
Regarding:  _the fillfactor option is omitted in generated script using Generate Scripts command_
I'm pretty sure this is because it uses the default value, so no specific value is set.

Let us know if you run into any specific discrepancies here.

Thanks!

#please-close

**Comment by kazshi** [comment]
@stevestein Thanks for your comment.
The fillfactor option is omitted even if we set the fillfactor option (sorry I didn't mention it previously) - I learned it's a bug in SSMS. I tried to do that using Visual Studio and it works as expected.
