### ISSUE TITLE
Wrong SQL version displayed for FULL-TEXT files

### ISSUE THREAD

**Issue by vladsMDCS** [MicrosoftDocs/sql-docs#3415]
For full-text files - the description states "Full-text catalogs earlier than SQL Server 2017...", but AFAIK full-text files (type 4)
have been deprecated since SQL 2012. Therefore the information is misleading - saying that I could use full-text file types in e.g. SQL 2016.
IMO the problem lies in "ssCurrent" variable used in document's source code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae823efc-d65f-9f4a-9a62-faad1d047a76
* Version Independent ID: 16cbcb94-577b-6998-0c65-c4107c509826
* Content: [sys.database_files (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-database-files-transact-sql?view=sql-server-ver15)
* Content Source: [docs/relational-databases/system-catalog-views/sys-database-files-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-catalog-views/sys-database-files-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@vladsMDCS -- thank you for your feedback.

@stevestein -- please look into this issue 3415.

**Comment by rothja** [comment]
@vladsMDCS Thanks for this feedback, and you are absolutely right that ssCurrent is causing this to read misleadingly. I'm going to work on getting that corrected and get back to you. Sorry for the delayed response!  #reassign:rothja

**Comment by rothja** [comment]
@vladsMDCS Thanks, again. We have decided to remove the parenthetical comment for now, because we are unsure what the right answer should be. We looked back at older content and the 2008 content had the same problem. We are asking internally, but until we know, it is just a confusing comment. We are also changing the ssCurrent value to be just "SQL Server" instead of "SQL Server 2019" because this is causing a lot of confusion in the docs. Thanks for pointing it out. I am going to close the issue for now, but please let me know if you have any questions. #please-close
