### ISSUE TITLE
WHERE IS DOWNLOAD LINK!!!????

### ISSUE THREAD

**Issue by NishSG** [MicrosoftDocs/sql-docs#3469]
Where is the download link. ? I have a job to do. don't make my life more complex

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Download SQL Server Management Studio (SSMS) - SQL Server](https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver15#feedback)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dnethi
* Microsoft Alias: **dinethi**

**Comment by BrynJones216** [comment]
The download links are the Available Languages section.  Click the name of the language you want SSMS localised in.

**Comment by NishSG** [comment]
Thank you . That gives me 32 bit version. Where is the options to select 64 bit.?

**Comment by OldVSDeveloper** [comment]
Click on 'Download SSMS' heading above

**Comment by msebolt** [comment]
@NishSG  Thank you for the question.

This was recently updated with large blue syntax near the top of the article.  64-bit is the default.

![Capture](https://user-images.githubusercontent.com/6675884/68233766-b5c08500-ffb4-11e9-8383-726667a22f70.PNG)

Please comment below if there are additional questions.

**Comment by Jehoel** [comment]
@msebolt Just because the text is blue doesn't mean I think it's a hyperlink. I thought it was just a big heading that had an incorrect style applied to it. I imagine most users don't expect blue heading-sized text to be links. Please add an affordance ( https://uxplanet.org/ux-design-glossary-how-to-use-affordances-in-user-interfaces-393c8e9686e4 ) that makes it an obvious hyperlink by adding an underline or style it as a button.

**Comment by JamesHorsley** [comment]
Or just wording as Click here to Download SSMS :-)  ... sad to say I had to look at comments to get the download link too!

**Comment by jimicze** [comment]
@msebolt Its not 64bit by default, default is 32bit. Please add 64bit download option.

**Comment by firefly237** [comment]
Yeah -- pretty weird. When I couldn't find the download link in the obvious places, I just looked at doing it in another language I knew and saw that English was an option there - how very counter-intuitive. The "Download SSMS" definitely doesn't look like a link and I didn't go anywhere near it.

**Comment by prashantprp** [comment]
Kindly improve your instructions on how to Download, just because it is hyperlink no one could assume that clicking there would download the software. Kindly improve the texting like "click here to download SSMS to your local computer".

**Comment by pjcorreia** [comment]
It's insane that in the year 2020 the people responsible by this page have zero knowledge of the basic principles of usability. This is the type of arrogance that the IT guys are associated with that make the rest of the world waste a huge amount of time (multiply that by the number of downloads of the SSMS) just because someone thought the way he thinks is the "correct" one. Fix the link and don't use one in the title for a section where people expect to have instructions on how to download. Absolutely surreal.
