### ISSUE TITLE
How to create tags with T-SQL?

### ISSUE THREAD

**Issue by AlainBorletHote** [MicrosoftDocs/sql-docs#3482]
The scenario is the following: as part of the DB creation script -or- DB upgrade scripts, tags are included.
How to do it in T-SQL?
Kind Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34863695-cd07-1260-4fea-66738c5fa80a
* Version Independent ID: 4c01015d-9c1d-db8e-84f5-379ffc5d5133
* Content: [SQL Data Discovery & Classification - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/sql-data-discovery-and-classification?view=sql-server-ver15)
* Content Source: [docs/relational-databases/security/sql-data-discovery-and-classification.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/sql-data-discovery-and-classification.md)
* Service: **sql-database**
* GitHub Login: @barmichal
* Microsoft Alias: **mibar**

**Comment by WilliamAntonRohm** [comment]
@AlainBorletHote -- thank you for your question.  It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation.  You may find answers here:
- [Transact-SQL - MSDN forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=transactsql)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server) 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
