### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by CSharkie** [MicrosoftDocs/sql-docs#3526]
I have updated to the last version of mssql 19 since I was having problems with connection to the server due to the update of openssl to 1.1 and I still cannot connect to my server. And even if i install openssl 1.0.2 it will still give me the same error:

Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : TCP Provider: Error code 0x2746.
Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : Client unable to establish connection.

If anyone has any ideas I have tried a few solutions that I found around and none of them works.
I have ubuntu server 16.04 installed and mssql 15.0.2000.5-5.

**Comment by msebolt** [comment]
@CSharkie  Thank you for the feedback, you can see if [this post](https://stackoverflow.com/questions/57265913/error-tcp-provider-error-code-0x2746-during-the-sql-setup-in-linux-through-te) resolves the problem.

For additional support options, refer to:

- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)
- [Azure DevOps Support Bot](https://azuredevopsvirtualagent.azurewebsites.net/)

If this is still unresolved and since your issue is with the product itself, you'll need to submit a bug to the product team [here](https://developercommunity.visualstudio.com/content/problem/post.html?space=21).

**Comment by msebolt** [comment]
Closing the issue now, please comment below if there are any issues.
