### ISSUE TITLE
Mssql tools not found Fedora 30

### ISSUE THREAD

**Issue by marvinhosea** [MicrosoftDocs/sql-docs#3528]
I am getting this error when trying to install sqlcmd 

No match for argument: mssql-tools
Error: Unable to find a match

**Comment by msebolt** [comment]
@marvinhosea Thank you for the feedback.

Since Fedora is not officially supported, see [supported platforms](https://docs.microsoft.com/sql/linux/sql-server-linux-setup?view=sql-server-ver15#supportedplatforms), you will need to submit a feature request to the product team [here](https://feedback.azure.com/forums/908035-sql-server).

In the meantime, this [post](https://kifarunix.com/install-microsoft-sql-server-2017-on-fedora-29-centos-7/) describes how to run on Fedora 29.

**Comment by marvinhosea** [comment]
I have followed this [post](https://kifarunix.com/install-microsoft-sql-server-2017-on-fedora-29-centos-7) and the official Microsoft article and i am still getting the same error. 
`No match for argument: mssql-tools
Package unixODBC-devel-2.3.7-4.fc30.x86_64 is already installed.
Error: Unable to find a match`

The issue is caused when trying to install mssql-tools.

**Comment by msebolt** [comment]
@marvinhosea Sorry for the delay on this.

I'm able to install using [these instructions](https://docs.microsoft.com/sql/linux/sql-server-linux-setup-tools#install-tools-on-rhel-7) on RHEL 7.7, so it's likely Fedora specific.

Unfortunately, since we don't support Fedora there's nothing further I can do except recommend you add a requrest for Fedora in the [SQL Server feedback](https://feedback.azure.com/forums/908035-sql-server) forum.

**Comment by marvinhosea** [comment]
This what fixed my problem https://stackoverflow.com/questions/57265913/error-tcp-provider-error-code-0x2746-during-the-sql-setup-in-linux-through-te
