### ISSUE TITLE
Add new content and correct article errors

### ISSUE THREAD

**Issue by v-maudel** [MicrosoftDocs/sql-docs#3559]
Text below is machine translated

@yupengcheng0719 commented on [Tue Nov 12 2019](https://github.com/MicrosoftDocs/sql-docs.zh-cn/issues/132)

Add <nnn> to identify version 190 and SQL Server 2019 (15.x), correct the article below for each instance name of SQL Server 2019

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: b3ca4320-49c8-31a4-84c6-0185ba176216
* Version Independent ID: 04a1843f-813d-fe8e-611b-af6ada02ef01
* Content: [SQL Server 的默认实例和命名实例的文件位置 - SQL Server](https://docs.microsoft.com/zh-cn/sql/sql-server/install/file-locations-for-default-and-named-instances-of-sql-server?redirectedfrom=MSDN&view=sql-server-ver15#feedback)
* Content Source: [docs/sql-server/install/file-locations-for-default-and-named-instances-of-sql-server.md](https://github.com/MicrosoftDocs/sql-docs.zh-cn/blob/live/docs/sql-server/install/file-locations-for-default-and-named-instances-of-sql-server.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

---

@srvbpigh commented on [Tue Nov 12 2019](https://github.com/MicrosoftDocs/sql-docs.zh-cn/issues/132#issuecomment-553016442)

Hello, @yupengcheng0719
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by WilliamAntonRohm** [comment]
@v-maudel -- Mauricio, thank you for relaying this information.

@MashaMSFT -- Masha, please look into this issue 3559.

**Comment by MashaMSFT** [comment]
Hi @yupengcheng0719 , thank you for contacting Microsoft! Thanks for bringing this to our attention. We have proceed a change to add SQL 2019 to the article, and make the paths version-agnostic. 

Hope that helps and please let us know if there is anything else we can do for you? Otherwise we will proceed with closing out the Git Issue in a few business days.

Thanks again for making our docs  better and hope you have a great rest of your day!
Masha from the SQL Docs team
