### ISSUE TITLE
Azure: STONITH configuration guide missing for SQL Server 2017 on Ubuntu

### ISSUE THREAD

**Issue by jamesattard** [MicrosoftDocs/sql-docs#3594]
Hello guys,

I just noticed that in the [documentation ](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-availability-group-cluster-ubuntu?view=sql-server-ver15), the section describing STONITH configuration is missing for Ubuntu. 

This is not the case for Red Hat where it is fully documented.

**Comment by WilliamAntonRohm** [comment]
@jamesattard -- James, thank you for your feedback.

@MikeRayMSFT -- Mike, please look into this issue 3594.  The article in question is:  https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-availability-group-cluster-ubuntu?view=sql-server-ver15

**Comment by MikeRayMSFT** [comment]
@vin-yu - can you please look at this?

**Comment by MikeRayMSFT** [comment]
@jamesattard  - what specific RHEL documentation are you referring to? 

Is it the [high-availability-guide-rhel-pacemaker#create-stonith-device](https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/high-availability-guide-rhel-pacemaker#create-stonith-device)?

**Comment by jamesattard** [comment]
In the Ubuntu documentation the STONITH configuration is set to disabled and not documented to explain how to enable and configure it - https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-availability-group-cluster-ubuntu?view=sql-server-ver15#configure-fencing-stonith.

**Comment by tejasaks** [comment]
As far as I recall, we haven’t documented steps for fencing configuration in any cases. The reason being, how to enable fencing could potentially be different for different distributions and in different configurations (including on-premise, private cloud/virtualization environments and other public cloud configurations). Since fencing itself is more of an operating system concept that is dependent on its environment, we typically suggest relying on the OS distributor documentation for enabling that.

~Tejas Shah | Principal Program Manager | Data Platform – SQL Server

**Comment by MikeRayMSFT** [comment]
Staging update in https://github.com/MicrosoftDocs/sql-docs-pr/pull/13134
