### ISSUE TITLE
The counter "Extension page evictions/sec" does not appear to be correct

### ISSUE THREAD

**Issue by FzzyBnny** [MicrosoftDocs/sql-docs#3598]
At least in 2017 Standard Edition, the description of this event and the cntr_value returned for it do not appear to match. The description is that of a calculated rate of change per second. The value returned appears to be an ever increasing counter, presumably the number of pages evicted from the Buffer Pool Extension file since the instance last started.

Assuming that my observation is correct in at least 2017 Standard, then it is necessary to calculate the uptime in seconds and divide this counter by it. Something to the effect of the query below. Be advised that the column sqlserver_start_time was added in 2008 so this should work for anything calculating this counter for BPE since BPE is a feature added after 2008.

SELECT
	CAST(dopc.cntr_value * 1.0 / (SELECT DATEDIFF(SECOND, dosi.sqlserver_start_time, SYSDATETIME()) FROM sys.dm_os_sys_info AS dosi) AS DECIMAL(18,2))
FROM
	sys.dm_os_performance_counters AS dopc
WHERE
	dopc.object_name = 'SQLServer:Buffer Manager'
	AND dopc.counter_name = 'Extension page evictions/sec'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20bbd3bb-9820-ed3e-20e5-46708940a9dc
* Version Independent ID: 8f62a995-ec15-e038-63d6-fe464bbb6fa5
* Content: [SQL Server, Buffer Manager Object - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/performance-monitor/sql-server-buffer-manager-object?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/performance-monitor/sql-server-buffer-manager-object.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/performance-monitor/sql-server-buffer-manager-object.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by FzzyBnny** [comment]
The above behavior appears to also apply to two other BPE related counters, "Extension page reads/sec" and "Extension page writes/sec"

**Comment by WilliamAntonRohm** [comment]
@FzzyBnny -- thank you for your feedback.

@julieMSFT -- please look into this issue 3598.

**Comment by julieMSFT** [comment]
@FzzyBnny - Thank you for your feedback. I am researching this issue with the product group.

**Comment by julieMSFT** [comment]
@FzzyBnny It appears that the counter in question " Extension page evictions/sec" does indeed increment the counter rather than calculate the rate per second. This is not a documentation bug but rather that the counter was not implemented correctly. Please submit a feedback item through https://aka.ms/sqlfeedback to have this addressed. If this is actually causing a business issue, you also have the option of opening a case with CSS and having CSS file a hotfix request if you can provide a business impact statement.

I will proceed with closing this documentation issue but you can still reply using the @ notation and we will reply.

**Comment by julieMSFT** [comment]
#please-close
