### ISSUE TITLE
An additional limitation discovered

### ISSUE THREAD

**Issue by gani746** [MicrosoftDocs/sql-docs#3618]
One of the limitations for Plan Guide that I observed:
If the the Stored procedure in question has if conditions where we have SQL statements to be executed for the condition that is met as true among the several if conditions in the Stored Procedure, it turned out that attempting to create a plan guide for a stored procedure with sub-queries completes successfully. However, these plans don’t get picked up during the execution of the stored procedure.  Further, even the new plan that gets compiled during the run time doesn’t get cached. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eee0b5d2-7bdc-d081-abb1-0ced18f51c1c
* Version Independent ID: a875cca1-c080-aab9-b824-063da6b742b7
* Content: [Create a New Plan Guide - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/performance/create-a-new-plan-guide?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/performance/create-a-new-plan-guide.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/performance/create-a-new-plan-guide.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by WilliamAntonRohm** [comment]
@gani746 -- thank you for your detailed feedback.

@julieMSFT -- please look into this issue 3618.

**Comment by julieMSFT** [comment]
@gani746 Hello and thank you for your question. I have checked with the product team for Plan Guides. They are telling me that the example you describe should work. To get further help on this please submit a support ticket at https://support.microsoft.com/en-us/supportforbusiness/productselection, so that your issue can be reproduced. I will proceed with closing this issue. The @notification mechanism continues to work even after an item is closed, in case further communication is needed. We hope to hear from you again.

**Comment by julieMSFT** [comment]
#please-close
