### ISSUE TITLE
The name Single User Mode is misleading, you should call it single user connection mode.

### ISSUE THREAD

**Issue by rafiksamman1982** [MicrosoftDocs/sql-docs#3636]
The name Single User Mode is misleading, you should call it single user connection mode.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b67ab534-229d-f12a-6216-9550d790ea42
* Version Independent ID: 529e1ec2-00c5-9c13-1a75-dfc183765aff
* Content: [Set a Database to Single-user Mode - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/databases/set-a-database-to-single-user-mode?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/databases/set-a-database-to-single-user-mode.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/databases/set-a-database-to-single-user-mode.md)
* Product: **sql**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by msebolt** [comment]
@rafiksamman1982 Thank you for the suggestion.

Since the syntax for this mode uses the term `SINGLE_USER` adding the word "connection" might cause confusion for those looking on information to `SINGLE_USER` vs. 'MULTI_USER` settings, etc.

Please consider moving this issue to the [SQL Server forums](https://feedback.azure.com/forums/908035-sql-server) for product team feedback and further review.
