### ISSUE TITLE
Description of IsPrecise is confusing.

### ISSUE THREAD

**Issue by samrueby** [MicrosoftDocs/sql-docs#3640]
"IsPrecise property of the COLUMNPROPERTY function. COLUMNPROPERTY returns 1 if TRUE, 0 if FALSE, and NULL for input that is not valid. This means the column is not deterministic or not precise."

This is confusing. If IsDeterministic is available, why wouldn't you use that to determine if it is deterministic? This description of IsPrecise doesn't explain how it's different than IsDeterministic.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a452207-5ac2-1a41-c5b1-3baf085a79b4
* Version Independent ID: a590e66c-ed9f-4d80-1511-1864128d2e8e
* Content: [Create Indexed Views - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/views/create-indexed-views?view=sql-server-ver15)
* Content Source: [docs/relational-databases/views/create-indexed-views.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/views/create-indexed-views.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by msebolt** [comment]
@samrueby Thank you for the feedback, apologies for the confusion.

You should use `IsDeterministic` alone if the precision property is not required.

Note the `IsPrecise` property is only coupled with `IsDeterministic` when three states are required:

1. Deterministic and precise
1. Deterministic and non-precise
1. Not deterministic

However, allowing the use of NULL to classify this third state now provides an easy way to only use `IsPrecise` instead of both `IsDeterministic` and `IsPrecise`.

Please find the definition of precise stated later in the section as:

`Deterministic expressions that do not contain float expressions are called precise.`
