### ISSUE TITLE
Put MSI at top of jump for Windows to avoid a lengthy and problematic pip install

### ISSUE THREAD

**Issue by BuckWoody** [MicrosoftDocs/sql-docs#3684]
[Enter feedback here]

Recommend that "Install azdata" have a direct link for Windows, otherwise readers assume pip, which is less reliable for the Windows audience than the MSI. Could be a pointer, or note at the top of the jump page.

Also recommend the jump to Kubernetes page for kubectl command be a open tab link rather than a straight jump, unless that's just how it has to work.

- Buck Woody

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 225c76de-9bda-8814-23ae-3b615f2b071d
* Version Independent ID: c49cc461-22ad-f1f4-3c4e-ba4f6f51504d
* Content: [Install big data tools - SQL Server big data clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/deploy-big-data-tools?view=sql-server-ver15)
* Content Source: [docs/big-data-cluster/deploy-big-data-tools.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/deploy-big-data-tools.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@BuckWoody Thank you for the feedback.

Good idea since the first azdata topic listed is the installer:

![Capture](https://user-images.githubusercontent.com/6675884/69602893-dedd9f80-0fcd-11ea-9bb9-d9ed277c6cc7.PNG)

However, the links are rendered automatically from the article's Markdown syntax, so you'll need to use right-click for separate tabs.
