### ISSUE TITLE
Outdated content

### ISSUE THREAD

**Issue by LearnsHappily** [MicrosoftDocs/sql-docs#3717]
I am using SSMS 2017. The content here doesn't reflect nor explains the current interface. I made this comment on 30 NOV 2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b39a6f87-ff17-e358-4a7c-ea7c2a037cde
* Version Independent ID: a8691d00-99a1-ec0d-346b-fee8f78202dd
* Content: [Quickstart: Backup & restore to Azure Blob storage service - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tutorial-sql-server-backup-and-restore-to-azure-blob-storage-service?view=sql-server-ver15&tabs=SSMS#feedback)
* Content Source: [docs/relational-databases/tutorial-sql-server-backup-and-restore-to-azure-blob-storage-service.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tutorial-sql-server-backup-and-restore-to-azure-blob-storage-service.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by msebolt** [comment]
@LearnsHappily Thank you for the feedback, assigning this to the author for review.

**Comment by rothja** [comment]
@LearnsHappily Thank you and sorry for the confusion. So you are using an older version of SSMS? Or are you saying that the current screenshots are outdated? Typically in the latest content, we keep the documentation updated to the latest version in most cases. This is especially true of SSMS, because it works fine with any version of SQL Server. But if the screenshots are not current, we do need to fix that. Thank you!

**Comment by rothja** [comment]
@LearnsHappily Thanks again for reaching out. I haven't heard back from you, so I'm not sure if I'm understanding the problem correctly. I am going to close the issue at this time, but please let me know on this thread if you have more information, and we can discuss it further. Thanks, and I'm sorry for the confusion.
