### ISSUE TITLE
Missing WITH CREDENTIAL = 'https://.....'

### ISSUE THREAD

**Issue by LearnsHappily** [MicrosoftDocs/sql-docs#3718]
The backup command example is missing the WITH CREDENTIAL clause.
Provide an example of how to create the CREDENTIAL in SQL

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15e8e46c-01f3-a76a-761f-5206e6d878e9
* Version Independent ID: 3945290e-ef38-b04c-9ee6-d3889b4b94e4
* Content: [Tutorial: Use Azure Blob storage service with SQL Server 2016 - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tutorial-use-azure-blob-storage-service-with-sql-server-2016?view=sql-server-ver15)
* Content Source: [docs/relational-databases/tutorial-use-azure-blob-storage-service-with-sql-server-2016.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tutorial-use-azure-blob-storage-service-with-sql-server-2016.md)
* Product: **sql**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by msebolt** [comment]
@LearnsHappily Thank you for the feedback, assigning this to the author for review.

**Comment by MashaMSFT** [comment]
Hi @LearnsHappily , thank you for contacting Microsoft! The backup with credential command has been deprecated. From the article associated with this Git Issue: 
If you wish to backup a SQL Server 2012 SP1 CU2 or later database or a SQL Server 2014 database to this Azure container, you can use the [deprecated syntax documented here](https://docs.microsoft.com/en-us/sql/relational-databases/backup-restore/sql-server-backup-to-url?view=sql-server-2014) to backup to URL using the WITH CREDENTIAL syntax.

However, I'm not sure I understand your comment "Provide an example of how to create the CREDENTIAL in SQL" as the example to create the credential is in [Step 2](https://docs.microsoft.com/en-us/sql/relational-databases/tutorial-use-azure-blob-storage-service-with-sql-server-2016?view=sql-server-ver15#2---create-a-sql-server-credential-using-a-shared-access-signature) of the tutorial: 

```sql
/* Example:
USE master  
CREATE CREDENTIAL [https://msfttutorial.blob.core.windows.net/containername] 
WITH IDENTITY='SHARED ACCESS SIGNATURE'   
, SECRET = 'sharedaccesssignature' 
GO */

USE master  
CREATE CREDENTIAL [https://<mystorageaccountname>.blob.core.windows.net/<mystorageaccountcontainername>] 
  -- this name must match the container path, start with https and must not contain a forward slash at the end
WITH IDENTITY='SHARED ACCESS SIGNATURE' 
  -- this is a mandatory string and should not be changed   
 , SECRET = 'sharedaccesssignature' 
   -- this is the shared access signature key that you obtained in section 1.   
GO
```

Please let me know if I've misunderstood something, or if you have any further questions? Otherwise, we will proceed with closing out this Git Issue in a few business days.

Thanks!
Masha from the SQL Docs team

**Comment by MashaMSFT** [comment]
Hi @LearnsHappily , thanks again for contacting Microsoft! It's been some time since we've heard from you so we're going to assume your question has been addressed and close out the Git Issue. However, if you need anything further, please feel free to comment within the Git Issue. 

Thanks and hope you have a wonderful rest of your day!
Masha from the SQL Docs team
