### ISSUE TITLE
MSDTC and Tightly Coupled Transactions 

### ISSUE THREAD

**Issue by kishh143** [MicrosoftDocs/sql-docs#3738]
Hi, I am referring to the article https://docs.microsoft.com/en-us/sql/connect/jdbc/understanding-xa-transactions?view=sql-server-2017 or https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/jdbc/understanding-xa-transactions.md

The doc says that there is a hotfix for MSDTC and Tightly Coupled Transactions for enabling support for tightly-coupled XA branches, but the link doesn't work and directs to **page not found**,does that mean hot fix is not required anymore? Please clarify thanks

**Comment by WilliamAntonRohm** [comment]
@kishh143 -- thank you for your feedback.  My understanding is that this hotfix is only required for Windows Server 2003.

@MightyPen -- Gene, can you confirm this behavior?  If so, I'll update the first of the following sentences under https://docs.microsoft.com/en-us/sql/connect/jdbc/understanding-xa-transactions?view=sql-server-2017#guidelines-and-limitations-when-using-xa-transactions:

The hotfix provided at MSDTC and Tightly Coupled Transactions enables support for tightly-coupled XA branches where multiple XA branches with same global transaction ID (GTRID) are mapped to a single MS DTC transaction ID. This support enables multiple tightly coupled XA branches to see each other's changes in the resource manager, such as SQL Server.

**Comment by MightyPen** [comment]
@WilliamAntonRohm Hi William, The article no longer needs to reference KB 938653, because Windows Server 2003 was too far back into the distant past.

- `https://support.microsoft.com/help/938653`

Ideally you can make the appropriate edits to the article, and label this Issue #3738 'cba'.

Also, the initialism "XA" should be defined in the article, as standing in for the two-word phrase "extended architecture" (all lowercase). To make the fix quick, you could simply add a one-sentence paragraph at the end of the introduction (before the WARNING alert) that says the following:

- In this article, `XA` stands for `extended architecture.`

Thanks.  G

cc: @kishh143

**Comment by WilliamAntonRohm** [comment]
@MightyPen -- thank you for the clarifications.  Please review my changes in the above-mentioned PR 13102.

**Comment by MightyPen** [comment]
I have entered my "I Approve" review in the PR #13102 (about one hour ago).
