### ISSUE TITLE
"Read-scale availability group" on Standard Edition

### ISSUE THREAD

**Issue by JohanEnblom** [MicrosoftDocs/sql-docs#3744]
This document states that "Read-scale availability group" is included in the standard edition.
Is it really true?
I have tried to activate this, but I always get the error message that I have the wrong edition.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 453dc1e2-0c9c-fe95-c6fc-90be886432ad
* Version Independent ID: cd472bc0-26b9-a4a6-4089-31b79be787cb
* Content: [Editions and supported features of SQL Server 2017 - SQL Server](https://docs.microsoft.com/en-us/sql/sql-server/editions-and-components-of-sql-server-2017?view=sql-server-ver15#feedback)
* Content Source: [docs/sql-server/editions-and-components-of-sql-server-2017.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/editions-and-components-of-sql-server-2017.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@JohanEnblom Thank you for the feedback.

This might be due to incompatibility with the **Always On** feature which is only available in the Enterprise edition.

Please see if [this post](https://stackoverflow.com/questions/58186180/replica-database-is-not-accessible-in-read-scale-availability-group-in-sql-serve) relates, after following the instructions [here](https://docs.microsoft.com/sql/database-engine/availability-groups/windows/configure-read-scale-availability-groups?view=sql-server-2017) (excluding anything involving **Always On**).

You'll also need to link this issue to a ticket in the [SQL Server forums](https://social.msdn.microsoft.com/Forums/sqlserver/home) for feedback from the product team since this might be unrelated to the documentation.

@MikeRayMSFT

**Comment by msebolt** [comment]
Closing the issue now, please comment below if there are any questions.
