### ISSUE TITLE
Block these steps.

### ISSUE THREAD

**Issue by Larvaman** [MicrosoftDocs/sql-docs#3746]
I am working on program that uses a SQL database locally. Is there a way to block these steps so the end user can't access the database outside of my software?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d41367fc-38cf-0c73-3ea8-93bff726f421
* Version Independent ID: 07b2d0b3-2013-a133-9d1e-ee2d249740d5
* Content: [Connect to SQL Server When System Administrators Are Locked Out - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/connect-to-sql-server-when-system-administrators-are-locked-out?view=sql-server-ver15#feedback)
* Content Source: [docs/database-engine/configure-windows/connect-to-sql-server-when-system-administrators-are-locked-out.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/connect-to-sql-server-when-system-administrators-are-locked-out.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@Larvaman Thank you for the question.

The easiest way would be to use [encryption keys](https://docs.microsoft.com/sql/relational-databases/security/encryption/sql-server-and-database-encryption-keys-database-engine) and hide the private key in such a way that the user needs to run the software to obtain the key.

Please note that since this is a documentation forum, our support options are limited and for further assistance please refer to the [SQL Server support policy](https://support.microsoft.com/en-us/help/4047326/support-policy-for-microsoft-sql-server).

**Comment by msebolt** [comment]
Closing the issue now, please comment below if there are any questions.
