### ISSUE TITLE
Upgrade or Update SQL Server Instances with Multiple AGs

### ISSUE THREAD

**Issue by rohan2962** [MicrosoftDocs/sql-docs#3748]
Under the section, Upgrade or Update SQL Server Instances with Multiple AGs step 3, should AG1 be failed over to NODE2 or NODE3, considering the fact that NODE2 since already upgraded, can not send data to NODE3 for AG1 since NODE3 is not yet updated at the time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bcf4d06-aac4-bf20-1ff5-e19ff14c83fa
* Version Independent ID: 8a67bcab-2958-8174-a086-795c7fdd447f
* Content: [Upgrade availability group replicas - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/upgrading-always-on-availability-group-replica-instances?view=sql-server-2016#upgrade-or-update-sql-server-instances-with-multiple-ags)
* Content Source: [docs/database-engine/availability-groups/windows/upgrading-always-on-availability-group-replica-instances.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/upgrading-always-on-availability-group-replica-instances.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@rohan2962 -- Rohan, thank you for your feedback.

@MashaMSFT -- Masha, please look into this issue 3748.

**Comment by MashaMSFT** [comment]
Hi @rohan2962 , thank you for contacting Microsoft and for your feedback! You're right, it may be cleaner to fail AG1 to Node03, update Node01, and then move the AGs to a combination of Node01 and Node02 in order to upgrade Node03. However, the challenge with that is you would be hosting all 3 AGs on Node03 during the upgrade of Node02. If Node03 doesn't have enough resources to host all three AGs, or if there is some prohibition against having all AGs running on a single node (single point of failure), that might be an issue. 

I've created an internal work item to add clarity to this documentation ([1655478](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1655478)). I will close out this Git Issue in the meantime, but please feel free to comment should you need anything further from us.

Thanks again for helping improve our documentation and hope you have a wonderful rest of your day!
Masha from the SQL Docs team
