### ISSUE TITLE
1986 sprint DST change date is not correct for US

### ISSUE THREAD

**Issue by LuisGonzalezLT** [MicrosoftDocs/sql-docs#3763]
AT TIME ZONE uses 04/06/1986 as the date that clocks in the US were set forward. I believe the correct date should be 04/27/1986. In 1986 Congress enacted P.L. 99-359, amending the Uniform Time Act by changing the beginning of DST to the first Sunday in April and having the end remain the last Sunday in October. These start and end dates were in effect from 1987 to 2006. The measure became law in 07/1986 AFTER the 1986 spring DST switch had already occurred using the previous rule, which was 04/27/1986. Some online conversion utilities do this properly, using 04/27 (example: https://www.timeanddate.com/time/change/usa?year=1986) but AT TIME ZONE does not. You can test it in SQL showing it is using 04/06:

DECLARE @TimeZone SYSNAME = 'Eastern Standard Time';
DECLARE @Date1 DATETIMEOFFSET(7) = CONVERT(DATETIMEOFFSET(7), '19860406 06:59:59.9999999 +00:00');
DECLARE @Date2 DATETIMEOFFSET(7) = CONVERT(DATETIMEOFFSET(7), '19860406 07:00:00.0000000 +00:00');
SELECT @Date1 AT TIME ZONE @TimeZone, @Date2 AT TIME ZONE @TimeZone;
1986-04-06 01:59:59.9999999 -05:00	1986-04-06 03:00:00.0000000 -04:00

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc8b3b24-5a50-6b88-277a-e8ce528b49b2
* Version Independent ID: ed560876-5e84-cb31-1bd4-65b3b0e5da8b
* Content: [AT TIME ZONE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/queries/at-time-zone-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/queries/at-time-zone-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/queries/at-time-zone-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by LuisGonzalezLT** [comment]
Looks like 1985 may also be incorrect, using 04/07/1985 instead of 04/28.
Maybe I am overlooking something and I am wrong but seems off.

**Comment by WilliamAntonRohm** [comment]
@LuisGonzalezLT -- thank you for finding these; we appreciate your thoroughness.  Please enter your feedback at:

- [SQL Server Feedback](https://aka.ms/sqlfeedback)

**Comment by srutzky** [comment]
@LuisGonzalezLT (and @WilliamAntonRohm and @VanMSFT ): I just ran into this myself and here is what I discovered.

This is not a SQL Server issue. This is a Windows issue. The `AT TIME ZONE` functionality is actually coming from .NET (similar to `FORMAT`, `COMPRESS`, etc), and .NET gets its [Time Zone Info](https://docs.microsoft.com/en-us/dotnet/api/system.timezoneinfo) from Windows (Registry Key: **HKEY\_LOCAL\_MACHINE\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Time Zones** ). For example:

`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Time Zones\Eastern Standard Time\Dynamic DST`

If you look there, there are two rules: one for 2006 and one for 2007. Hence, it handles "&lt;= 2006" via the first rule, and "&gt;= 2007" via the second rule. This explains the following examples:

```sql
SELECT CONVERT(DATETIMEOFFSET, '2007-11-03 20:23:45')
    AT TIME ZONE 'Eastern Standard Time' AS [DstYes-2007],
       CONVERT(DATETIMEOFFSET, '2007-11-04 20:23:45')
    AT TIME ZONE 'Eastern Standard Time' AS [DstNo-2007];
-- 2007-11-03 16:23:45.0000000 -04:00	2007-11-04 15:23:45.0000000 -05:00


SELECT CONVERT(DATETIMEOFFSET, '2006-10-28 20:23:45')
    AT TIME ZONE 'Eastern Standard Time' AS [DstYes-2006],
       CONVERT(DATETIMEOFFSET, '2006-10-29 20:23:45')
    AT TIME ZONE 'Eastern Standard Time' AS [DstNo-2006];
-- 2006-10-28 16:23:45.0000000 -04:00	2006-10-29 15:23:45.0000000 -05:00


-- Should be 1953-09-27, but is Oct 25th as that is the last Sunday in Oct:
SELECT CONVERT(DATETIMEOFFSET, '1953-10-24 20:23:45')
    AT TIME ZONE 'Eastern Standard Time' AS [DstYes-1953],
       CONVERT(DATETIMEOFFSET, '1953-10-25 20:23:45')
    AT TIME ZONE 'Eastern Standard Time' AS [DstNo-1953];
-- 1953-10-24 16:23:45.0000000 -04:00	1953-10-25 15:23:45.0000000 -05:00
```

I suppose, since the data was initially just for the OS, that it makes sense that they're not concerned with historical accuracy. 

Take care,
Solomon...
https://SqlQuantumLift.com/
https://SqlQuantumLeap.com/
https://SQLsharp.com/

**Comment by srutzky** [comment]
For historical accuracy, I believe your best option at the moment is using Matt Johnson's open source [SQL Server Time Zone Support project](https://github.com/mj1856/SqlServerTimeZoneSupport).
