### ISSUE TITLE
Copy into command copying only one row from the blob storage specified not the whole table.

### ISSUE THREAD

**Issue by shikharbsar** [MicrosoftDocs/sql-docs#3795]

**Comment by msebolt** [comment]
@shikharbsar Thank you for the feedback.

Please provide a link to the documentation in question and we will be happy to provide an update.

**Comment by shikharbsar** [comment]
https://docs.microsoft.com/en-us/sql/t-sql/statements/copy-into-transact-sql?view=azure-sqldw-latest. This is the command I am talking about. It is copying only the first row not the entire row.

**Comment by msebolt** [comment]
@shikharbsar Thank you for the update.

I was able to fix a couple of quote issues in the statements, however since the queries are based off of user-provided data, you will need to send this to sqldwcopypreview@service.microsoft.com.

Be sure to provide the specific query in question along with a test data set.
