### ISSUE TITLE
Error in documentation in regards to "IntegratedSecurity" argument/option.

### ISSUE THREAD

**Issue by Jazzbear** [MicrosoftDocs/sql-docs#3817]
Hey, i've noticed an error or "mismatch" in the documentation in regards to how the IntegratedSecurity option.
In the documentation it is stated as two-word connected and pascal cased string, like so: IntegratedSecurity=SSPI. 
Reference link: https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/listeners-client-connectivity-application-failover?view=sql-server-ver15#ConnectToPrimary

But i encountered an error when trying to deploy my replica set configuration, which turned out to be because of a missing space in-between the variable. So after changing it to: Integrated Security=SSPI, it deployed successfully. Which is also supported by your own examples:

https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlconnectionstringbuilder?view=netframework-4.8#remarks

https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlconnectionstringbuilder.integratedsecurity?view=netframework-4.8#System_Data_SqlClient_SqlConnectionStringBuilder_IntegratedSecurity

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c76c2d8c-17da-8982-8a91-dd9968efa26e
* Version Independent ID: 2ecd127b-9f05-1f89-bcea-a93e8ded60eb
* Content: [Connect to an availability group listener - SQL Server Always On](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/listeners-client-connectivity-application-failover?view=sql-server-ver15#ConnectToPrimary)
* Content Source: [docs/database-engine/availability-groups/windows/listeners-client-connectivity-application-failover.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/listeners-client-connectivity-application-failover.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @jazzbear, thank you so much for bringing this to our attention! Did you want to make the change yourself? This will list you as a contributor to the doc :)

If so, here are the steps: 
1. Navigate to the page of interest
2. Select the "Edit" button at the top right of the page
3. Select the "Pencil" icon on the right
4. Modify the text within the text box in markdown format - more info: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet
5. Name your file change and provide a description, if necessary
6. Select "Propose file change"
7. Select "Create pull request" on the 'Comparing changes' page
8. Select "Create pull request" on the 'Open a pull request' page

Otherwise, we would be happy to make this change for you :)

Thanks for helping improve our documentation!
Masha from the SQL Docs team

**Comment by Jazzbear** [comment]
Hey, thanks for getting back to me so fast. I would love to give it a go
changing it myself, I will do it tomorrow then, as it is 23:35 her in
Denmark right now :)


man. 16. dec. 2019 22.18 skrev Masha at MSFT <notifications@github.com>:

**Comment by MashaMSFT** [comment]
Hi @Jazzbear , thank you so much for submitting your [PR ](https://github.com/MicrosoftDocs/sql-docs/issues/3817) and improving our documentation! Your change has been merged and is now live :) I will close out this Git Issue but please feel free to comment should you need anything further.

Thanks again and hope you have a wonderful rest of your day!
Masha from the SQL Docs team
