### ISSUE TITLE
Not easy enough to navigate to old version of SQL server

### ISSUE THREAD

**Issue by Ma8e** [MicrosoftDocs/sql-docs#3823]
I'm working with SQL Server 2014, and tried to use TRIM in an script, which of course didn't work. So I search for TRIM and en up on the Transact-SQL (T-SQL) Reference page for TRIM. On that page there's no information which versions TRIM works for. So I choose SQL Server 2014 in the version selector in the upper left corner of the page, but gets immediately transferred to the SQL Server 2019 page again, but now with a message that the page is not available for SQL Server 2014.  So I still don't know which is the earliest version of SQL Server that TRIM works for. ok. So I navigate to this page to see what string functions that are available for SQL Server 2014. But this page doesn't exist for 2014 either. So I navigate to the page for SQL Server and again try to select SQL Server 2014, but end up on a page without any direct links to reference documentation. After clicking around a bit I end up on this page (again redirected to SQL Server 2019). This is where I'm getting a bit annoyed. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ee56333-3495-ebd5-55ff-4d561fdf8c7c
* Version Independent ID: 8eac0316-4538-6b14-617e-a60604e716bb
* Content: [String Functions (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/string-functions-transact-sql?view=sql-server-ver15&viewFallbackFrom=sql-server-2014#feedback)
* Content Source: [docs/t-sql/functions/string-functions-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/string-functions-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@Ma8e Thank you for the feedback, we're sorry you had to experience issues Microsoft Docs.

The issue you're describing is based on the `moniker` system used within the docs, seen in the article's meta data, for example https://github.com/MicrosoftDocs/sql-docs/edit/live/docs/t-sql/functions/string-functions-transact-sql.md.  

Since the issue is with how the site handles the `moniker` and not the `moniker` itself, please move the issue [here](https://github.com/MicrosoftDocs/feedback/issues).
