### ISSUE TITLE
Question regarding Transact-SQL Syntax Conventions documentation

### ISSUE THREAD

**Issue by OBezhan** [MicrosoftDocs/sql-docs#3832]
Hello,

In this article in the section "Transact-SQL Syntax Conventions (Transact-SQL)" there are some words about the semicolon :

> Although the semicolon isn't required for most statements in this version of SQL Server, it will be required in a future version.

Is this still relevant? Should we always add semicolons to be prepared for possible breaking changes in T-SQL syntax / SQL Server?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f865e11f-ddd9-0812-6e86-9fa219d7eb09
* Version Independent ID: 42a8f774-e731-d336-b20c-f47747592d9e
* Content: [Transact-SQL Syntax Conventions (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/transact-sql-syntax-conventions-transact-sql?redirectedfrom=MSDN&view=sql-server-ver15&viewFallbackFrom=sql-server-ver13)
* Content Source: [docs/t-sql/language-elements/transact-sql-syntax-conventions-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/language-elements/transact-sql-syntax-conventions-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by msebolt** [comment]
@OBezhan  Thank you for the question.

Please note that questions about upcoming changes are better handled in the [SQL Server forums](https://social.msdn.microsoft.com/Forums/sqlserver/home?category=sqlserver) or with [SQL Server feedback](https://feedback.azure.com/forums/908035-sql-server) where the product team can provide direct feedback.

Assigning this to the author for review.

**Comment by rothja** [comment]
@OBezhan Thanks you for the feedback. It appears that the semi-colon is part of a standard but was never enforced by Transact-SQL in SQL Server. I think that we still want the comment in the docs if we ever adjust to be stricter on this point (and a lot of newer commands require the semi-colon but error out if you don't use it). So here is my suggestion:

- I think we should leave this here for now because using the semi-colon does not hurt.
- I would *not* suggest changing any of your existing scripts at this time. If Microsoft decided to enforce this, then they would need to warn everyone frequently and far in advance to avoid breaking existing scripts.
- Also, per the previous point, I think any change would probably happen with a new version of SQL Server and a new compatibility level. If that were the case, your old scripts would continue to function at the older compatibility level. And considering that we just released 2019, I think it would be some time before this were a risk.

I hope this helps, and I do think you have a strong case to make for removing it. But I believe we should keep it in for now. At this time I am going to close the git issue, but let me know if you have any questions. Thanks!
