### ISSUE TITLE
sys.database_principals doesn't exist on SQL Azure

### ISSUE THREAD

**Issue by IanKemp** [MicrosoftDocs/sql-docs#3934]
All of the given queries that use `sys.database_principals` fail in SQL Azure, because that object doesn't exist.

@@version = Microsoft SQL Azure (RTM) - 12.0.2000.8   Dec  4 2019 21:24:18   Copyright (C) 2019 Microsoft Corporation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bd57f24-f012-e3b1-1d20-089e7445c87e
* Version Independent ID: c3fd1ed6-2686-8c61-6caa-c08dcf207310
* Content: [Determining Effective Database Engine Permissions - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/security/authentication-access/determining-effective-database-engine-permissions?view=sql-server-ver15)
* Content Source: [docs/relational-databases/security/authentication-access/determining-effective-database-engine-permissions.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/authentication-access/determining-effective-database-engine-permissions.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hi @IanKemp - Thanks for your feedback. That object does exist:

![image](https://user-images.githubusercontent.com/40007119/72100256-2480ce00-32d7-11ea-9f81-fc85fa6735ff.png)

Since this is not a documentation issue, I will go ahead and close this request. If there are any concerns, please let us know. Thanks again!
