### ISSUE TITLE
Loops cannot be inlined?

### ISSUE THREAD

**Issue by blobbles78** [MicrosoftDocs/sql-docs#3993]
Please update the documentation to indicate whether loop structures within UDFs will/will not result in inlining of the function. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4e3344e-e4a8-4356-7036-729c77f6fbd1
* Version Independent ID: a57b3944-c108-081a-6308-a2fedec15de6
* Content: [Scalar UDF Inlining in Microsoft SQL databases - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/user-defined-functions/scalar-udf-inlining?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/user-defined-functions/scalar-udf-inlining.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/user-defined-functions/scalar-udf-inlining.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @s-r-k
* Microsoft Alias: **karam**

**Comment by msebolt** [comment]
@blobbles78 Thank you for feedback.

Assigning this to the author for further review.

**Comment by rothja** [comment]
@blobbles78 Thanks for the suggestion to improve the documentation. @s-r-k Do you know the answer so we can update the documentation? Thank you. #assign:rothja

**Comment by AlanJBurstein** [comment]
Loops cannot be inlined. 
According to Microsoft’s documentation on [Inlineable scalar UDFs requirements](https://docs.microsoft.com/en-us/sql/relational-databases/user-defined-functions/scalar-udf-inlining?view=sql-server-ver15#inlineable-scalar-udfs-requirements):

> **1** SELECT with variable accumulation/aggregation (for example, SELECT @val += col1 FROM table1) _**is not supported for inlining**_.

To clarify, any type of _variable mutation_ is not allowed with scalar inlining. Variable mutation is when you change the value of a variable/parameter at runtime. For inlining, the optimizer needs to know the value of a variable to **_before_** it can build an inline plan. This is not possible if the variable changes during processing. Loops require variable mutation:

```
DECLARE @i INT = 1;
WHILE @i <= 5
BEGIN
  <do something>
  SET @i = @i+1;
END
```
It's necessarily the loop that's not allowed, it's this code `SET @i = @i+1` , which is required to create a loop, which is not allowed when doing scalar inlining. 

You can, however, natively compile a function that uses a loop on 2014 systems or better. You can also use a [tally table](https://www.sqlservercentral.com/articles/the-numbers-or-tally-table-what-it-is-and-how-it-replaces-a-loop-1).  instead of a loop. A third option is recursive, self-referencing scalar UDFs, which, if you know what you're doing, can be used for looping _**without** variable mutation._

Take this function, for example, which uses a loop to calculate interest:

```
CREATE FUNCTION dbo.CalculateInterest_loop
(
  @Cash DECIMAL(10,6),
  @MPR  DECIMAL(10,6),
  @Mo   TINYINT
)
RETURNS DECIMAL(10,2) AS
BEGIN
  WHILE @Mo > 1 SELECT @Cash = @Cash*@MPR+@Cash, @Mo-=1;
  RETURN @Cash;
END;
```
As you can see, this function uses variable mutation. `@Cash = @Cash*`. We can rewrite this as a recursive, self-referencing scalar UDF like so:

```
CREATE OR ALTER FUNCTION dbo.CalculateInterest_rsr
(
  @Cash DECIMAL(10,6),
  @MPR  DECIMAL(10,6),
  @Mo   TINYINT
)
RETURNS DECIMAL(10,2) WITH RETURNS NULL ON NULL INPUT, INLINE = ON AS
BEGIN
  RETURN IIF(@Mo=1,@Cash,dbo.CalculateInterest_rsr(@Cash*@MPR+@Cash,@MPR,@Mo-1));
END;
```
Instead of repeatedly changing the value of @Cash, we are instead calling the function recursively with a different value for @Cash. Some result, no variable mutation.

This function can be inlined. According to the same Microsoft documentation I posted above, 
> **2** Recursive UDFs will be inlined to a certain depth only. 

I don't know what that "certain depth" is but I have been successful at inlining recursive scalar UDFs.

**Comment by rothja** [comment]
@AlanJBurstein Thank you for these details. This is well-researched. @blobbles78 does this address your question? Also, do either of you think the article in question in this issue needs to include a statement to this effect? Any recommendations are welcome for where to add it. Thanks!

**Comment by SQLKiwi** [comment]
> It's necessarily the loop that's not allowed, it's this code `SET @i = @i+1` , which is required to create a loop, which is not allowed when doing scalar inlining.

If that were true, we wouldn't be able to inline functions like the following (which does inline):

```
CREATE OR ALTER FUNCTION dbo.F
    (@r integer)
RETURNS integer
WITH INLINE = ON
AS
BEGIN
    SET @r += 1;
    SET @r += 1;
    SET @r += 1;
    RETURN @r;
END;
```

`WHILE` loops cannot be inlined currently because the available inline plan shapes do not support them easily. Loops _could_ be implemented in various ways, including perhaps a stack spool as used by recursive CTE plans. I don't know if any work has been done in this area.

> I don't know what that "certain depth" is but I have been successful at inlining recursive scalar UDFs.

Non-inline functions have the usual module depth limit of 32.

Inline functions originally inlined up to 32 levels of tail recursion as iteration, then fell back to calling the function directly, giving another 32 levels for a total of 64. There is a risk of compilation failure with recursion due to the increasing complexity of expressions breaching internal limits e.g. error 8632 - _an expression services limit has been reached_.

In the current build (CU4) recursion is limited to 3 levels unrolled in the execution plan, before the function is called recursively (32 levels) for a total of 35. These limits are undocumented and could change again.

> Based on my initial research, inlined scalar UDFs can not leverage a parallel execution plan. There is nothing in Microsoft's documentation to suggest why this is so but it does not appear to be possible.

A statement that uses an inlined non-recursive scalar function can use parallelism. For example:

```
SELECT MAX(dbo.F(T.some_column))
FROM dbo.SomeLargeTable AS T;
```

![image](https://user-images.githubusercontent.com/30526583/82890434-4639d380-9fa0-11ea-9eef-8c7655527b0d.png)

**Recursive** scalar functions prevent a parallel plan, whether inlined or not.

**Comment by rothja** [comment]
@SQLKiwi Thank you for adding your knowledge to the discussion. @blobbles78 At this point, I am hoping that the discussion shed some light on your question. I'll consider updating this article in the future, but I think we'll need more research and product team confirmation of the behaviors before we can change it definitively. 

I'm going to close out the issue, but anyone is welcome to continue the discussion or suggest specific changes in the article that you'd like to recommend. It's also possible to click "Edit" at the top of the article and make the direct changes you want to see, and we'll review it. Thank you!
