### ISSUE TITLE
What's the meaning of user? Normal database user or DBA user?

### ISSUE THREAD

**Issue by AnyiYang** [MicrosoftDocs/sql-docs#4002]
Hi team, 
My customer has raised a question on the meaning of user mentioned in this document for the following two part:

16
Indicates general errors that can be corrected by the user.

17-19
Indicate software errors that cannot be corrected by the user. Inform your system administrator of the problem.

Does the user above mean the normal database user or DBA or end user for application? And what does system administrator mean? DBA or the administrator on OS level?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6af9754-613c-a789-7b94-15ffbeb51190
* Version Independent ID: 79043af2-7d17-ee2e-b4bc-557a6de16796
* Content: [Database Engine Error Severities - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/errors-events/database-engine-error-severities?view=sql-server-ver15)
* Content Source: [docs/relational-databases/errors-events/database-engine-error-severities.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/errors-events/database-engine-error-severities.md)
* Product: **sql**
* Technology: **supportability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @AnyiYang, thanks for contacting Microsoft! 

In this context, by user we mean whomever is receiving the error. Severities 11-16 include things like objects that don’t exist, syntax errors, deadlocks, permission issues etc. Whether or not the person receiving the error can actually fix the underlying problem is going to depend on the environment, but these are generally related to the application, not to the system itself.

By system administrator we mean whomever is responsible for supporting the system. In some customer environments that will be the DBA, in some it may be someone else. In many cases there will be a system administrator for SQL Server and a separate administrator for the OS. In this case you would start with the SQL Server admin since these are SQL Server related errors, and then that person may need to bring in the OS admin depending on what the error is.

I hope that helps and please let me know if we can be of further assistance?
Thanks!
Masha from the SQL Docs team

**Comment by MashaMSFT** [comment]
Hi @AnyiYang , it's been some time since we've heard from you so we're going to assume your question has been addressed and close out this Git Issue. However, if you need more assistance, please feel free to comment.

Thanks and hope you have a wonderful rest of your day!
Masha from the SQL Docs team
