### ISSUE TITLE
Incorrect error message while trying to truncate partition range

### ISSUE THREAD

**Issue by venky085** [MicrosoftDocs/sql-docs#4007]
![image](https://user-images.githubusercontent.com/6082222/72926601-b7335b00-3d22-11ea-8dae-290e83e2a224.png)

**Comment by msebolt** [comment]
@venky085  Thank you for the feedback.

Please note since this is a documentation forum, our support options are limited to specific article examples.

If this issue is product-related, please submit your bug [here](https://feedback.azure.com/forums/908035-sql-server) for feedback from the product team.

Or, for additional options, see:

- [SQL Server forums](https://social.msdn.microsoft.com/Forums/sqlserver/home?category=sqlserver)

- [SQL Server on Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server)

- [SQL Server support policy](https://support.microsoft.com/help/4047326/support-policy-for-microsoft-sql-server)

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
