### ISSUE TITLE
SUM supports the Windows Frame syntax

### ISSUE THREAD

**Issue by MikeGriffinReborn** [MicrosoftDocs/sql-docs#4032]
You are not showing it here, you're documentation is pretty inconsistent in the syntax description for all functions supporting the OVER syntax.  For instance, FIRST_VALUE correctly shows this syntax:

OVER ( [ partition_by_clause ] order_by_clause [ rows_range_clause ] )  

as it does support the WINDOW FRAME syntax, so does SUM and many of the other Aggregate functions, but it is now shown here, it's hard to really know which ones do and which ones do not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a6a0fa2-2aaf-d779-ddf9-a3a8aeb84944
* Version Independent ID: cfb1ffd2-4d74-0d58-27cc-4b4bbcd151bc
* Content: [SUM (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/sum-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/functions/sum-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/sum-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@MikeGriffinReborn Thank you for the feedback.

Assigning this to the author for further review.

**Comment by MikeRayMSFT** [comment]
Hi @MikeGriffinReborn 

I see what you're saying, the Syntax Diagrams for some analytic functions include window frame syntax, but some of the functions (especially the older functions like `SUM` do not. 



The [Aggregate Functions](https://docs.microsoft.com/en-us/sql/t-sql/functions/aggregate-functions-transact-sql) article says:
"The OVER clause may follow all aggregate functions, except the STRING_AGG, GROUPING or GROUPING_ID functions."

[SUM](https://docs.microsoft.com/en-us/sql/t-sql/functions/sum-transact-sql) includes: OVER ( [ partition_by_clause ] order_by_clause)
partition_by_clause divides the result set produced by the FROM clause into partitions to which the function is applied. If not specified, the function treats all rows of the query result set as a single group. order_by_clause determines the logical order in which the operation is performed. order_by_clause is required. For more information, see OVER Clause (Transact-SQL).

Thanks for contacting Microsoft with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment. 

If you're suggesting a simple change to the documentation, it might be faster to submit the suggestion yourself by creating a GitHub pull request (PR). Here's how:

1. On the page you have feedback about, select the **Edit** link at the top right.
1. On the next page, select the **Pencil** icon at the top right.
1. On the next page, in the **Edit file** text window, make your edits directly to the text you want to change.
    If you need help with formatting the new or changed text, see our [Markdown Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet).
1. After you've made your edits, under **Commit changes**:
    a. In the first text box, enter a brief description of the change you've made.
    b. In the **Add an optional extended description** box, paste the link to your GitHub issue.
1. Select **Propose file change**.
1. On the **Comparing changes** page, select **Create pull request**.	
1. On the **Open a pull request** page, select **Create pull request**. 
    
Allow a day or more for the article's author to review and approve your change or offer an alternative solution.
    
By opening a pull request, you're helping the author add your approved change directly to the documentation. After the updated article is published, GitHub lists you as an article contributor.

If your issue is more complex than a simple change in the documentation, that's okay.  We'll continue to research your suggestion and then get back to you with our response.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.
