### ISSUE TITLE
Worse than rubbish. It doesn't work

### ISSUE THREAD

**Issue by johndeighan** [MicrosoftDocs/sql-docs#4081]
(1 row affected)

(1 row affected)
Msg 207, Level 16, State 1, Line 13
Invalid column name 'myTS'.

Completion time: 2020-02-04T09:36:29.0545960-05:00

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21550d41-12b6-37f6-0cd0-9212e0529d9d
* Version Independent ID: 2949dbcd-13bd-8777-0e85-6845726aa6e7
* Content: [rowversion (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/data-types/rowversion-transact-sql?redirectedfrom=MSDN&view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/data-types/rowversion-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/data-types/rowversion-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@johndeighan -- John, thank you for your feedback.

@MikeRayMSFT -- Mike, please look into this issue #4081.

**Comment by DaveBoltman** [comment]
@johndeighan, @TDK1964,
Please read the notes below the code snippet you are referring to. You'll realise that they are not rubbish, although they do require some thinking on the part of the reader!
`myRv` is the rowversion column value for the row that indicates the last time that you read the row. **This value must be replaced by the actual rowversion value**. An example of the actual rowversion value is 0x00000000000007D3.
etc.

**Comment by MikeRayMSFT** [comment]
In order to address the concerns raised here and in #3829, I want to update the T-SQL so that it's clear where you need to manually define the specific rowversion or timestamp. 

Would the update below help?

```sql
CREATE TABLE MyTest (myKey int PRIMARY KEY  
    ,myValue int, RV rowversion);  
GO   
INSERT INTO MyTest (myKey, myValue) VALUES (1, 0);  
GO   
INSERT INTO MyTest (myKey, myValue) VALUES (2, 0);  
GO  
```  
  
You can then use the following sample [!INCLUDE[tsql](../../includes/tsql-md.md)] statements to implement optimistic concurrency control on the `MyTest` table during the update. The script uses `<myRv>` to represent the **rowversion** value from the last time you read the row. Replace the value with the actual **rowversion** value. An example of an actual **rowversion** value is `0x00000000000007D3`.
  
```sql
DECLARE @t TABLE (myKey int);  
UPDATE MyTest  
SET myValue = 2  
    OUTPUT inserted.myKey INTO @t(myKey)   
WHERE myKey = 1   
    AND RV = <myRv>;  
IF (SELECT COUNT(*) FROM @t) = 0  
    BEGIN  
        RAISERROR ('error changing row with myKey = %d'  
            ,16 -- Severity.  
            ,1 -- State   
            ,1) -- myKey that was changed   
    END;  
```  
  


You can also put the sample [!INCLUDE[tsql](../../includes/tsql-md.md)] statements into a transaction. By querying the `@t` variable in the scope of the transaction, you can retrieve the updated `myKey` column of the table without requerying the `MyTest` table.

The following is the same example using the **timestamp** syntax. Replace `<myTS>` with an actual **timestamp**.

```sql
CREATE TABLE MyTest2 (myKey int PRIMARY KEY  
    ,myValue int, TS timestamp);  
GO   
INSERT INTO MyTest2 (myKey, myValue) VALUES (1, 0);  
GO   
INSERT INTO MyTest2 (myKey, myValue) VALUES (2, 0);  
GO  
DECLARE @t TABLE (myKey int);  
UPDATE MyTest2  
SET myValue = 2  
    OUTPUT inserted.myKey INTO @t(myKey)   
WHERE myKey = 1   
    AND TS = <myTS>;  
IF (SELECT COUNT(*) FROM @t) = 0  
    BEGIN  
        RAISERROR ('error changing row with myKey = %d'  
            ,16 -- Severity.  
            ,1 -- State   
            ,1) -- myKey that was changed   
    END;  
```
