### ISSUE TITLE
^ field terminator

### ISSUE THREAD

**Issue by cdawson1971** [MicrosoftDocs/sql-docs#4090]
To specify a field terminator of ^ using the -t switch you use an escape chararcter of ^ so the switch looks like -t^^. That is not documented on this page or on the referenced "Specify Field and Row Terminators (SQL Server)" page. It took me an hour of scouring the internet to discover this. Please update the doc to include the need for the escape character.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86bd520a-7468-fd55-c357-b0f645a917ef
* Version Independent ID: 3dc9dee5-afcb-8287-4441-e84ff717186a
* Content: [bcp Utility - SQL Server](https://docs.microsoft.com/en-us/sql/tools/BCP-utility?view=sql-server-ver15#feedback)
* Content Source: [docs/tools/bcp-utility.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/bcp-utility.md)
* Product: **sql**
* Technology: **tools-other**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@cdawson1971 -- thank you for your feedback.

@markingmyname -- please look into this issue 4090.

**Comment by srutzky** [comment]
@cdawson1971 and others:

To be clear, the issue here of needing to escape a `^` character as `^^` is a DOS / Command Prompt issue. The carrot character is used for line-continuation. This has nothing to do with `BCP` (nor `SQLCMD` or any other command-line utility).

Run the following in a command prompt window to see:

```
C:\>ECHO A^B
AB

C:\>ECHO A^^B
A^B
```

I'm not saying that it wouldn't be helpful to document this since not that many people know of the special command-line characters (also `&` and `|` I believe), just making sure it isn't stated or implied to be an issue with any particular SQL Server command line utility.


Take care,
Solomon...
https://SqlQuantumLift.com/
https://SqlQuantumLeap.com/
https://SQLsharp.com/

**Comment by cdawson1971** [comment]
Fair enough, srutzky. It's not a blame game; it just needs to be documented for practical purposes. See, for example, https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/set_1 where they include this blurb:

    Using special characters

    The characters <, >, |, &, ^ are special command shell characters, and they must be preceded by the escape character (^) ...

Thanks.

**Comment by markingmyname** [comment]
@cdawson1971 

Thank you for your feedback! We will investigate and get back to you with the relevant info.

However, please add your experience in [UserVoice](https://feedback.azure.com/forums/908035-sql-server) to find if you see more people experience the same situation.

**Comment by markingmyname** [comment]
I reworked the "Remarks" section a bit.

I made it more of a bulleted section, and I added an extra note of using special characters from the article you mentioned in this Issue.

I also added how to determine where to see where the bcp utility is installed.

By the end of the week, the article will show the changes.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the UserVoice site.
