### ISSUE TITLE
bcp -G Option not working as described

### ISSUE THREAD

**Issue by HuubvdP** [MicrosoftDocs/sql-docs#4102]
For Azure Active Directory Integrated authentication, provide the -G option without a user name or password. This configuration assumes that the current Windows user account (the account the bcp command is running under) is federated with Azure AD.

This is not working. If you don't provide a username: you get the error:

SQLState = FA004, NativeError = 0
Error = [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Failed to authenticate the user '' in Active Directory (Authentication option is 'ActiveDirectoryIntegrated').
Error code 0x800401F0; state 10
CoInitialize has not been called.

If you provide user and password you get the error:

SQLState = FA004, NativeError = 0
Error = [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Failed to authenticate the user 'xxxxxx' in Active Directory (Authentication option is 'ActiveDirectoryPassword').
Error code 0x800401F0; state 10
CoInitialize has not been called.

For details also see:

https://social.msdn.microsoft.com/Forums/en-US/e6269455-2090-432f-be27-363e9fd486e6/bcp-login-failed-using-activedirectorypassword-authentication?forum=sqltools

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86bd520a-7468-fd55-c357-b0f645a917ef
* Version Independent ID: 3dc9dee5-afcb-8287-4441-e84ff717186a
* Content: [bcp Utility - SQL Server](https://docs.microsoft.com/en-us/sql/tools/bcp-utility?view=sql-server-ver15#feedback)
* Content Source: [docs/tools/bcp-utility.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/bcp-utility.md)
* Product: **sql**
* Technology: **tools-other**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@HuubvdP -- thank you for your feedback.  Please file this as a product issue at [SQL Server Feedback](https://aka.ms/sqlfeedback).

@markingmyname -- please look into this issue #4102.

**Comment by HuubvdP** [comment]
I've filed it there:

https://feedback.azure.com/forums/908035-sql-server/suggestions/39643693-bcp-g-option-not-working-as-described

**Comment by markingmyname** [comment]
@HuubvdP 

Thank you for your feedback! We will investigate and get back to you with the relevant info.

Thank you for adding your experience in [UserVoice](https://feedback.azure.com/forums/908035-sql-server) to find for others.

**Comment by markingmyname** [comment]
I reworked the "Remarks" section a bit.

I made it more of a bulleted section, and I added an extra note of using special characters from the article you mentioned in this Issue.

I also added how to determine where to see where the bcp utility is installed.

By the end of the week, the article will show the changes.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) site.

**Comment by markingmyname** [comment]
@HuubvdP 

I was able to test this issue.

When testing on my machine, it did not work.  I got the error stated in this issue.  However, when I built a new clean VM, it did work.  Please make sure you are using the latest version of the BCP utility tool.

The bottom line of my finding is that this issue is generally due to an environmental issue.

Here are the steps and tools I used to make it work.

I reviewed this article to help me set up an AAD Admin to my Azure SQL DB server - https://docs.microsoft.com/en-us/azure/sql-database/sql-database-aad-authentication-configure?tabs=azure-powershell.

Then once I assigned an admin, I had to make sure that I am an admin for the entire tenant to have the ability to assign the admin. So if you are not an admin for your actual Azure tenant, ten, I would have that admin assign an admin to your Azure SQL DB.

I would try and test by using SSMS to see if you can log in to the Azure SQL DB server using Azure Active Directory - Password first.

![image](https://user-images.githubusercontent.com/22989000/75275467-33113f00-57ca-11ea-9ebe-e48cb80a8185.png)


If that works, then you should be to try and test the example in the [article](https://docs.microsoft.com/en-us/sql/tools/bcp-utility?view=sql-server-ver15#arguments)

Then you should be ok.

If you can't get it to work using -P ten leave off the -P and have the tool request a Password or PIN code when the script is executed.

I hope this helps.

Thank you.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [UserVoice](https://feedback.azure.com/forums/908035-sql-server) site.

**Comment by HuubvdP** [comment]
@markingmyname I've tested thes steps but still didn't get this working. Can you confirm that you tested bcp with only -G option (NO -U and-P) and that you get data back from a Azure sql server?

**Comment by wojaczek** [comment]
Hey! 
I'm facing same problem: bcp Version: 15.0.1300.359 gives message: Failed to authenticate the user '' in Active Directory, like it couldn't get proper authorization info from the system. If I use -U and put my id explicitly, it displays browser window with password prompt and lets me in. 
SSMS works fine with Active Directory - Integrated. I can also create ODBC datasource with the driver 17 using Azure Active Directory Integrated. So it's only BCP not working on my machine.

**Comment by markingmyname** [comment]
Reopening this issue to investigate further.

**Comment by HuubvdP** [comment]
Microsoft has found the error and fixed this. It will be released in the next odbc version. 
For more information you need to contact Microsoft.

**Comment by wojaczek** [comment]
Perfect, guys, thanks!

śr., 10 cze 2020, 08:51 użytkownik HuubvdP <notifications@github.com>
napisał:

**Comment by markingmyname** [comment]
Currently, there is no specific release notes article for cmd line tools for SQL separately.

I will take this feedback to the parties involved.

Thank you.
