### ISSUE TITLE
Examples for various databases

### ISSUE THREAD

**Issue by shawnnesser** [MicrosoftDocs/sql-docs#4138]
It would be nice to have specific examples for the major databases such as SAP, DB2 etc.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dad6b54f-7b8d-0d9b-0ece-815b8874f751
* Version Independent ID: dee28cea-a153-0d80-b3f1-982aa4d16a87
* Content: [Access external data: ODBC generic types - PolyBase - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/polybase/polybase-configure-odbc-generic?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/polybase/polybase-configure-odbc-generic.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/polybase/polybase-configure-odbc-generic.md)
* Product: **sql**
* Technology: **polybase**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@shawnnesser -- thank you for your feedback.  You may some examples here:
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server) 

You are welcome to raise this issue here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)
