### ISSUE TITLE
The "SQL Server Express" download link is wrong

### ISSUE THREAD

**Issue by ticianaciminari** [MicrosoftDocs/sql-docs#4154]
@doggy8088 commented 2 days ago — with docs.microsoft.com
It should be a link to SQL Server 2019 page: https://docs.microsoft.com/zh-tw/sql/sql-server/editions-and-components-of-sql-server-version-15?view=sql-server-ver15

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d663fffb-d444-59c0-714f-433cf91980c4
* Version Independent ID: ee6da2f6-9ab0-792c-8a5d-d3c725779669
* Content: [Editions and supported features of SQL Server 2019 - SQL Server](https://docs.microsoft.com/en-us/sql/sql-server/editions-and-components-of-sql-server-version-15?view=sql-server-ver15)
* Content Source: [docs/sql-server/editions-and-components-of-sql-server-version-15.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/editions-and-components-of-sql-server-version-15.md)
* Product: **sql**
* Technology: **install**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by ticianaciminari** [comment]
Hi Team,

Could you please check the issue from user?

Kind regards,
Microsoft DOCS International Team

**Comment by WilliamAntonRohm** [comment]
@doggy8088, @ticianaciminari -- Will, Ticiana -- thank you for your feedback.  I am looking into this issue.

**Comment by jsantosh14** [comment]
Even the SQL Developer Edition 2019 is downloading the 2017 version. "https://www.microsoft.com/en-in/sql-server/sql-server-downloads#"

**Comment by WilliamAntonRohm** [comment]
@ticianaciminari -- Ticiana, after further research, I'm unsure of the issue here.  There is no "SQL Server Express download link" on that page (English version is https://docs.microsoft.com/en-us/sql/sql-server/editions-and-components-of-sql-server-version-15?view=sql-server-ver15), only "Download SQL Server 2019 (15.x) from the Evaluation Center".  Is the originator referring to a different source location (page) containing the SQL Server Express download link?

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
