### ISSUE TITLE
Possible mistake in this page:

### ISSUE THREAD

**Issue by Peled-Zohar** [MicrosoftDocs/sql-docs#4204]
The sentence "Note that this example does not allow for multirow data modifications." is referring to the first code example on this page (it's the one-before-last sentence of the last paragraph before the code example). However, the code example itself seems to have no problem with multirow inserts - in fact, it should perform the same with one or many inserted rows.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de204ead-2a80-46ec-6adc-3d8b13977602
* Version Independent ID: eb4f715f-eba6-5d39-b2ba-5baae1b58c71
* Content: [Use the inserted and deleted Tables - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/triggers/use-the-inserted-and-deleted-tables?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/triggers/use-the-inserted-and-deleted-tables.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/triggers/use-the-inserted-and-deleted-tables.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by WilliamAntonRohm** [comment]
@Peled-Zohar -- Zohar, thank you for your feedback.  I am looking into this document.

**Comment by WilliamAntonRohm** [comment]
@rothja -- Jason, please look into this issue #4204.

**Comment by rothja** [comment]
@Peled-Zohar Thank you. I'll look into this and get back to you.

**Comment by rothja** [comment]
@Peled-Zohar Thanks for your patience and for the feedback. I see your point in looking at the example. More correctly, I think this article doesn't focus on multi-row inserts, so I'll move that comment and keep the link for more information (instead of the confusing comment about the sample). Once I merge the changes, the git issue will close and the changes will appear live in a day or so. Thank you!
