### ISSUE TITLE
Implies gMSAs not supported in SQL 2014.  Whereas the SQL 2014 documentation states that they are.

### ISSUE THREAD

**Issue by RodEdwards999** [MicrosoftDocs/sql-docs#4235]
Group Managed Service Accounts

A Group Managed Service Account is an MSA for multiple servers. Windows manages a service account for services running on a group of servers. Active Directory automatically updates the group managed service account password without restarting services. You can configure SQL Server services to use a group managed service account principal. Beginning with SQL Server 2014, SQL Server supports group managed service accounts for standalone instances, and SQL Server 2016 and later for failover cluster instances, and availability groups.

Whereas the SQL 2014 documentation states:
From &lt;https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/configure-windows-service-accounts-and-permissions?view=sql-server-2014&gt;

Group Managed Service Accounts

A Group Managed Service Account is an MSA for multiple servers. Windows manages a service account for services running on a group of servers. Active Directory automatically updates the group managed service account password without restarting services. You can configure SQL Server services to use a group managed service account principal. Beginning with SQL Server 2014, SQL Server supports group managed service accounts on Windows Server 2012 R2 and later for standalone instances, failover cluster instances, and availability groups.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b3831a3-6c86-243c-4b07-8960e4d06d7b
* Version Independent ID: dfd7599d-88eb-99f2-c227-0c9dc82bfd87
* Content: [Configure Windows Service Accounts and Permissions - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/configure-windows-service-accounts-and-permissions?view=sql-server-2016#feedback)
* Content Source: [docs/database-engine/configure-windows/configure-windows-service-accounts-and-permissions.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/configure-windows-service-accounts-and-permissions.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@RodEdwards999 -- thank you for your feedback.

@MikeRayMSFT -- please look into this issue #4235.

**Comment by CarlRabeler** [comment]
@RodEdwards999 Please help me understand what I am missing. I read your git issue, but I do not understand it. I just pasted below the current content that explicitly says that Beginning with SQL Server 2014, SQL Server supports group managed service accounts for standalone instances. 

Group Managed Service Accounts

A Group Managed Service Account is an MSA for multiple servers. Windows manages a service account for services running on a group of servers. Active Directory automatically updates the group managed service account password without restarting services. You can configure SQL Server services to use a group managed service account principal. Beginning with SQL Server 2014, SQL Server supports group managed service accounts for standalone instances, and SQL Server 2016 and later for failover cluster instances, and availability groups.

To use a group managed service account for SQL Server 2014 or later, the operating system must be Windows Server 2012 R2 or later. Servers with Windows Server 2012 R2 require KB 2998082 applied so that the services can log in without disruption immediately after a password change.

**Comment by dokier** [comment]
@CarlRabeler You're not looking at the link for 2014 documentation. In that link it says gmsa can be used for standalones, failover cluster instances and availability groups in 2014 whereas the document you're referencing it only states 2014 supports gmsa for standalone instances only.

Which one is the correct one?

SQL 2014 documentation states:
From <https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/configure-windows-service-accounts-and-permissions?view=sql-server-2014>

**Comment by CarlRabeler** [comment]
Beginning with SQL Server 2014, SQL Server supports group managed service accounts for standalone instances, and SQL Server 2016 and later for failover cluster instances, and availability groups.

To use a group managed service account for SQL Server 2014 or later, the operating system must be Windows Server 2012 R2 or later. Servers with Windows Server 2012 R2 require KB 2998082 applied so that the services can log in without disruption immediately after a password change.

**Comment by CarlRabeler** [comment]
PR to update 2014 has merged
