### ISSUE TITLE
Error in setwd(mainDir) : cannot change working directory

### ISSUE THREAD

**Issue by awilbert** [MicrosoftDocs/sql-docs#4248]
Having issues setting the output folder for images generated by the RPlotHist stored procedure. I've created C:\temp\plots on my computer. Does the error have something to do with isolation level changes in SQL Server 2019? (https://docs.microsoft.com/en-us/sql/advanced-analytics/install/sql-server-machine-learning-services-2019?view=sql-server-ver15)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddb4497c-66d7-b890-bb98-fb4bdb9e32d6
* Version Independent ID: 3794acda-9e96-834e-9931-c8e115014db9
* Content: [R + T-SQL tutorial: Explore data - SQL Server Machine Learning Services](https://docs.microsoft.com/en-us/sql/advanced-analytics/tutorials/sqldev-explore-and-visualize-the-data?view=sql-server-ver15#feedback)
* Content Source: [docs/advanced-analytics/tutorials/sqldev-explore-and-visualize-the-data.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/advanced-analytics/tutorials/sqldev-explore-and-visualize-the-data.md)
* Product: **sql**
* Technology: **machine-learning**
* GitHub Login: @dphansen
* Microsoft Alias: **davidph**

**Comment by dphansen** [comment]
@awilbert Thank you for opening a GitHub issue. Would you be able to provide us with the error/output message that you get? Thanks.

**Comment by awilbert** [comment]
**Error returned in messages window:**
Msg 39004, Level 16, State 20, Line 1
A 'R' script error occurred during execution of 'sp_execute_external_script' with HRESULT 0x80004004.
Msg 39019, Level 16, State 2, Line 1
An external script error occurred: 
Error in setwd(mainDir) : cannot change working directory
Calls: source -> withVisible -> eval -> eval -> setwd

Error in execution.  Check the output for more information.
Error in eval(ei, envir) : 
  Error in execution.  Check the output for more information.
Calls: runScriptFile -> source -> withVisible -> eval -> eval -> .Call
Execution halted

**------
SQL Server log just says:** 
SQL Server received abort message and abort execution for major error : 18 and minor error : 42

**Comment by dphansen** [comment]
@awilbert Thanks. We will investigate and get back to you.

**Comment by dphansen** [comment]
@awilbert You are correct. This is due to the isolation level changes in SQL Server 2019. 

The issue can be resolved by granting **Read & execute** permissions to **ALL APPLICATION PACKGES** to the folder you are trying to change their working directory to:

1. In File Explorer, right click on the folder you want to use as working directory, and select **Properties**.
1. Select **Security** and click **Edit...** to change permissions.
1. Click **Add...**
1. Make sure the **From this location** is the local computer name.
1. Enter **ALL APPLICATION PACKAGES** in **Enter the object names to select** and click **Check Names**. Click **OK**.
1. Select **Read & execute** under the **Allow** column. Click **OK** and **OK**.

I will update the docs to point out this change. Thank you for bringing it to our attention.

**Comment by dphansen** [comment]
The documentation has been updated. Please see [the File permissions section in SQL Server 2019 on Windows: Isolation changes for Machine Learning Services](https://docs.microsoft.com/en-us/sql/advanced-analytics/install/sql-server-machine-learning-services-2019?view=sql-server-ver15#file-permissions).
