### ISSUE TITLE
TOP function in UDF

### ISSUE THREAD

**Issue by jctbak** [MicrosoftDocs/sql-docs#4384]
Regarding "Important Notes" (item #6), it looks like TOP function in UDF will return different value in 2019 comparing to 2016. If you have a select in UDF with TOP that returns no rows, in 2016 UDF returns 0, in 2019 returns NULL.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4e3344e-e4a8-4356-7036-729c77f6fbd1
* Version Independent ID: a57b3944-c108-081a-6308-a2fedec15de6
* Content: [Scalar UDF Inlining in Microsoft SQL Server - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/user-defined-functions/scalar-udf-inlining?view=sql-server-ver15)
* Content Source: [docs/relational-databases/user-defined-functions/scalar-udf-inlining.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/user-defined-functions/scalar-udf-inlining.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @s-r-k
* Microsoft Alias: **karam**

**Comment by WilliamAntonRohm** [comment]
@jctbak -- thank you for your feedback.

@s-r-k -- please look into this issue #4384.

**Comment by rothja** [comment]
@jctbak Thanks for the feedback, and apologies for the long delay. Are you suggesting adding another item (7) to the list of important notes at the end that points out the change in behavior? Something like this:

## Important Notes

As described in this article, scalar UDF inlining transforms a query with scalar UDFs into a query with an equivalent scalar subquery. Due to this transformation, users may notice some differences in behavior in the following scenarios:

1. Inlining will result in a different query hash for the same query text.
2. etc
3. etc
4. etc
5. etc
6. etc.
7. If you use `TOP` in a UDF in SQL Server 2019 and no rows are returned, the return value is NULL. In past versions of SQL Server, the return value might be zero.

**Comment by rothja** [comment]
@jctbak Also, if you had an example to test with, we could try against several versions to see if there is a difference. A simple sample script that creates the function and tests it would be great. Thanks! #assign:rothja

**Comment by rothja** [comment]
@jctbak At this time, I'm not sure how to proceed with the suggestion. If you have more information regarding the comments I added above, please let me know and I'll continue to investigate. For now, I will close the git issue, but I would be glad to reopen to work on it again at any time. Thank you!
