### ISSUE TITLE
The order of the <COLUMN> elements defines the order in which they are returned by the bulk operation?

### ISSUE THREAD

**Issue by kind03** [MicrosoftDocs/sql-docs#4413]
What does it mean by "The order of the &lt;COLUMN&gt; elements in the &lt;ROW&gt; element defines the order in which they are returned by the bulk operation."? Why does the bulk operation return anything? Are we only trying to load data into the table in this example?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b3384ba-bb57-c651-d1e7-ebcb608c3170
* Version Independent ID: 7e8b85c3-70b6-8f55-8090-78021387d324
* Content: [Map table columns to data-file fields with a format file - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/import-export/use-a-format-file-to-map-table-columns-to-data-file-fields-sql-server?view=sql-server-ver15#import_data)
* Content Source: [docs/relational-databases/import-export/use-a-format-file-to-map-table-columns-to-data-file-fields-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/import-export/use-a-format-file-to-map-table-columns-to-data-file-fields-sql-server.md)
* Product: **sql**
* Technology: **data-movement**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@kind03 -- thank you for your questions.

@MashaMSFT -- please look into this issue.

**Comment by MashaMSFT** [comment]
Hi @kind03 , thanks for contacting Microsoft! 

The reason it says “returned by the bulk operation” is because the bulk operation can have different targets, it’s just the pipeline between a source and a target. In this case, the source is a flat file and the target is a table, so the bulk operation is reading the data from the flat file and “returning” it in the order defined by the format file to the target which is a table.

However, it may provide more clarity if we update the sentence to: 
The order of the <COLUMN> elements in the <ROW> element defines the order in which the bulk operation sends them to the target.

@WilliamAntonRohm , would you be able to process this change please?

Thanks again for reaching out, and please let us know if we can be of further assistance!
Masha from the SQL Docs team

**Comment by MashaMSFT** [comment]
Hi @kind03 , thanks for bringing this to our attention! I have processed a change that hopefully provides a but more clarity around this statement.

I hope that helps and please let us know if we can be of further assistance? I am going to close out this Git Issue, but please feel free to comment should you need anything further.

Thanks again and I hope you have a wonderful rest of your day!
Masha from the SQL Docs team

**Comment by kind03** [comment]
Thanks a lot for everyone above!
