### ISSUE TITLE
UNCLUSTERED is optional so should be [ NONCLUSTERED ] in ALTER TABLE ADD UNIQUE

### ISSUE THREAD

**Issue by Hal-H2Apps** [MicrosoftDocs/sql-docs#4416]
In the ALTER TABLE ADD CONSTRAINT UNIQUE , the UNCLUSTERED should be [ NONCLUSTERED ]

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abcca5d2-d433-96cc-930e-4de020c5785d
* Version Independent ID: fde147ff-b157-502c-276a-d3a2bf9bb3c7
* Content: [ALTER TABLE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-table-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/statements/alter-table-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/alter-table-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by CarlRabeler** [comment]
@Hal-H2Apps Thanks for you submission, but I cannot find exactly which section of this article you are referring to. I did several string searches. Please either be more precise or, better yet, click the Edit button in the upper right and submit your change directly in a Github PR - which will make it to my inbox for review.
Thank you, Carl

**Comment by KalleOlaviNiemitalo** [comment]
Perhaps the original poster refers to the mandatory `NONCLUSTERED` keywords in `<table_constraint>` for memory-optimized tables:

<https://github.com/MicrosoftDocs/sql-docs/blob/fc5b757bb27048a71bb39755648d5cefe25a8bc6/docs/t-sql/statements/alter-table-transact-sql.md#L308-L320>

[Transact-SQL Constructs Not Supported by In-Memory OLTP](https://docs.microsoft.com/en-us/sql/relational-databases/in-memory-oltp/transact-sql-constructs-not-supported-by-in-memory-oltp?view=sql-server-ver15#memory-optimized-tables) says that memory-optimized tables indeed do not support clustered indexes and require the `NONCLUSTERED` keyword when a `PRIMARY KEY` is being created. So, if that is the issue, then the documentation seems to be correct.

However, the "Syntax for disk-based tables" section refers to `<table_constraint>` without defining it, and the nearest definition is in the "Syntax for memory-optimized tables" section. That seems confusing to me. Perhaps it could be clarified by adding a link to [ALTER TABLE table_constraint (Transact-SQL)](https://docs.microsoft.com/sql/t-sql/statements/alter-table-table-constraint-transact-sql) at the end of the "Syntax for disk-based tables" section, so that searching for "table_constraint" with a Web browser finds that link before the memory-optimized definition.

**Comment by Hal-H2Apps** [comment]
Hi,

It’s exactly that.

I think a <table_constraint> should be put in the "Syntax for disk-based tables". So the NONCLUSTERED keyword would be marked as optional.

Kind Regards,

Alexis Leroy

**Comment by CarlRabeler** [comment]
thanks - working on it

**Comment by CarlRabeler** [comment]
Added this note after the disk-based syntax block:

For additional information, see:

ALTER TABLE column_constraint
ALTER TABLE column_definition
ALTER TABLE computed_column_definition
ALTER TABLE index_option
ALTER TABLE table_constraints

(these are links)

**Comment by CarlRabeler** [comment]
will be live later today

**Comment by CarlRabeler** [comment]
@Hal-H2Apps if this does not address your concern, please re-open this issue.
