### ISSUE TITLE
Permissions to select

### ISSUE THREAD

**Issue by know-where** [MicrosoftDocs/sql-docs#4471]
What permissions are neeeded to select from this table? Permissions section is missing on this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5d480f8-09bc-78bf-e34e-678cf9b8f769
* Version Independent ID: 4383b908-7a01-e762-314a-3fb9728944c9
* Content: [dbo.sysjobschedules (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-tables/dbo-sysjobschedules-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/system-tables/dbo-sysjobschedules-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-tables/dbo-sysjobschedules-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by cawrites** [comment]
@know-where thank you for contacting Microsoft. Please review: https://docs.microsoft.com/en-us/sql/t-sql/statements/grant-system-object-permissions-transact-sql?view=sql-server-ver15

**Comment by know-where** [comment]
What about SQL Server Agent Fixed Database Roles, like SQLAgentUserRole, SQLAgentReaderRole, SQLAgentOperatorRole?

**Comment by cawrites** [comment]
@know-where please review: https://docs.microsoft.com/en-us/sql/ssms/agent/sql-server-agent-fixed-database-roles?view=sql-server-ver15. You should be able to search docs.microsoft for any role you are looking for related to SQL Server. The previous comment answers the specific question you originally posted.

**Comment by know-where** [comment]
Thanks, I'm aware of those pages. What is missing from the though, is the information about that tables do the roles grant access to. The documentation mostly says that a role grants access to certain functionality but it's up to the user to figure out which objects access is granted to.

**Comment by cawrites** [comment]
@know-where your request is what role is needed for a system table. https://docs.microsoft.com/en-us/sql/relational-databases/security/authentication-access/database-level-roles?view=sql-server-ver15

This page contains the information that you need because it defines the role. 

https://docs.microsoft.com/en-us/sql/relational-databases/security/authentication-access/database-level-roles?view=sql-server-ver15

For example:
db_owner
Members of the db_owner fixed database role can perform **all configuration and maintenance activities on the database, and can also drop the database in SQL Server.** 

sa Login
The sa login is a member of the sysadmin fixed server-level role. The sa login has all permissions on the server and cannot be limited. The sa login cannot be dropped, but it can be disabled so that no one can use it.   https://docs.microsoft.com/en-us/sql/relational-databases/security/authentication-access/principals-database-engine?view=sql-server-ver15

In the case of users, you create you would need to GRANT them permission.  You can also create a role and assign permissions and users to that role.

For example if you wanted to give a user you created permission to dbo.sysjobschedules you would use the example found here  https://docs.microsoft.com/en-us/sql/t-sql/statements/grant-system-object-permissions-transact-sql?view=sql-server-ver15

Your 'sa' user should have access to all (sys) system tables in SQL Server

**Comment by cawrites** [comment]
@know-where In regards to SQLAgent roles which are different, I would refer to: https://docs.microsoft.com/en-us/sql/ssms/agent/sql-server-agent-fixed-database-roles.  These give administrators finer control over access to SQL Server Agent

By default, users do not have access to the msdb. If you need to provide access to a user you can select one of the roles associated with the msdb database.

**Comment by cawrites** [comment]
https://docs.microsoft.com/en-us/sql/relational-databases/security/permissions-database-engine
https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-database-permissions-transact-sql

**Comment by cawrites** [comment]
@know-where thank you for contacting Microsoft. Please take a moment to review the information pertaining to ROLES and GRANTS for tables. The results shown for the table you requested are based on the 'sa' user. Keep in mind the documentation will define the name of the table, and what information it contains. I recommend closely reviewing the other documentation to determine the type of table and what access it needs, like in the case of system tables. 

A simple test is to do a select top (with your user):
 https://docs.microsoft.com/en-us/sql/t-sql/queries/top-transact-sql . 
Note the error (if applicable) and grant the appropriate access for the user.

**Comment by cawrites** [comment]
#please-close
