### ISSUE TITLE
Be aware of the "non-reserved" keywords when naming identifiers

### ISSUE THREAD

**Issue by valgevali** [MicrosoftDocs/sql-docs#4472]
The full list can be found here: https://link.springer.com/content/pdf/bbm%3A978-1-4302-0387-2%2F1.pdf

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f79ec4df-5309-60fc-1c20-f32b219fb9b9
* Version Independent ID: 6ee85c34-9a2c-e007-dcda-fb6016b98119
* Content: [Reserved Keywords (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/reserved-keywords-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/language-elements/reserved-keywords-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/language-elements/reserved-keywords-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by valgevali** [comment]
e.g. keyword CONTRACT

**Comment by WilliamAntonRohm** [comment]
@valgevali -- thank you for your feedback.

@rothja -- please look into this issue.

**Comment by rothja** [comment]
@valgevali Thank you for reaching out with this suggestion and the link. This is something we will consider doing in the future, but in the past we have not been making this distinction/warning about non-reserved keywords. Due to resourcing and priorities, this is not something that we will be able to complete/add in the near future. But, I appreciate you calling it out as an improvement. Requests like this help us to prioritize for future improvements. At this time, I am going to close the git issue, but please feel free to reply or add any additional comments on this thread. Other users are also welcome to add their feedback on this suggestion by commenting on this issue. Thank you!
