### ISSUE TITLE
18.5 and notebook support

### ISSUE THREAD

**Issue by dsolodow** [MicrosoftDocs/sql-docs#4508]
The release notes mention "Added Notebook as a destination for Generate Scripts wizard."
Does this require the installation of Azure Data Studio to be an active option?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cac198c9-abf9-b7ae-0827-dac03ddf4ad6
* Version Independent ID: 9f2afe99-e7c3-726f-fa89-08fc1e4ed653
* Content: [Release notes for (SSMS) - SQL Server Management Studio (SSMS)](https://docs.microsoft.com/en-us/sql/ssms/release-notes-ssms?view=sql-server-ver15#feedback)
* Content Source: [docs/ssms/release-notes-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/release-notes-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@dsolodow -- Damien, thank you for your question.  Please see here for possible answers:
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server) 

You are welcome add this issue here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)
