### ISSUE TITLE
The installation process took too long, it kept "Loading package, please wait ...". Time has lasted almost a day already

### ISSUE THREAD

**Issue by HuynhThanhCanh** [MicrosoftDocs/sql-docs#4567]
Hello,
I have successfully installed SQL Server 2017 and next I install SSMS, the link takes me to the SSMS 18.5 download page and I have already downloaded and installed it, but it keeps saying "Loading package, please wait ... ". I have waited more than 1 day but the process is not complete. We hope to help, thanks.

**Comment by WilliamAntonRohm** [comment]
@HuynhThanhCanh -- Huỳnh, thank you for your feedback.  You may find further information here:
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server) 

And you are welcome to add your issue here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

cc @markingmyname for awareness
