### ISSUE TITLE
List of supported assemblies

### ISSUE THREAD

**Issue by TheConstructor** [MicrosoftDocs/sql-docs#4614]
Hi,

while mostly the same, there are a few differences between the supported assemblies listed on [https://docs.microsoft.com/en-us/sql/relational-databases/clr-integration/database-objects/supported-net-framework-libraries?view=sql-server-ver15#supported-libraries](https://docs.microsoft.com/en-us/sql/relational-databases/clr-integration/database-objects/supported-net-framework-libraries?view=sql-server-ver15#supported-libraries) and here. (e.g. `System.Xml.Linq.dll`). What is the right set? Is this SQL Server-version dependent?

Best regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c06ceefc-d551-9564-a753-c4148150f5d0
* Version Independent ID: bb433cbe-c273-d066-482c-2d6423003586
* Content: [Designing Assemblies - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/clr-integration/assemblies-designing?view=sql-server-ver15)
* Content Source: [docs/relational-databases/clr-integration/assemblies-designing.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/clr-integration/assemblies-designing.md)
* Product: **sql**
* Technology: **clr**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by WilliamAntonRohm** [comment]
@TheConstructor -- Matthias, thank you for your questions.  

@rothja -- Jason, please look into this issue.

**Comment by rothja** [comment]
@TheConstructor Thanks for the question. So, what version of SQL Server are you using right now? 2019? And you're wondering if this list gets changed as new versions are released or as the framework is updated?

**Comment by TheConstructor** [comment]
@rothja yes I am on 2019 and I saw that the lists in https://docs.microsoft.com/en-us/sql/relational-databases/clr-integration/database-objects/supported-net-framework-libraries?view=sql-server-ver15#supported-libraries and https://docs.microsoft.com/en-us/sql/relational-databases/clr-integration/assemblies-designing?view=sql-server-ver15#restrictions-on-assemblies differ. So I really have two questions:
- Why do the two lists differ?
- What is "the list" for 2019?

Thanks for looking into this!

**Comment by srutzky** [comment]
Hello @TheConstructor (and @rothja ). The list found on the [Supported .NET Framework Libraries](https://docs.microsoft.com/en-us/sql/relational-databases/clr-integration/database-objects/supported-net-framework-libraries#supported-libraries) page is correct. The [Assemblies - Designing](https://docs.microsoft.com/en-us/sql/relational-databases/clr-integration/assemblies-designing#supported-net-framework-assemblies) page (the one that you created the issue on) is missing 3 libraries, and I believe this is due to timing and the sheer volume of documentation that exists (i.e. who knows which pages to update when things change when info is duplicated in multiple places?). The missing libraries are:

* **System.Deployment**
    This was added in SP1 for SQL Server 2005 as noted in this blog post by Bob Beauchemin:
    [New “SQLCLR-approved” assembly in SP1](https://www.sqlskills.com/blogs/bobb/new-sqlclr-approved-assembly-in-sp1/)
* **System.Core** and **System.Xml.Linq**
    These were added in SQL Server 2008.

So, as far as I'm aware, the list has not changed between SQL Server 2008 and SQL Server 2019 (current). Hence, that is _the_ list unless you are using SQL Server 2005, in which case you wouldn't have **System.Core** and **System.Xml.Linq**.

For more info, please see the following article that I wrote:
[Stairway to SQLCLR Level 5: Development (Using .NET within SQL Server)](https://www.sqlservercentral.com/steps/stairway-to-sqlclr-level-5-development-using-net-within-sql-server)

While that article only covers up through SQL Server 2014, the only change since then is the (rather unfortunate) addition of the "CLR strict security" server-level configuration option. You can read about that here:
[SQLCLR vs. SQL Server 2017, Part 1: “CLR strict security” – The Problem](https://sqlquantumleap.com/2017/08/07/sqlclr-vs-sql-server-2017-part-1-clr-strict-security/)


Take care,
Solomon...
https://SqlQuantumLift.com/
https://SqlQuantumLeap.com/
https://SQLsharp.com/

**Comment by srutzky** [comment]
@TheConstructor and @rothja : please see PR #4638 . I fixed both pages. And, to help prevent the lists from getting out of sync again in the future, I added an HTML comment below the "Supported Libraries" list (on the "Supported .NET Framework Libraries" page that was being updated) indicating the other page containing the same list (i.e. the "Designing Assemblies" page that hasn't been updated since SQL Server 2005 went RTM) so that hopefully it will be easier to maintain consistency across future updates.

**Comment by rothja** [comment]
@TheConstructor I have merged @srutzky 's changes in his PR, and we should see the list updated soon. @srutzky your help here is *much* appreciated and the comment in the article for the future is a great idea. Thank you!!
