### ISSUE TITLE
Contradictory heading / body

### ISSUE THREAD

**Issue by stevepmo** [MicrosoftDocs/sql-docs#4639]
Memory Grants Outstanding	

:- If something is outstanding then it has NOT been satisfied

Specifies the total number of processes that have successfully acquired a workspace memory grant.

:- If processes have acquired a grant wouldn't a better title text be Successful Workspace Memory Grants (per second)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcb948c5-600e-9883-4471-7cc21ab0ec36
* Version Independent ID: 977c626b-8df7-d4fb-5faf-04a60f671de6
* Content: [SQL Server, Memory Manager Object - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/performance-monitor/sql-server-memory-manager-object?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/performance-monitor/sql-server-memory-manager-object.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/performance-monitor/sql-server-memory-manager-object.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by msebolt** [comment]
@stevepmo Thank you for the feedback, apologies for the delay.

This is an interesting point, though since the values are based on fixed system object tables, you would need to solicit support from the product team to see it changed.

Please start a thread using [SQL Server feedback](https://feedback.azure.com/forums/908035-sql-server) or [SQL Server forums](https://social.msdn.microsoft.com/Forums/sqlserver/home?category=sqlserver) and link back to this issue for updates and until then, use a temporary alias:

```
select object_name, counter_name = 'Successful Workspace Memory Grants (per second)', cntr_value from (
select object_name, 
       counter_name, 
       instance_name, 
       cntr_value, 
       cntr_type
  from sys.dm_os_performance_counters
 where [object_name] = 'SQLServer:Memory Manager' and counter_name = 'Memory Grants Outstanding') a
```

**Comment by msebolt** [comment]
Closing this issue now.
