### ISSUE TITLE
Why is FORMAT() non-deterministic? 

### ISSUE THREAD

**Issue by Mitch-Wheat** [MicrosoftDocs/sql-docs#4648]
Surely for a given fixed format string it produces the same output?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f019407-5787-6f54-1027-084e817b6b8e
* Version Independent ID: a92541d0-b63a-9603-2a1f-18e210be89e4
* Content: [FORMAT (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/format-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/functions/format-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/format-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by msebolt** [comment]
@Mitch-Wheat Thank you for the question.

The `FORMAT` function appears to be the one exception, see complete list [here](https://docs.microsoft.com/sql/relational-databases/user-defined-functions/deterministic-and-nondeterministic-functions).

Assigning this to the author for further review.

**Comment by rothja** [comment]
@julieMSFT Could you please look more into this issue? Thank you! #reassign:juliemsft

**Comment by julieMSFT** [comment]
@Mitch-Wheat Hello and thank you for contacting Microsoft. I am sorry for the delayed response. Please see this link for a discussion of why FORMAT() is non-deterministic, https://dba.stackexchange.com/questions/174739/format-is-a-nondeterministic-built-in-string-function-right. FORMAT() is not always deterministic because it can be used on numeric data types. Please let me know if you have a further question.

**Comment by julieMSFT** [comment]
@Mitch-Wheat Hi, I will proceed with closing this item. The @notification mechanism continues to work even after an item is closed, in case further communication is needed. We hope to hear from you again.

**Comment by julieMSFT** [comment]
#please-close
