### ISSUE TITLE
Syntax example is... lacking

### ISSUE THREAD

**Issue by AaronBertrand** [MicrosoftDocs/sql-docs#4677]
The syntax example in the middle of this topic is just the DMV name (without even a schema). Surely this is meant to show how you query the DMV, not simply re-state its name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55a39e9d-4884-bcba-59c8-d1a8be5bce51
* Version Independent ID: c521a71a-94c2-17bb-f242-c7777a0bb807
* Content: [sys.dm_tran_transactions_snapshot (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-tran-transactions-snapshot-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/system-dynamic-management-views/sys-dm-tran-transactions-snapshot-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-dynamic-management-views/sys-dm-tran-transactions-snapshot-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@AaronBertrand -- thank you for your keen eye.

@stevestein -- please look into this issue.

**Comment by rothja** [comment]
@CarlRabeler Could you please look into this issue? Thank you! #reassign:CarlRabeler

**Comment by rothja** [comment]
#reassign:CarlRabeler

**Comment by CarlRabeler** [comment]
@AaronBertrand Hi Aaron, Actually, what are you saying is a poor implementation of a very old template for reference content. A syntax block is required for things like CREATE TABLE, ALTER DATABASE, etc. For DMV's, there is no syntax that needs to be included in a syntax block. If you look at the other DMVs in the Transactions node, you will see that some have a SYNTAX block and some do not. All this being said, are you suggesting that a usage example is needed here? I do not think that one is needed, but am willing to be persuaded otherwise.
Thanks,
Carl

**Comment by AaronBertrand** [comment]
I'm saying either a block that says "Syntax" should contain valid syntax (that block contains syntax, I suppose, but it will not parse or run). Or, there simply shouldn't be a block that says "Syntax." What's currently there is obviously wrong.

**Comment by CarlRabeler** [comment]
updated article - will be live within 24 hours
