### ISSUE TITLE
Optimize For Sequential Key Edition Availability

### ISSUE THREAD

**Issue by erikdarlingdata** [MicrosoftDocs/sql-docs#4706]
Please note whether Optimize For Sequential Key is available across editions, or Enterprise only. It would help people doing side-by-side evaluations. 

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13793c61-629f-f379-fcb7-e9178e4f5dce
* Version Independent ID: ced6efc1-1e34-f452-f995-b597e812c2f2
* Content: [CREATE INDEX (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-index-transact-sql?view=sql-server-ver15#sequential-keys)
* Content Source: [docs/t-sql/statements/create-index-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-index-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @pmasl
* Microsoft Alias: **carlrab**

**Comment by pmasl** [comment]
@bluefooted to address

**Comment by bluefooted** [comment]
@erikdarlingdata I'm not sure how to handle this one. We generally go by the principle that if it's not stated otherwise, it applies to all editions. I'm concerned that if I call that out here and don't go back and state the same for every other section, it's going to open a can of worms. If this were a standalone feature that had its own page, I would just call it out there, but I'm not convinced we should add anything to this article. Thoughts?

**Comment by erikdarlingdata** [comment]
@bluefooted I certainly don't want to make unnecessary work for you. I'm not sure at what point improvements like this are classified as "features" by Microsoft, but I don't think this one is any less deserving than the online rebuild syntax, which has both a note here as well as some dedicated pages about guidelines for use, etc.

If this page isn't the right place, then perhaps [this one](https://docs.microsoft.com/en-us/sql/sql-server/editions-and-components-of-sql-server-version-15?view=sql-server-ver15) is? There are many things listed in the **RDBMS scalability and performance** section which will undoubtedly appeal to a more selective audience than this one. If _Multiple filestream containers_ can get a mention here, there has to be room for the sequential key optimization.

Thanks!

**Comment by bluefooted** [comment]
We talked about it a lot because it helps improve a common performance issue, but it's not a feature, it's a performance improvement to an existing feature. Online Index Rebuild is a feature that has SKU differentiation, that's why it's called out here. Any feature that has SKU differentiation will be called out in the Editions and support page you linked above and hopefully in any other documentation that mentions it. If no SKU differentiation is mentioned, it's supported in all editions. Some of the things you pointed out above that appear in the Editions and support page are older features that used to have SKU differentiation but are now supported on all editions, they continue to be listed for clarity. I don't think it makes sense to start documenting SKU support for things that don't have SKU differentiation, I fear it will be a slippery slope.

**Comment by erikdarlingdata** [comment]
Gotcha. No problem. Thanks for explaining. 

When you say "it's a performance improvement to an existing feature", what's the existing feature?

**Comment by bluefooted** [comment]
SQLOS Scheduler, technically, but you could call it an index improvement as that's how it's being applied.

**Comment by erikdarlingdata** [comment]
Cool, thanks for that!
