### ISSUE TITLE
install sqlserver error

### ISSUE THREAD

**Issue by maliangzhu** [MicrosoftDocs/sql-docs#4719]
I'm using a centos-7.7 based docker, 
I copy  mssql-server-15.0.4033.1-2.x86_64.rpm into docker and run 
`sudo rpm -ivh mssql-server-15.0.4033.1-2.x86_64.rpm`
it seems ok, and then run
`sudo  /opt/mssql/bin/mssql-conf setup`

and I got an error `/var/tmp/scl04Xu1N: line 8: -EH: command not found`

here is /var/tmp/scl04Xu1N:
```
1 eval "SCLS=( ${X_SCLS[*]} )"
2 /usr/bin/scl_enabled devtoolset-8
3 if [ $? != 0 ]; then
4   SCLS+=(devtoolset-8)
5   export X_SCLS=$(printf '%q ' "${SCLS[@]}")
6 . /opt/rh/devtoolset-8//enable
7 fi
8  '/sbin/sshd' '-D'
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b543b57-f397-779d-6fe4-1bc2ecd3bdca
* Version Independent ID: e274a0f3-ec74-e809-f4d3-515782b29a92
* Content: [RHEL: Install SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-red-hat?view=sql-server-linux-ver15#feedback)
* Content Source: [docs/linux/quickstart-install-connect-red-hat.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-red-hat.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@maliangzhu -- thank you for your feedback.  Please try these resources:
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server) 

You are welcome to report this issue here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

cc @VanMSFT for awareness
