### ISSUE TITLE
Running on CentOS 7

### ISSUE THREAD

**Issue by dontmesswithbill** [MicrosoftDocs/sql-docs#4721]
I'm trying to run this on CentOS 7.7 but I get this error.

/opt/mssql/bin/sqlservr: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /opt/mssql/bin/../lib/libc++abi.so.1)

**Comment by WilliamAntonRohm** [comment]
@dontmesswithbill -- thank you for your feedback.  Are you following a particular docs.microsoft.com article?  Meanwhile, please try these resources:
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server) 

You are welcome to add this issue here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)

**Comment by dontmesswithbill** [comment]
I tried following the instructions on https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-red-hat?view=sql-server-2017

**Comment by WilliamAntonRohm** [comment]
@dontmesswithbill -- thank you for clarifying.  That article is specific to RHEL, and this repo is solely for existing documentation & examples.  Please try the links I sent previously, including the feedback one.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by rdawise** [comment]
@dontmesswithbill I don't know if you fixed this, but I ran into the issue when I used the wrong repo for my OS. The instructions are for RHEL 8 by default. I just changed it to point to 7 since I'm using Centos 7.
