### ISSUE TITLE
Install Binn folder (ssbdiagnose and other \Tools\Binn)

### ISSUE THREAD

**Issue by IFetisov** [MicrosoftDocs/sql-docs#4729]
I have installed SSMS 18.5 
But ssbdiagose and other utilities not installed from downloaded installation file (18.5)

I've copied C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn from other PC
Now error not found assembly
Microsoft.SqlServer.Smo, Version=14.0.0.0
How to solve this?

**Comment by WilliamAntonRohm** [comment]
@IFetisov -- thank you for your question.  Are you following a particular docs.microsoft.com article?  Meanwhile, please try these resources:
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server) 

You are welcome to report this issue here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)
