### ISSUE TITLE
Problem with Peek Definition

### ISSUE THREAD

**Issue by youssef-sno** [MicrosoftDocs/sql-docs#4737]
When I try to show Peek Definitions for dbo.Customers it says no definition found for 'dbo' and same thing happens with rcustomer'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6d68e91-6a5b-7f3b-0e72-1b88691b0c72
* Version Independent ID: 6f4e07e3-eb0b-cd4c-cc82-399e4a2ad715
* Content: [Use the Transact-SQL editor to create database objects - Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/tutorial-sql-editor?view=sql-server-2017#feedback)
* Content Source: [docs/azure-data-studio/tutorial-sql-editor.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/azure-data-studio/tutorial-sql-editor.md)
* Product: **sql**
* Technology: **azure-data-studio**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@youssef-sno -- thank you for your feedback.  It appears you're having an issue with your scenario, rather than the documentation.  Please consider these resources:
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server) 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
