### ISSUE TITLE
Need a full example

### ISSUE THREAD

**Issue by sb08854** [MicrosoftDocs/sql-docs#4743]
A full DSN example covering AdventureWorks or something similar would be needed. Examples to configure unixODBC for SQL Server are almost non-existent.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cfdda44-e9f6-d18a-6fbb-311b12847f4e
* Version Independent ID: 4755f473-a601-79d8-1de9-15e7bc18c51e
* Content: [Connecting using ODBC - SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/connection-string-keywords-and-data-source-names-dsns?view=sql-server-ver15#feedback)
* Content Source: [docs/connect/odbc/linux-mac/connection-string-keywords-and-data-source-names-dsns.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/linux-mac/connection-string-keywords-and-data-source-names-dsns.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by David-Engel** [comment]
@sb08854 Thanks for the feedback.

When you say "full DSN example", do you just mean the contents of the odbc.ini file? Because you can use any of the keywords and values listed in the [DSN and Connection String Keywords and Attributes](https://docs.microsoft.com/en-us/sql/connect/odbc/dsn-connection-string-attribute?view=sql-server-ver15) link at the top of the article to build your DSN entry. They are the same keywords you would use to build a connection string. And there are numerous connection strings examples around.

I'm adding some clarification in the article to note that DSNs are optional and how the simple DSN is the equivalent of a simple connection string. I'm hoping that clears things up for you.

**Comment by sb08854** [comment]
David:

Thanks for responding and adding clarifications.

Here’s what I meant by a full DSN example:
http://www.unixodbc.org/odbcinst.html

Need a similar example for SQL Server 2019.

True that DSN and connection string are same info, but having a quick jumpstart sample would immensely help devs save time.

Srinivasan Balram, CTO
Marlabs

**Comment by arzoo1995** [comment]
Hi whether is it the right place to ask or not. I just started working on ODBC driver 17 and want to know a little bit more about it.

1. ODBC uses TLS for it's communication or it can work without TLS also?
2. What happens if I disable all TLS(1.0, 1.1, 1.2) from server will it still connect to sql database?

I go through everywhere but did not find this detailed information about it or you can tell me reference also where I can find about it?

**Comment by sb08854** [comment]
@arzoo1995 -- this could help:
https://support.microsoft.com/en-us/help/3135244/tls-1-2-support-for-microsoft-sql-server
