### ISSUE TITLE
Need sample code

### ISSUE THREAD

**Issue by sb08854** [MicrosoftDocs/sql-docs#4745]
Where is the "hello world" for ODBC C program -- there used to be plenty 15-20 years ago?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7474e319-db4f-fdc7-1b58-716bf202a7e8
* Version Independent ID: 5e6b42fb-4610-384f-1c3c-d9dcc95e2e89
* Content: [Programming Guidelines (ODBC Driver) - SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/programming-guidelines?view=sql-server-ver15)
* Content Source: [docs/connect/odbc/linux-mac/programming-guidelines.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/linux-mac/programming-guidelines.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @v-makouz
* Microsoft Alias: **v-daenge**

**Comment by WilliamAntonRohm** [comment]
@sb08854 -- thank you for your question.  Please see these resources:
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server) 

You are welcome to raise this issue here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)

cc @v-makouz for awareness
