### ISSUE TITLE
Authentication issue after deploying single node

### ISSUE THREAD

**Issue by ManuelBeltran2019** [MicrosoftDocs/sql-docs#4754]
Hello,
I followed instructions on deploying bash script to single node to kubeadm, and I get the below authentication error when trying to run-  azdata bdc endpoint list -o table

Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Date': 'Mon, 11 May 2020 14:53:10 GMT', 'Content-Length': '0', 'WWW-Authenticate': 'Basic realm="Login credentials required", Bearer error="invalid_token", error_description="The token is expired"'

**Comment by WilliamAntonRohm** [comment]
@ManuelBeltran2019 -- thank you for your feedback.  Which docs.microsoft.com article are you following?  Meanwhile, please see these resources:
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server) 

You're welcome to report this issue here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)

**Comment by ManuelBeltran2019** [comment]
Hi WilliamThe author Mohammed on a different site, resolve the issue for me. I had to login to azdata with correct acct prior to this command.This was on the the BDC deployment to single node article. This can be closed.Thank you for fast response

    On Monday, May 11, 2020, 05:52:25 PM CDT, William Anton Rohm <notifications@github.com> wrote:  
 
 


@ManuelBeltran2019 -- thank you for your feedback. Which docs.microsoft.com article are you following? Meanwhile, please see these resources:
   
   - DBA Stack Exchange
   - Stack Overflow

You're welcome to report this issue here:
   
   - SQL Server Feedback

**Comment by WilliamAntonRohm** [comment]
@ManuelBeltran2019 -- glad you got it to work for you, and thank you!
