### ISSUE TITLE
Configure SQL Server Container on Docker Persistence does not work!

### ISSUE THREAD

**Issue by c0dingarchit3ct** [MicrosoftDocs/sql-docs#4766]
Following in [Configure SQL Server container images on Docker](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-docker?view=sql-server-ver15#persist) 

**Host Operating System**:  Microsoft Windows 10 Pro : Version	10.0.18363 Build 18363
**Docker Info** :  Docker Desktop community version 2.3.0.2(45183)

**Command**
docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=Compl3xPassw0rd" -p 1433:1433 -v sqldata:/var/opt/mssql/data -d mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04

**Error  from Docker logs command**
SQL Server 2019 will run as non-root by default.
This container is running as user mssql.
To learn more visit https://go.microsoft.com/fwlink/?linkid=2099216.
2020-05-12 16:09:53.24 Server      Setup step is copying system data file 'C:\templatedata\master.mdf' to '/var/opt/mssql/data/master.mdf'.
2020-05-12 16:09:53.28 Server      ERROR: Setup FAILED copying system data file 'C:\templatedata\master.mdf' to '/var/opt/mssql/data/master.mdf':  2(The system cannot find the file specified.)
ERROR: BootstrapSystemDataDirectories() failure (HRESULT 0x80070002)

**Comment by WilliamAntonRohm** [comment]
@c0dingarchit3ct -- Ahmed, thank you for your feedback.  Please consider these resources:
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server) 

You are welcome to add this issue here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
