### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by russellg59** [MicrosoftDocs/sql-docs#4792]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Download SQL Server Management Studio (SSMS) - SQL Server Management Studio (SSMS)](https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver15)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dnethi
* Microsoft Alias: **dinethi**

**Comment by WilliamAntonRohm** [comment]
@russellg59 -- Russell, thank you for your feedback.  Please clarify your issue.  Meanwhile, please consider these resources:
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server)

**Comment by russellg59** [comment]
It absolutely drives me nuts when I see Microsoft Documents with dates like 1/12/19. Is that 1st of December (I live in the UK) or is it 12th of January. Please can you show dates as 1 Jan 19. Then there is no possibility of confusion. I know you’ll say “use regional settings”. But in some cases they just plain don’t work.

Kind Regards

Russell


Russell Gilbert
russell@sandyatom.uk<mailto:russell@sandyatom.uk>
Sandy Atom Technology

Tel: +44 118 328 2445
Mob +44 7960 674911

[cid:image001.jpg@01D62CF2.7FFEC880]<https://www.linkedin.com/in/developerrussell/>

**Comment by WilliamAntonRohm** [comment]
@russellg59 -- Russell, thank you for clarifying.  Please try "en-gb" instead of "en-us" in the docs.microsoft.com URL, for example:
- https://docs.microsoft.com/en-gb/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver15

vs

- https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver15

Also, you can submit issues related to overall site experience, or suggestions for improved site functionality or design, at [https://aka.ms/sitefeedback/](https://aka.ms/sitefeedback). 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
