### ISSUE TITLE
Full-Text Search?

### ISSUE THREAD

**Issue by DanielSmon** [MicrosoftDocs/sql-docs#4798]
It would be helpful if there was a hint on the recommended way to run on docker with full-text search support. There are instructions on installing full-text on Linux (https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup-full-text-search?view=sql-server-ver15), but no mention of docker. It looks like we need to mint our own docker image?

Cheers,
Daniel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b152444b-dfb8-5cbe-cf45-9830bd085a68
* Version Independent ID: 31719660-d4d0-7f63-efcc-846c822a63c2
* Content: [Docker: Install containers for SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-linux-ver15&pivots=cs1-bash#feedback)
* Content Source: [docs/linux/quickstart-install-connect-docker.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-docker.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @vin-yu
* Microsoft Alias: **vinsonyu**

**Comment by rothja** [comment]
@DanielSmon Thanks for your question, and apologies for the delayed response. This question might be better suited to the forums:

- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server) 

Have you made any progress finding the answer since you posted this?

However, @vin-yu might know the answer here as well, and maybe it is something we should call out in the docs. Vin, do you know if there is a way to use containers with full-text search support?

Thank you! +@VanMSFT as well.

**Comment by VanMSFT** [comment]
Hey @vin-yu - Do you know if full text search is supported in with SQL Server in Containers?

**Comment by VanMSFT** [comment]
#reassign:amvin87

**Comment by VanMSFT** [comment]
Hey @amvin87 - Do you mind checking on this? Thanks!

**Comment by amvin87** [comment]
hi @DanielSmon ! thanks for the feedback, here is a sample dockerfile example to help you install FTS and other components https://github.com/microsoft/mssql-docker/blob/master/linux/preview/examples/mssql-agent-fts-ha-tools/Dockerfile  Let me know if you need any further help. 
@VanMSFT, can we add this link to our customize docker section, so users can find it easily please.

**Comment by VanMSFT** [comment]
Adding as a next steps to our [Configure and customize SQL Server Docker containers](https://docs.microsoft.com/sql/linux/sql-server-linux-docker-container-configure) article.
