### ISSUE TITLE
SSMS View Designer forces CONCAT to {fn CONCAT

### ISSUE THREAD

**Issue by AnandaSim** [MicrosoftDocs/sql-docs#4805]
I had to figure a way to search for the phrase { fn in Google Search and Fn is some pop singer's name so reference to this article took me a long time to get there. Somehow, there must be a way to make {fn easier to find.

The reason why I was looking for {fn was that SSMS View Designer 17 and 18 changed my T-SQL from CONCAT(field1, field2, field3) to { fn CONCAT(...)} and then caused the issue that the View Designer would not keep the T-SQL statement. This is horrible. You actually have to run a CREATE VIEW statement using a standard T-SQL request instead of using the View GUI designer in SSMS - I have not found this issue documented anywhere
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1261946-c141-3c55-0734-074362e64740
* Version Independent ID: 5ca65f3e-2a1d-8907-765b-f22ce1d6f548
* Content: [ODBC Scalar Functions (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/odbc-scalar-functions-transact-sql?view=sql-server-ver15&source=docs#feedback)
* Content Source: [docs/t-sql/functions/odbc-scalar-functions-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/odbc-scalar-functions-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by WilliamAntonRohm** [comment]
@AnandaSim -- thank you for your feedback.  Please consider these resources:
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server) 

You are welcome to add this issue here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)


@julieMSFT -- please look into this potential documentation issue.

**Comment by AnandaSim** [comment]
Thanks for that. I found the tip about how the SSMS Query Designer does not
recognise SQL Server's 2012 (onwards) CONCAT keyword just before save from
Stack Overflow but I was puzzled how to phrase the search for the article

Either fix the SSMS Query Designer (both 17 and 18 don't understand this
and other enhancements even though they would be tools meant for SQL Server
2012, 2014, 2017 and 2019 - How many generations of SQL Server is that
already?



Ananda Sim
mailto:anandasim@gmail.com
LinkedIn: https://www.linkedin.com/in/anandasim/
Microsoft Office Resources: http://TheNewOfficeCoach.blogspot.com/

**Comment by WilliamAntonRohm** [comment]
@AnandaSim -- thank you for clarifying.  I am as well puzzled by how to search for a left brace; Googling "\\{" brings up items matching "\\{" exactly, which is not helpful here.

Please add your suggestion regarding Query Designer here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by Matteo-T** [comment]
The issue here is that the old SSMS designer seems to be confused and consider CONCAT() an ODBC scalar function, rather than "normal" T-SQL. That's why you see the funny syntax: "{ fn CONCAT ...}". The ODBC scalar function is pretty limited (only 2 argument), hence the error when >2 argument are used.

I'll see if a fix is reasonably simple do implement when I get a chance (I doubt it's going to be simple, but we'll see... :))
