### ISSUE TITLE
Read-Only Routing support

### ISSUE THREAD

**Issue by crimean-celica** [MicrosoftDocs/sql-docs#4815]
You have to specify (and support) "Load Balance Timeout" or "Connection Lifetime" parameters when you're talking about RO Routing support.
https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlconnection.connectionstring?view=netframework-4.7.2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ddd9a68-472e-514c-0b9f-e08de99004a7
* Version Independent ID: ebdd9d5c-de3a-7d2c-702a-adfe21c8d327
* Content: [JDBC driver support for High Availability, disaster recovery - SQL Server](https://docs.microsoft.com/en-us/sql/connect/jdbc/jdbc-driver-support-for-high-availability-disaster-recovery?view=sql-server-ver15#feedback)
* Content Source: [docs/connect/jdbc/jdbc-driver-support-for-high-availability-disaster-recovery.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/jdbc/jdbc-driver-support-for-high-availability-disaster-recovery.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by David-Engel** [comment]
@crimean-celica Thanks for submitting feedback.

The [link you provided](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlconnection.connectionstring?view=netframework-4.7.2) is for .NET Framework's System.Data.SqlClient. The page you are submitting feedback for is for the Microsoft JDBC Driver for SQL Server.

The "Load Balance Timeout"/"Connection Lifetime" connection properties in System.Data.SqlClient apply to the connection pool implementation inside SqlClient. The Microsoft JDBC Driver for SQL Server does not contain its own connection pool implementation. Connection pooling is provided by other libraries that can be used in conjunction with JDBC drivers, like [Apache Commons DBCP](https://commons.apache.org/proper/commons-dbcp/), [HikariCP](https://github.com/brettwooldridge/HikariCP), or [c3po](https://www.mchange.com/projects/c3p0/).

I understand that if you use a connection pool implementation with the JDBC driver, that you would want to implement a connection lifetime in order to ensure pooled connections are eventually redirected to a read-only replica if one wasn't available when the connection was first opened. A lifetime setting can also ensure that pooled connections are distributed more evenly across servers in an availability group. I'll have to think about how this can be incorporated into the JDBC driver documentation.

Thanks,
David

**Comment by crimean-celica** [comment]
Hello David,

> The page you are submitting feedback for is for the Microsoft JDBC Driver for SQL Server.
> you would want to implement a connection lifetime in order to ensure pooled connections are eventually redirected to a read-only replica if one wasn't available when the connection was first opened

You are right. I have a "balanced" environment (based on AlwaysOn's readable mirrors) with a bunch of applications. And that ability helps us a lot. But JDBC.

> I'll have to think about how this can be incorporated into the JDBC driver documentation.

This would be great!

Thanks,
Sergey

________________________________

**Comment by David-Engel** [comment]
I added a section on connection pooling that lists considerations that need to be taken depending on your deployment environment.

#please-close
