### ISSUE TITLE
Can't find the list of the errors, someone must have deleted it from the page!

### ISSUE THREAD

**Issue by traderhut** [MicrosoftDocs/sql-docs#4818]
Obviously, this page would link to a list of error codes we could / should use.. Although, with the option of it being a string, I expect most people won't use the magic numbers...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 472beb1c-1682-d2db-c2b1-3083c174b0cc
* Version Independent ID: 099a81a1-42cb-bd91-9147-bc761d4be177
* Content: [RAISERROR (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/raiserror-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/language-elements/raiserror-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/language-elements/raiserror-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by rothja** [comment]
@traderhut Thank you for the feedback. It looks like you're suggesting we link to an article with common errors that might be raised. Is that correct? Would this article be a good option or are you thinking of something else?

- [Database engine errors](https://docs.microsoft.com/en-us/sql/relational-databases/errors-events/database-engine-events-and-errors?view=sql-server-ver15)

**Comment by rothja** [comment]
@traderhut Thanks, again for your question. In looking at your question again, I think you're asking about custom errors rather than system errors. In that case, I do not think that there are specific error numbers but rather the error ranges that matter. And then, as you noted, the custom strings for the errors. So, in this case, I don't think there is additional information that we can add to the article other than what's there. If you disagree or want to point out something I am missing, I would be glad to take another look. Thank you!
