### ISSUE TITLE
It seems to me that example don't work in MSSQL-2019

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/sql-docs#4841]
@OneLonelly commented on [Thu May 21 2020](https://github.com/MicrosoftDocs/sql-docs.ru-ru/issues/85)

The "CREATE ASSEMBLY HelloWorld   
FROM &lt;system_drive&gt;:\Program Fi... " don't really work cause file name have to be quoted like string constant (on nvarchar-type variable). And   the next "CREATE ASSEMBLY ... FROM 0x4D5A900000000000 ... "  don't work cause new (since 2017) security politic.  Correct me if I wrong.  

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 7bc10b70-11b5-a892-da24-fe25fa86c8c2
* Version Independent ID: 9c95ecb5-175c-d8e7-22d3-a81f1f58f6c3
* Content: [CREATE ASSEMBLY (Transact-SQL) - SQL Server](https://docs.microsoft.com/ru-ru/sql/t-sql/statements/create-assembly-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/statements/create-assembly-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs.ru-ru/blob/live/docs/t-sql/statements/create-assembly-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

---

@srvbpigh commented on [Fri May 22 2020](https://github.com/MicrosoftDocs/sql-docs.ru-ru/issues/85#issuecomment-632539837)

Hello, @OneLonelly
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

---

@CarlRabeler commented on [Fri May 22 2020](https://github.com/MicrosoftDocs/sql-docs.ru-ru/issues/85#issuecomment-632812596)

@OneLonelly Thanks for the feedback. Fixing the first issue. Could be please elaborate on the second issue? Thank you.
Carl

**Comment by CarlRabeler** [comment]
@VanMSFT could you look at this ?

**Comment by VanMSFT** [comment]
We'll need clarity on the second issue. What makes creating assembly from bits not work from the end user standpoint?

**Comment by OneLonelly** [comment]
> We'll need clarity on the second issue. What makes creating assembly from bits not work from the end user standpoint?

Cause security politic was changed since MSSQL2017 release. And ones have to firstly registry trusted hash for assembly. Only then add assembly from binary. 

This described, for example,  with link to Solomon Rutzky , here : https://stackoverflow.com/questions/54953930/tsql-create-assembly-from-varbinary-breaks-the-class-name-parameter 

By the way, if I remember correctly, I'll can exchange registered  "trusted" assembly to another with the same name but without "securing". It seems to me, this moment will be fixed in the next release. Or not. 
Perhaps, I can wrong. Excuse me for my bad T-SQL and English ;-)

**Comment by srutzky** [comment]
@OneLonelly (and @VanMSFT and @CarlRabeler ): I think there was a little misunderstanding of my StackOverflow answer noted by @OneLonelly . The "CLR strict security" server configuration option (new in SQL Server 2017), does require that all assemblies meet the same requirements that `UNSAFE` assemblies have. And yes, 1 of the 3 options is registering a hash of the assembly to make it a "trusted" assembly, but this option is _never_ required. In fact, while some people do like that option, I am personally [very much against it, and for a variety of reasons](https://feedback.azure.com/forums/908035-sql-server/suggestions/32898688-trusted-assemblies-are-more-problematic-yet-less-f).

So, there is nothing wrong or different when creating assemblies from hex bytes / `VARBINARY` literal. The requirements are the same between creating the assembly from a file and creating it from the hex bytes. You just need to have the security in place _first_, starting in SQL Server 2017. Of course, that would be 100 times easier if the following suggestion was implemented:

[Allow Asymmetric Key to be created from binary hex bytes string just like CREATE CERTIFICATE](https://feedback.azure.com/forums/908035-sql-server/suggestions/32896978-allow-asymmetric-key-to-be-created-from-binary-hex)



Take care,
Solomon...
https://SqlQuantumLift.com/
https://SqlQuantumLeap.com/
https://SQLsharp.com/

**Comment by CarlRabeler** [comment]
#reassign: @VanMSFT

**Comment by VanMSFT** [comment]
If I'm reading this right, there's nothing wrong with the document. Please correct me if I have misunderstood.

**Comment by srutzky** [comment]
Well, the example is currently the following:

```sql
CREATE ASSEMBLY HelloWorld  
    FROM 0x4D5A900000000000  
WITH PERMISSION_SET = SAFE; 
```

That example is structurally accurate. However, that example is not:

* runnable. `0x4D5A900000000000` is not a valid assembly. But, that should be fine given that a) even a small assembly would be a little lengthy (though that might not matter), and b) there is a disclaimer just above the example, stating:

    > Replace the sample bits (which are not complete or valid) with your assembly bits.

    Nothing here has changed, neither for SQL Server 2017 nor 2019.
* a complete tutorial. The statement in the example, _if_ the assembly bits / hex bytes were replaced with a valid _`SAFE`_ assembly, _would_ complete successfully, prior to SQL Server 2017 (and technically even in 2017 and newer _if_ the instance-level config option "CLR strict security" is disabled). However, for `EXTERNAL_ACCESS` and `UNSAFE` assemblies, those require additional steps (either [signing the assembly](https://modulesigning.info/) {preferred}, or enabling `TRUSTWORTHY` on the database {[bad / yuck / stay away](https://sqlquantumleap.com/2017/12/30/please-please-please-stop-using-impersonation-execute-as/)}). 

    Starting in SQL Server 2017, even `SAFE` assemblies are required to do one of those additional steps. I believe this is what @OneLonelly is referring to: without either disabling "CLR strict security", or enabling "TRUSTWORTHY" (both of which should be avoided and are recommended against), the `CREATE ASSEMBLY` statement, _by itself_, is not enough to create a `SAFE` assembly.

Personally, I don't really see either of these nuances as being a problem:

1. The example assembly is stated as being invalid (and it has been since SQLCLR was introduced in SQL Server 2005).
1. The fact that additional prerequisite steps are necessary, starting in SQL Server 2017, in order to get even a `SAFE` assembly created is not _necessarily_ the responsibility of this particular example. While many statements do show prerequisite steps in their examples, examples for [`CREATE INDEX`](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-index-transact-sql#examples-all-versions-uses-the-adventureworks-database) and [`CREATE TRIGGER`](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-trigger-transact-sql#examples) do not show the `CREATE TABLE` statements that would be required for those statements to execute.

    The prerequisite steps are noted in the **Permissions with CLR strict security** section.

**Comment by VanMSFT** [comment]
Hi All,

I'm so sorry for the delay. This got lost in the shuffle. If I understand this issue correctly, there's nothing necessarily needed with the documentation. I would be happy to add any clarity if there are suggestions. For now, I will close this issue, but feel free to @ me on any issues.

Thanks,
Van
