### ISSUE TITLE
Correction ? 

### ISSUE THREAD

**Issue by yvesgui41** [MicrosoftDocs/sql-docs#4880]
when I read this : 
The Buffer Cache Hit Ratio counter is specific to an application. However, a rate of 90 percent or higher is desirable. Add more memory until the value is consistently greater than 90 percent.

I think the third sentence is in opposite to the second : 90 percent or higher is desirable and add more memory until the value is consistently greater than 90 percent 

Thank for your answer 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56ae21ee-e345-0f62-9e51-e1495228c9ed
* Version Independent ID: 7ae44dfe-8aba-5945-e758-a3c5c7fc991a
* Content: [Monitor Memory Usage - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/performance-monitor/monitor-memory-usage?view=sql-server-ver15#feedback)
* Content Source: [docs/relational-databases/performance-monitor/monitor-memory-usage.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/performance-monitor/monitor-memory-usage.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by julieMSFT** [comment]
#assign:julieMSFT

**Comment by julieMSFT** [comment]
@yvesgui41 Hello, thank you for contacting Microsoft. Buffer Cache Hit Ratio indicates the percentage of pages found in the buffer cache without having to read from disk. Because reading from the cache is much less expensive than reading from disk, you want this ratio to be high. Generally, you can increase the buffer cache hit ratio by increasing the amount of memory available to SQL Server for storing pages in memory. Please refer to this [article](https://docs.microsoft.com/en-us/sql/relational-databases/performance-monitor/sql-server-buffer-manager-object?view=sql-server-ver15#buffer-manager-performance-objects).  I hope this answers your question. I will go ahead and close this issue. The @notification mechanism continues to work even after an item is closed, in case further communication is needed. We hope to hear from you again.

**Comment by julieMSFT** [comment]
#please-close
