### ISSUE TITLE
The supported versions tag list at the top says Azure SQL Database but...

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/sql-docs#4891]
... the linked "Supported Editions" doc page doesnt mention Azure SQL. Are online rebuilds supported with AzureSQL Database?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0eae78f-d106-1ace-5e19-f406a514562f
* Version Independent ID: 55201a91-16e8-3888-3aa8-b258ee7400c7
* Content: [Guidelines for Online Index Operations - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/indexes/guidelines-for-online-index-operations?view=sql-server-ver15)
* Content Source: [docs/relational-databases/indexes/guidelines-for-online-index-operations.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/indexes/guidelines-for-online-index-operations.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@StingyJack -- thank you for your question.  We are investigating.

**Comment by MikeRayMSFT** [comment]
Hi @StingyJack 

The [Editions and supported features](https://docs.microsoft.com/sql/sql-server/editions-and-components-of-sql-server-version-15?view=sql-server-ver15) article doesn't apply to Azure SQL Database because SQL Database doesn't have different editions. 

Online Index Operations is supported in Azure SQL DB and in SQL Server Enterprise Edition. 

Thank you for submitting the comment.

**Comment by StingyJack** [comment]
@MikeRayMSFT  - Seeing as Azure SQL database is just an install of SQL Server (probably Enterprise) on a VM that I dont have to manage it seems to be splitting hairs a bit that its not one of the editions of SQL server, but thanks for the confirmation nonetheless.
