### ISSUE TITLE
Missing definition for optional_spid

### ISSUE THREAD

**Issue by brettshearer** [MicrosoftDocs/sql-docs#4895]
optional_spid is not documented here and i believe it should be.

http://esdbp.createaforum.com/general-9/whats-the-optional_spid-in-sys-dm_exec_plan_attributes/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2a77d63-0ef7-54c8-4f02-59f736298c70
* Version Independent ID: 1688ab2b-7894-bbb5-d19d-8d26b6e820aa
* Content: [sys.dm_exec_plan_attributes (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-exec-plan-attributes-transact-sql?view=sql-server-ver15)
* Content Source: [docs/relational-databases/system-dynamic-management-views/sys-dm-exec-plan-attributes-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-dynamic-management-views/sys-dm-exec-plan-attributes-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by WilliamAntonRohm** [comment]
@brettshearer -- Brett, thank you for your feedback.

@CarlRabeler -- Carl, please look into this issue.

**Comment by CarlRabeler** [comment]
#resassign: pmasl

**Comment by rothja** [comment]
@brettshearer Apologies for the long delay. @WilliamDAssafMSFT could you take a look at the link provided and other anecdotal research on the internet to come up with a potential description of the optional_spid attribute for this reference article. When you have a potential description, we can get it approved by @pmasl. Leaving both of you assigned on this for now. #assign:WilliamDAssafMSFT

**Comment by WilliamDAssafMSFT** [comment]
@brettshearer Thanks for contacting Microsoft with feedback about our product documentation. A document update is in flight. 

The connection session_id (spid) becomes part of the cache key in order to reduce the number of re-compiles. This prevents recompilations for a single session's re-use of a plan involving non-dynamically bound temp tables. You may find more information about this scenario [here](https://techcommunity.microsoft.com/t5/sql-server/3-0-how-cache-lookups-work/ba-p/383205).

It should take a few business days to appear live. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment. 

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by WilliamDAssafMSFT** [comment]
@brettshearer Thanks again for submitting your feedback, a doc update has been approved and should be live later today.
