### ISSUE TITLE
SMO Server Event Handling Issue

### ISSUE THREAD

**Issue by kidmusky** [MicrosoftDocs/sql-docs#4898]
There appear to be some security considerations for subscribing to SQL Server events not addressed by the article titled "Handling SMO Events". Using the sample code provided, I encounter an error that states: "Cannot start an event subscription" and "The RPC server is unavailable". I am an administrator on the target server and have successfully used SMO to perform many tasks using the DataTransfer object, but encounter these errors after I attempt to start the events using db.Events.StartEvents(). Are there server or firewall settings that need to be enabled to subscribe to and start events on a remote server? Thank you!

**Comment by WilliamAntonRohm** [comment]
@kidmusky -- thank you for your question regarding this article:
https://docs.microsoft.com/en-us/sql/relational-databases/server-management-objects-smo/create-program/handling-smo-events

Please consider these resources:
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server) 

You are welcome to add this issue here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)


cc @markingmyname for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
