### ISSUE TITLE
Exclude Object Type: Always Encrypted Column Master Keys and Column Encryption Keys

### ISSUE THREAD

**Issue by pokorourk** [MicrosoftDocs/sql-docs#4902]
I'm not seeing an option to exclude these two object types. Is it possible to do so with sqlpackage?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac30c0d5-990b-1114-cb66-d6bbb789b698
* Version Independent ID: 9432dace-7676-2a86-485a-dd5bc6568e86
* Content: [SqlPackage.exe - SQL Server](https://docs.microsoft.com/en-us/sql/tools/sqlpackage?view=sql-server-ver15)
* Content Source: [docs/tools/sqlpackage.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/sqlpackage.md)
* Product: **sql**
* Technology: **tools-other**
* GitHub Login: @pensivebrian
* Microsoft Alias: **broneill**

**Comment by WilliamAntonRohm** [comment]
@pokorourk -- thank you for your question.  Please consider these resources:
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server) 

You are welcome to add this issue here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
