### ISSUE TITLE
Explain why cast and convert don't support alias types

### ISSUE THREAD

**Issue by IanKemp** [MicrosoftDocs/sql-docs#4917]
In the description for the arguments, `data_type` states:

> Alias data types cannot be used.

Why is this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f56efc1-e90f-68dd-cb02-2f2ba21373fd
* Version Independent ID: aa110136-4520-ed90-97fe-1fdedd1863ad
* Content: [CAST and CONVERT (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/cast-and-convert-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/functions/cast-and-convert-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/cast-and-convert-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by WilliamAntonRohm** [comment]
@IanKemp -- Ian, thank you for your feedback. 

@pmasl -- Pedro, please look into this issue.

**Comment by pmasl** [comment]
Please provide an example of what you mean (alias type, CLR type, etc). UDTs are supported. See https://docs.microsoft.com/en-us/sql/t-sql/functions/cast-and-convert-transact-sql?view=sql-server-ver15#implicit-conversions for details of which conversions are possible.

**Comment by IanKemp** [comment]
> Please provide an example of what you mean (alias type, CLR type, etc). UDTs are supported. See https://docs.microsoft.com/en-us/sql/t-sql/functions/cast-and-convert-transact-sql?view=sql-server-ver15#implicit-conversions for details of which conversions are possible.

Yes, I am talking about alias types. I have updated the title to reflect this.

```sql
create type [dbo].[Test] from nvarchar(800);

select cast('foo' as [dbo].[Test]);
```

yields:

```
Type dbo.Test is not a defined system type.
```

I don't understand why this can't work. Wouldn't it be as simple as looking up the underlying system type and using that?

It cannot be that alias types can be defined as `NOT NULL`, since some system types are defined as such and the conversion still works. For example `sysname`:

```sql
select cast(null as sysname); -- no error
```

**Comment by rothja** [comment]
@IanKemp Thanks for the question. I think based on your example that you have shown that the documentation is correct in saying this does not work. I'm not sure why there is this restriction in the product (and @pmasl is welcome to jump in and offer any thoughts on this from a design perspective). However, if you would like to suggest that this behavior is changed, a good place to do this is in our [SQL Server Feedback forum](https://feedback.azure.com/forums/908035-sql-server). I'm sorry that you are unable to use the alias types in these statements. Because there is no documentation correction we can do here, I am going to close out this issue. Please let me know if you have any other questions. Thank you!
