### ISSUE TITLE
Identity is not incremental in Synapse

### ISSUE THREAD

**Issue by Robert-Kostecki** [MicrosoftDocs/sql-docs#4935]
This bit of documentation does not seem to be correct for Synapse: "Is the incremental value that is added to the identity value of the previous row that was loaded."

The values generated for identity(1,1) are not incremental. The code to reproduce is:

```
drop table t1;
go

create table t1 (id int identity(1,1), date_ datetime2 );
go

declare @date datetime2, @i int = 10

while @i > 0 
	begin 
		set @date = getdate()
		insert into t1 (date_) values (@date)
		set @i=@i-1
	end
go

select * from t1 order by date_;
```

The id values ordered by date_ were 16, 36, 52, 43, 6, 33, 57, 11, 34, 10

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33014f93-e2e9-f0e7-804b-e50493a32627
* Version Independent ID: 38498f73-63c2-4557-bf4b-c20923b45656
* Content: [IDENTITY (Property) (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-table-transact-sql-identity-property?view=sql-server-ver15)
* Content Source: [docs/t-sql/statements/create-table-transact-sql-identity-property.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/create-table-transact-sql-identity-property.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Thanks for letting us know, @Robert-Kostecki!

@julieMSFT - Do you mind checking on this issue? Thanks!

#assign:julieMSFT

**Comment by julieMSFT** [comment]
@Robert-Kostecki Hello Robert and thank you for contacting Microsoft. I have recreated what you are seeing. I am researching this and will get back to you soon.

**Comment by julieMSFT** [comment]
@Robert-Kostecki Thank you again for you question. You are correct and this statement has restrictions listed in the remarks section. The identity value is not guaranteed to provide consecutive values. This is more pronounced in Synapse SQL pool as stated [here](https://docs.microsoft.com/en-us/azure/synapse-analytics/sql-data-warehouse/sql-data-warehouse-tables-identity#allocation-of-values). The IDENTITY property doesn't guarantee the order in which the surrogate values are allocated, which reflects the behavior of SQL Server and Azure SQL Database. However, in Synapse SQL pool, the absence of a guarantee is more pronounced. The IDENTITY property is designed to scale out across all the distributions in the Synapse SQL pool without affecting load performance. Therefore, the implementation of IDENTITY is oriented toward achieving these goals. 
If you cannot use identity values because of these restrictions, create a separate table holding a current value and manage access to the table and number assignment with your application.
I am still reviewing how we can make the document more clear.

**Comment by Robert-Kostecki** [comment]
Thanks for the information and reply Julie. I've raise issues with the wording of the other article you provided above - I think it is incorrect. I'm pretty sure IDENTITY in SQL Sever and Azure SQL DB is indeed ordered. (https://github.com/MicrosoftDocs/azure-docs/issues/56794). 

I'd be keen to understand the IDENTITY generation mechanism and if it can provide the uniqueness in Synapse. 

As for your suggestion, this a Data Warehouse in Synapse loaded via Azure Data Factory. Implementing my own sequencing mechanism via table in Synapse would likely kill the load performance as this is MPP. On that note it would be good to have a Synapse performance optimised sequences.

All the best!

**Comment by julieMSFT** [comment]
Hi Robert, Thank you for your patience. I have updated IDENTITY (Property) (Transact-SQL) - SQL Server with a note that the identity values generated for Azure Synapse are not incremental due to the distributed nature of the warehouse architecture. You will see this change in the document tomorrow. thankyou for helping to improve the quality of Microsoft Docs! I will proceed with closing this issue. The @notification mechanism continues to work even after an item is closed, in case further communication is needed. We hope to hear from you again.

**Comment by julieMSFT** [comment]
#https://github.com/MicrosoftDocs/sql-docs-pr/pull/16097

**Comment by julieMSFT** [comment]
#please-close
