### ISSUE TITLE
The nvarchar data type not working for me.

### ISSUE THREAD

**Issue by MoisesGonzaga** [MicrosoftDocs/sql-docs#4941]
Hello there, I was following the example to use the Decrypt function. But I was getting the result in a different language or at least with symbols and not with letters. I had to change the nvarchar data type to a varchar data type and it worked perfectly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc9c48d3-9c69-6897-c547-d0e7b4a76126
* Version Independent ID: cb28d268-9d47-c049-229f-23591dc69c1b
* Content: [DECRYPTBYPASSPHRASE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/decryptbypassphrase-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/functions/decryptbypassphrase-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/decryptbypassphrase-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@MoisesGonzaga -- Moises, thank you for your feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@MoisesGonzaga -- Moises, I was able to reproduce that behavior and have updated the article.

@VanMSFT -- Van, please review [private PR 15555](https://github.com/MicrosoftDocs/sql-docs-pr/pull/15555).

**Comment by srutzky** [comment]
@MoisesGonzaga You didn't include the code you were testing with. That would be extremely helpful as it wouldn't require guesswork on anyone else's part to figure out exactly what you are doing.

I suspect that you encrypted a string in the form of `'string'` instead of `N'string'`. Without the `N` it is `VARCHAR`. With the `N` prefix it is `NVARCHAR`. This needs to be clarified on both this page and the page for [ENCRYPTBYPASSPHRASE](https://docs.microsoft.com/en-us/sql/t-sql/functions/encryptbypassphrase-transact-sql). I had planned on submitting a PR to fix both pages at the same time. I see now that @WilliamAntonRohm has already made some update. Sorry I didn't respond sooner (been busy). Should I still submit my updates?

**Comment by VanMSFT** [comment]
@srutzky - Hi Solomon! Thanks for the clarification. I believe the string being encrypted/decrypted in the example is this:

```sql
USE AdventureWorks2012;  
-- Get the pass phrase from the user.  
DECLARE @PassphraseEnteredByUser nvarchar(128);  
SET @PassphraseEnteredByUser   
= 'A little learning is a dangerous thing!';  
  
-- Decrypt the encrypted record.  
SELECT CardNumber, CardNumber_EncryptedbyPassphrase   
    AS 'Encrypted card number', CONVERT(nvarchar,  
    DecryptByPassphrase(@PassphraseEnteredByUser, CardNumber_EncryptedbyPassphrase, 1   
    , CONVERT(varbinary, CreditCardID)))  
    AS 'Decrypted card number' FROM Sales.CreditCard   
    WHERE CreditCardID = '3681';  
GO
```

That's probably why @WilliamAntonRohm can reproduce the issue. I'll approve his PR, which the changes should take place tomorrow morning.

Please go ahead and submit your PR after tomorrow if you wish. We appreciate your assistance!

**Comment by WilliamAntonRohm** [comment]
@srutzky -- Solomon, my update should be live in a few hours, after which you are most welcome to touch it up.
