### ISSUE TITLE
Full text behavior

### ISSUE THREAD

**Issue by phaselden** [MicrosoftDocs/sql-docs#4952]
The link to "Behavior Changes to Full-Text Search." goes to a page which does not discuss the changes in 2019 (or 2017 or 2014).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf05483b-cafa-542e-9c44-0f6f6ae19fb4
* Version Independent ID: 4eb0cc19-79cd-69db-de13-bb367941751a
* Content: [Change the Word Breaker Used for US English and UK English - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/search/change-the-word-breaker-used-for-us-english-and-uk-english?view=sqlallproducts-allversions)
* Content Source: [docs/relational-databases/search/change-the-word-breaker-used-for-us-english-and-uk-english.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/search/change-the-word-breaker-used-for-us-english-and-uk-english.md)
* Product: **sql**
* Technology: **search**
* GitHub Login: @pmasl
* Microsoft Alias: **pelopes**

**Comment by WilliamAntonRohm** [comment]
@phaselden -- Phil, thank you for your feedback.

@pmasl -- Pedro, please look into this issue.

**Comment by scorellis** [comment]
This is still an issue @WilliamAntonRohm and @pmasl - we are upgrading to SQL Server 2019 and I cannot find any info that details the behavior change except for [https://docs.microsoft.com/en-us/sql/relational-databases/search/change-the-word-breaker-used-for-us-english-and-uk-english?view=sql-server-ver15](url) this link on this page, which doesn't go to any content about behavior changes.

**Comment by cawrites** [comment]
@scorellis I understand that this issue is several months old. Our content is regularly updated and I hope it can now address the concerns of the original request. On the same content page, you are referring to there are several options of updated contact that discuss the versions of SQL Server you are referring to. Once you arrive on the page https://docs.microsoft.com/sql/relational-databases/search/get-started-with-full-text-search?view=sql-server-ver15 you can toggle to a different version of SQL Server through the table of contents. There are several content pages on the page you initially were referring to. Thank you for contacting Microsoft.

**Comment by pmasl** [comment]
@WilliamAntonRohm actually the supposed section “Behavior Changes to Full-Text Search” isn’t in the 2016 page too. The page is incorrect, I'll stage a fix. But the changes last occurred in SQL 2012, not 2016. In 2016 RTM we accidently shipped new word breakers, but in SP1 we reverted to the 2012 word breakers. 

@scorellis so for the immediate answer, see the changes in https://docs.microsoft.com/en-us/previous-versions/sql/2014/database-engine/behavior-changes-to-full-text-search?view=sql-server-2014#behavior-changes-in-full-text-search-in--1

**Comment by WilliamAntonRohm** [comment]
@pmasl -- thank you for that information.
