### ISSUE TITLE
@freq_subday_type is marked as INT but does not accept INT

### ISSUE THREAD

**Issue by ssubramanian84** [MicrosoftDocs/sql-docs#4995]
When using this SP to add a job schedule to be Daily and **every minute,** I supply the @freq_subday_type parameter. The document says that it is an INT but the value table specifies a hexadecimal value of 0x4 which converts to 4 (decimal). 

I am trying to call this through powershell but keep getting the following error message.

What should I be doing here?

```
Invoke-Sqlcmd : The schedule for this job is invalid (reason: The specified '@freq_subday_interval' is invalid.). 
 Msg 14278, Level 16, State 1, Procedure sp_verify_schedule, Line 214.
At C:\sql\ps_ls_add_job_schedule.ps1:32 char:1
+ Invoke-Sqlcmd -Query "EXEC msdb.dbo.sp_add_jobschedule
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Invoke-Sqlcmd], SqlPowerShellSqlExecutionException
    + FullyQualifiedErrorId : SqlError,Microsoft.SqlServer.Management.PowerShell.GetScriptCommand
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d5339c9-a5eb-98e1-5f77-41b72d994a5e
* Version Independent ID: 485f803f-e5ed-fbee-f987-2dd898bb2554
* Content: [sp_add_jobschedule (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-add-jobschedule-transact-sql?view=sql-server-ver15)
* Content Source: [docs/relational-databases/system-stored-procedures/sp-add-jobschedule-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-stored-procedures/sp-add-jobschedule-transact-sql.md)
* Product: **sql**
* Technology: **system-objects**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by WilliamAntonRohm** [comment]
@ssubramanian84 -- thank you for your feedback and question.  The error message is regarding freq_subday_interval rather than freq_subday_type.  The document says:
> [ @freq_subday_interval = ] frequency_subday_interval Number of frequency_subday_type periods to occur between each execution of the job. frequency_subday_interval is int, with a default of 0.

Please also consider these resources:
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server) 

You're welcome to file this as a bug here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

cc @CarlRabeler for awareness
