### ISSUE TITLE
document how to "reload the driver"

### ISSUE THREAD

**Issue by dadamssg** [MicrosoftDocs/sql-docs#5001]
In the [Linux and macOS](https://docs.microsoft.com/en-us/sql/connect/php/connection-pooling-microsoft-drivers-for-php-for-sql-server?view=sql-server-ver15#linux-and-macos) section it says:

> The driver should be reloaded for the changes to take effect.

What does that mean? Which driver exactly? How do you reload it?

If i'm using php-fpm, does that just mean restarting the php-fpm? Or does that mean restarting ODBC somehow? If so, how?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 307839fa-683f-3d29-ff9e-c746249e6263
* Version Independent ID: 9f26e212-27ca-40fd-ae21-f3bcce6c9b3b
* Content: [Connection Pooling (Microsoft Drivers for PHP for SQL Server) - SQL Server](https://docs.microsoft.com/en-us/sql/connect/php/connection-pooling-microsoft-drivers-for-php-for-sql-server?view=sql-server-ver15)
* Content Source: [docs/connect/php/connection-pooling-microsoft-drivers-for-php-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/php/connection-pooling-microsoft-drivers-for-php-for-sql-server.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by David-Engel** [comment]
@dadamssg The ODBC driver. Since the application loads the PHP driver (which loads the ODBC driver), unless the application has specifically implemented a way to unload and reload the PHP driver (which would then unload the ODBC driver), this generally means restarting the application. In your case, that sounds like restarting php-fpm.

Regards,
David

**Comment by dadamssg** [comment]
@David-Engel thank you for the quick reply!

Is there a way to check that the changes have taken affect? Some way to read these settings in php? or from the command line?

**Comment by David-Engel** [comment]
@dadamssg I don't think there is a way to check it from PHP since it's the underlying behavior of the ODBC driver. The easiest way is probably to watch active connections in your database. Pooled connections will not disconnect immediately while non-pooled ones will. Otherwise, you can enable [Tracing with the ODBC Driver on Linux](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/data-access-tracing-with-the-odbc-driver-on-linux?view=sql-server-ver15) and try to decipher the logs (which I'm not even sure would make it obvious).

**Comment by dadamssg** [comment]
@David-Engel ok, that makes sense. thank you.

**Comment by David-Engel** [comment]
#please-close

I assume that answers all your questions. Feel free to reopen if not.
