### ISSUE TITLE
Security scenario

### ISSUE THREAD

**Issue by awilbert** [MicrosoftDocs/sql-docs#5007]
I'm having trouble seeing how the security scenario presented on this page would actually work. In order to run "GRANT CONTROL SERVER TO JohnDoe;" the security context would first need to be set to the master database. However, you can't include a USE statement to switch contexts inside of a trigger. It seems like this trigger wouldn't actually elevate JohnDoe's permissions, it would fail with an error whenever the sysadmin inadvertently fires it.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6c6196a-41af-9c74-36ef-fcb6a4d28c27
* Version Independent ID: 72127529-08f8-5305-35d6-7ccd012a5862
* Content: [Manage Trigger Security - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/triggers/manage-trigger-security?view=sql-server-ver15)
* Content Source: [docs/relational-databases/triggers/manage-trigger-security.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/triggers/manage-trigger-security.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by srutzky** [comment]
@awilbert : True, the current code on this page will generate an error for anyone executing it _unless_ the trigger is on a table in the `master` DB. However, that does seem impractical as it is (or at least should be) rare for anyone to be creating a user table in `master`.

However, regarding not being able to change context via `USE` in a trigger: that _is_ possible, as long as it's done in dynamic SQL. If the example used on this page were updated to use the following variation (merely wrapped in an `EXEC()`), then it would work from any database:

```sql
EXEC(N'
  USE [master];
  GRANT CONTROL SERVER TO [JohnDoe];
');
```

However numero 2: the "corrected" example code _could_ still be impractical as it will fail for anyone without the required permissions. Hence, it could be fairly obvious and easy to detect if someone who is only `dbo` in this database executes it and it errors, because not only is there a visible error message, but the operation itself will fail and the `ALTER` will not succeed. This `EXEC()` would need to be wrapped in a `TRY...CATCH` construct in order to go undetected and thus be a realistic exploit:

```sql
BEGIN TRY
  EXEC(N'
    USE [master];
    GRANT CONTROL SERVER TO [JohnDoe];
');
END TRY
BEGIN CATCH
  DECLARE @DoNothing INT;
END CATCH;
```

I suppose I can add a PR to make this update (the example code block on this page looks wrong anyway, like it's not even a code block).


Take care,
Solomon...
https://SqlQuantumLift.com/
https://SqlQuantumLeap.com/
https://SQLsharp.com/

**Comment by WilliamAntonRohm** [comment]
@awilbert -- Adam, thank you for your feedback.

@srutzky -- Solomon, we appreciate your contributions here.

@rothja -- Jason, please look into this issue.

**Comment by rothja** [comment]
@awilbert Thanks for posing the question, and thanks @srutzky for proposing a change to the article along with a lot of other fixes. Very helpful. It's in review.

**Comment by rothja** [comment]
@awilbert We have merged in Solomon's suggested changes to address the doc problems, and the issue closed automatically. Thanks, again to you both!

**Comment by srutzky** [comment]
@rothja (and @awilbert ): You're welcome 😺 .
