### ISSUE TITLE
Consistent use of semicolon in sql-docs

### ISSUE THREAD

**Issue by rcaldwell-hiusa** [MicrosoftDocs/sql-docs#5065]
This page shows semicolon use as a statement end indicator in the syntax block at the head, but then the examples below are inconsistent with the syntax block. This is confusing. And there is no mention of any requirement for explicit statement end indicator (;) use anywhere in the text. 

Which is it — required for IF ELSE statements, or not? Or only required in certain statement configuration contexts? That are also not documented here?

If implicit statement end determination from context is truly deprecated in T-SQL, why not conform the examples to reflect that reality? And make it clear in the text. I know it's a pain to edit this stuff, but that pain is only multiplied by every reader like me who scratches his head and thinks, "is this why my code is not working?"

Let's clear up this confusion. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5c4b818-4333-c6f1-3a13-bdcd32afccbb
* Version Independent ID: eb3f02b0-214d-eff7-cc6e-f2bee0607ae5
* Content: [IF...ELSE (Transact-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/if-else-transact-sql?view=sql-server-ver15)
* Content Source: [docs/t-sql/language-elements/if-else-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/language-elements/if-else-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by WilliamAntonRohm** [comment]
@rcaldwell-hiusa -- thank you for your feedback.

@rothja -- please look into this issue.

**Comment by rothja** [comment]
@rcaldwell-hiusa Thank you for the feedback, and apologies for the confusion on the use of the semi-colon. You're right that we should be more clear. In our [Transact-SQL syntax conventions](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/transact-sql-syntax-conventions-transact-sql?view=sql-server-ver15) we say the following:

```
Transact-SQL statement terminator. Although the semicolon isn't required for most statements in this version of SQL Server, it will be required in a future version.
```

But I believe that has been in the documentation for some time and the semicolon still is not required in all contexts. So I think what has happened is that some examples and syntax blocks have started using the semicolon based on this information, but it hasn't been consistent because most statements still work without a semicolon. Obviously, as a reader, this is confusing, and I apologize for the inconsistency.

For a community discussion of the exact confusion you describe, see the Stack Overflow post here: [https://stackoverflow.com/questions/8004322/when-should-i-not-use-a-semicolon](https://stackoverflow.com/questions/8004322/when-should-i-not-use-a-semicolon). Note from that thread in the comments that there are some cases where T-SQL requires semicolons, but those cases are usually clearly called out in the docs. I think the assumption is that if the semicolon is important, the article should talk about it. If it does not, then you can use or not use it for statement termination.

Let me consult with others internally and see if there is a best-practice we should be aligning to. My guess is that although this was intended to be enforced, it never was due to the massive amount of T-SQL that does not use semicolons. And anything that is not enforced becomes very hard to consistently apply or recommend.

**Comment by rcaldwell-hiusa** [comment]
Jason –

I appreciate your timely response to my comment, and the information you provided.

I’d like to give you a bit more information in response to one point you made:  “there are some cases where T-SQL requires semicolons, but those cases are usually clearly called out in the docs”.

This is actually what prompted me to give feedback. I found in testing that the attached T-SQL query would enter an infinite loop at line 384 when there was no semicolon present after END. Curious, I consulted the documentation page we’re discussing. I did not find any reference(s) to circumstances where a BEGIN-END statement block contained within an IF-ELSE needed a terminating semi-colon, so I thought that my code was correct. The docs only say “To define a statement block, use the control-of-flow keywords BEGIN and END.” and none of the examples cover the use of a statement block or use terminating semicolons. So I was puzzled.

Given that the code (starting at line 384) was acting as if it was caught in the looping WHILE block beginning at line 313 when the line 317 IF Boolean expression evaluated to FALSE, instead of acting as if it was the END statement that was intended as the terminus of the BEGIN statement at line 318, my instinct was to add semicolons to all of my END statements. It looked to me like the logic designed to infer statement end points from code context was misinterpreting the intent of my code.

That fixed my problem. It wasn’t clearly called out in the docs. And that prompted my feedback.

My meta-comment to all this is, leaving something in place that “kinda works most of the time” creates a trap for people who then depend on that crutch. While I was pulling my hair out debugging, the last thing I thought of was the missing semicolon.

From now on, I’ll be placing semicolons at the ends of all my statements. Thanks again for your time spent on my behalf.


All the best - Rich

Rich Caldwell
Business Intelligence Developer
Digital Technology Team
Hostelling International USA
8401 Colesville Road | Suite 600
Silver Spring, MD  20910
TEL: +1.240.650.2119
richard.caldwell@hiusa.org

**Comment by rothja** [comment]
@rcaldwell-hiusa Thanks for the additional context, and you're right that this not being explained in the docs is clearly a problem. I'm going to look to update this one example. As for the overall solution or best practice in our docs on this, I'm consulting with others internally to see what can/should be done. I'm sorry for your frustration and lost time! 

BTW, when you reply to a git issue email, it adds the entire email to the issue on GitHub. This included your contact information. I'm going to edit your comment to remove that with the assumption that you don't want this picked up randomly by anyone on the internet. Thanks.

**Comment by rothja** [comment]
@rcaldwell-hiusa After consulting internally, we are all agreed that it is a best practice to use semicolons as a delimiter (and newer functionality does use that) but there are no immediate plans to enforce it. With that said, we should fix T-SQL examples to use the semicolon at the end of statements when we go back to old articles. In this case, it doesn't even work without the semicolon, so it is even more important. I'll see if I can fix this one article and encourage all of our Microsoft writers to pay attention to this. Sorry, again, for the confusion!

**Comment by rcaldwell-hiusa** [comment]
Many thanks and best wishes. 

Rich
