### ISSUE TITLE
DateTime comparisons broken for fn_xe_telemetry_blob_target_read_file

### ISSUE THREAD

**Issue by NTDLS** [MicrosoftDocs/sql-docs#5069]
Using SQL Azure: DateTime2 comparison on `timestamp_utc` for the `fn_xe_telemetry_blob_target_read_file` function does not seem to function correctly.

If I query for data in the current century, nothing is returned - I only get data when I ask for data in the distant past.

![image](https://user-images.githubusercontent.com/11428567/86178422-52143a80-baf6-11ea-81d1-77c7a1e3bcd0.png)

**Comment by WilliamAntonRohm** [comment]
@NTDLS -- Josh, thank you for your feedback.  Are you reading a particular docs.microsoft.com article?  Please consider these resources:
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server) 

You are welcome to add this issue here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)

**Comment by NTDLS** [comment]
I will submit instead to the feedback page. Thanks.

**Comment by NTDLS** [comment]
https://feedback.azure.com/forums/908035-sql-server/suggestions/40795192-using-sql-azure-datetime2-comparison-on-timestamp

**Comment by WilliamAntonRohm** [comment]
@NTDLS -- thank you.
