### ISSUE TITLE
MSmerge_conflict_publication_article does not contain the ModifiedDate column on 11.0.7493.4

### ISSUE THREAD

**Issue by willibrandon** [MicrosoftDocs/sql-docs#5212]
The Merge Replication system table MSmerge_conflict_publication_article does not contain the **ModifiedDate** column on version 11.0.7493.4. According to the documentation, this column's description is "The time when the conflict occurred". I'm not sure if this is a document bug, software bug, or if the design has changed at some point. Either way, I'm seeing an inconsistency between the documentation and the software. I've attached a screenshot for review.

![MSmerge_conflict_publication_article](https://user-images.githubusercontent.com/5017479/87964538-3fdf4980-ca6f-11ea-8506-2247d769022a.PNG)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a786ae93-a9b5-153a-a27e-63112cc327c2
* Version Independent ID: 2a83653f-eb4f-bc91-2a0d-62fe325376f2
* Content: [MSmerge_conflict_publication_article (T-SQL) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/system-tables/msmerge-conflict-publication-article-transact-sql?view=sql-server-ver15)
* Content Source: [docs/relational-databases/system-tables/msmerge-conflict-publication-article-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/system-tables/msmerge-conflict-publication-article-transact-sql.md)
* Product: **sql**
* Technology: **replication**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by WilliamAntonRohm** [comment]
@willibrandon -- Brandon, thank you for bringing this to our attention.

@CarlRabeler -- Carl, please look into this issue.

**Comment by CarlRabeler** [comment]
#reassign: @MashaMSFT

**Comment by MashaMSFT** [comment]
Hi @willibrandon , thanks for contacting Microsoft! We'll need to investigate this further. Can you please open a ticket with Microsoft support, or submit your findings to [aka.ms/sqlfeedback](https://aka.ms/sqlfeedback)? This goes directly to the product group, and is the intended audience for this issue. 

We appreciate you reaching out! Since this forum is intended for doc bugs, and we're not yet certain this is a doc bug, we'll close out the Git Issue for the time being. However, please feel free to comment should you need anything further from the SQL Docs team. 

Thanks again for bringing this to our attention and I hope you have a wonderful rest of your day!
Masha from the SQL Docs team
