### ISSUE TITLE
Columns without a Name page need correction

### ISSUE THREAD

**Issue by ykhabins** [MicrosoftDocs/sql-docs#5281]
The code sample needs correction.
The documentation has a small typo in the the namespace declaration.

It should be http://... instead of http**s**://...

```
USE AdventureWorks2012;  
GO

-- fixed namespace
SELECT ProductModelID,  
       Name,  
       Instructions.query('declare namespace MI="http://schemas.microsoft.com/sqlserver/2004/07/adventure-works/ProductModelManuInstructions";  
                /MI:root/MI:Location   
              ')   
FROM Production.ProductModel  
WHERE ProductModelID=7  
FOR XML PATH;  
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a88a7156-6a29-a433-ead6-c55aefc41e58
* Version Independent ID: e20f7df5-5324-217a-39f4-0f1fbceccb4b
* Content: [Columns without a Name - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/xml/columns-without-a-name?view=sql-server-ver15)
* Content Source: [docs/relational-databases/xml/columns-without-a-name.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/xml/columns-without-a-name.md)
* Product: **sql**
* Technology: **xml**
* GitHub Login: @MightyPen
* Microsoft Alias: **genemi**

**Comment by MightyPen** [comment]
@ykhabins Thank you for bringing this error (Issue #5281) to our attention here at Microsoft.
The fix for this is building as I write these words (in private sister repo, PR 16398). The fix should be live on our Docs website before Tue Aug/04.

- `https://github.com/MicrosoftDocs/sql-docs-pr/pull/16398`

If you find any more errors, please let us know again. &nbsp; :-) 

I am now finishing / Closing this successful Issue.

MightyPen
