### ISSUE TITLE
What are the changes Microsoft has made  to SQL Server 2017 CU19 (February 2020) that is preventing the Plug-in for SQL Server (third-party )to protect SQL Server 2017 CU19?

### ISSUE THREAD

**Issue by MuthuramanD** [MicrosoftDocs/sql-docs#5379]
What are the changes Microsoft has made to SQL Server 2017 CU19 (February 2020) that is preventing the Plug-in for SQL Server (third-party )to protect SQL Server 2017 CU19 on Linux Installed Environment?

Environment :

The  version of OS:  **x86_64 x86_64 x86_64 GNU/Linux**
Sqlservr
Version 14.0.3335.7
Build ID 8437c4d7ea0c407855fdf5e6d199b4f6a2b62c761c0cbbd72773d53348711e00
Build Type release
Git Version 5c7ee6c

PAL
Build ID bf2ab14a753fb4a15f020c1adcaf4b2476f6487bd265370ca52ee6941a70906d
Build Type release
Git Version 95da3ad

Packages
system.certificates 6.2.9200.25,unset,
secforwarderxplat 14.0.5005.60667
sqlservr 14.0.3335.7
system 6.2.9200.25,unset,
sqlagent 14.0.3335.7

**ODBC Error Number:42000, MsgState=1, Severity=16, Servername= ProcName=, LineNumber=1, Message:[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]BACKUP DATABASE** 

2. **Most common Error is  VDI OpenDevice fails**

**Also, note Testing shows any version CU18 or prior doesnt report the said error**
An impacted link which needs to amend  if the issue is confirmed (find the link) -> 

[https://support.microsoft.com/en-in/help/4535007/cumulative-update-19-for-sql-server-2017](https://support.microsoft.com/en-in/help/4535007/cumulative-update-19-for-sql-server-2017)

Is the same issue as reported under SQL Server Version 2019 ( https://support.microsoft.com/en-us/help/4563007/fix-vdi-backup-fails-with-error-after-applying-sql-server-2019-cu2-cu3)

**Comment by MuthuramanD** [comment]
@stevestein @WilliamAntonRohm please have a look

**Comment by WilliamAntonRohm** [comment]
@MuthuramanD -- Muthuraman, thank you for your thorough feedback.  Please consider these resources:
- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/en-us/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server) 

@stevestein, @MikeRayMSFT, @VanMSFT, @CarlRabeler -- gentlemen, please assign this issue.

**Comment by MuthuramanD** [comment]
Thanks, @WilliamAntonRohm 

I tried the resources except for the reported one below I couldn't see any discussion on the related subject, thanks for looking into this, will wait for your update on this.

Is the same issue as reported under SQL Server Version 2019 ( https://support.microsoft.com/en-us/help/4563007/fix-vdi-backup-fails-with-error-after-applying-sql-server-2019-cu2-cu3)

**Comment by MuthuramanD** [comment]
Any updates ?

**Comment by rothja** [comment]
@MuthuramanD Thank you for reaching out to us with this reported problem. I will pass this along to our product team that handles SQL Server on Linux to keep them informed of customer reports. If they know why this might be happening, I will definitely reply on this thread to let you know.

This problem at this point might be a product bug or a support issue. In this case, the git issue on documentation is not yet the right place for it, because we are not sure where the problem lies to document it. I would recommend entering this in our product feedback page: [SQL Server Feedback](https://feedback.azure.com/forums/908035-sql-server). You could also choose to open this up as a support case for our engineers to dive into. I'm sorry I can't help more in this issue, but I hope you can find some answers at one of those two places. I am closing the issue, but please respond with any comments and questions, and I will see your responses and try to get back to you as soon as possible. Thank you!

**Comment by rothja** [comment]
#reassign:rothja I'm assigning this to myself so I can help address any followup questions. Thank you!

**Comment by MuthuramanD** [comment]
@rothja thanks much for the response , will be interested in this space for your response (Y)

**Comment by rothja** [comment]
@MuthuramanD Hello! I got some feedback from the product team that they believe this problem has been fixed in CU22 [https://support.microsoft.com/en-us/help/4577467/kb4577467-cumulative-update-22-for-sql-server-2017](https://support.microsoft.com/en-us/help/4577467/kb4577467-cumulative-update-22-for-sql-server-2017). I hope you find this to be the case? Thank you for reaching out!
