### ISSUE TITLE
Misleading/missing information regarding TCP and IPAll

### ISSUE THREAD

**Issue by cambob1** [MicrosoftDocs/sql-docs#5386]
The following paragraph does not appear to be entirely correct.
See bold below:
`For the SQL Server port, use SQL Server Configuration Manager to check the SQL Server network configuration for the TCP/IP protocol for the instance you want to unblock.` **You must enable the TCP port for IPALL if you want to connect to SQL Server using TCP after installation.** `By default, SQL Browser listens on UDP port 1434.`

This does not sound logical. For my own instance, I have, in the protocol tab, Enabled = Yes, and Listen All = No (which disables IPAll in the IP Addresses tab).  In the IP Addresses tab I have made sure to have one of the IP slots set to Active for the main interface and specified the default TCP Port (1433).  Obviously I can connect just fine.

Also, is the default TCP port of 1433 an omission?

Thanks
Bob

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30225758-8196-5216-31fc-8380133d577e
* Version Independent ID: 4718f672-8fd8-9956-45dc-4329bfcc0b7b
* Content: [Before Installing Failover Clustering - SQL Server Always On](https://docs.microsoft.com/en-us/sql/sql-server/failover-clusters/install/before-installing-failover-clustering?view=sql-server-ver15)
* Content Source: [docs/sql-server/failover-clusters/install/before-installing-failover-clustering.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/failover-clusters/install/before-installing-failover-clustering.md)
* Product: **sql**
* Technology: **high-availability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@cambob1 -- thank you for your feedback.  Please consider these resources:
- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/en-us/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server) 

@MashaMSFT -- please look into this issue.

**Comment by MashaMSFT** [comment]
#assign: kfarlee

**Comment by kfarlee** [comment]
The text could be clearer.  It's referring to the SQL Server Configuration Manager, which specifies which IP adresses the instance will listen on, out of the multiple addresses registered for the host.  Most people configure SQL to listen on all of them, and use the firewall to restrict which connections from the outside can make it through.  You can, if you wish, select specific addresses to listen on, and ignore any connection requests coming in via other addresses.
In the Windows Firewall configuration, you can choose specific ports to listen on (1433, 1434, any AG Listener ports, etc.) and/or you can specify that the firewall should allow connections on any port that this specific binary opens up.

**Comment by MashaMSFT** [comment]
Hi @cambob1 , thanks for reaching out! In order to connect to a SQL Server that is running on a non-default port (something other than 1433), you have two options - 
1. specify the port number in your connection string 
2. leverage the SQL Browser Service
   
The SQL Browser service is not a clustered service, so it won't be listening on the same IP address as a failover clustered instance of SQL Server. This is why the firewall must be opened for IP_ALL, even though the SQL Server is only listening on one IP. If you do not require the Browser Service because your FCI is listening on port 1433 or because your connection strings all supply the port number, you don't need to worry about this recommendation.

However, having said that, I agree that the bullet point can benefit from some clarity so I've processed a change to rewrite it and it will be live later this week, or possibly next.

I hope that helps! I'll close out this Git Issue in the meantime but please feel free to comment should you need anything further.

Thanks again for reaching out and I hope you have a wonderful rest of your day!
Masha from the SQL Docs team
#assign:bluefooted
