### ISSUE TITLE
SQL 2019 SSRS Not Found on SQL Server Features Discovery Report

### ISSUE THREAD

**Issue by LindaLF** [MicrosoftDocs/sql-docs#5409]
I have a SQL 2019 SSRS (Reporting Services) installation, and ran the SQL Installer > Tools > **Installed SQL Server features discovery report**.  I was amazed to find that my SSRS installation did not appear!  I expect that when I run this report, that it will search out all of the components for SQL Server that are installed, but report what versions of these products are available.  This is the behavior of prior versions of SSRS installations,

What changed that SSRS is not longer considered part of a SQL Server feature, that it would NOT be included in this report?  It is bad enough that it doesn't show up in the **SQL 2019 Configuration Manager** as an SSRS service - although it is clearly running as a Windows service (i.e. _SQL Server Reporting Services_).

**Comment by WilliamAntonRohm** [comment]
@LindaLF -- thank you for your feedback.  Are you following a docs.microsoft.com article?  Meanwhile, please consider these resources:
- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/en-us/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server) 

You're welcome to add this issue here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)
