### ISSUE TITLE
Article is no longer accurate

### ISSUE THREAD

**Issue by Pxtl** [MicrosoftDocs/sql-docs#5417]
[Enter feedback here]

As of SQL 2017, adding an assembly requires signing and managing signatures, SAFE is no longer allowed apparently.

The complexity of this process is *extreme* and so a clear guide on how to do so would be expected here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a21d0936-6216-2251-6bdc-b1d7746c7039
* Version Independent ID: cd19b31a-b56d-6958-a404-a5a04db7b4bc
* Content: [Deploying CLR Database Objects - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/clr-integration/deploying-clr-database-objects?view=sql-server-ver15)
* Content Source: [docs/relational-databases/clr-integration/deploying-clr-database-objects.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/clr-integration/deploying-clr-database-objects.md)
* Product: **sql**
* Technology: **clr**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by WilliamAntonRohm** [comment]
@Pxtl -- Martin, thank you for your feedback.  Please consider these resources:
- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/en-us/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server) 

@rothja -- Jason, please look into this issue.

**Comment by rothja** [comment]
@Pxtl Martin, thanks for the feedback and sorry for any confusion. Let me confirm your suggestion here with the product team and get back to you with my recommendations here. Thanks!

**Comment by srutzky** [comment]
@Pxtl (and @WilliamAntonRohm and @rothja ): `SAFE` assemblies are still allowed, they just need to be signed. That is the main difference, though it is not a trivial one. The `CLR strict security` server configuration option added in SQL Server 2017 definitely over-complicates things, especially because there's no easy way to create an asymmetric key based on the public key of the strong-name key used to sign/strongly-name the assembly (please vote on this suggestion to hopefully make that happen: [Allow Asymmetric Key to be created from binary hex bytes string just like CREATE CERTIFICATE](https://feedback.azure.com/forums/908035-sql-server/suggestions/32896978-allow-asymmetric-key-to-be-created-from-binary-hex) ).

I have written a series of articles showing how to create publishable T-SQL scripts with no external DLL dependencies:

* [SQLCLR vs. SQL Server 2017, Part 2: “CLR strict security” – Solution 1](https://sqlquantumleap.com/2017/08/09/sqlclr-vs-sql-server-2017-part-2-clr-strict-security-solution-1/)
* [SQLCLR vs. SQL Server 2017, Part 3: “CLR strict security” – Solution 2](https://sqlquantumleap.com/2017/08/16/sqlclr-vs-sql-server-2017-part-3-clr-strict-security-solution-2/)

And, for unsigned, `SAFE` assemblies that already exist (typically in DBs upgraded/restored from prior versions), here is how to sign them in-place:
* [SQLCLR vs. SQL Server 2017, Part 4: “Trusted Assemblies” – The Disappointment (Msg 10314)](https://sqlquantumleap.com/2017/08/28/sqlclr-vs-sql-server-2017-part-4-trusted-assemblies-the-disappointment/)


The documentation, in several places, states that all assemblies are now considered `UNSAFE`, and this is clearly incorrect ( [SQLCLR vs SQL Server 2017, Part 9: Does PERMISSION_SET Still Matter, or is Everything Now UNSAFE?](https://sqlquantumleap.com/2018/10/30/sqlclr-vs-sql-server-2017-part-9-does-permission_set-still-matter-or-is-everything-now-unsafe/) ). However, the situation is slightly more complicated and requires a little more investigation before I can submit a fix for that wording (am working on it, though).


Related info: [Signing an Assembly = Signing with Strong Name Key #2052](https://github.com/MicrosoftDocs/sql-docs/issues/2052#issuecomment-491104047)

Take care,
Solomon...
https://SqlQuantumLift.com/
https://SqlQuantumLeap.com/
https://SQLsharp.com/

**Comment by rothja** [comment]
@srutzky Solomon, thanks for the in depth analysis and pointer to your articles. Your expertise in this area continues to pay off for improvements to our docs that you suggest. Please do consider submitting a suggestion for us to get this messaging right, and I will approve it with the product team. @Pxtl Martin, can you take a look at the explanation and references that Solomon provides and see if that makes sense. Obviously, we still need to make the docs more clear, so apologies on the confusion.

**Comment by rothja** [comment]
@Pxtl Martin, since Solomon provided some guidance and plans an update in the near future, I am going to close out this git issue. But please let me know if you have any more questions or concerns. Thank you!
