### ISSUE TITLE
A connection was successfully established with the server, but then an error occurred during the login process.

### ISSUE THREAD

**Issue by selmankeskin** [MicrosoftDocs/sql-docs#5463]
Hi;

I use Microsoft SQL Server 2019 (RTM-CU7) (KB4570012) - 15.0.4063.15 (X64)   Aug 15 2020 10:48:11   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Linux (Ubuntu 18.04.5 LTS) <X64>

I develop with  .net core 3.1.8 web api using Kestrel : 

problem/error message:   "A connection was successfully established with the server, but then an error occurred during the login process. (provider: TCP Provider, error: 0 - Success)

What can be the problem? 

**my config file:**

`[sqlagent]
enabled = false

[EULA]
accepteula = Y

[network]
tlsciphers= AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:!ECDHE-RSA-AES128-GCM-SHA256:!ECDHE-RSA-AES256-GCM-SHA384:!ECDHE-ECDSA-AES256-GCM-SHA384:!ECDHE-ECDSA-AES128-GCM-SHA256:!ECDHE-ECDSA-AES256-SHA384:!ECDHE-ECDSA-AES128-SHA256:!ECDHE-ECDSA-AES256-SHA:!ECDHE-ECDSA-AES128-SHA:!ECDHE-RSA-AES256-SHA384:!ECDHE-RSA-AES128-SHA256:!ECDHE-RSA-AES256-SHA:!ECDHE-RSA-AES128-SHA:!DHE-RSA-AES256-GCM-SHA384:!DHE-RSA-AES128-GCM-SHA256:!DHE-RSA-AES256-SHA:!DHE-RSA-AES128-SHA:!DHE-DSS-AES256-SHA256:!DHE-DSS-AES128-SHA256:!DHE-DSS-AES256-SHA:!DHE-DSS-AES128-SHA:!DHE-DSS-DES-CBC3-SHA:!NULL-SHA256:!NULL-SHA`

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e57953d0-a43f-3e01-a792-bcf4fe241579
* Version Independent ID: 1c4a4f72-bc1d-1a03-fbe6-df21c0149d03
* Content: [Release notes for SQL Server 2019 on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-release-notes-2019?view=sql-server-ver15#cu7)
* Content Source: [docs/linux/sql-server-linux-release-notes-2019.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-release-notes-2019.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Thanks for your comment, @selmankeskin. This looks like a support request rather than documentation feedback. Unfortunately, we are unable to assist with your connection issues in this forum.

Please visit one of the following pages depending on your product or service.

[On Prem users](https://support.microsoft.com/en-us/supportforbusiness/productselection)
[SQL on Azure](https://ms.portal.azure.com/#home)
[Services Hub (Unified/premier customers)](https://serviceshub.microsoft.com/support/create/097a91e3-084a-46a8-b385-d5b07ffedcfe)
