### ISSUE TITLE
Image is not readable in dark mode

### ISSUE THREAD

**Issue by mobinseven** [MicrosoftDocs/sql-docs#5466]
The histogram diagram is not dark mode friendly:
![image](https://user-images.githubusercontent.com/5783101/93563391-08bce400-f99d-11ea-842e-e7116ab50d65.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82e5062c-ab80-eace-5cbb-8868c17014c3
* Version Independent ID: 7bcb85b7-ee68-ae1c-5385-91f6db828c06
* Content: [Statistics - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/statistics/statistics?view=sql-server-ver15)
* Content Source: [docs/relational-databases/statistics/statistics.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/statistics/statistics.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @julieMSFT
* Microsoft Alias: **jrasnick**

**Comment by WilliamAntonRohm** [comment]
@mobinseven -- Mobin, thank you for your feedback.

@julieMSFT -- Julie, please look into this image.

**Comment by julieMSFT** [comment]
@mobinseven Hi and thank you for contacting Microsoft. I am working on resolving the issue with this image.

**Comment by julieMSFT** [comment]
#https://github.com/MicrosoftDocs/sql-docs-pr/pull/17113

**Comment by julieMSFT** [comment]
@mobinseven Hi Mobin, I have updated the image so that it is clearly visible in dark mode. You will see the update in the next few days. Thank you for your contribution to Microsoft Docs. I will go ahead and close this issue. The @notification mechanism continues to work even after an item is closed, in case further communication is needed. We hope to hear from you again.

**Comment by julieMSFT** [comment]
#please-close
