### ISSUE TITLE
Clarification required on CHECK constraint behavior with NULL values

### ISSUE THREAD

**Issue by anttikes** [MicrosoftDocs/sql-docs#5506]
On this page, there's a sentence:

_CHECK constraints reject values that evaluate to FALSE. Because null values evaluate to UNKNOWN, their presence in expressions may override a constraint. For example, suppose you place a constraint on an int column MyColumn specifying that MyColumn can contain only the value 10 (MyColumn=10). If you insert the value NULL into MyColumn, the Database Engine inserts NULL and does not return an error._

This given example is a bit odd as the column is defined as 'int', not as a 'nullable int' so in theory it should not even be possible to add a row with a NULL value into the table. Maybe this is just a typo in the text that could be fixed by specifying that the int column supports NULL values in the first place?

Furthermore, a case which involves NULL values should be clarified a bit. For example, is it true that any expression -- if it involves a column that contains a NULL value -- will always return UNKNOWN? An expression such as (MyNullableColumn > 10 AND MyNullableColumn < 20). Does this evaluate to (UNKNOWN AND UNKNOWN), and eventually to just (UNKNOWN) if MyNullableColumn contains a NULL?

This comment applies to all versions of the document (i.e. all SQL Server versions).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3709c36d-5f11-41b8-0926-e4549bd2b78e
* Version Independent ID: cff4179f-03c9-bba8-b87b-a4e13fb3e919
* Content: [Unique Constraints and Check Constraints - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tables/unique-constraints-and-check-constraints?view=sql-server-ver15)
* Content Source: [docs/relational-databases/tables/unique-constraints-and-check-constraints.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/unique-constraints-and-check-constraints.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by stevestein** [comment]
@anttikes - thanks for the feedback.

The example works as is, and is showing that unexpected results can be encountered in some situations with null values and empty tables.

When the table is created it allows nulls by default, which can be verified by modifying the 2nd code block and inserting a null value in the INSERT statement.

CREATE TABLE CheckTbl (col1 int, col2 int);  
GO  
CREATE FUNCTION CheckFnctn()  
RETURNS int  
AS   
BEGIN  
   DECLARE @retval int  
   SELECT @retval = COUNT(*) FROM CheckTbl  
   RETURN @retval  
END;  
GO  
ALTER TABLE CheckTbl  
ADD CONSTRAINT chkRowCount CHECK (dbo.CheckFnctn() >= 1 );  
GO

INSERT INTO CheckTbl VALUES (**Null**, 10);  
GO  
DELETE CheckTbl WHERE col1 = 10;

Thanks

#please-close

**Comment by stevestein** [comment]
@anttikes - to clarify, this first paragraph is not referring to the code snippet, and is referring to possible unexpected results with null values:

CHECK constraints reject values that evaluate to FALSE. Because null values evaluate to UNKNOWN, their presence in expressions may override a constraint. For example, suppose you place a constraint on an int column MyColumn specifying that MyColumn can contain only the value 10 (MyColumn=10). If you insert the value NULL into MyColumn, the Database Engine inserts NULL and does not return an error.

----
This next paragraph is referring to the code snippet below it, and is referring to new tables that don't have any rows when they're created, so unexpected results may be encountered (due to it being a new table with no rows)

A CHECK constraint returns TRUE when the condition it is checking is not FALSE for any row in the table. A CHECK constraint works at the row level. If a table that has just been created does not have any rows, any CHECK constraint on this table is considered valid. This situation can produce unexpected results, as in the following example.

The second code snippet, is showing that _CHECK constraints are not validated during DELETE statements._ 

Hope that helps.

**Comment by anttikes** [comment]
Thank you @stevestein for the comments and clarification.
