### ISSUE TITLE
Different recommended values for vm.max_map_count

### ISSUE THREAD

**Issue by alkolome** [MicrosoftDocs/sql-docs#5507]
The page references two different values for  vm.max_map_count:

1) 262144 (here: For this reason, change the vm.max_map_count value to 262144 for a SQL Server deployment)
2) 1600000 (here: vm.max_map_count=1600000)

It's a bit confusing. Could you clarify which one you recommend to use.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc91cc25-7d13-a975-76ee-6d97bdcf9416
* Version Independent ID: ae8d2f7e-0c69-1269-a438-d6d36594dd27
* Content: [Performance best practices for SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-performance-best-practices?view=sql-server-ver15)
* Content Source: [docs/linux/sql-server-linux-performance-best-practices.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-performance-best-practices.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @tejasaks
* Microsoft Alias: **tejasaks**

**Comment by WilliamAntonRohm** [comment]
@alkolome -- thank you for your feedback.  Please consider these resources:
- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/en-us/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server) 

@tejasaks -- please look into this issue.

**Comment by tejasaks** [comment]
@tfevriermsft and @amvin87 as FYI. 

Let me try to clarify this a bit. The vm.max_map_count value defaults at 64K for Linux installs. For sheer stability and reliability reasons, at a minimum it should be set to 256K. In some Microsoft internal performance testing the number 1600000 has been used for high end configuration. Since higher vm.max_map_count parameter can require some additional memory usage per process, the number shouldn't be set to highest possible value by default. Please use testing and discretion to configure this value based on your own configuration and requirements.

**Comment by VanMSFT** [comment]
Updated the doc for clarity.
