### ISSUE TITLE
unable to download SSMS

### ISSUE THREAD

**Issue by onna1** [MicrosoftDocs/sql-docs#5527]
[I've tried to download SSMS numerous times with various browsers.
I've disabled firewall.
Nothing works. 
I always get the notification: 'C:\path\TEMP\xxxxxx.exe could not be saved, because the source file could not
be read. Try again later or contact the server administrator.' ]
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45daf2f0-bb22-338f-062b-a9fabcb71a92
* Version Independent ID: b6e909fe-15d9-c1cf-c018-d4f6f36ff31f
* Content: [Download SQL Server Management Studio (SSMS) - SQL Server Management Studio (SSMS)](https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017)
* Content Source: [docs/ssms/download-sql-server-management-studio-ssms.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/download-sql-server-management-studio-ssms.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @dzsquared
* Microsoft Alias: **drskwier**

**Comment by WilliamAntonRohm** [comment]
@onna1 -- thank you for your feedback.  This repo is solely for documentation issues, and it appears your issue is regarding product behavior.  Please consider these resources:
- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/en-us/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server) 

cc @dzsquared for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
