### ISSUE TITLE
sqlcmd exits with 0 on error

### ISSUE THREAD

**Issue by jonfen** [MicrosoftDocs/sql-docs#5602]
I am not sure where to report this, I recognize sql-docs is not likely the right place, please point me in the correct direction.

**sqlcmd** exits with a `0` instead of `1` (or something else) when errors happen such as `RESTORE DATABASE is terminating abnormally.` which makes bash scripting problematic.  Since the script doesn't know to exit when something fails and marches on.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39bb4ba1-ae62-07a3-f79a-138f14cf2f10
* Version Independent ID: beaa4e7d-e771-cc96-0e59-34d9b1d5e8cc
* Content: [Install SQL Server command-line tools on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup-tools?view=sql-server-ver15)
* Content Source: [docs/linux/sql-server-linux-setup-tools.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-setup-tools.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@jonfen -- Jonathon, thank you for your feedback.  Please consider these resources for scripting assistance:
- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/en-us/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server) 

This is probably the best place to raise your concern, as it involves product code rather than documentation:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)

cc @VanMSFT for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
