### ISSUE TITLE
Is Truncate Table a DDL or a DML command?

### ISSUE THREAD

**Issue by marcosdimitrio** [MicrosoftDocs/sql-docs#5615]
The [Transact-SQL statements](https://docs.microsoft.com/en-us/sql/t-sql/statements/statements?view=sql-server-ver15) (source [here](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/statements.md)) says that `TRUNCATE TABLE` is part of the Data Manipulation Language (DML), and not of Data Definition Language (DDL).

In the [Truncate Table reference page](https://docs.microsoft.com/en-us/sql/t-sql/statements/truncate-table-transact-sql?view=sql-server-ver15) we see that one of the permissions that enables this command is `db_ddladmin`, which leads me to understand that it is actually a DDL command, and not a DML command.

This is also what most people believe, example [here](https://social.msdn.microsoft.com/Forums/en-US/726e9ac7-f8fa-46ad-8768-eac6a51090f5/why-truncate-in-ddl?forum=sqlexpress) stated by a few MVPs, and also [here](https://www.mssqltips.com/sqlservertip/4248/differences-between-delete-and-truncate-in-sql-server/).

If this is correct, my suggestion is to move "TRUNCATE TABLE" from the DML list to the DDL list in the [docs](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/statements/statements.md).

**Comment by WilliamAntonRohm** [comment]
@marcosdimitrio -- Marcos, thank you for your well-researched question.

@markingmyname -- Mark, please look into this issue.

**Comment by cawrites** [comment]
@marcosdimitrio thank you for contacting Microsoft regarding this issue. I am in agreement with the definition you provided for the choice DDL over DML for the following reason.

TRUNCATE TABLE is classified as a DDL statement rather than a DML statement. It differs from DELETE in the following ways:

Truncate operations drop and re-create the table, which is much faster than deleting rows one by one, particularly for large tables.

Truncate operations cause an implicit commit, and so cannot be rolled back. 

Truncation operations cannot be performed if the session holds an active table lock.

We will make the appropriate adjustment that categorizes this properly as a DDL.

**Comment by cawrites** [comment]
@marcosdimitrio the suggestion will be reflected in the next update of the content. We appreciate you identifying this issue. Please feel free to contact us again if you have any questions.

**Comment by cawrites** [comment]
#sign-off

**Comment by cawrites** [comment]
#reassign:cawrites
