### ISSUE TITLE
Linked Server between connects between two server when port 1433 is in public

### ISSUE THREAD

**Issue by SarveshPandey** [MicrosoftDocs/sql-docs#5638]
HI,

I have two SQL Servers in two different vnet. I setup a Vnet peering between them so we can connect there SQL Server. Now, i had a requirement to setup linked service between to query there database. I got to know, linked service need port 1433 (in firewall and advance setting) but it should be in public not in private or domain. And whenever I select other then public, linked server doesn't work.
Linked server only work in public, can this be a problem in terms of security? 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7695b6a-e69f-7ee8-6493-d6276d5ea167
* Version Independent ID: 71d085f6-643b-4223-54d7-be831a9b0bf3
* Content: [Linked Servers (Database Engine) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/linked-servers/linked-servers-database-engine?view=sql-server-ver15)
* Content Source: [docs/relational-databases/linked-servers/linked-servers-database-engine.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/linked-servers/linked-servers-database-engine.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @stevestein
* Microsoft Alias: **sstein**

**Comment by WilliamAntonRohm** [comment]
@SarveshPandey -- thank you for your question.  Please consider these resources:
- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/en-us/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server) 

This repo is solely for documentation issues, and this appears to be product-related instead.  You are welcome to add your issue here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)

cc @stevestein for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
