### ISSUE TITLE
Blank localhost/testsql.php file

### ISSUE THREAD

**Issue by RickPerez10** [MicrosoftDocs/sql-docs#5639]
Issue is I'm having a constant blank php file when I look at it from the browser.

Environment:
Ubuntu 20 LTS

Followed and installed curl, pdo_sqlsrv, sqlsrv, php, loaded drivers at php.ini, verified with phpinfo.php, verified php works with a simple php hello world file, verified php installed with php -v, yet when i run the sample script thats at the bottom of the page, and after i input the sql info, i always come up with a blank page. Please assist thank you.

![image](https://user-images.githubusercontent.com/73620521/97509260-04da9500-193f-11eb-97bf-3f8432c9c6a2.png)

**Comment by WilliamAntonRohm** [comment]
@RickPerez10 -- thank you for your feedback.  This repo is solely for documentation issues, and this appears to be an issue with the product.  Are you following a particular docs.microsoft.com article?  Meanwhile, please consider these resources:
- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/en-us/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server)

**Comment by RickPerez10** [comment]
Hi @WilliamAntonRohm 
Thank you for getting back to me. Yes, I was following the Microsoft documentation at https://docs.microsoft.com/en-us/sql/connect/php/installation-tutorial-linux-mac?view=sql-server-ver15#installing-the-drivers-on-ubuntu-1604-1804-and-2004
If you see the bottom text script, that one comes up empty after all the configuration has been done.

**Comment by WilliamAntonRohm** [comment]
@RickPerez10 -- thank you for clarifying.

@David-Engel -- please look into this potential documentation issue.

**Comment by David-Engel** [comment]
@RickPerez10 If you view the page source for the output of testsql.php, what do you see?

**Comment by RickPerez10** [comment]
![image](https://user-images.githubusercontent.com/73620521/98023132-578ed380-1dbb-11eb-8af3-1b6ba47786d1.png)
Hi @David-Engel , this is what I see.

I added the requested code but unfortunetly I keep getting a blank page, as well as when I look at page code it's also blank.

**Comment by RickPerez10** [comment]
![image](https://user-images.githubusercontent.com/73620521/98026653-4d230880-1dc0-11eb-98bc-128dfb0eef7f.png)
Here's the code as I have it currently

**Comment by David-Engel** [comment]
@RickPerez10

I updated the doc page to include the error handling and tested it for failure scenarios including exceptions and connectivity errors. I don't know why your scenario produces a blank page. Since this forum is not for product support, I suggest [posting an issue on the msphpsql GitHub repo](https://github.com/microsoft/msphpsql/issues/new) where they can help you troubleshoot your environment. Feel free to link to this issue there so that they can see the details you have already provided.

I'm closing this doc issue, but if you find that the test script on the doc page could be improved based on your experience, please follow-up and @ me on this issue and I will update the docs to include any improvements you identify there.

Thanks,
David

#please-close

**Comment by yitam** [comment]
@David-Engel the user made a typo in the php script. We may add a short paragraph about troubleshooting by examining the [Apache log files](https://linuxize.com/post/apache-log-files/#location-of-the-log-files)
