### ISSUE TITLE
ActiveDirectoryMsi Environment Configuration

### ISSUE THREAD

**Issue by pboueri-kalderos** [MicrosoftDocs/sql-docs#5684]
Hello! 

For the authentication option: ActiveDirectoryMsi for the ms sql odbc driver I would like to know how to set environment variables locally such that I can authenticate w/ an MSI. To do so i have set the following env variables:
- AZURE_TENANT_ID
- AZURE_CLIENT_SECRET
- AZURE_CLIENT_ID

Currently when I attempt do to so it spits out an error:
```
message: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Error 12029 opening URL http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fdatabase.windows.net%2F
```

I believe this is because I am unable to set the AUTHORITY host. What environment variable needs to be set to configure this correctly? Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45a0e668-ba07-ce4f-2b40-b386650dcd99
* Version Independent ID: 82d61083-b354-c135-5d3f-230555d13d57
* Content: [Using Azure Active Directory with the ODBC Driver - SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/using-azure-active-directory?view=sql-server-ver15#feedback)
* Content Source: [docs/connect/odbc/using-azure-active-directory.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/using-azure-active-directory.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by David-Engel** [comment]
@pboueri-kalderos Thanks for submitting feedback.

You do not need to set any environment variables to use Azure Active Directory Managed Identity (MSI) authentication through the Microsoft ODBC Driver for SQL Server. As long as you are running in the context of an Azure VM, App Service, or Function that supports Managed Identity, you simply specify Authentication=ActiveDirectoryMsi and, optionally for a user-assigned managed identity, UID=myObjectId.

Tenant is implied by the context of the Azure resource. And Client ID and secret do not come into play. Authority is obtained by the driver from the Azure SQL endpoint that is being connected to.

Regards,
David

**Comment by pboueri-kalderos** [comment]
Thanks @David-Engel, We're trying to connect, without the need for MFA which is required by our AD accounts and in a platform independent manner (i.e. mac too), to SQL Server by using AD. 

I have explored this option: https://stackoverflow.com/a/61071850 which does use those credentials to pull in the token. Unfortunately the python ODBC client i am using (turbodbc https://turbodbc.readthedocs.io/en/latest/) does not expose a way to prepend attributes to the connection. 

I was hoping that there are just some hidden configuration options for this SQL SERVER ODBC Driver authentication method, should we use them, would resolve this issue. It sounds like the Authority being obtained from the sql endpoint isn't working locally, because of some differences in how a VM/AppService/Function is configured. Is this something that _could_ be replicated locally?

**Comment by David-Engel** [comment]
> Is this something that could be replicated locally?

@pboueri-kalderos If I understand correctly, it sounds like you are trying to connect to a local SQL Server instance (not Azure SQL). If that's the case, you will have to use database authentication to get around your AD-imposed MFA requirement. SQL Server does not currently support token-based authentication. Other non-Azure AD auth options, like integrated Windows authentication aren't cross-platform, so that wouldn't work for you.

If you really are trying to connect to an Azure SQL database (just from a local client), you can try using Azure AD Integrated authentication. That does work cross-platform as of the latest version of the ODBC Driver 17 for SQL Server as long as you are able to set up a kerberos ticket on Linux/macOS clients. From your original post, it sounds like you are trying to use a service principal (basically an app registration) to authenticate and obtain a token yourself, then pass it to the ODBC driver. It sounds like it can be done through pyODBC, but not turbodbc.

One final tip: AAD Service Principal authentication was recently introduced in the .NET library Microsoft.Data.SqlClient:
https://github.com/dotnet/SqlClient/blob/master/release-notes/2.0/2.0.0.md#active-directory-service-principal
There is a good chance the same feature will be making its way into other drivers in coming releases. Most of the current drivers release twice a year and the ODBC driver's next release is in January.

Regards,
David

**Comment by pboueri-kalderos** [comment]
Thanks @David-Engel, I am indeed trying to connect to Azure SQL and do what you describe. I have seen the option about setting up kerberos, and think it is too heavy a dependency for our use case and not something we want to try to do. Thanks for the tip on using AAD Service Principal; I agree that would achieve what I am trying to do!

We can close this ticket. I believe I misunderstand how MSI works and will do some more reading. If there was a way to configure it as i described originally, I think it would be a more obvious path.

**Comment by David-Engel** [comment]
@pboueri-kalderos This might help, too: https://www.npmjs.com/package/msilocal
Looks like someone created a local MSI emulator if you are node.js savy.
