### ISSUE TITLE
the five steps of processing an SQL statement

### ISSUE THREAD

**Issue by ShamilKuramshin** [MicrosoftDocs/sql-docs#5697]
What are these 5 steps?

_it is wasteful if those statements are similar_
What impact exactly does this have on performance? 1, 5, 10% ?
Is this comparable to the performance loss caused by a non-optimal execution plan?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8606c200-380e-6d26-379d-3d948f4a03b2
* Version Independent ID: db53b0b2-7ee0-6f5b-fb76-48521d9c66e1
* Content: [Dynamic SQL - SQL Server](https://docs.microsoft.com/en-us/sql/odbc/reference/dynamic-sql?view=sql-server-ver15)
* Content Source: [docs/odbc/reference/dynamic-sql.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/odbc/reference/dynamic-sql.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by David-Engel** [comment]
@ShamilKuramshin Thanks for submitting feedback.

Performance measurement is not straightforward. There are too many variables to be able to say exactly how much impact that particular piece will have on any specific scenario. If you are executing similar statements that only differ by parameter values, you can optimize as the article suggests. But your application also needs to keep a handle for those prepared statements so that it can simply call execute again with different parameters. If the application closes the prepared statement after every execute, any possible performance gain would be wasted. In fact, it will be slightly slower because the statement prepare step is a separate call to the database. So instead of a single prepare and execute call, you would have introduced a new call for prepare and a subsequent call for execute for every statement. You generally want to minimize network trips to maintain performance. However, adding a prepare trip to the first execute can speed up subsequent executes if you are executing a significant number of the same query. You can see the trade-off/benefit. The benefit will increase the more times you will be performing the execute without having to prepare.

That said, I would tune database indexes and execution plans before making application changes. Execution plans, indexes, and database maintenance will usually have the biggest performance impact on queries in anything more than the simplest of databases. All this depends on your data and your queries. If you are coding a new application, keeping performance principles in mind is always a good thing, though.

https://docs.microsoft.com/en-us/sql/relational-databases/performance/monitor-and-tune-for-performance?view=sql-server-ver15

Regards,
David

**Comment by ShamilKuramshin** [comment]
@David-Engel 
Thank you for detailed answer to my second question!
It more important than the first, but what are those _five steps of processing an SQL statement_ you metioned in the article?

**Comment by David-Engel** [comment]
@ShamilKuramshin 

> It more important than the first, but what are those _five steps of processing an SQL statement_ you metioned in the article?

https://docs.microsoft.com/en-us/sql/odbc/reference/processing-a-sql-statement?view=sql-server-ver15

Regards,
David

**Comment by ShamilKuramshin** [comment]
@David-Engel 
Thanks!
Wouldn't it be better to add this link to the article?

**Comment by David-Engel** [comment]
> Wouldn't it be better to add this link to the article?

Done. The change should be reflected some time tomorrow.

**Comment by ShamilKuramshin** [comment]
Thanks!
Seems, we can close the issue
