### ISSUE TITLE
Entitizing

### ISSUE THREAD

**Issue by KentGorrell** [MicrosoftDocs/sql-docs#5782]
I'm guessing that the line
 characters &, <, and > are always entitized to &, <, and > respectively
should be displaying the entitized string but when posting the page they have been un-entitized

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a4b4c7d-dbc7-1e59-9dd5-8aaff8a3d061
* Version Independent ID: 47b3b896-bc7d-8b6e-9c28-60e7d2fd8491
* Content: [Define the Serialization of XML Data - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/xml/define-the-serialization-of-xml-data?view=sql-server-ver15)
* Content Source: [docs/relational-databases/xml/define-the-serialization-of-xml-data.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/xml/define-the-serialization-of-xml-data.md)
* Product: **sql**
* Technology: **xml**
* GitHub Login: @MightyPen
* Microsoft Alias: **genemi**

**Comment by MightyPen** [comment]
This Issue #5782 is now Fixed by private PR 18024.

- `https://github.com/MicrosoftDocs/sql-docs-pr/pull/18024`

The fix should be live in less than 48 hours.

@KentGorrell , thank you for bringing mistake to our attention.  The origin of the problem was in imperfection in a tool we used a few years ago to bulk translate from our old Content source into markdown.  This was a tricky case, and the tool was not literally perfect.

I am Closing this Issue 5784 now, as fixed.  We hope to hear from you again.

GeneMi (= MightyPen)
