### ISSUE TITLE
Not able to add second node. Facing error : Connection could not be established to secondary vm

### ISSUE THREAD

**Issue by Harshitjain188** [MicrosoftDocs/sql-docs#5828]
I am performing failover clustering for the basic availability group in SQL Server Standard 2019 but while adding a second node to the cluster..it gives a connection error.
I have tried pinging the secondary server in the primary server and it is working correctly. 
So is there any prerequisite or any step that I am not performing.

Plz help
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f9acc7d-6894-0b85-1e4c-07b5932545ee
* Version Independent ID: 31badaaf-00d5-191c-00cb-190260711cd7
* Content: [Add, remove nodes Failover Cluster Instance - SQL Server Always On](https://docs.microsoft.com/en-us/sql/sql-server/failover-clusters/install/add-or-remove-nodes-in-a-sql-server-failover-cluster-setup?view=sql-server-ver15)
* Content Source: [docs/sql-server/failover-clusters/install/add-or-remove-nodes-in-a-sql-server-failover-cluster-setup.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/failover-clusters/install/add-or-remove-nodes-in-a-sql-server-failover-cluster-setup.md)
* Product: **sql**
* Technology: **failover-cluster-instance**
* GitHub Login: @cawrites
* Microsoft Alias: **chadam**

**Comment by msebolt** [comment]
@Harshitjain188 Thank you for the feedback and we apologize for the issue.

Please include a reference to at which point in the documentation the issue occurs and an author can review the steps for possible inconsistencies.

Otherwise, for additional support, please start a thread in [Azure SQL answers](https://docs.microsoft.com/answers/topics/azure-sql-database.html) and [Azure SQL VM answers](https://docs.microsoft.com/answers/topics/azure-sql-virtual-machines.html), or view the [SQL Server support policy](https://support.microsoft.com/help/4047326/support-policy-for-microsoft-sql-server).

**Comment by WilliamAntonRohm** [comment]
@Harshitjain188 -- please also consider these resources:
- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/en-us/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server)

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
