### ISSUE TITLE
Complete disclosure on minimum version

### ISSUE THREAD

**Issue by brettshearer** [MicrosoftDocs/sql-docs#5861]
Hi,

Writing at the top of docs 'all supported versions' is ambiguous. And it actively hides when the feature was actually added.
This information is (and has always been) important when choosing to use features in SQL.

Can you PLEASE be specific as to the minimum version in SQL documentation. It is impossible to tell whether this feature is supported in SQL 2014 (with extended support) simply by reading the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c4aa661-a5fe-f0cf-3301-2c72a83b4cee
* Version Independent ID: b754be39-e648-0c6a-50a1-9cfdc2a1cd4a
* Content: [Selective XML Indexes (SXI) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/xml/selective-xml-indexes-sxi?view=sql-server-ver15)
* Content Source: [docs/relational-databases/xml/selective-xml-indexes-sxi.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/xml/selective-xml-indexes-sxi.md)
* Product: **sql**
* Technology: **xml**
* GitHub Login: @MightyPen
* Microsoft Alias: **genemi**

**Comment by MightyPen** [comment]
TO: @brettshearer 

Hello Brett, We are aware of the problem you describe, that too often our SQL Server documentation is vague about stating the first/earliest version of SQL Server had this or that feature. I do sympathize.
Several years ago, Microsoft made a major investment to improve its online documentation, by replacing the MSDN (and TechNet) website with the Docs website (`https://docs.microsoft.com/`). Docs soon added a formal Versioning system. For SQL Server, versions 2016 (@@version 13.*) is the earliest that is well supported by the new Docs & Versioning systems. But yes, versions SQL Server 2014 and earlier are sometimes murky in answering when the earliest supporting version was.

For the SQL XML 'SXI' feature emphasized in this Issue #5861 , the SXI feature was available at least as early as SQL Server 2008, and possibly even earlier. (I am unsure about earlier than 2008).
Here is a link to an external website from May 2009, that discusses XML SXI in SQL Server:

- `https://www.sqlskills.com/blogs/bobb/selective-xml-indexes-in-sql-server-first-try-it-works/`

Within the past 12 months, the SQL Docs Content team has revisited the APPLIES-TO info they place near the top inside each article. They made improvements, and some other changes to make ongoing maintenance more plausible and more accurate. Perfection may not be within reach, due to legacy factors beyond current or future control.

I will forward to the SQL Docs Content team your Issue for their awareness.

Going forward, the Versioning drop-down control (above the TOC) on each Docs article webpage for SQL Server should enable anyone to see what the oldest SQL version is that supported the given documented feature.

With all that info, I am now Closing this Issue #5861.
We hope to hear from you again.

LINKS

- `https://docs.microsoft.com/sql/`
- `https://docs.microsoft.com/previous-versions/sql/`

Thank you.

@MikeRayMSFT  .  @rothja 

. .

**Comment by MightyPen** [comment]
@brettshearer Brett, Oops, I meant to write "as early as SQL Server 2012" (not "2008").
I have edited the long comment to make this correction to 2012.
