### ISSUE TITLE
predicted vs actual are identical

### ISSUE THREAD

**Issue by wvaughn409** [MicrosoftDocs/sql-docs#5864]
***UPDATE*** just trying to verify if this is working-as-intended

Hello. I have followed this tutorial and at the last part, it shows the table values as being slightly different, i.e. the predicted values are off a little bit on most entries, but when I generate this I get identical values for RentalCount_Predicted and RentalCount_Actual. Am I doing something wrong, or is it predicting perfectly because I already completed this tutorial previously on my server, or has predictability improved substantially since this tutorial was created and more complex data is needed to demonstrate predictions being approximate, but not exact?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a32e6416-4a53-2d8b-ad22-f097b5b51e70
* Version Independent ID: cf34396e-0f4d-e284-8d40-1ae784f4b81a
* Content: [Python tutorial: Deploy model - SQL machine learning](https://docs.microsoft.com/en-us/sql/machine-learning/tutorials/python-ski-rental-linear-regression-deploy-model?view=sql-server-ver15)
* Content Source: [docs/machine-learning/tutorials/python-ski-rental-linear-regression-deploy-model.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/machine-learning/tutorials/python-ski-rental-linear-regression-deploy-model.md)
* Product: **sql**
* Technology: **machine-learning**
* GitHub Login: @dphansen
* Microsoft Alias: **davidph**

**Comment by wvaughn409** [comment]
from tutorial page...
![image](https://user-images.githubusercontent.com/9452611/103573830-c18f2c00-4e83-11eb-8497-d95e1fafa25b.png)

**Comment by wvaughn409** [comment]
my results...
![image](https://user-images.githubusercontent.com/9452611/103573858-ce138480-4e83-11eb-9ad3-346fc6d3d072.png)

**Comment by garyericson** [comment]
#in-process

**Comment by garyericson** [comment]
I'm asking a couple people if they have any ideas.

**Comment by garyericson** [comment]
@wvaughn409 - Sorry this has taken so long. I asked a number of people and wasn't able to get any more insight on this. Theoretically, if you use the same data as the tutorial, the same random number seed when separating out the test data, and the same code for training the model, then you should get the same results as shown in the tutorial regardless of how many times you run it. 

Since it doesn't look like I can be of any help here, my suggestion is to try the [SQL Q&A](https://docs.microsoft.com/en-us/answers/products/sql-server) forum to see if anyone there has any ideas.

#please-close
