### ISSUE TITLE
Lesson 0?

### ISSUE THREAD

**Issue by zopefiend** [MicrosoftDocs/sql-docs#5888]
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c35290b-b676-c52d-4204-ada11a3bb2af
* Version Independent ID: 87264101-997a-d17a-c96a-7a2cf15689e1
* Content: [Lesson 1: Connecting to the Database Engine - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/lesson-1-connecting-to-the-database-engine?view=sql-server-ver15)
* Content Source: [docs/relational-databases/lesson-1-connecting-to-the-database-engine.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/lesson-1-connecting-to-the-database-engine.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by zopefiend** [comment]
Is there a "Lesson 0", because I'm pretty sure you have skipped essential steps. I have installed the Dev version of Ms SQL Server, and this lesson assumes that it is running, or at least ready to run. That is a bad assumption. This is titled "Lesson 1", on connecting to the server. Is there something I need to do first, to make sure the server is ready to be connected (to)? Seriously, beginners don't need stumbling blocks strewn in their paths.

**Comment by WilliamAntonRohm** [comment]
@zopefiend -- thank you for your feedback.  Please consider these resources:
- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/en-us/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server) 

@MashaMSFT -- please look into this potential documentation issue.

**Comment by MashaMSFT** [comment]
Hi @zopefiend , thanks for your feedback! Once SQL Server is installed, there should not be any additional actions to take to connect to SQL Server other than to install the connectivity tool SQL Server Management Studio and open it. 

Once you have SQL Server and SQL Server Management Studio installed, you should be able to connect to the database engine. If SQL Server is failing to start, that would require troubleshooting to determine the root cause and would be outside the scope of a basic tutorial. Unfortunately, the tutorial does assume that your SQL Server engine has been installed correctly, and is running. 

As this is outside the scope of a documentation request, I'm going to close out this Git Issue but please feel free to comment should you need anything further.

Thanks!
Masha from the SQL Docs team
#please-close
