### ISSUE TITLE
Is there an RSA-key certificate requirement for enabling encrypted connections to the database engine?

### ISSUE THREAD

**Issue by bmcarnahan** [MicrosoftDocs/sql-docs#5934]
[Enter feedback here]
I created a SAN certificate with a CNG key and secured it so that the SQL (2016 running on Windows Console Server 2016) service account could access it (and verified that). When trying to configure the SQL Server Network Configuration, Protocols for <instance-name>, my certificate did not appear in the dropdown list on the Certificate tab. Must the certificate have an RSA key as opposed to a CNG key in order to work?

Thanks in advance for your assistance,
BarryC
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfa20275-e415-5531-3ef4-7472d859753b
* Version Independent ID: cc1346a6-9336-91ba-bcff-9fff79847c35
* Content: [Enable encrypted connections - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/enable-encrypted-connections-to-the-database-engine?view=sql-server-ver15)
* Content Source: [docs/database-engine/configure-windows/enable-encrypted-connections-to-the-database-engine.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/enable-encrypted-connections-to-the-database-engine.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hi @bmcarnahan - The only certificate requirements are listed in the [Certificate requirements](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/enable-encrypted-connections-to-the-database-engine?view=sql-server-ver15#certificate-requirements) section of the doc. The most common issue we see for the certificate not appearing in the SQL Server Network Configuration dropdown is not putting the correct CN for the machine.

![image](https://user-images.githubusercontent.com/40007119/105403526-b5be9c00-5bdd-11eb-86a4-8631c4a21f45.png)

![image](https://user-images.githubusercontent.com/40007119/105403632-d2f36a80-5bdd-11eb-92a9-e695a41567b9.png)

Since this is not a documentation issue, I will go ahead and close this. Please feel free to let us know if there are any concerns.
