### ISSUE TITLE
ODBC Support for Serverless

### ISSUE THREAD

**Issue by furlong46** [MicrosoftDocs/sql-docs#6017]
Does the latest version of the ODBC driver support Synapse Serverless?  I see Synapse Analytics at the top, but when I try to connect to Serverless with ODBC it errors out for me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a36a1d7f-a410-b597-0eb7-98212934fb0e
* Version Independent ID: e706f2bd-e051-fcff-7c3d-2ef3d9f80e87
* Content: [Download ODBC Driver for SQL Server - SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/download-odbc-driver-for-sql-server?view=sql-server-ver15)
* Content Source: [docs/connect/odbc/download-odbc-driver-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/odbc/download-odbc-driver-for-sql-server.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-daenge**

**Comment by WilliamAntonRohm** [comment]
@furlong46 -- Leo, thank you for your question.  Please consider these resources:
- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/en-us/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server) 

@David-Engel -- David, please look into this issue.

**Comment by David-Engel** [comment]
@furlong46

The Microsoft ODBC Driver for SQL Server does not differentiate between provisioned and serverless Synapse instances.

My understanding of the issue with Azure Synapse serverless is that since there is no constantly provisioned resource behind it, when the database is in a paused state, the first connection request to the database may fail or take longer than the default connection timeout period used by the ODBC driver (all drivers, really). So your application needs to be able to handle the initial error(s) and retry until the database is fully available. There is desire to add functionality to the driver to be able to recognize these errors itself and implement transparent retry logic for applications, but the driver does not currently have that capability.

Regards,
David

**Comment by furlong46** [comment]
The connection works just fine, but it fails when I try and link an actual table.

![image](https://user-images.githubusercontent.com/43998889/106054435-080a2c00-60ba-11eb-9ae8-b3910a382d5a.png)

![image](https://user-images.githubusercontent.com/43998889/106054469-15271b00-60ba-11eb-8e7e-b3a9671eccd6.png)

**Comment by David-Engel** [comment]
@furlong46 That's interesting. I think this is an issue with serverless not supporting that specific procedure used by the driver. See the note on this doc page for that procedure:
https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-special-columns-100-sql-data-warehouse?view=azure-sqldw-latest
![image](https://user-images.githubusercontent.com/26262303/106060139-85c53c00-60a8-11eb-9a14-ddb4413c62c2.png)

This would affect the ability of many drivers to support browse-mode type functionality in applications. You can probably still write and execute SQL manually, though. The "#15871" in the error message from the server indicates to me that the Synapse team probably is aware of the issue. You could raise an issue with Microsoft Support to be certain.

This does not appear to be an ODBC documentation issue.

**Comment by David-Engel** [comment]
Closing since this isn't an ODBC driver doc issue.

#please-close
