### ISSUE TITLE
None of the links in the customer Case studies are working. Please fix them

### ISSUE THREAD

**Issue by stunugun** [MicrosoftDocs/sql-docs#6197]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f91f89b-5196-0ea5-28fc-79cf59ab327e
* Version Independent ID: 0f4f2d0d-0913-8b47-15ab-7300dc2aa1a3
* Content: [Overview and Usage Scenarios - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/in-memory-oltp/overview-and-usage-scenarios?view=sql-server-ver15)
* Content Source: [docs/relational-databases/in-memory-oltp/overview-and-usage-scenarios.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/in-memory-oltp/overview-and-usage-scenarios.md)
* Product: **sql**
* Technology: **in-memory-oltp**
* GitHub Login: @Kevin-Farlee
* Microsoft Alias: **kfarlee**

**Comment by WilliamAntonRohm** [comment]
@stunugun -- thank you for your feedback.  Please consider these resources:
- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/en-us/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server)

@kfarlee -- please look into this issue.

**Comment by kfarlee** [comment]
The customer case studies are curated and managed by a different organization, and are continuously reviewed and periodically some specific stories are taken offline, sometimes because agreements with the customer being quoted have expired, other times because there are more timely stories to bring attention to.
I'm working on this issue with the docs team.  We will find and reconnect these stories if possible, or else we may rewrite the article without them.
