### ISSUE TITLE
Database Restore folder location

### ISSUE THREAD

**Issue by LindaLF** [MicrosoftDocs/sql-docs#6233]
This web site indicated that a backup could ***_ONLY_*** be used for a database restore if the file was located in a specific location ["_Before restoring the database to SQL Server, you must place the backup in a subdirectory of /var/opt/mssql._"].  However, other references say that we can have backups redirected to an installation standard location via the [**filelocation.defaultbackupdir**].  Are we not able to create subfolders of that redirected location and have the SQL instance recognize them when we request a database restore via TSQL?
**Does this mean that if we take a backup to this alternate location, and want to restore it, we must move it to a different folder first?**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8714d60-ce51-aa48-7619-cc95a8843a7f
* Version Independent ID: 9580d01a-4d40-bcca-2c05-72aa069370d0
* Content: [Migrate SQL Server database from Windows to Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-migrate-restore-database?view=sql-server-ver15&source=docs)
* Content Source: [docs/linux/sql-server-linux-migrate-restore-database.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-migrate-restore-database.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hey @amvin87 - Amit, can you please help answer this question? Thanks!

#assign:amvin87

**Comment by amvin87** [comment]
Sure @VanMSFT. Hi @LindaLF to you question
"Does this mean that if we take a backup to this alternate location, and want to restore it, we must move it to a different folder first?"
Ans: No, the document says that the backup must be placed under the /var/opt/mssql subdirectory because that subdirectory under the path /var/opt/mssql will be owned by the user mssql and group mssql. If you need to write and read from a location on the disk, that folder path and file should be accessible by user mssql and group mssql. This way from SQL Server you will be able to read and write from that path. If you do setup the filelocation.defaultbackupdir, then the next step you should do as documented is to ensure that mssql user and mssql group has access to the path. Let me know if that answers your question.

![image](https://user-images.githubusercontent.com/63835878/112907618-d1797d80-910b-11eb-85da-5382f0293428.png)

**Comment by amvin87** [comment]
Done, answered

Thanks,
Amit Khandelwal
Sr. Program Manager| Data Platform- SQL Server

**Comment by PRMerger13** [comment]
amvin87

-
You is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by LindaLF** [comment]
Perhaps you could update the documentation to state when and how other locations are available to be used?  Currently the statements are misleading if you say that alternate locations ***are*** able to be used (and how) instead of the URL currently stating "_you must_" use the stated folder.

**Comment by VanMSFT** [comment]
Hi @LindaLF - Thanks for the feedback.

@amvin87 - Thank you so much for the clarification! I think some more clarification in the doc would not hurt. I added a link to the details that you pointed out, and hopefully others will find it useful.
