### ISSUE TITLE
The Note on Static Filters

### ISSUE THREAD

**Issue by AtHalfPastTwo** [MicrosoftDocs/sql-docs#6274]
This note still leaves some questions: how small is reasonably small? 1 million? 10000? Depends on the hardware available?
All of the subscribers can support the full data load but the point of the filtering is to avoid unnecessary rows in the relevant subscribers. I'm not sure how to interpret the warning in the note.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2600e46b-2e5b-5649-1f2b-a56630ecb6fe
* Version Independent ID: 7f19f25c-f2c9-8924-4348-cc929e20a22a
* Content: [Parameterized Row Filters - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/replication/merge/parameterized-filters-parameterized-row-filters?view=sql-server-ver15)
* Content Source: [docs/relational-databases/replication/merge/parameterized-filters-parameterized-row-filters.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/replication/merge/parameterized-filters-parameterized-row-filters.md)
* Product: **sql**
* Technology: **replication**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by TimShererWithAquent** [comment]
@WilliamAntonRohm for awareness.

**Comment by MashaMSFT** [comment]
Hi @AtHalfPastTwo , thanks for contacting Microsoft! My apologies, I looked at the 2 notes and 3 important notes, but I am  not sure which note you're referring to, or what your question is. Would you mind clarifying what you're trying to understand?

Thanks!
Masha from the SQL Docs team

**Comment by MashaMSFT** [comment]
Hi @AtHalfPastTwo , it seems this issue came through for a different article than perhaps you intended? I believe the note in question is in the [filter published data](https://docs.microsoft.com/sql/relational-databases/replication/publish/filter-published-data) article. 

Yes, the overhead depends on the size of the data and the efficiency of the hardware. The greater the size of the data, and/or the slower the hardware, the greater the overhead will be when using row filters with transactional replication. You would need to evaluate the performance impact compared to the benefit and business need of using row filters based on your environment, and determine if row filters are suitable for your needs. 

I hope that helps and please let us know if you have any additional questions. I'll close out this Git Issue for the time being but please feel free to comment should you need anything further. 

Thanks and I hope you have a wonderful rest of your day!
Masha from the SQL Docs team

**Comment by AtHalfPastTwo** [comment]
Hallo Masha,

You are spot on: it is the article on filter published data.
I have seen several warnings that static filters will cause an overhead in resource usage and I wanted to know to what extent this was true.
Our hardware is reasonably up-to-date and the volume of data won’t be that great. We are expecting in the region of 100’000 new rows and maybe as many updates per year.
I have tried it out myself on a one-instance server and I noticed no difference between replication with static filters and without. I am trying it out now on a multi-server replication setup.

Thanks for your reply,
Sean Redmond.
