### ISSUE TITLE
please reconsider statement 'the default value of 5 is adequate for most systems'

### ISSUE THREAD

**Issue by ingebeumer** [MicrosoftDocs/sql-docs#6275]
Hi,
 
Please reconsider the statement 'the default value of 5 is adequate for most systems' in this doc. I think the majority of the SQL Server community agrees on this value not being adequate anymore for most modern systems. There are many blogposts out there discussing the matter and it would be nice if our documentation reflected some considerations on the value. For many other configuration options, we also have recommendations to not leave them at the default. 
 
With the default value of 5 many smaller queries that are executed in parallel experience more overhead of parallelism than they benefit from it. When lots of smaller queries go parallel you run out of threads sooner which lower concurrency on your system. In my customer conversations I always recommend starting with a value of 50 and test and monitor to find the optimum value for instances that have high (performance) requirements. That 50 is also not an exact value (other SME could advise a somewhat different number), but in my experience it's a good starting point for most OLTP workload to not go parallel and OLAP and reporting workload to go parallel. As said, test and monitor specific workloads in systems that need high optimization.  
 
If you like you could even include a little history on what it represented and why it was a proper default in the past but is not anymore, and why it used to equal seconds but does not anymore (doc does state the value is not a unit of time). 
 
Please review if the documentation is eligible for improvement. 
 
Thank you and regards,
Inge van der Zouw-Beumer

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b3387d8-a989-2905-4173-829ff4c722be
* Version Independent ID: 7b1db588-759f-2c16-0598-d358b66a478d
* Content: [Configure the cost threshold for parallelism Server Configuration Option - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/configure-the-cost-threshold-for-parallelism-server-configuration-option?view=sql-server-ver15)
* Content Source: [docs/database-engine/configure-windows/configure-the-cost-threshold-for-parallelism-server-configuration-option.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/configure-the-cost-threshold-for-parallelism-server-configuration-option.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by cawrites** [comment]
@ingebeumer thank you for contacting Microsoft. I understand your concern regarding the default value stated in the paragraph. Because SQL Server is a customizable database system, this is a value that can be adjusted according to customer needs. It is stated in the Recommendations section. "While the default value of 5 is adequate for most systems, a different value may be appropriate. Perform application testing with higher and lower values if needed to optimize application performance." You should test to determine what's best for your environment and adjust accordingly. It is also recommended that this be performed by an experienced DBA. Based on this information and your feedback we will remove the stated value in the initial paragraph, and leave the Recommendations section to be used for guidance.  This update will appear in the next content refresh. Thank you for contacting Microsoft.
