### ISSUE TITLE
PolyBase can't connect to any Hadoop instance if Knox is enabled

### ISSUE THREAD

**Issue by tesseract1919** [MicrosoftDocs/sql-docs#6304]
Are there plans to enable this feature? (Hadoop via Knox)
Alternately is there a plan to more seamlessly integrate with Cloudera in general.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 066808bd-cf93-7fa7-d84c-fb2da46558ab
* Version Independent ID: 415a5039-44e1-0654-10e2-ca4916732df3
* Content: [PolyBase features and limitations - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/polybase/polybase-versioned-feature-summary?view=sql-server-ver15)
* Content Source: [docs/relational-databases/polybase/polybase-versioned-feature-summary.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/polybase/polybase-versioned-feature-summary.md)
* Product: **sql**
* Technology: **polybase**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@tesseract1919 -- Jon, thank you for your question.  Your question appears to be product-related, rather than documentation-related.  Please add this issue here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)

Also, consider these resources:
- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/en-us/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server)


cc @MikeRayMSFT for awareness
