### ISSUE TITLE
sp_describe_undeclared_parameters cannot determine undeclared parameter in sqlxml

### ISSUE THREAD

**Issue by lsoft** [MicrosoftDocs/sql-docs#6451]
the following

```sql
     execute sp_describe_undeclared_parameters @tsql = N'
        
     select
         *
     from TestTable0
     where
         myxmlcolumn.exist(''/a[. = sql:variable("@a")]'') = 1
        
     '
```

fails with

`XQuery: Unable to resolve sql:variable('@a'). The variable must be declared as a scalar TSQL variable.`

I guess there is a little chance to have it fixed, so it's good to make the mark about this restriction in the MS doc page.

Thank you!

**Comment by WilliamAntonRohm** [comment]
@lsoft -- Авдеев, thank you for your feedback.  Are you referring to this article?
- [sp_describe_undeclared_parameters (Transact-SQL)](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-describe-undeclared-parameters-transact-sql)

You're welcome to add this issue here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)

@markingmyname -- Mark, please look into this issue.

**Comment by pmasl** [comment]
@markingmyname you can add that note in the Remarks section.

#reassign:markingmyname

**Comment by markingmyname** [comment]
Thank you, @lsoft, for bringing this to our attention.

Thank you, @pmasl, for the review.

Changes will be made to the remarks section later this week.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [SQL Server User Feedback](https://feedback.azure.com/forums/908035-sql-server) site.
