### ISSUE TITLE
SQLPackage for MacOS throws error when attempting to execute

### ISSUE THREAD

**Issue by shaunraj** [MicrosoftDocs/sql-docs#6453]
Performing the steps as per the documentation (https://docs.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage-download?view=sql-server-ver15):

```
$ mkdir sqlpackage
$ unzip ~/Downloads/sqlpackage-osx-<version string>.zip -d ~/sqlpackage 
$ echo 'export PATH="$PATH:~/sqlpackage"' >> ~/.bash_profile
$ source ~/.bash_profile
$ sqlpackage
```

The file doesn't appear to want to be executed:

`zsh: permission denied: sqlpackage`

This is because the sqlpackage executable does not have the executable permission applied to it by default. It would probably be a good idea to add this step in the documentation. Furthermore, the executable has to be authorized in the user's system's and preferences because this application isn't notarized.

**Comment by WilliamAntonRohm** [comment]
@shaunraj -- thank you for your feedback.

@dzsquared -- please look into this issue.

**Comment by dzsquared** [comment]
@shaunraj - to confirm, you are proposing that we add the `chmod +x` command to the instructions for installing on macOS?
We do include instructions for disabling Gatekeeper since the executable isn't notarized - were these commands sufficient in your scenario?
https://docs.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage-download?view=sql-server-ver15#get-sqlpackage-net-core-for-macos

**Comment by shaunraj** [comment]
@dzsquared Yup! I had to `chmod +x` the executable as it did not come with execute permissions upon unzipping. I didn't try to execute those commands. I instead did another workaround disabling the quarantine on the individual files. I really should have read the directions more closely :(.

**Comment by dzsquared** [comment]
Thank you for the feedback, the article has been updated!
#please-close
