### ISSUE TITLE
Add json files for Grafana Dashboards

### ISSUE THREAD

**Issue by jingli0118** [MicrosoftDocs/sql-docs#6460]
Hi,

Could you please also add the json files of the dashboards? 
I missed the Hosted Node Metrics and Pods and Containers Metrics and want to import it manually.

Could you please help with this?

Thank you very much

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 571a1a4a-600d-a5e9-d4bc-3b4efb7bf59f
* Version Independent ID: 8649b0e6-450a-5273-892c-b3998584c326
* Content: [Monitor cluster with Grafana Dashboard - SQL Server Big Data Clusters](https://docs.microsoft.com/en-us/sql/big-data-cluster/cluster-monitor-grafana?view=sql-server-ver15)
* Content Source: [docs/big-data-cluster/cluster-monitor-grafana.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/cluster-monitor-grafana.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @cloudmelon
* Microsoft Alias: **melqin**

**Comment by WilliamAntonRohm** [comment]
@jingli0118 -- thank you for your questions.  This repo is solely for documentation issues, and this issue seems more product-related.  Please consider these resources:
- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/en-us/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server)

You are welcome to add your suggestion here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)

cc @cloudmelon for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
