### ISSUE TITLE
Unclear documentation

### ISSUE THREAD

**Issue by DarkoRadivojevic** [MicrosoftDocs/sql-docs#6541]
[Enter feedback here]
Hello,

While reading [documentation](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-ver15&preserve-view=true&pivots=cs1-powershell#remove-your-container) for installing sql server with docker I noticed that when running `docker rm` or `docker stop`  all SQL data is lost if not somehow preserved. 

So following the big warning to persist the data using the [data persistence technique](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-docker-container-configure?view=sql-server-ver15&pivots=cs1-powershell#persist), which says that stopping and running a container will persist the data.

These two contradict themselves, I am interested if this is just my, most likely, misunderstanding of docker or is this an issue in the documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19f77423-91bb-21e4-5e1b-a956a7161ca2
* Version Independent ID: b2d30183-00b8-302d-ab1e-4f9882a2eed0
* Content: [Configure and customize SQL Server Docker containers - SQL Server](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-docker-container-configure?view=sql-server-ver15#persist)
* Content Source: [docs/linux/sql-server-linux-docker-container-configure.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-docker-container-configure.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @amvin87
* Microsoft Alias: **amitkh**

**Comment by WilliamAntonRohm** [comment]
@darko997 -- thank you for your feedback and question.  Please consider these resources:
- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/en-us/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server)

@amvin87 -- please look into this potential documentation issue.

**Comment by leisiamedeiros** [comment]
@DarkoRadivojevic if you run `docker stop` **and** `docker rm`  you'll have data loss because basically you're stopping and dropping any reference of the container with no volume. But if you just **stop** your container you can re-execute it again (`docker start`) with no data loss. 

> The command `docker ps -a` will show the stopped containers, and you can just run it again! 

I'm reading right now the documentation and I'm not seeing anything wrong (I don't know if someone had already correct), but in resume;
- Files are persisted in the container even if you restart the container with `docker stop` and `docker start` (**notice stop and start no data loss**);
- Stopping and removing a container permanently deletes any SQL Server data in the container (**notice stop and rm data loss**);
- If you remove the container with `docker rm`, everything in the container is deleted, including SQL Server and your databases;

Obs: Text above from the documentation ([Persist your data](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-docker-container-configure?view=sql-server-ver15&pivots=cs1-powershell#persist), [Remove your container](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-ver15&preserve-view=true&pivots=cs1-powershell#remove-your-container))

**Comment by VanMSFT** [comment]
Hi @DarkoRadivojevic , thank you for your question, and thank you @leisiamedeiros for helping to answer! We really appreciate this community! As the answer has been provided, and the documentation is correct, I'm going to close this thread. Thanks again!
