### ISSUE TITLE
Is the serializable isolation needed in the stored procedure?

### ISSUE THREAD

**Issue by zikato** [MicrosoftDocs/sql-docs#6546]
In the stored procedure which moves rows from hot to cold, two statements are used with serializable isolation.

```
INSERT INTO dbo.SalesOrders_cold_staging WITH (TABLOCKX)
      SELECT so_id , cust_id , so_date , so_total
         FROM dbo.SalesOrders_hot WITH (serializable)
         WHERE so_date <= @splitdate;

      -- Delete the moved data from the hot table.
      DELETE FROM dbo.SalesOrders_hot WITH (SERIALIZABLE)
         WHERE so_date <= @splitdate;
```

If I instead used a single statement with `SNAPSHOT` isolation and `OUPUT` clause, like this:

```
DELETE soh 
OUTPUT 
	deleted.so_id,
	deleted.cust_id,
	deleted.so_date,
	deleted.so_total 
INTO dbo.SalesOrders_cold_staging 
( so_id, cust_id, so_date, so_total )
FROM dbo.SalesOrders_hot AS soh WITH (SNAPSHOT)
WHERE soh.so_date <= @splitdate
```

Would it achieve the same thing? I'm worried about extensive locking on the hot table when `SERIALIZABLE` is used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae143071-a443-cd21-1da4-0f7897e31575
* Version Independent ID: 2b0e6251-0690-6d8f-b7ed-f2fdb6e74d72
* Content: [Application pattern - partitioning memory-optimized tables - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/in-memory-oltp/application-pattern-for-partitioning-memory-optimized-tables?view=sql-server-ver15)
* Content Source: [docs/relational-databases/in-memory-oltp/application-pattern-for-partitioning-memory-optimized-tables.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/in-memory-oltp/application-pattern-for-partitioning-memory-optimized-tables.md)
* Product: **sql**
* Technology: **in-memory-oltp**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by WilliamAntonRohm** [comment]
@zikato -- thank you for your considered question.  Please consider these resources:
- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/en-us/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server)

@rothja -- please look into this potential documentation issue.

**Comment by rothja** [comment]
@zikato Thanks for the question. I'm not sure of the answer to your technical question here, and, unfortunately, feedback items are mainly meant for suggestions on fixes to the articles or recommendations on what to change (rather than technical discussions). 

However, I would absolutely recommend reaching out to the forums that @WilliamAntonRohm listed above to search and then post your questions to the community. If you find there is a consensus there on the best approach that you think we should change in the article, you can reopen this git issue (by commenting), create a new feedback item on the article, or edit the article with your suggestion from your research for us to review. Include the forum post if there is supporting discussion in the community for the change.

We would be happy to consider updates to the article, but at this time, it is not clear what that might be. I am going to close the issue for now, but please reply to this thread if you want more context or if you have more research to indicate what the change should be. Thanks!
