### ISSUE TITLE
Readonly filegroup causes new database deployment to fail

### ISSUE THREAD

**Issue by bdquig** [MicrosoftDocs/sql-docs#6549]
When deploying a database with a readonly filegroup, the deployment fails.  I think the deploy should set the reaonly status at the end of the deploy

**Comment by WilliamAntonRohm** [comment]
@bdquig -- thank you for your feedback.  Are you following a particular docs.microsoft.com article?

**Comment by bdquig** [comment]
No particular article. We were trying to deploy databases to a new server and our deploy fails.

**Comment by WilliamAntonRohm** [comment]
@bdquig -- thank you for clarifying.  This repo is solely for documentation issues, and this appears to be product-related. 
 Please consider these resources:
- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/en-us/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server)

You are welcome to raise this issue here:
- [SQL Server Feedback](https://aka.ms/sqlfeedback)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
