### ISSUE TITLE
Which 'help'?

### ISSUE THREAD

**Issue by robertplata** [MicrosoftDocs/sql-docs#6558]
Which help section is referred to in this section?
     
<html>
<body>

/Properties: | /p | {PropertyName}={Value} | Specifies a name value pair for an action-specific property;{PropertyName}={Value}. Refer to the help for a specific action to see that action's property names. Example: sqlpackage.exe /Action:Import /?.
-- | -- | -- | --

</body>
</html>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f7954fa-99b7-be69-922b-4cadbcedcf2f
* Version Independent ID: a87d86dd-0354-ba30-eb0d-fbf3f4e0f8e5
* Content: [SqlPackage Import - SQL Server](https://docs.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage-import?view=sql-server-2017)
* Content Source: [docs/tools/sqlpackage/sqlpackage-import.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/sqlpackage/sqlpackage-import.md)
* Product: **sql**
* Technology: **tools-other**
* GitHub Login: @dzsquared
* Microsoft Alias: **drskwier**

**Comment by WilliamAntonRohm** [comment]
@robertplata -- thank you for your question.  

@dzsquared -- please look into this issue.  Does the `?` in the example indicate to return inline help text for that action?

**Comment by dzsquared** [comment]
Hi @robertplata - sorry that the messaging there is confusing.

You used to have to run `sqlpackage.exe /Action:Import /?` to get information about the properties that work on a specific action.  However, since then, we have improved the docs and the properties for the import action are detailed on that page.
https://docs.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage-import#properties-specific-to-the-import-action

(using /? in the command does still return the help info)

I'll get this cleared up in the docs shortly.

**Comment by dzsquared** [comment]
I wasn’t able to get the updates merged in before the last publish of the week, so you should see updated docs early next week.

#please-close

**Comment by dzsquared** [comment]
#please-close
