### ISSUE TITLE
Bad Information

### ISSUE THREAD

**Issue by rvahaver** [MicrosoftDocs/sql-docs#6580]
This statement and the associated link is wrong.  There is no information in this link to tell you how to install Report Server instances.

Statement
Review Install SQL Server from the Installation Wizard (Setup) for instructions on how to install report server instances.

Link
https://docs.microsoft.com/en-us/sql/database-engine/install-windows/install-sql-server-from-the-installation-wizard-setup?view=sql-server-ver15

**Comment by WilliamAntonRohm** [comment]
@rvahaver -- David, thank you for your feedback.  Please consider these resources:
- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/en-us/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server)

@cawrites -- Cheryl, please look into this issue.

**Comment by cawrites** [comment]
@rvahaver thank you for bringing this to our attention. It's under review.

**Comment by cawrites** [comment]
@rvahaver we making another attempt to follow up with you to define what article you found this information in. We are unable to move forward because you did not provide the originating article the link and statement appear in. Without this information, we are unable to view the content and make an adjustment.

**Comment by rvahaver** [comment]
Can you please reread this.  I provided the statement and link in the original comment.

**Comment by cawrites** [comment]
Here is my path for research.

@rvahaver I looked for the "specific" line of text in this article:  https://docs.microsoft.com/en-us/sql/database-engine/install-windows/install-sql-server-from-the-installation-wizard-setup?view=sql-server-ver15

This is the line of text you mentioned:  
"Review Install SQL Server from the Installation Wizard (Setup) for instructions on how to install report server instances."

This specific "text" I cannot locate in the link you provided. If you asking us to review the instructions, and not look for the specific text please advise. That was my original question.

**Comment by cawrites** [comment]
@rvahaver it appears based on your original request that you are looking for instructions, not necessarily an update to SQL Server Installation page that you provided. I would like to refer to landing page for Report Server which contains the information you are looking for. https://docs.microsoft.com/en-us/sql/reporting-services/create-deploy-and-manage-mobile-and-paginated-reports

**Comment by cawrites** [comment]
@rvahaver we appreciate you contacting Microsoft. Because there are multiple services available for SQL Server the content is broken up into different articles. I understand that this may impact your experience if you were looking for everything to be covered in one article. The information you requested is covered in detail in another article with the links that were provided to you. Since we have not determined a need to update this core document you referenced, we will be closing this case. Thank you again.
