### ISSUE TITLE
Discrepancy on "Applies to" section and "Database requirements" on create a report server (SSRS)

### ISSUE THREAD

**Issue by luis-aranda** [MicrosoftDocs/sql-docs#6582]
When checking the database requirements for creating a report server on the 2016 edition the below requirements are specified

https://docs.microsoft.com/en-us/sql/reporting-services/install-windows/ssrs-report-server-create-a-report-server-database?view=sql-server-2016#database-server-version-requirements

![DB requirements 2016](https://user-images.githubusercontent.com/65820140/125001732-f3db3b00-e018-11eb-8a07-745b8f0b24e3.png)

The "applies to" section mentions this is applicable to 2016 and later (see highlighted in yellow). Version on the left hand side specifies 2016 version
![Applies to 2016](https://user-images.githubusercontent.com/65820140/125001785-12d9cd00-e019-11eb-9e21-4cbc98c60b80.png)

Comparing the same against the 2019 edition we can see that the database requirements are different as there are more options

https://docs.microsoft.com/en-us/sql/reporting-services/install-windows/ssrs-report-server-create-a-report-server-database?view=sql-server-ver15#database-server-version-requirements

![DB requirements 2019](https://user-images.githubusercontent.com/65820140/125001906-592f2c00-e019-11eb-81c5-358ae4589192.png)

However as you can see on the "Applies to" section it mentions 2016 version and later are applicable. So this would conflict with the docs on the 2016 documentation. On the left hand side we can see (highlighted in yellow) that this is for 2019 edition
![Applies to 2019](https://user-images.githubusercontent.com/65820140/125001949-6ea45600-e019-11eb-8076-81a8d0184969.png)

This could create confusion as to what is indeed supported or not

**Comment by WilliamAntonRohm** [comment]
@luis-aranda -- thank you for your well-researched feedback.

@maggiesMSFT -- please look into this issue.

**Comment by maggiesMSFT** [comment]
Hi, @luis-aranda -- I'm investigating. Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @luis-aranda -- the product team reviewed all 3 versions of the page:
- 2019: https://docs.microsoft.com/en-us/sql/reporting-services/install-windows/ssrs-report-server-create-a-report-server-database?view=sql-server-ver15#database-server-version-requirements
- 2017: https://docs.microsoft.com/en-us/sql/reporting-services/install-windows/ssrs-report-server-create-a-report-server-database?view=sql-server-2017#database-server-version-requirements
- 2016: https://docs.microsoft.com/en-us/sql/reporting-services/install-windows/ssrs-report-server-create-a-report-server-database?view=sql-server-2016#database-server-version-requirements
And says they are correct as written. 
"Those are correct in terms of supported versions because we’ve not tested 2017 on SQL Server 2019 thoroughly."
It's a matter of testing. We don't list versions as supported if we haven't tested and verified them.
Thanks!
#please-close
