### ISSUE TITLE
Mistake version number in documentation?

### ISSUE THREAD

**Issue by CorGuzzi** [MicrosoftDocs/sql-docs#6618]
The note with Supplementary Characters says:
*Starting with SQL Server 2014 (12.x), all new _140 collations automatically support supplementary characters.*
I think it should be:
**Starting with SQL Server 2017 (14.x), all new _140 collations automatically support supplementary characters.**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bda69849-66d9-0b69-1041-c526a406c04f
* Version Independent ID: 7a8927c6-95b4-47bf-d866-3c5585cf9383
* Content: [Collation and Unicode support - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/collations/collation-and-unicode-support?view=sql-server-ver15#Supplementary_Characters)
* Content Source: [docs/relational-databases/collations/collation-and-unicode-support.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/collations/collation-and-unicode-support.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @pmasl
* Microsoft Alias: **wiassaf**

**Comment by WilliamAntonRohm** [comment]
@CorGuzzi -- thank you for your feedback.  I am updating this article.

**Comment by srutzky** [comment]
@CorGuzzi and @WilliamAntonRohm : Correct, it _should_ be SQL Server **2017**, not 2014.

I actually introduced this error a while back (by accident) due to multiple inconsistent include file naming conventions. So, I figured I should probably fix it, and I hadn't seen this issue when I posted my PR a moment ago that fixes this issue. William: I'm not sure how far you've gotten in your update, but I made several other corrections as well in mine if you just want to go with what I submitted. Please see #6657 for more details.

**Comment by WilliamAntonRohm** [comment]
@srutzky -- Solomon, thank you again for your contributions.

@pmasl -- Pedro, please review PR #6657.
