### ISSUE TITLE
that example under "Using Transact-SQL"  

### ISSUE THREAD

**Issue by alexhatcher** [MicrosoftDocs/sql-docs#6643]
its not actually SQL.  its still just using the Studio.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f4a6423-c509-5cc1-30f9-1fb55fe26833
* Version Independent ID: af8a0bd9-a993-8458-aebf-3ecc1462b228
* Content: [Duplicate tables - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tables/duplicate-tables?view=sql-server-ver15)
* Content Source: [docs/relational-databases/tables/duplicate-tables.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/duplicate-tables.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamAntonRohm** [comment]
@alexhatcher -- thank you for your feedback.  Please consider these resources:
- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/en-us/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server)

@WilliamDAssafMSFT -- please look into this issue.

**Comment by WilliamDAssafMSFT** [comment]
Hi @alexhatcher! Thanks for your feedback. Need more info on what you think should change here, this seems straightforward. 

Might be easier for you to [create a Pull Request](https://docs.microsoft.com/sql/sql-server/sql-server-docs-contribute) and get the ball rolling on a change yourself, instead of trying to describe it. By opening a pull request, you're helping the author add your approved change directly to the documentation. After the updated article is published, GitHub lists you as an article contributor. Either way, thanks for your feedback!
