### ISSUE TITLE
Sql Package Script Generation is not proper

### ISSUE THREAD

**Issue by santosh-v** [MicrosoftDocs/sql-docs#6732]
Hi , 
  I use the Jenkins Platform to generate the difference script for the Database project with Sqlpackage . i have generated the script comparing the Source project with destination database and i have got the difference script also. when i execute the difference script in Destination database and when i regenerate the script as per logic it should show nothing , but some objects are again listing in the script . how many times i execute the difference script is not getting reduced. 
 
 the objects affected in my difference script is mostly user defined functions , when i check the script and ansi null and Quoted identifier setting , everything is same .when i compare it from Visual studio , it is not giving the difference . 
 now how can i get to know what is the difference , which property is different ?? 
 what are all the properties being checked on comparing the user defined function ?? 
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac30c0d5-990b-1114-cb66-d6bbb789b698
* Version Independent ID: 9432dace-7676-2a86-485a-dd5bc6568e86
* Content: [SqlPackage.exe - SQL Server](https://docs.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage?view=sql-server-ver15#feedback)
* Content Source: [docs/tools/sqlpackage/sqlpackage.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/tools/sqlpackage/sqlpackage.md)
* Product: **sql**
* Technology: **tools-other**
* GitHub Login: @dzsquared
* Microsoft Alias: **drskwier**

**Comment by WilliamAntonRohm** [comment]
@santosh-v -- thank you for your feedback & questions.  This issue seems to be regarding the product and not the documentation.  Please consider these resources:
- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/en-us/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
