### ISSUE TITLE
LDAPs - Would be important to review the section "Traffic and Ports" with the purpose of clarifying the use of LDAPs

### ISSUE THREAD

**Issue by lcanastreiro** [MicrosoftDocs/sql-docs#6743]
Hello all,

Would be important to review the section "Traffic and Ports" with the purpose of clarifying the use of LDAPs on the communication of SQL BDC with AD.

Thanks very much for your attention,
Luís.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37e93258-ada8-594a-c725-005e5cf94e7c
* Version Independent ID: 995e0663-2823-c258-193a-5904620f805d
* Content: [Deploy in Active Directory mode - SQL Server Big Data Cluster](https://docs.microsoft.com/en-us/sql/big-data-cluster/active-directory-deploy?view=sql-server-ver15)
* Content Source: [docs/big-data-cluster/active-directory-deploy.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/big-data-cluster/active-directory-deploy.md)
* Product: **sql**
* Technology: **big-data-cluster**
* GitHub Login: @cloudmelon
* Microsoft Alias: **melqin**

**Comment by WilliamDAssafMSFT** [comment]
Hi @lcanastreiro, thanks for taking the time to create this issue. We document the ports for LDAP and LDAPS, can you be specific as to what information needs to be reviewed or clarified?

**Comment by lcanastreiro** [comment]
Hi William,

The need for review is that would be important to clarify how LDAPs could be used in the deployment, normal usage and upgrade actions of SQL BDC.

Thanks,
Luís.

**Comment by WilliamDAssafMSFT** [comment]
Thanks @lcanastreiro for taking the time to create this issue. To be more specific on the information we can provide customers, would you like to take a shot at creating a PR and proposing a start to the changes [via quick edit](https://docs.microsoft.com/contribute/#quick-edits-to-existing-documents)?  Might be easier for you to create a Pull Request and get the ball rolling on a change yourself, instead of trying to describe it. By opening a pull request, you're helping the product team add your approved change directly to the documentation. After the updated article is published, GitHub lists you as an article contributor.

**Comment by WilliamDAssafMSFT** [comment]
Discussed with the PM team and we feel this is currently adequately documented. If you have any specific suggestions to improve the documentation would be happy to discuss or see them [in a quick edit](https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents).
