### ISSUE TITLE
Event notifications not supported in Azure SQL DB

### ISSUE THREAD

**Issue by jasonhorner** [MicrosoftDocs/sql-docs#6797]
A note should be added to say this is not supported on Azure SQL DB  the top calls out all supported versions which is misleading.

https://docs.microsoft.com/en-us/azure/azure-sql/database/features-comparison
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9871df5-01b4-72e4-33bf-d77856ba8656
* Version Independent ID: 2bd78481-34eb-bddb-89f2-c7a0850963b2
* Content: [Event Notifications - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/service-broker/event-notifications?view=sql-server-ver15)
* Content Source: [docs/relational-databases/service-broker/event-notifications.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/service-broker/event-notifications.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@jasonhorner -- thank you for bringing this to our attention.

@MashaMSFT -- please look into this issue.

**Comment by MikeRayMSFT** [comment]
Our current method of identifying products is to affirm the products that do apply (SQL Server generally includes the boxed product). Azure SQL Database and Azure SQL Managed Instance are not SQL Server for these purposes. We don't list products that features do not apply to because of the scope of the list.
