### ISSUE TITLE
Insufficient information

### ISSUE THREAD

**Issue by ml3z** [MicrosoftDocs/sql-docs#6841]
This article did not mention where & how to run the following the script.

> sp_configure 'contained database authentication', 1;  
> GO  
> RECONFIGURE;  
> GO

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca41d5a8-c8b5-0b5c-9560-c12fa42fd956
* Version Independent ID: 00d537f8-e0e0-3adf-cbd8-7ce7b14ad81a
* Content: [contained database authentication Server Configuration Option - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/contained-database-authentication-server-configuration-option?view=sql-server-2017)
* Content Source: [docs/database-engine/configure-windows/contained-database-authentication-server-configuration-option.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/contained-database-authentication-server-configuration-option.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by cawrites** [comment]
@millat-hossain thank you for contacting Microsoft with this question. I will review this article and locate the information you requested.

**Comment by cawrites** [comment]
The command shown is executed based on a connection to SQL Server(commonly used in a query window). I will include a link that shows how to run a stored procedure. https://docs.microsoft.com/en-us/sql/relational-databases/stored-procedures/execute-a-stored-procedure?view=sql-server-ver15.  However it may be beneficial to label this as a SQL command so that it is clear to the user reading this. Thank you for your contribution to Microsoft.
