### ISSUE TITLE
The section on Table-Valued Parameters being on this page seems irrelevant and has nothing to do with CLR User-Defined Aggregates. 

### ISSUE THREAD

**Issue by cbogota** [MicrosoftDocs/sql-docs#6924]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a861430-2277-5e5e-db65-16aebb041283
* Version Independent ID: 2928021b-c23c-0e75-8aa9-0b45ea02efb6
* Content: [Requirements for CLR User-Defined Aggregates - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/clr-integration-database-objects-user-defined-functions/clr-user-defined-aggregates-requirements?view=sql-server-ver15)
* Content Source: [docs/relational-databases/clr-integration-database-objects-user-defined-functions/clr-user-defined-aggregates-requirements.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/clr-integration-database-objects-user-defined-functions/clr-user-defined-aggregates-requirements.md)
* Product: **sql**
* Technology: **clr**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by srutzky** [comment]
@ShannonLeavitt , @WilliamAntonRohm , and @cbogota : I'm not sure that the TVP section is irrelevant. I believe it might just be not labeled well and might include some extraneous info.

I believe the relevant part of the TVP paragraph is:

> A user-defined table type cannot be passed as a table-valued parameter to, or be returned from, a managed stored procedure or function executing in the SQL Server process.

I assume this is the reason for having this section as it is consistent with the other two function type pages in that section:

* CLR Scalar-Valued Functions: https://docs.microsoft.com/en-us/sql/relational-databases/clr-integration-database-objects-user-defined-functions/clr-scalar-valued-functions#table-valued-parameters
* CLR Table-Valued Functions: https://docs.microsoft.com/en-us/sql/relational-databases/clr-integration-database-objects-user-defined-functions/clr-table-valued-functions#table-valued-parameters

Of course, I couldn't find that paragraph in the User-Defined Type page, nor could I even find a page for Stored Procedures or one for Triggers. Whatever.


Rather than removing the entire paragraph, it might be better to do the following:

1. Change the title of the section to indicate that this is a restriction, such as: "**Restriction on using Table-Valued Parameters**" 
1. Remove the following three sentences in the middle of that paragraph as they are extraneous:

    > They also provide the potential for better performance. Table-valued parameters also help reduce the number of round trips to the server. Instead of sending multiple requests to the server, such as with a list of scalar parameters, data can be sent to the server as a table-valued parameter.
