### ISSUE TITLE
More informatino about ConnectionPoolPerformanceCounterDetail and what the `value` means

### ISSUE THREAD

**Issue by saboco** [MicrosoftDocs/sql-docs#6963]
I tried to find information about this key and haven't found much.

https://github.com/MicrosoftDocs/sql-docs/blob/4e25a12561f86cc5575160afb6bb209b53863e53/docs/connect/ado-net/performance-counters.md?plain=1#L55

Could we please add some information about what `4` means or a link to more detail documentation about `ConnectionPoolPerformanceCounterDetail` key

**Comment by rothja** [comment]
Apologies for the delay. @David-Engel David, is this something you would be able to investigate or answer? I'll co-assign us while we discuss how to find this answer. #assign:david-engel

**Comment by JRahnama** [comment]
@saboco this is the [link](https://docs.microsoft.com/en-us/sql/connect/ado-net/performance-counters?view=sql-server-ver15#activate-off-by-default-counters) to the current documentation.  The number 4 is for comming from System.Diagnostics.TraceLevel

```C#
namespace System.Diagnostics
{
    //
    // Summary:
    //     Specifies what messages to output for the System.Diagnostics.Debug, System.Diagnostics.Trace
    //     and System.Diagnostics.TraceSwitch classes.
    public enum TraceLevel
    {
        //
        // Summary:
        //     Output no tracing and debugging messages.
        Off = 0,
        //
        // Summary:
        //     Output error-handling messages.
        Error = 1,
        //
        // Summary:
        //     Output warnings and error-handling messages.
        Warning = 2,
        //
        // Summary:
        //     Output informational messages, warnings, and error-handling messages.
        Info = 3,
        //
        // Summary:
        //     Output all debugging and tracing messages.
        Verbose = 4
    }
}
```
The driver, `netfx` only, implements the code and catches tracing only when `verbose` level is requested otherwise nothing would be captured.

A sample of implementation inside the driver is like this :

```C#
 TraceSwitch perfCtrSwitch = new TraceSwitch("ConnectionPoolPerformanceCounterDetail", "level of detail to track with connection pool performance counters");
                if (TraceLevel.Verbose == perfCtrSwitch.Level)
                {
                    verboseCategoryName = categoryName;
                }
```
link to actual code on [GitHub.](https://github.com/dotnet/SqlClient/blob/c56baaabb641de6dd595203f78a2e93b65ac2317/src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/ProviderBase/DbConnectionPoolCounters.cs#L212)

More useful documents:
https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics?view=net-6.0
https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.tracelevel?view=net-6.0

**Comment by David-Engel** [comment]
I added a comment in the XML on the doc page noting that 4 corresponds to System.Diagnostics.TracelLevel.Verbose for future reference.

#please-close

**Comment by saboco** [comment]
thank you all!
