### ISSUE TITLE
A user transaction that accesses memory optimized tables or natively compiled modules cannot access more than one user database or databases model and msdb, and it cannot write to master

### ISSUE THREAD

**Issue by sonben** [MicrosoftDocs/sql-docs#7006]
Example does not work. Still get the error "A user transaction that accesses memory optimized tables or natively compiled modules cannot access more than one user database or databases model and msdb, and it cannot write to master". 

Give the database are on the same server, I fail to see why read only access from another database is not permitted. This could easily be enforced by functions only access.  This restriction renders the functionality almost useless. The only work around you offer is to make a copy of the data on the destination database which is inefficient, prone to error and just not workable.  I have spent a great deal of time splitting the system in functional database - each with their own specialities. Now I would the system to work as a coherent system and this restriction make this impossible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b010d6e-62ef-88b9-5597-bba2b9c51291
* Version Independent ID: 9f2bbb30-8079-3024-58bd-5d778971f0a3
* Content: [Cross-Database Queries - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/in-memory-oltp/cross-database-queries?view=sql-server-2017)
* Content Source: [docs/relational-databases/in-memory-oltp/cross-database-queries.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/in-memory-oltp/cross-database-queries.md)
* Product: **sql**
* Technology: **in-memory-oltp**
* GitHub Login: @rothja
* Microsoft Alias: **jroth**

**Comment by WilliamAntonRohm** [comment]
@sonben -- thank you for your feedback.  Please consider these resources:
- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server)

You are welcome to add this issue here:
- [SQL feedback](https://aka.ms/sqlfeedback)

@rothja -- please look into this potential documentation issue.

**Comment by rothja** [comment]
@sonben I am really sorry that you have run into this restriction that is preventing you from connecting your two data sources! I'll take a look at the work around to see if it is incorrect. However, it seems from what you are saying that this would still not help, because the work around itself is not really usable. I'll look into this some and see if I have any suggestions. In the meantime, I would strongly encourage you to search or post in the groups William pointed you to above to see if the community has some great ideas on the best approach. Thank you!

**Comment by rothja** [comment]
Apologies on the lack of response and follow-up on this issue. @WilliamDAssafMSFT William, when you get some time, could you take a look at this issue and scenario. I realize that it may still be a while with the other issues and work going on, but I feel like you have the expertise to investigate better than me. Thank you! #reassign:williamdassafmsft
