### ISSUE TITLE
Doecument does not specify limitations of Azure Synapse Analytics

### ISSUE THREAD

**Issue by cameron-interactive** [MicrosoftDocs/sql-docs#7106]
The document here lists processes that do not work with Azure Synapse Analytics, but are not mentioned at all in the document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7f1c141-dea3-1a2c-ba2f-86163be24aa6
* Version Independent ID: 5d4a7221-2821-feb8-c74d-509c0c6e3889
* Content: [Add Columns to a Table (Database Engine) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tables/add-columns-to-a-table-database-engine?view=sql-server-ver15)
* Content Source: [docs/relational-databases/tables/add-columns-to-a-table-database-engine.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/add-columns-to-a-table-database-engine.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamAntonRohm** [comment]
@cameron-interactive -- thank you for your feedback.  Please clarify "The document here lists processes that do not work with Azure Synapse Analytics, but are not mentioned at all in the document." -- do you mean the listed processes (that do not work with Azure Synapse Analytics) are not otherwise documented?  Meanwhile, consider these resources:
- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server)

@WilliamDAssafMSFT -- please look into this issue.

**Comment by cameron-interactive** [comment]
It's not that they're not otherwise documented, but rather the instructions on making changes to tables with SSMS doesn't work with Synapse (by design, or bug, hard to tell), it should be noted here so people don't try it and fail.

**Comment by WilliamDAssafMSFT** [comment]
Hi @cameron-interactive! Thanks for taking the time to provide this feedback to Microsoft Docs. The same TSQL steps do work in Azure Synapse dedicated pools, and while [SSMS is supported for many Azure Synapse purposes](https://docs.microsoft.com/azure/synapse-analytics/sql/get-started-ssms), the SSMS table designer for SQL Server doesn't work for Azure Synapse tables. Looks like we have some metadata to update. It would make sense to add that caveat to a page on the [Table Designer](https://docs.microsoft.com/sql/ssms/menu-help/options-designers-table-and-database-designers-page), I'll do that. Thanks for bringing this to our attention! Your suggestions help improve our documentation.
