### ISSUE TITLE
documentation is unclear, repetitive, and not informative

### ISSUE THREAD

**Issue by DWAK-ATTK** [MicrosoftDocs/sql-docs#7116]
This page could really use some editing.  It is unclear what anything other than the first paragraph is saying.
I ended up on this page trying to figure out what permissions were needed to restore a database, whether existing or not.  Imagine my disappointment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d41647b7-e5c6-bb8d-e390-125142c631a2
* Version Independent ID: 18659f20-65ab-adb7-50d5-02dcb1e08e53
* Content: [Restore Database (General Page) - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/backup-restore/restore-database-general-page?view=sql-server-ver15)
* Content Source: [docs/relational-databases/backup-restore/restore-database-general-page.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/backup-restore/restore-database-general-page.md)
* Product: **sql**
* Technology: **backup-restore**
* GitHub Login: @LitKnd
* Microsoft Alias: **kendralittle**

**Comment by WilliamAntonRohm** [comment]
@DWAK-ATTK -- thank you for your feedback.  Please consider these resources:
- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server)

@LitKnd -- please look into this issue.

**Comment by LitKnd** [comment]
Hi @DWAK-ATTK ,

Thanks for bringing this issue to our attention. I agree that this wording could be much more clear. 

I have created a pull request which will update the permissions paragraph on this page to be more like [how permissions are explained in the RESTORE Transact-SQL article](https://docs.microsoft.com/en-us/sql/t-sql/statements/restore-statements-transact-sql#permissions). That language looks much clearer to me, and it still covers both new and existing databases.

I am also reviewing the rest of the page for clarity.

Because of the holiday and our review processes, I expect that this won't publish until the new year. I'll update this issue as the process completes on this.

Cheers,
Kendra

Kendra Little
Content Developer on the Database Docs Team

**Comment by DWAK-ATTK** [comment]
Thank you very much Kendra. Your efforts are greatly appreciated.

**Comment by LitKnd** [comment]
Hi @DWAK-ATTK ,

Thanks for your patience on this. We've completed our content review process of my proposed change and I've signed off on this today. It will flow through some more checks as part of the publishing process, but I expect this to go out today!

I'm going to go ahead and close this out (mostly so I don't forget). Thanks for helping us improve the docs!

Kendra
Content Developer on the Database Docs Team

#please-close
