### ISSUE TITLE
Documentation on Temporal Table Usage

### ISSUE THREAD

**Issue by JpsKaGitHub** [MicrosoftDocs/sql-docs#7117]
Despite Microsoft strongly discouraging use of the sp prefix for user stored procedures, there is at least one example in this document that does precisely that. And I have seen similar transgressions in other Microsoft SQL Server documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16923b34-9fbb-86a2-071d-c4fa47e639ff
* Version Independent ID: 83127f7a-a6cd-0b63-a723-ee72f7511a6a
* Content: [Temporal Table Usage Scenarios - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tables/temporal-table-usage-scenarios?view=sql-server-ver15)
* Content Source: [docs/relational-databases/tables/temporal-table-usage-scenarios.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/temporal-table-usage-scenarios.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@JpsKaGitHub -- JPS, thank you for your feedback.

@markingmyname -- Mark, please look into this issue.-

**Comment by markingmyname** [comment]
Hello, @JpsKaGitHub.

We appreciate you mentioning this type of awareness about labeling store procedures.

But may I ask you where specifically it states Microsoft discourages using "sp" as a prefix for stored procedures?

thank you.

**Comment by markingmyname** [comment]
Due to no response we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community is wanting, please visit the [SQL Server User Feedback](https://feedback.azure.com/d365community/forum/04fe6ee0-3b25-ec11-b6e6-000d3a4f0da0) site or the [Q & A](https://docs.microsoft.com/en-us/answers/products/sql-server) site.
