### ISSUE TITLE
String_split: example from docs with ordinal doesn't work on SQL Server 2019

### ISSUE THREAD

**Issue by pregress** [MicrosoftDocs/sql-docs#7131]
When trying the following example from the docs:

```
SELECT * FROM STRING_SPLIT('E-D-C-B-A', '-', 1) ORDER BY ordinal DESC;  
```

We receive an error: 

> Msg 8144 Level 16 State 3 Line 1
> Procedure or function STRING_SPLIT has too many arguments specified.

See [db fiddle](https://dbfiddle.uk/?rdbms=sqlserver_2019&fiddle=28d27e1ddf2b3c712e3ece821f1bc3fb)
Links to docs:  https://docs.microsoft.com/en-us/sql/t-sql/functions/string-split-transact-sql?view=sql-server-ver15#g-order-rows-by-ordinal-values

File on github: https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/t-sql/functions/string-split-transact-sql.md

**Comment by WilliamAntonRohm** [comment]
@pregress -- Preben, thank you for your feedback.  Please consider these resources:
- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server)

@WilliamDAssafMSFT -- William, please look into this potential documentation issue.

**Comment by WilliamDAssafMSFT** [comment]
Hi @pregress! The _enable_ordinal_ argument and `ordinal` output column are currently only supported in Azure SQL Database, Azure SQL Managed Instance, and Azure Synapse Analytics (serverless SQL pool only).

**Comment by RKDMax** [comment]
I realize this is closed, but related:

SQL Server Management Studio (v18.10)
SQL Server 15.0.4073.23 Database Server

Intellisense complains that "An insufficient number of arguments were supplied for the procedure or function STRING_SPLIT." if you don't provide a value in the ordinal parameter.

![Ssms_2022-01-07_15-22-51](https://user-images.githubusercontent.com/12748819/148602584-35de7e0b-b643-44ea-9505-6f04e1d0142e.png)

If this parameter is only valid for Azure SQL Database, Azure SQL Managed Instance, and Azure Synapse Analytics (serverless SQL pool only), then intellisense should reflect that since I'm connecting to a SQL Server instance (not Azure).

**Comment by WilliamAntonRohm** [comment]
@RKDMax -- Max, thank you for your followup.  Please add this here:
- [SQL Server feedback](http://aka.ms/sqlfeedback)

**Comment by RKDMax** [comment]
> @RKDMax -- Max, thank you for your followup. Please add this here:
> 
> * [SQL Server feedback](http://aka.ms/sqlfeedback)

Thanks -- looks like this issue does exist from someone a posting a month ago: [SSMS 18.10 STRING_SPLIT IntelliSense Bug](https://feedback.azure.com/d365community/idea/39b44a36-cb4e-ec11-a819-0022484bf651)

**Comment by WilliamAntonRohm** [comment]
@RKDMax -- Max, thank you for relating this.

cc @WilliamDAssafMSFT for awareness
