### ISSUE TITLE
sp_configure user_options does not mention contained databases

### ISSUE THREAD

**Issue by twiggy** [MicrosoftDocs/sql-docs#7137]
sp_configure will not work for user options when a database is contained on the server. The fact that contained databases removes the ability to set defaults doesn't seem to be mentioned anywhere else either. I suspect because contained dbs is abandonware.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c6695aa-46cb-5317-8712-ce0820214a6a
* Version Independent ID: f514c661-41e7-c2b4-1efd-66d3f9da898a
* Content: [Configure the user options Server Configuration Option - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/configure-the-user-options-server-configuration-option?view=sql-server-ver15)
* Content Source: [docs/database-engine/configure-windows/configure-the-user-options-server-configuration-option.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/configure-the-user-options-server-configuration-option.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@twiggy -- thank you for your feedback.  Please consider these resources:
- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server)

@markingmyname -- please look into this issue.

**Comment by markingmyname** [comment]
#assign @WilliamDAssafMSFT

**Comment by markingmyname** [comment]
@WilliamDAssafMSFT 

any thoughts?

**Comment by WilliamDAssafMSFT** [comment]
@twiggy The nature of contained databases is to be portable between SQL Server instances and insulated from any instance-level settings. The behavior of sp_configure here is intentional as it configures instance-level options.  Some options, like MAXDOP, can be configured at the database level via the [ALTER DATABASE SCOPED CONFIGURATION](https://docs.microsoft.com/sql/t-sql/statements/alter-database-scoped-configuration-transact-sql) option. For more information on different features for contained databases, see [Modified Features (Contained Database)](https://docs.microsoft.com/en-us/sql/relational-databases/databases/modified-features-contained-database?view=sql-server-ver15).
