### ISSUE TITLE
Worst guide ever

### ISSUE THREAD

**Issue by kakamble13052** [MicrosoftDocs/sql-docs#7144]
If Ubuntu doesn't have the latest unixodbc package, then it is YOUR RESPONSIBILITY to ensure that you add a disclaimer and a solution in your docs instead of forcing people to surf the Net just to find a solution. Your doc ends up wasting everyone's time. I was expecting to set everything up within an hour given my internet speed but now I am 3 hours in just trying to make it work due to YOUR NEGLIGENCE. I want to have a nice long chat with whoever is providing material for the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5634d572-0020-808b-693a-13addc8861d9
* Version Independent ID: 136bab7d-d4d1-1e82-ba89-be2020bc784b
* Content: [Ubuntu: Install SQL Server on Linux - SQL Server](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-ubuntu?view=sql-server-ver15)
* Content Source: [docs/linux/quickstart-install-connect-ubuntu.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/quickstart-install-connect-ubuntu.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
unixODBC section is listed in the doc, and further ODBC information is listed in the same section of the doc.

https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-ubuntu?view=sql-server-ver15#tools

Perhaps we'll need some clarification on what is the issue so that we can better service the doc. Since there hasn't been a reply, closing this issue for now.
