### ISSUE TITLE
Microsoft.SqlServer.Management.CloudAdapter is required

### ISSUE THREAD

**Issue by stevehurcombe** [MicrosoftDocs/sql-docs#7294]
[Enter feedback here]
If you use the SQL Server PowerShell then Microsoft.SqlServer.Management.CloudAdapter is required. 

[Sepcifically Set-SqlNetworkConfiguration] 

However this is not available to download and is "The only environment this version supports is Windows Azure".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca91cbd9-efe5-1de5-7da6-6137b0437a3d
* Version Independent ID: 836f506c-0e26-8277-1a9f-451853e0d21b
* Content: [Load the SMO Assemblies in Windows PowerShell - SQL Server](https://docs.microsoft.com/en-us/sql/powershell/load-the-smo-assemblies-in-windows-powershell?view=sql-server-ver15)
* Content Source: [docs/powershell/load-the-smo-assemblies-in-windows-powershell.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/powershell/load-the-smo-assemblies-in-windows-powershell.md)
* Product: **sql**
* Technology: **sql-server-powershell**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@stevehurcombe -- Steve, thank you for your feedback.  Please consider these resources:
- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server)

You're welcome to add this here:
- [SQL Server feedback](http://aka.ms/sqlfeedback)

@markingmyname -- Mark, please look into this potential documentation issue.

**Comment by shueybubbles** [comment]
Calling @Matteo-T !

**Comment by WilliamAntonRohm** [comment]
#reassign:Matteo-T

**Comment by Matteo-T** [comment]
The story here is pretty simple: cloud adapter has long been retired (I believe around year 2016 or so).

The corresponding cmdlets have been removed from version 22 or the SQLServer module.

Currently, i have no plans of trying to bring them back due to the fact that nobody (until now) noticed they have been broken for 6+ years.

If there is a strong desire to have some of those cmdlets ported over to something more modern, please log an issue here in GitHub.com in the SqlServer repo (not this one, which is only about docs)

For the documentation, we should check and make sure that is called out for older version of the module. I'll take a look when I'm back from vacation...

Thanks for bringing this to my attention?

**Comment by WilliamAntonRohm** [comment]
@Matteo-T -- Matteo, thank you for your clarifications!
