### ISSUE TITLE
Performance Impact of Computed Columns

### ISSUE THREAD

**Issue by JediSQL** [MicrosoftDocs/sql-docs#7297]
Hi,

I was wondering about the performance impact of computed columns. I would like to think that if a computed column is not referenced in a query, that the computations associated with it would not be performed. However, I have found that SQL Server sometimes performs evaluations that are unexpected, like running a scalar function on all rows of a table when a where clause or join condition would result in only a few rows being returned. It would be helpful to have some explicit documentation regarding exactly when, and when not, computed column computation occurs. If this is already described elsewhere, a link in the "Next Steps" section would helpful.

Sincerely,
Dan Jameson

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7155e90b-8b59-5029-6020-223ea44bac84
* Version Independent ID: 48027234-b139-14b5-b790-c65285664360
* Content: [Specify Computed Columns in a Table - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/tables/specify-computed-columns-in-a-table?view=sql-server-ver15)
* Content Source: [docs/relational-databases/tables/specify-computed-columns-in-a-table.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/specify-computed-columns-in-a-table.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamDAssafMSFT** [comment]
Hi @JediSQL. I'm not sure this line of questions can be answered best here, other than to say computed columns are updated when the underlying columns are updated. This might a question best for [Microsoft Q&A](https://docs.microsoft.com/answers/products/sql-server) if you have some sample queries and scenarios. Or, if you have unexpected reproduceable results: [aka.ms/sqlfeedback](https://feedback.azure.com/d365community/forum/04fe6ee0-3b25-ec11-b6e6-000d3a4f0da0).

**Comment by JediSQL** [comment]
Hi @WilliamDAssafMSFT. The situation "computed columns are updated when the underlying columns are updated" only applies when the PERSISTED option is included in the column DDL. Without the PERSISTED option, the computed columns are computed at SELECT time. I will, though, check out the resources you provided.

**Comment by WilliamDAssafMSFT** [comment]
I see your point now. Computed columns are virtual columns and not stored unless they are persisted or indexed.  Because they are not stored, they must be calculated. The virtual nature of the column when not persisted is implied in the docs but not specifically called out in a performance context, I understand your point. We'll review internally with the product group of what we may add. I will leave this Issue closed for now.

If you want to get the ball rolling and call attention to scenarios you have encountered, instead of a GitHub issue, it might be easier for you to [create a Pull Request](https://docs.microsoft.com/sql/sql-server/sql-server-docs-contribute). By opening a pull request, you're collaborating with the authors to add changes directly to the documentation. After the updated article is published, GitHub will list you as an article contributor.
