### ISSUE TITLE
MSmerge_subscriptions.status values are not documented

### ISSUE THREAD

**Issue by jnm2** [MicrosoftDocs/sql-docs#7325]
https://docs.microsoft.com/en-us/sql/relational-databases/system-tables/msmerge-subscriptions-transact-sql?view=sql-server-ver15

The meanings of the `subscription_type` and `sync_type` values are documented, but not `status`:

![image](https://user-images.githubusercontent.com/8040367/154819402-fc944fa2-11b3-420a-b674-91780ef3766c.png)

**Comment by WilliamAntonRohm** [comment]
@jnm2 -- Joseph, thank you for your feedback.  Please consider these resources:
- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server)

@LitKnd -- Kendra, please look into this issue.

**Comment by LitKnd** [comment]
Hi @jnm2 ,

Our engineering team reviewed this request and clarified that this column is no longer in use. 

I have opened a pull request to update the documentation for this column. The description will now read:

> This column is no longer in use. To check the status of a merge subscription, review the status column in the sysmergesubscriptions table in the publication or subscription database.

There will be a hyperlink to sysmergesubscriptions for convenience. This change should publish within the working day today, so I am going to go ahead and close out this issue. You will still be able to comment after the issue is closed.

Thanks again for raising this issue and for helping us improve the documentation!

Kendra from the Database Docs team
#please-close
