### ISSUE TITLE
SSMS 2018 > Options should be saved for later use.

### ISSUE THREAD

**Issue by gbthakkar** [MicrosoftDocs/sql-docs#7332]
I am using SSMS 2018. I need to have my indexes available in the script when I right-click the table name and generate the script.
So I navigate to Tools > Options > Object Explorer > Scripting. And change the option there.

Here, If I close the SSMS and open it second time, the change I made in "Options" are lost.

I believe- ssms should remember it as like its doing with other things.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3049d3f-bf85-583e-7fd9-f8407702f177
* Version Independent ID: 836c83b8-6d8b-1d90-f486-03492f03a0eb
* Content: [SSMS components and configuration' - SQL Server Management Studio (SSMS)](https://docs.microsoft.com/en-us/sql/ssms/tutorials/ssms-configuration?view=sql-server-ver15)
* Content Source: [docs/ssms/tutorials/ssms-configuration.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/tutorials/ssms-configuration.md)
* Product: **sql**
* Technology: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@gbthakkar -- Gaurang, thank you for your feedback.  This is a product-related issue, rather than documentation-related.  Please add it here:
- [SQL Server feedback](http://aka.ms/sqlfeedback)

cc @markingmyname for awareness


I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
