### ISSUE TITLE
No documentation on how to create functions on Serverless Sql 

### ISSUE THREAD

**Issue by gfree76** [MicrosoftDocs/sql-docs#7372]
The page for CREATE FUNCTION in Synapse , https://docs.microsoft.com/en-us/sql/t-sql/statements/create-function-sql-data-warehouse?view=aps-pdw-2016-au7 there is a note that the syntax does not work on Serverless SQL. It in unclear which syntax is unsupported, and does not provide a link to documentation on what is supported on Serverless Sql.

**Comment by WilliamAntonRohm** [comment]
@gfree76 -- Geoffrey, thank you for your feedback.  Please consider these resources:
- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server)

@LitKnd -- Kendra, please look into this issue.

**Comment by LitKnd** [comment]
Hi @gfree76 ,

Thank you for getting in touch.

I believe that the intended meaning is that the scalar function Transact-SQL reference just above the note is not supported in serverless SQL pool. 

In the [T-SQL support](https://docs.microsoft.com/en-us/azure/synapse-analytics/sql/on-demand-workspace-overview#t-sql-support) section on the page for serverless SQL pools, it mentions that the "workload can be organized using familiar concepts" which include:

> Views, stored procedures, inline table value functions

It does not mention scalar functions. 

However, I can see how this is unclear to you and other readers. I'm going to reach out to other team members to confirm if I am interpreting this correctly, and if so to check if we can update this article to be more clear.

Thanks,
Kendra from the Database Docs team

**Comment by gfree76** [comment]
Hey Kendra,

I'm pretty sure you're correct, from playing around with the functionality on Serverless. But yes, it would be nice to have it more explicit somewhere.

Thanks for taking a look!
Geoff
________________________________

**Comment by LitKnd** [comment]
Hi @gfree76 ,

Changes have now been merged to clarify this: the note will now read, "Scalar functions are not available in the serverless SQL pools."

Some further clarifications have been added to the article, such as "Inline table-value functions are available in the serverless SQL pools, but in preview in the dedicated SQL pools."

These changes should go live in our next publish cycle, so you should be able to see them within the current business day. Since this change has merged, I'm going to go ahead and close out this issue.

Thanks for bringing this to our attention and for making the docs better!

Kendra from the Database Docs team

#please-close
