### ISSUE TITLE
Link for feedback is missing on T-SQL documentation pages

### ISSUE THREAD

**Issue by sdebruyn** [MicrosoftDocs/sql-docs#7375]
There are no links for feedback about the docs on all pages in this section: https://docs.microsoft.com/en-us/sql/t-sql/statements/statements?view=azure-sqldw-latest

Most other Azure documentation pages have links directly to GitHub to create an issue with the documentation.

**Comment by WilliamAntonRohm** [comment]
@sdebruyn -- Sam, thank you for your feedback.  I am investigating.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.

**Comment by rothja** [comment]
@sdebruyn @WilliamAntonRohm I'm the manager of the Database Docs team. Thanks for proactively suggesting the change (and making it). However, we purposefully turned off git issues from the T-SQL reference due to challenges in resourcing to keep up with the feedback (as well as the tendency for the issues to be difficult to reproduce and more like support issues that we weren't staffed to respond to). Instead, we hope customers take advantage of the Public Pull Request option to suggest specific changes that are more targeted and easier to review and approve (clicking the "Edit" pencil at the top of the article). Customers can also respond with issues on relevant conceptual docs. 

We know that this is not ideal, and I apologize that we had to make this call. I'm turning the issues back off today. Please let me know if you have any questions. Thank you!
