### ISSUE TITLE
No 'sys.dm_os_loaded_modules' in Azure SQL DB?

### ISSUE THREAD

**Issue by epiphany-it** [MicrosoftDocs/sql-docs#7430]
This page states that it applies to Azure SQL Database. However, when I try to execute the SQL statement:
```
SELECT
		mod1.name,
		mod1.description
	from
		sys.dm_os_loaded_modules  as mod1
	where
		mod1.description = 'XTP Native DLL';
```
I get an error:
```
Invalid object name 'sys.dm_os_loaded_modules'.
```
I have tried the above statement both in the `master` database and in one of my application databases.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e73faff-9baf-2c59-2039-61c0a957d581
* Version Independent ID: a13e94c7-98dd-f801-4e4d-b5cfa061cab5
* Content: [Native compilation of tables & stored procedures - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/in-memory-oltp/native-compilation-of-tables-and-stored-procedures?view=azuresqldb-current)
* Content Source: [docs/relational-databases/in-memory-oltp/native-compilation-of-tables-and-stored-procedures.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/in-memory-oltp/native-compilation-of-tables-and-stored-procedures.md)
* Product: **sql**
* Technology: **in-memory-oltp**
* GitHub Login: @LitKnd
* Microsoft Alias: **kendralittle**

**Comment by WilliamAntonRohm** [comment]
@epiphany-it -- thank you for your feedback.  Please consider these resources:
- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server)

@LitKnd -- please look into this issue.

**Comment by LitKnd** [comment]
Hi @epiphany-it ,

Thanks for reporting this issue to us. 

I can reproduce the issue. The article for [sys.dm_os_loaded_modules](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-os-loaded-modules-transact-sql?view=sql-server-ver15) itself applies to SQL Server and Azure Synapse, and doesn't apply to Azure SQL Database, which I believe is accurate.

Reviewing this, I think there are a few things that could use refreshing in the article:
- As you point out, we should clarify that the sys.dm_os_loaded_modules DMV is not available, and perhaps provide an alternate way of querying memory optimized tables and procedures for SQL DB.
- I also see that there's a code sample in that article which enables In-Memory OLTP and adds a filegroup. This isn't necessary or possible against an Azure SQL Database, it's automatically enabled if you are using a service tier which supports it, so we should clarify that.
- In-Memory OLTP is supported by Azure SQL Managed Instance, which we don't have in the 'Applies to'. 

We should also scan related articles for similar issues.

I have created a work item to get this work scheduled. I don't have a hard date for when this will be scheduled, but it's something we have ready to be prioritized as our team has availability. 

Thanks again for reporting this. I am going to close out this issue since we now have the work item for tracking, but you can still respond to the issue even after it is closed.

Cheers,
Kendra Little from the Database Docs Team

#please-close
