### ISSUE TITLE
Where is msoledbsql.dll?

### ISSUE THREAD

**Issue by keithmbarrett** [MicrosoftDocs/sql-docs#7434]
I'm confused.  The documentation lists msoledbsql.dll as the main component, but the linked download does not install it - it installs msoledbsql19.dll instead.  How do I get msoledbsql.dll?  Or do I have to change my code to use the specific version?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63ec32fe-6b32-8d78-cc60-5780ff1ba347
* Version Independent ID: 7736fe33-e2f2-9e5c-0ea4-4ec6258cf7f2
* Content: [Components of OLE DB Driver for SQL Server - OLE DB Driver for SQL Server](https://docs.microsoft.com/en-us/sql/connect/oledb/applications/components-of-oledb-driver-for-sql-server?view=sql-server-ver15)
* Content Source: [docs/connect/oledb/applications/components-of-oledb-driver-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/oledb/applications/components-of-oledb-driver-for-sql-server.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by David-Engel** [comment]
The latest release, Microsoft OLE DB Driver 19 for SQL Server installs msoledbsql19.dll. The previous major version, Microsoft OLE DB Driver [18] for SQL Server installs msoledbsql.dll. Since major versions can be installed side-by-side, the filename changed to include the major version. There are breaking changes in v19, as noted on the download page, so be aware in case your application depends on the relevant v18 behavior.

I do see there were some missed doc updates for the v19 release around file names. I'll update those ASAP.

Regards,
David

**Comment by David-Engel** [comment]
The [Components of OLE DB Driver for SQL Server](https://docs.microsoft.com/en-us/sql/connect/oledb/applications/components-of-oledb-driver-for-sql-server?view=sql-server-ver15) page has been updated. Closing this issue now.

#please-close

**Comment by keithmbarrett** [comment]
Thanks.
