### ISSUE TITLE
sql-docs/docs/integration-services/devops/ssis-devops-overview.md limitation updates

### ISSUE THREAD

**Issue by mmercan** [MicrosoftDocs/sql-docs#7438]
Windows 2016 is deprecated and will be removed Tomorrow (2022/04/01) 
Doc still suggest to use 

SSIS Build task relies on Visual Studio and SSIS designer, which is mandatory on build agents. Thus, to run SSIS Build task in the pipeline, **you must choose vs2017-win2016 for Microsoft-hosted agents**, or install Visual Studio and SSIS designer (either VS2017 + SSDT2017, or VS2019 + SSIS Projects extension) on self-hosted agents.

going forward, is there any update on docs, how to use Microsoft-hosted agents from tomorrow morning as the statement will be invalid.

**Comment by VanMSFT** [comment]
https://docs.microsoft.com/en-us/lifecycle/products/windows-server-2016

Windows Server 2016 is still supported. Not a docs issue. Closing for now.

#reassign:VanMSFT

**Comment by VanMSFT** [comment]
@mmercan - Can you please clarify where you see it deprecated on 4/1/22? Is the option no longer available in the tool for selection, or are the jobs using that configuration failing? Is Windows 2019 an option that you can use?

**Comment by VanMSFT** [comment]
@mmercan - I see it mentioned here, but that it has been postponed. https://github.com/actions/virtual-environments/issues/5403. Thanks for bringing up this issue.

Since this is still valid, and support for windows-2019 is available according to the product page, https://marketplace.visualstudio.com/items?itemName=SSIS.ssis-devops-tools, I'll close this thread.

@chugugrace - Grace, please confirm any upcoming support for the SSIS DevOps Tools, and make the necessary changes in Docs. Thanks!
