### ISSUE TITLE
Not able to install `msodbcsql18`

### ISSUE THREAD

**Issue by Ryn0K** [MicrosoftDocs/sql-docs#7482]
Why i am not able to install `msodbcsql18`,
i follow full instruction given here [https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15)

keep note that i tried these whole installation steps in ubuntu 22.04(docker container)
![https://imgur.com/ZaXxSXX.png](https://imgur.com/ZaXxSXX.png)

i also try on earlier version of ubuntu and debian maybe some thing wrong with package respository.

Thank you

**Comment by TimShererWithAquent** [comment]
@Ryn0K - Thanks for your question. It looks like you're working through an issue with your scenario or implementation, rather than an issue with the documentation. Please consider these resources:

- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server)

**Comment by Ryn0K** [comment]
sir only question why i can't able to install `msodcsql18`

**Comment by TimShererWithAquent** [comment]
Hi @Ryn0K This board supports the documentation. The links above might help with troubleshooting.

**Comment by Ryn0K** [comment]
ok let me try
