### ISSUE TITLE
"Creating User-Defined Types - Coding" mentions undefined C# variable `nullMarker`

### ISSUE THREAD

**Issue by CaiusJard** [MicrosoftDocs/sql-docs#7560]
Affected page: https://docs.microsoft.com/en-gb/sql/relational-databases/clr-integration-database-objects-user-defined-types/creating-user-defined-types-coding?view=sql-server-ver15

Issue: C# example code uses a variable that isn't defined anywhere; it has unknown type and content

Ctrl-F on this page for `nullMarker`, one hit;

```
// IBinarySerialize methods  
// The binary layout is as follow:  
//    Bytes 0 - 19:Culture name, padded to the right   
//    with null characters, UTF-16 encoded  
//    Bytes 20+:Decimal value of money  
// If the culture name is empty, the currency is null.  
public void Write(System.IO.BinaryWriter w)  
{  
    if (this.IsNull)  
    {  
        w.Write(nullMarker); 
                ^^^^^^^^^^
          no code example code defines this     
```

**Comment by WilliamAntonRohm** [comment]
@CaiusJard -- thank you for bringing this to our attention.  Please consider these resources:
- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server)

@rothja -- please look into this issue.

**Comment by rwestMSFT** [comment]
@rothja I suspect `nullMarker` is meant to store a value like `Nothing` (equivalent of a `null`) in C#, based on the context, but the code writes a null marker and then immediately follows that with a zero, so perhaps it's redundant.

@CaiusJard Do you mind removing the line that contains the reference to `nullMarker` and see if it still works? If so, we'll remove it from the article.

**Comment by rothja** [comment]
@rwestMSFT Thanks for the suggestion! @CaiusJard If you get a chance to test the code without that line, let us know if it works and we'll update the article, as Randolph mentioned. Otherwise, we'll make a note to take a look at this article and its code samples for a refresh in the future when we have time to set up an environment to test and verify the change. I am going to close this issue for now, but please comment on it at any time and we'll follow up. Thank you!
