### ISSUE TITLE
Clarify Restore Limitations 

### ISSUE THREAD

**Issue by RandyInMarin** [MicrosoftDocs/sql-docs#7771]
[Enter feedback here]
Under the section "Limitations on Restoring System Databases", there is this statement.  

_System databases can be restored only from backups that are created on the version of SQL Server that the server instance is currently running._

It is not clear what version means.  Is the version just related to the patch level version number or does it include the edition?  For example, can a master backup from a ENT edition be restored to a DEV edition of the same patch level?  How about STD<->DEV, etc. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4344151b-127b-b10b-9b45-b877d0b965da
* Version Independent ID: bdcad8d7-587e-118b-e4c0-facebdce84c4
* Content: [Backup & restore: system databases - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/backup-restore/back-up-and-restore-of-system-databases-sql-server?view=sql-server-ver16)
* Content Source: [docs/relational-databases/backup-restore/back-up-and-restore-of-system-databases-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/backup-restore/back-up-and-restore-of-system-databases-sql-server.md)
* Product: **sql**
* Technology: **backup-restore**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@RandyInMarin -- Randy, thank you for your feedback.  Please consider these resources:
- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server)

@MashaMSFT -- Masha, please look into this issue.

**Comment by rwestMSFT** [comment]
Version refers to major version (for example, SQL Server 2019). There were some caveats in older (unsupported) versions when features were introduced in service packs, where restoring to a previous build on the same major version might affect the internal database version. This is far less likely nowadays, especially since SQL Server 2016 Service Pack 1.

In *most* cases for any database which is at least on SQL Server 2016 Service Pack 1, a restore will work across editions on the same version, but you should check whether you're using enterprise-only features by querying `sys.dm_db_persisted_sku_features`. This is because Developer edition has the same features as Enterprise edition, so you don't want to be taken by surprise if going from Developer to Standard, which is where that DMV comes into play.

I hope that helps.

**Comment by RandyInMarin** [comment]
Yes it does.  Thanks.

**Comment by rwestMSFT** [comment]
#please-close
