### ISSUE TITLE
Optimized Plan Forcing and dbcompat

### ISSUE THREAD

**Issue by rgward** [MicrosoftDocs/sql-docs#7862]
I have found that this statement is not true

Optimized plan forcing is enabled by default for new databases created in SQL Server 2022 and higher. The Query Store must be enabled for every database where optimized plan forcing is used. Upgraded instances with existing databases or databases restored from a lower version of SQL Server will not have optimized plan forcing enabled by default.

I've been able to get OPF working with databases at any dbcompat level

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69bc661e-a0db-c612-bb24-bdfb666403ab
* Version Independent ID: 69bc661e-a0db-c612-bb24-bdfb666403ab
* Content: [Optimized plan forcing with Query Store - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/performance/optimized-plan-forcing-query-store?view=sql-server-ver16)
* Content Source: [docs/relational-databases/performance/optimized-plan-forcing-query-store.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/performance/optimized-plan-forcing-query-store.md)
* Product: **sql**
* Technology: **performance**
* GitHub Login: @thesqlsith
* Microsoft Alias: **derekw**

**Comment by thesqlsith** [comment]
"I've been able to get OPF working with databases at any dbcompat level"
That is correct.  The feature is not gated by db compat but is on by default.  The db scoped configuration currently shows 0 for the feature, which is on in this particular case.  Long story behind the 0 and 1 bits and their meaning for this feature.

"The Query Store must be enabled for every database where optimized plan forcing is used."
This is a requirement for us to persist the optimization replay script.  It is true that technically the Query Store can be in a read only state or off and OPF will continue to capture and replay its generated optimization replay script.  The replay script is saved as part of the showplan_xml and is cached.  Because there is limited space in the procedure cache (as you know as the inventor of the "Inside the Memory of SQL Server" series :-) ), so the presence of the ORS can affect the total number of query plans that can be stored in procedure cache, so another "temporary" cache has been created to hold the ORS data.  We align the ORS capture policy with the Query Store capture policy in order to reduce the amount of memory used by ORS.

![image](https://user-images.githubusercontent.com/34077013/181154326-0572f5e1-25c4-4ea7-8e1b-f9867faf4ef5.png)

In cases where the replay step fails for some reason, the optimizer will fall back to forcing the plan using the "USE PLAN" code path in case of APRC’s plan forcing, or to a normal compile of the query from the plan cache if the plan still exists in cache.  Otherwise, it is just a regular compile.

"Upgraded instances with existing databases or databases restored from a lower version of SQL Server will not have optimized plan forcing enabled by default"
Would you mind sharing which CTP you are using?  OPF should not be on when a database is restored from a SQL Server 2019 or lower instance.  Will definitely investigate that behavior.

**Comment by thesqlsith** [comment]
#please-close
