### ISSUE TITLE
Default for "ADR Preallocation Factor" seems to be 0 instead of 4

### ISSUE THREAD

**Issue by MelK-HH** [MicrosoftDocs/sql-docs#7892]
[Enter feedback here]
The article states that the default for "ADR Preallocation Factor" is 4. Throughout all my SQL 2019 installations this configuration is set to 0 and has not been changed by me. Has the default been changed or is this a documentation error?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f0e86a7-309a-65ac-35a1-60af5d705e03
* Version Independent ID: 5d632653-e6c0-efa1-a5d4-31193018f340
* Content: [ADR Preallocation Factor configuration option - SQL Server](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/adr-preallocation-factor-server-configuration-option?view=sql-server-ver16)
* Content Source: [docs/database-engine/configure-windows/adr-preallocation-factor-server-configuration-option.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/adr-preallocation-factor-server-configuration-option.md)
* Product: **sql**
* Technology: **configuration**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by TimShererWithAquent** [comment]
@MelK-HH Thanks for finding this. We'll check what's going on.

**Comment by rwestMSFT** [comment]
@MelK-HH It turns out that there was a known issue depending on the CU you had installed, and we updated the article in the time since this was written.

[This should give you some more information about the issue](https://learn.microsoft.com/sql/database-engine/configure-windows/adr-preallocation-factor-server-configuration-option?view=sql-server-ver15#known-issue).

**Comment by MelK-HH** [comment]
@rwestMSFT: Thank you for the clarification.
