### ISSUE TITLE
Columnstore index creation on computed column generates error, does not match documentation

### ISSUE THREAD

**Issue by JohnTatro** [MicrosoftDocs/sql-docs#7916]
Would this sentence:  "You cannot create a nonclustered index on a columnstore index that has a computed column."
be more clearly written like this:

"You cannot create a nonclustered columnstore index on a computed column."

I tried to create a nonclustered index on several columns (SQL Server 2019), but got this error: "Columnstore index cannot include a computed column implicitly or explicitly."

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f005780-e6f8-10e5-a891-00a20254a64b
* Version Independent ID: 5d875140-6fb9-d85b-3e15-fa440bc49096
* Content: [What's new in columnstore indexes - SQL Server](https://docs.microsoft.com/en-us/sql/relational-databases/indexes/columnstore-indexes-what-s-new?view=sql-server-ver16)
* Content Source: [docs/relational-databases/indexes/columnstore-indexes-what-s-new.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/indexes/columnstore-indexes-what-s-new.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@JohnTatro -- John, thank you for your suggestion.  I am updating the article.

**Comment by rwestMSFT** [comment]
I'm not sure this is technically correct, @WilliamAntonRohm. We should defer to the product group to confirm the change.

**Comment by rwestMSFT** [comment]
Hi @WilliamAntonRohm and @JohnTatro.

I used the `AdventureWorks2019` database, which is running in compatibility mode 140 (SQL Server 2017). I was able to create a **nonclustered columnstore index** on the `Sales.SalesOrderHeader` table, which contains two computed columns.

I then created a new table based on `Sales.SalesOrderHeader` that does not have a clustered index on the Primary Key, because a clustered columnstore index is not possible on a table that already has a clustered index. I then attempted to create a **clustered columnstore index** on this table using SQL Server Management Studio's index wizard. SSMS suggested that creating an index was not possible, and listed computed columns and foreign key relationships as reasons why.

However, I was able to script the change as Transact-SQL, and it ran successfully.

These findings are curious. For starters, the proposed edit by @JohnTatro is unfortunately not correct. However, the original sentence in the article appears to be incorrect as well, or more likely a version-specific issue. It is possible that more recent versions of SQL Server allow the creation of these indexes, but the tooling has not been updated. Or, it could be something else entirely.

I need to go back to the product group and present my findings, but I wanted to let you both know what I discovered in the meantime.

**Comment by rwestMSFT** [comment]
#assign:rwestMSFT

**Comment by rwestMSFT** [comment]
@JohnTatro We're closing this here because we're tracking it internally and will update the article during our next refresh cycle. I want to thank you on behalf of the product team for raising this issue. A lot of work has happened behind the scenes to confirm columnstore and nonclustered index behaviour, and it wouldn't have been possible without your help.

When we have something to share, I'll add a comment here.

#please-close

**Comment by JohnTatro** [comment]
Thanks for all your work on this and for the updates. Glad I was able to help a bit by raising this issue.

On Sep 16, 2022, at 12:54 PM, Randolph West MSFT ***@***.***> wrote:

﻿

@JohnTatro<https://github.com/JohnTatro> We're closing this here because we're tracking it internally and will update the article during our next refresh cycle. I want to thank you on behalf of the product team for raising this issue. A lot of work has happened behind the scenes to confirm columnstore and nonclustered index behaviour, and it wouldn't have been possible without your help.

When we have something to share, I'll add a comment here.

#please-close
