### ISSUE TITLE
when support MACOS Ventura 13.0

### ISSUE THREAD

**Issue by pongsan-dev** [MicrosoftDocs/sql-docs#7995]
[Enter feedback here]

for document, When support macOS Ventura 13.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35f591be-6564-c959-7a92-6489bdd4f60b
* Version Independent ID: eec72536-eda0-1bc8-a41a-36ed4b9a8883
* Content: [Linux and macOS Installation for the Drivers for PHP - PHP drivers for SQL Server](https://docs.microsoft.com/en-us/sql/connect/php/installation-tutorial-linux-mac?view=sql-server-ver16#installing-on-macos)
* Content Source: [docs/connect/php/installation-tutorial-linux-mac.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/php/installation-tutorial-linux-mac.md)
* Product: **sql**
* Technology: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by WilliamAntonRohm** [comment]
@pongsan-dev -- Pongsan, thank you for your question.  Please consider these resources:
- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server)

@David-Engel -- David, do we have a roadmap document?

**Comment by David-Engel** [comment]
We don't have a public roadmap document. But I always tell people asking these types of questions to look at the past release patterns to discern the answer to this type of question:
[SQL Server Drivers Blog](https://techcommunity.microsoft.com/t5/sql-server-blog/bg-p/SQLServer/label-name/SQLServerDrivers)
[Release Notes for the Microsoft ODBC Driver for SQL Server on Linux and macOS](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/release-notes-odbc-sql-server-linux-mac?view=sql-server-ver16)

macOS Ventura 13.0 hasn't even had it's final release, yet. Look for official support in the regularly-scheduled ODBC release following Ventura's final release. In the meantime, if you are testing the Ventura beta out and the current MS ODBC Driver is not working for you, you could file an issue with details over at the [Microsoft/homebrew-mssql-release](https://github.com/Microsoft/homebrew-mssql-release) repo to give them a heads up of what they might expect to encounter when they start working on it. (Don't expect them to fix anything immediately, since it's not yet supported.)

Regards,
David

**Comment by WilliamAntonRohm** [comment]
@David-Engel -- David, thank you for your detailed clarification.

@pongsan-dev -- Pongsan, I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
