### ISSUE TITLE
Does set "Max server memory" to a specific value using sp_configure have any effect on SQL Server on Linux? 

### ISSUE THREAD

**Issue by wzcgh2019** [MicrosoftDocs/sql-docs#8221]
On Windows, SSMS/sp_configure is used to set "Max server memory". 
On Linux, if run those sp_configure commands, they will be successful as well.  
Will these settings take effect on Linux?
We understand we need to use memorylimitmb. Just wanna to understand, if we use the old Windows-style, does it have any effect or the database engine will ignore. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9c0b1027-3982-e114-0230-c6bd9bd81346
* Version Independent ID: 244740de-8817-1671-387d-970f8ee8dfcb
* Content: [Configure SQL Server settings on Linux - SQL Server](https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-configure-mssql-conf?view=sql-server-ver16#memorylimit)
* Content Source: [docs/linux/sql-server-linux-configure-mssql-conf.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-configure-mssql-conf.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by WilliamAntonRohm** [comment]
@wzcgh2019 -- thank you for your questions.  Please consider these resources:
- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server)

@VanMSFT -- Van, please look into this issue.

**Comment by amvin87** [comment]
I will also verify the below statement internally, but as far as I understand:
'max server memory' limits the size of the **_SQL Server buffer pool_**, whereas the memorylimitmb setting in the mssql conf enables SQL Server to identify the total memory on the host. By default, for SQL Server on Linux, the SQL Server process can only see 80% of the total memory, and using the 'max server memory' we can control the buffer pool size out of the total memory that SQL Server can identify on the host. 
Eg: If the total memory on SQL Server host Linux machine is 1TB, by default SQL Server is limited to 80% of 1TB i.e 800 GB, and the rest 200 GB is left for the OS. Now, using the memorylimitmb option in mssql.conf you can set that to 900GB thus SQL Server now sees 900GB instead of 800GB and using the max server memory option you can set the Bpool (Buffer pool) size to ensure other components of SQL Server have enough memory available like threads and stacks size for each thread.

**Comment by rwestMSFT** [comment]
This is correct, thanks Amit.

The Linux kernel tends to terminate processes using too many resources, and so by default we limit SQL Server to use 80% of the available RAM using `memorylimitmb` (a setting you can increase when you have more RAM, but be sure to test to avoid out-of-memory events).

We might say that the amount of RAM available to SQL Server on Linux is limited by **max server memory** or `memorylimitmb`, whichever is *lower*. However, the **max server memory** setting only limits the *buffer pool*. In other words, if your **max server memory** is set lower than `memorylimitmb`, SQL Server can still use anything in that range for other processes, but no more than `memorylimitmb`.

**Comment by wzcgh2019** [comment]
Thanks there. Awesome. That makes sense.
________________________________

**Comment by rwestMSFT** [comment]
#please-close
