### ISSUE TITLE
Friend query is directional, fails to find Alice and the restaurants that she likes.

### ISSUE THREAD

**Issue by thecatt** [MicrosoftDocs/sql-docs#8231]
Friend query is directional, fails to find Alice and the restaurants that she likes.  So the query "Find Restaurants that John's friends like" completely ignores Alice, who is a friend of John's, as defined by the friendOf.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 84c44dc1-637b-22b0-35db-0668d741818d
* Version Independent ID: 5425118c-d998-df3e-89ee-29656a8aa07c
* Content: [SQL Graph Database Sample - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/graphs/sql-graph-sample?view=sql-server-ver16)
* Content Source: [docs/relational-databases/graphs/sql-graph-sample.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/graphs/sql-graph-sample.md)
* Product: **sql**
* Technology: ****
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@thecatt -- thank you for your feedback.  Please consider these resources:
- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server)

@MikeRayMSFT -- please look into this issue.

**Comment by MikeRayMSFT** [comment]
Reviewing. Will get back to you.

**Comment by arvindshmicrosoft** [comment]
Yes, SQL graph implements a directional graph and hence traversals done via. MATCH are also strictly directional. I can see how this sample might create confusion as it depicts a one-way friendship. In order to represent a mutual friendship between John and Alice in this sample graph, an additional `friendOf` edge would have to be created from John to Alice:
```sql
INSERT INTO friendOf
VALUES ((SELECT $NODE_ID FROM Person WHERE ID = 1), (SELECT $NODE_ID FROM Person WHERE ID = 3))
```

For the future, we can re-examine the choice of the friendOf edge if it is causing confusion.

**Comment by MikeRayMSFT** [comment]
#please-close
