### ISSUE TITLE
Inaccurarcies in topic GRANT System Object Permissons

### ISSUE THREAD

**Issue by sommarskog** [MicrosoftDocs/sql-docs#8238]
This is about the topic 
https://learn.microsoft.com/en-us/sql/t-sql/statements/grant-system-object-permissions-transact-sql?view=sql-server-ver16

There is a quite bit of text in this topic, but it fails to point out two important things:
1) You must be in the master database to grant these permissions.
2) The principal you grant the permissions to must be a user in master. That is, if these are server-level permissions, you cannot grant them to server principals, only database principals.

And the second point leads to the question: should we really create users in master? But maybe the topic should not go that far in the discussion.

In any case, there is an example which starts with USE AdventureWorks2012 which is plain wrong.

**Comment by WilliamAntonRohm** [comment]
@sommarskog -- thank you again for your feedback.

@VanMSFT -- please look into this issue.

**Comment by VanMSFT** [comment]
Thanks, @sommarskog! You're correct, we should add some more context, as well as the example is wrong.

@AndreasWolter - Andreas, can you please help comment and give your thoughts?

**Comment by AndreasWolter** [comment]
@VanMSFT I will work through it. There are a few more imprecise statements I believe. Need to do some testing
@sommarskog Actually those are not server scope permissions. Server scoped permissions would be granted to Logins. But these are system objects (residing in resource-db), exposed in master and only controllable from master. And that's why it requires user-accounts. Its not ideal to do that, but if truly necessary, this is the technically correct way.

**Comment by rwestMSFT** [comment]
We've staged an update, which will publish in the next few days. Thanks again for your feedback, Erland.
