### ISSUE TITLE
After using this masking the SQL Server Enterprise Manager fails to generate create script

### ISSUE THREAD

**Issue by Thorium** [MicrosoftDocs/sql-docs#8253]
[Enter feedback here]
After using these maskings the SQL Server Enterprise Manager fails to generate create script for the table:

![image](https://user-images.githubusercontent.com/229355/201067774-e0b7c0dd-c8e3-4854-abba-461d28cee777.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5b9408bf-18b5-339f-cd25-6a3024be3243
* Version Independent ID: eea4b8dc-5598-b7e6-e01a-902d5ca1f96d
* Content: [Dynamic Data Masking - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/security/dynamic-data-masking?view=sql-server-ver16)
* Content Source: [docs/relational-databases/security/dynamic-data-masking.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/dynamic-data-masking.md)
* Product: **sql**
* Technology: **security**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hi @Thorium - Sorry you're having issues. Can you provide greater details on where you're having issues? Our doc examples don't include a `BirthDate` column. There's a **BirthDay** column in the example. If you're having issues other than from the documentation example, please see options for Support.

**Comment by Thorium** [comment]
Hi, I did try to change it to BirthDay but still having the same issue.

**Comment by VanMSFT** [comment]
Hi @Thorium - Sorry you're still having issues. Please try these resources to help with your issues:

- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server)

Since this isn't a documentation issue, I will be closing this.
