### ISSUE TITLE
Confusion as to minimum supported JDBC driver version for Azure Managed Instance

### ISSUE THREAD

**Issue by frachel** [MicrosoftDocs/sql-docs#8291]
A product we use bundles the SQL Server JDBC driver 6.4, and it started giving us errors today. We connect to a Managed Instance and I was looking for clarification on the support matrix.

According to the table, 6.4 is the lowest version that supports "Azure Managed Instance" - BUT - 6.4 does NOT support SQL Server 2019 - and it is my understanding that "under the hood" a Managed Instance is generally "equal to or newer than" the "latest GA release of SQL Server".. so at this point in time that is SQL Server 2022.. the confusion comes from the matrix saying 6.4 supports "Azure Sql MI", but under-the-hood the MI is probalby SQL server 2019 (or 2022 as of today), so it 6.4 officially supported by a MI?

I'm trying to get the vendor to upgrade and am looking for official word, since right now they look at the matrix and say "its supported", even though we're having problems now..

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 428f1edd-45d8-d0e1-5c77-970b18c877d8
* Version Independent ID: fe980aa0-299d-c16f-1b3e-8b5300cb70c1
* Content: [Support matrix - JDBC Driver for SQL Server](https://learn.microsoft.com/en-us/sql/connect/jdbc/microsoft-jdbc-driver-for-sql-server-support-matrix?view=sql-server-ver16)
* Content Source: [docs/connect/jdbc/microsoft-jdbc-driver-for-sql-server-support-matrix.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/jdbc/microsoft-jdbc-driver-for-sql-server-support-matrix.md)
* Service: **sql**
* Sub-service: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by WilliamAntonRohm** [comment]
@frachel -- Frank, thank you for your feedback.  Please consider these resources:
- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server)

@David-Engel -- David, please look into this issue.

**Comment by David-Engel** [comment]
From the client side (the driver), we don't go back and validate all previous versions of a driver when a new version of a server comes out. It's up to a server as to how backwards compatible it remains. This is why we define communication protocol specifications that both clients and servers adhere to. As long as they both support the same specification, things should work.

(Non-official response)
That said, servers generally attempt to remain _extremely_ backwards compatible with existing clients. (Caveat: That's to the extent that those clients supported server features at the time of their release. New server features _may_ require a newer client to support those features.)

So a client will generally be compatible with newer servers (including Azure SQL Managed Instance) for quite a long time. For example. the "SQL Server" ODBC driver that ships with Windows is over 20 years old, hasn't seen any significant updates since at least 2005, and still works against SQL Server 2022. (I don't think you'll find that combination officially documented as "supported" anywhere, though.)

The documentation for Azure SQL Managed Instance claims the highest SQL Server compatibility levels, so I doubt this is a driver compatibility issue. I highly recommend contacting Microsoft Support to help troubleshoot your errors. There is probably a configuration issue going on rather than a driver-incompatibility issue.

Regards,
David

**Comment by David-Engel** [comment]
#please-close
