### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by cavanleesears** [MicrosoftDocs/sql-docs#8401]
This:-

DECLARE @jsonVariable NVARCHAR(MAX);

SET @jsonVariable = N'[
  {
    "Order": {  
      "Number":"SO43659",  
      "Date":"2011-05-31T00:00:00"  
    },  
    "AccountNumber":"AW29825",  
    "Item": {  
      "Price":2024.9940,  
      "Quantity":1  
    }  
  },  
  {  
    "Order": {  
      "Number":"SO43661",  
      "Date":"2011-06-01T00:00:00"  
    },  
    "AccountNumber":"AW73565",  
    "Item": {  
      "Price":2024.9940,  
      "Quantity":3  
    }  
  }
]';

-- INSERT INTO <sampleTable>  
SELECT SalesOrderJsonData.*
FROM OPENJSON (@jsonVariable, N'$')
  WITH (
    Number VARCHAR(200) N'$.Order.Number',
    Date DATETIME N'$.Order.Date',
    Customer VARCHAR(200) N'$.AccountNumber',
    Quantity INT N'$.Item.Quantity'
  ) AS SalesOrderJsonData;

Causes this:-

Started executing query at Line 1
Msg 102, Level 15, State 1, Line 32
Incorrect syntax near '$.Order.Number'.
Total execution time: 00:00:00.002

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 991167bc-4e0e-1fc8-d0bb-f282b51b3321
* Version Independent ID: 0b5cf834-d452-dd57-d51d-268083011e33
* Content: [Work with JSON data - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/json/json-data-sql-server?view=sql-server-ver16)
* Content Source: [docs/relational-databases/json/json-data-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/json/json-data-sql-server.md)
* Service: **sql**
* Sub-service: ****
* GitHub Login: @jovanpop-msft
* Microsoft Alias: **jovanpop**

**Comment by WilliamAntonRohm** [comment]
@cavanleesears -- thank you for your feedback.  Please consider these resources:
- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server)

@jovanpop-msft -- please look into this issue.

**Comment by cavanleesears** [comment]
In my haste, I forgot to add that I was using Microsoft Azure Studio connected to a SQL Server 2019 Developer Edition.
Also, thanks for the resource links, I already know of these, but it's good to know that I'm approaching the right sites for answers.  :)

**Comment by jovanpop-msft** [comment]
The syntax is valid, I executed it successfully on Azure SQL/Synapse SQL.  @cavanleesears - could you re-try it with another version or endpoint because maybe something is wrong on your version.
<img width="765" alt="image" src="https://user-images.githubusercontent.com/20593304/208876479-448f39c2-a978-40d1-b917-6628cf56a808.png">

**Comment by cavanleesears** [comment]
Hi Jovan,

You are correct, the syntax is valid, but do you notice the difference between:

***@***.***

And this?:-

***@***.***

Both queries are exactly the same, except that the unsuccessful query is run from within a database created by me while the successful one runs under 'master'.  Why is that?

Regards,

Lee.

**Comment by jovanpop-msft** [comment]
Hi @cavanleesears, 

It seems that your text is masked, and I see just ***@***.***

Even if I run it in a different database this is working fine (tried on serverless SQL pool). 
This issue is for documentation only and we will not change this example because the syntax is valid, and it should work. I don't have SQL Server 2019 dev edition, so I cannot try it, but since it looks like a product specific or maybe a bug in that SQL Server version.

<img width="753" alt="image" src="https://user-images.githubusercontent.com/20593304/208922559-8dc08848-1e31-4fad-a3ac-f9ae8eb9bb06.png">

**Comment by rwestMSFT** [comment]
Agreed this is not a documentation issue.

#please-close
