### ISSUE TITLE
Fixing orphaned users in SQL Azure

### ISSUE THREAD

**Issue by ThinkElevenDave** [MicrosoftDocs/sql-docs#8449]
This page would benefit from additional details on addressing orphaned users in SQL Azure where there is no master database.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f1b639be-9b0f-3b6a-d4eb-0826663ec5d6
* Version Independent ID: 19cd7d45-f285-5b83-9144-f4f057dc3bcd
* Content: [Troubleshoot orphaned users - SQL Server Always On](https://learn.microsoft.com/en-us/sql/sql-server/failover-clusters/troubleshoot-orphaned-users-sql-server?view=sql-server-ver16)
* Content Source: [docs/sql-server/failover-clusters/troubleshoot-orphaned-users-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/failover-clusters/troubleshoot-orphaned-users-sql-server.md)
* Service: **sql**
* Sub-service: **high-availability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@ThinkElevenDave -- David, thank you for your suggestion.  Please consider these resources:
- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server)

@MashaMSFT -- Masha, please look into this issue.

**Comment by VanMSFT** [comment]
Hi @ThinkElevenDave, can you please elaborate on what you mean by orphaned users in Azure SQL?

**Comment by MashaMSFT** [comment]
Hi @ThinkElevenDave , thanks for contacting Microsoft! The steps to resolve orphaned users in the article are applicable to Azure SQL Database. As @VanMSFT mentioned, there's an accessible `master` database. It just doesn't always have the same tables, which is why identifying orphaned users is different for SQL Database. I'll go ahead and close out this Git Issue but please feel free to comment should you need anything further.

Thanks again and I hope you have a wonderful rest of your day!
Masha from the SQL Docs team
#please-close

**Comment by ThinkElevenDave** [comment]
The example would be backing up an on-premise DB and then restoring into Azure SQL.  The users become orphaned.  Accessing Master from SSMS is straightforward, but this wasn't obvious in Azure SQL Query Editor.
