### ISSUE TITLE
Symbolic debugging for SSMS

### ISSUE THREAD

**Issue by rwales1000** [MicrosoftDocs/sql-docs#8464]
I read your article on how to use the debugger.  It indicates that Debug is an option in the Query menu.  I'm not finding it.  It would be helpful to have more information about how to make the debugger available.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 51b0c608-968b-9d25-40ca-164da2afd599
* Version Independent ID: fc089c8c-7572-dbf6-dec9-f0ca1d0833cc
* Content: [Transact-SQL Debugger Information - T-SQL debugger](https://learn.microsoft.com/en-us/sql/ssms/scripting/transact-sql-debugger-information?view=sql-server-ver16)
* Content Source: [docs/ssms/scripting/transact-sql-debugger-information.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/scripting/transact-sql-debugger-information.md)
* Service: **sql**
* Sub-service: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by WilliamAntonRohm** [comment]
@rwales1000 -- thank you for your feedback.  Please consider these resources:
- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server)

@markingmyname -- please look into this issue.

**Comment by markingmyname** [comment]
@rwales1000 

May I ask what version of SSMs are you using, please?

thank you.

**Comment by markingmyname** [comment]
@@rwales1000 

Due to the delay in response and lack of info, we will close this issue.

We will now proceed to close this thread. If there are further questions, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue. To see what the community wants, please visit the [SQL Server User Feedback](https://feedback.azure.com/d365community/forum/04fe6ee0-3b25-ec11-b6e6-000d3a4f0da0) site or the [Q&A](https://docs.microsoft.com/en-us/answers/products/sql-server) site.
