### ISSUE TITLE
error installation in a LXC container

### ISSUE THREAD

**Issue by Zebracell** [MicrosoftDocs/sql-docs#8525]
lxc container from template ubuntu_20_04
after running /opt/mssql/bin/mssql-conf setup 

Choose an edition of SQL Server:
  1) Evaluation (free, no production use rights, 180-day limit)
  2) Developer (free, no production use rights)
  3) Express (free)
  4) Web (PAID)
  5) Standard (PAID)
  6) Enterprise (PAID) - CPU core utilization restricted to 20 physical/40 hyperthreaded
  7) Enterprise Core (PAID) - CPU core utilization up to Operating System Maximum
  8) I bought a license through a retail sales channel and have a product key to enter.
  9) Standard (Billed through Azure) - Use pay-as-you-go billing through Azure.
 10) Enterprise Core (Billed through Azure) - Use pay-as-you-go billing through Azure.

Details about editions can be found at
https://go.microsoft.com/fwlink/?LinkId=2109348&clcid=0x409

Use of PAID editions of this software requires separate licensing through a
Microsoft Volume Licensing program.
By choosing a PAID edition, you are verifying that you have the appropriate
number of licenses in place to install and run this software.
By choosing an edition billed Pay-As-You-Go through Azure, you are verifying 
that the server and SQL Server will be connected to Azure by installing the 
management agent and Azure extension for SQL Server.

Enter your edition(1-10): 3
The license terms for this product can be found in
/usr/share/doc/mssql-server or downloaded from:
https://go.microsoft.com/fwlink/?LinkId=2104294&clcid=0x409

The privacy statement can be viewed at:
https://go.microsoft.com/fwlink/?LinkId=853010&clcid=0x409

Enter the SQL Server system administrator password: 
Confirm the SQL Server system administrator password: 
Configuring SQL Server...

This program has encountered a fatal error and cannot continue running at Wed Jan 25 09:20:28 2023
The following diagnostic information is available:

         Reason: 0x00000001
         Signal: SIGABRT - Aborted (6)
          Stack:
                 IP               Function
                 ---------------- --------------------------------------
                 00005573f3fdd5b2 <unknown>
                 00005573f3fdcfd0 <unknown>
                 00005573f3fdc66f <unknown>
                 00007f051c033090 killpg+0x40
                 00007f051c03300b gsignal+0xcb
                 00007f051c012859 abort+0x12b
                 00005573f3f82f76 <unknown>
                 00005573f400deba <unknown>
        Process: 1209 - sqlservr
         Thread: 1214 (application thread 0x8)
    Instance Id: d90be36c-e3d0-42c8-ab90-3ca66ef0aa55
       Crash Id: 0b0f9e34-f31a-4121-bc62-5ed9a5b7e7fe
    Build stamp: d81e9b6de06534e649bd57dd609aa3050f5e380f361b7f8a80a80eeb71e7422c
   Distribution: Ubuntu 20.04.5 LTS
     Processors: 3
   Total Memory: 16744837120 bytes
      Timestamp: Wed Jan 25 09:20:28 2023
     Last errno: 2
Last errno text: No such file or directory
Capturing a dump of 1209
FAILED to capture a dump. Details in paldumper log.
Executing: /opt/mssql/bin/handle-crash.sh with parameters
     handle-crash.sh
     /opt/mssql/bin/sqlservr
     1209
     /opt/mssql/bin
     /var/opt/mssql/log/
     
     d90be36c-e3d0-42c8-ab90-3ca66ef0aa55
     0b0f9e34-f31a-4121-bc62-5ed9a5b7e7fe
     
     

Ubuntu 20.04.5 LTS
Capturing core dump and information to /var/opt/mssql/log...
dmesg: read kernel buffer failed: Operation not permitted
Hint: You are currently not seeing messages from other users and the system.
      Users in groups 'adm', 'systemd-journal' can see all messages.
      Pass -q to turn off this notice.
No journal files were opened due to insufficient permissions.
Hint: You are currently not seeing messages from other users and the system.
      Users in groups 'adm', 'systemd-journal' can see all messages.
      Pass -q to turn off this notice.
No journal files were opened due to insufficient permissions.
/usr/bin/tail: cannot open '/var/log/syslog' for reading: Permission denied
Wed Jan 25 09:20:28 +05 2023 Capturing program information
Wed Jan 25 09:20:28 +05 2023 Attempting to capture a dump with paldumper for pid 1209
WARNING: Capture attempt failure detected
Attempting to capture a filtered dump with paldumper for pid 1209
WARNING: Attempt to capture dump failed.  Reference /var/opt/mssql/log/core.sqlservr.1209.temp/log/paldumper-debug.log for details
Wed Jan 25 09:20:28 +05 2023 Attempting to capture a dump with gdb
WARNING: Unable to capture crash dump with GDB. You may need to
allow ptrace debugging, enable the CAP_SYS_PTRACE capability, or
run as root. See log in: /var/opt/mssql/log/core.sqlservr.1209.temp/log/gdb.log
Wed Jan 25 09:20:29 +05 2023 Capturing program binaries
Wed Jan 25 09:20:29 +05 2023 Compressing the dump files
Core dump and information are being compressed in the background. When
complete, they can be found in the following location:
  /var/opt/mssql/log/core.sqlservr.01_25_2023_09_20_28.1209.tbz2
Initial setup of Microsoft SQL Server failed. Please consult the ERRORLOG
in /var/opt/mssql/log for more information.

**Comment by WilliamAntonRohm** [comment]
@Zebracell -- thank you for your feedback.  This repo is solely for documentation, and this seems implementation-related.  Please consider these resources:
- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by SrinivasanMyGitHub** [comment]
@Zebracell , @WilliamAntonRohm 

No solutions in Stack overflow and others sites. 

lxc container from template ubuntu_20_04
after running /opt/mssql/bin/mssql-conf setup


This program has encountered a fatal error and cannot continue running at Sun May 28 13:41:45 2023
The following diagnostic information is available:

         Reason: 0x00000001
         Signal: SIGABRT - Aborted (6)
          Stack:
                 IP               Function
                 ---------------- --------------------------------------
                 0000563b22bfe0c1 std::__1::bad_function_call::~bad_function_call()+0x1b431
                 0000563b22bfda86 std::__1::bad_function_call::~bad_function_call()+0x1adf6
                 0000563b22bfd00f std::__1::bad_function_call::~bad_function_call()+0x1a37f
                 00007f6c012a6090 killpg+0x40
                 00007f6c012a600b gsignal+0xcb
                 00007f6c01285859 abort+0x12b
                 0000563b22b8b71b std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char>>::str() const+0x7cbb
                 0000563b22c28e8a std::__1::bad_function_call::~bad_function_call()+0x461fa
        Process: 77028 - sqlservr
         Thread: 77116 (application thread 0x178)
    Instance Id: 5a8eaec7-f80f-4c43-8afc-50094b481135
       Crash Id: 5f910460-c8de-47ba-ad4c-f5546b39f378
    Build stamp: fd0334c48e3976a8a1ce02d42ec138df591493ae62f85cc4c986a1266d2bba7f
   Distribution: Ubuntu 20.04.6 LTS
     Processors: 2
   Total Memory: 2147483648 bytes
      Timestamp: Sun May 28 13:41:45 2023
     Last errno: 2
Last errno text: No such file or directory
Capturing a dump of 77028
Successfully captured dump: /var/opt/mssql/log/core.sqlservr.5_28_2023_13_41_45.77028
Executing: /opt/mssql/bin/handle-crash.sh with parameters
     handle-crash.sh
     /opt/mssql/bin/sqlservr
     77028
     /opt/mssql/bin
     /var/opt/mssql/log/

     5a8eaec7-f80f-4c43-8afc-50094b481135
     5f910460-c8de-47ba-ad4c-f5546b39f378

     /var/opt/mssql/log/core.sqlservr.5_28_2023_13_41_45.77028

Ubuntu 20.04.6 LTS
Capturing core dump and information to /var/opt/mssql/log...
find: ‘/proc/77028/map_files’: Operation not permitted
find: ‘/proc/77028/map_files’: Operation not permitted
find: ‘/proc/77028/map_files’: Operation not permitted
find: ‘/proc/77028/map_files’: Operation not permitted
Hint: You are currently not seeing messages from other users and the system.
      Users in groups 'adm', 'systemd-journal' can see all messages.
      Pass -q to turn off this notice.
No journal files were opened due to insufficient permissions.
Hint: You are currently not seeing messages from other users and the system.
      Users in groups 'adm', 'systemd-journal' can see all messages.
      Pass -q to turn off this notice.
No journal files were opened due to insufficient permissions.
tail: cannot open '/var/log/syslog' for reading: Permission denied
Sun May 28 13:41:52 UTC 2023 Capturing program information
Dump already generated: /var/opt/mssql/log/core.sqlservr.5_28_2023_13_41_45.77028, moving to /var/opt/mssql/log/core.sqlservr.77028.temp/core.sqlservr.77028.gdmp
Moving logs to /var/opt/mssql/log/core.sqlservr.77028.temp/log/paldumper-debug.log
Sun May 28 13:41:53 UTC 2023 Capturing program binaries
Sun May 28 13:41:55 UTC 2023 Compressing the dump files
Core dump and information are being compressed in the background. When
complete, they can be found in the following location:
  /var/opt/mssql/log/core.sqlservr.05_28_2023_13_41_49.77028.tbz2
Initial setup of Microsoft SQL Server failed. Please consult the ERRORLOG
in /var/opt/mssql/log for more information.
