### ISSUE TITLE
Needs better explanation for parts of code

### ISSUE THREAD

**Issue by p2c4** [MicrosoftDocs/sql-docs#8533]
Following lines require additional explanation: 

KM = (sk_cluster.KMeans(n_clusters=k).fit(cdata) for k in K)
centroids = (k.cluster_centers_ for k in KM)

D_k = (sci_distance.cdist(cdata, cent, 'euclidean') for cent in centroids)
dist = (np.min(D, axis=1) for D in D_k)
avgWithinSS = [sum(d) / cdata.shape[0] for d in dist]

...

n_clusters = 4

means_cluster = sk_cluster.KMeans(n_clusters=n_clusters, random_state=111)
columns = ["orderRatio", "itemsRatio", "monetaryRatio", "frequency"]
est = means_cluster.fit(customer_data[columns])

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bcc4c909-69da-9b9b-cb65-e51af628514e
* Version Independent ID: 401e20a9-0e91-f10b-a04c-f6e747e5cd56
* Content: [Python tutorial: Build cluster model - SQL machine learning](https://learn.microsoft.com/en-us/sql/machine-learning/tutorials/python-clustering-model-build?view=sql-server-ver16)
* Content Source: [docs/machine-learning/tutorials/python-clustering-model-build.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/machine-learning/tutorials/python-clustering-model-build.md)
* Service: **sql**
* Sub-service: **machine-learning**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamAntonRohm** [comment]
@p2c4 -- thank you for your feedback.  Please consider these resources:
- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server)

@WilliamDAssafMSFT -- William, please look into this issue.

**Comment by WilliamDAssafMSFT** [comment]
Hi @p2c4! Might be easier for you to create a Pull Request and get the ball rolling on a change yourself, instead of trying to describe the change. To give you credit as a contributor to the article, would you like to [create a Pull Request](https://docs.microsoft.com/sql/sql-server/sql-server-docs-contribute) and get the ball rolling on a change yourself? By opening a pull request, you're collaborating with the authors to add changes directly to the documentation. After the updated article is published, GitHub lists you as an article contributor. Select the **Edit** pencil at the top of the article to begin a pull request on our open source docs. You can reference this issue and my GitHub in your pull request, and I'll personally review and carry it across the finish line. Either way, thanks for your feedback!

**Comment by WilliamDAssafMSFT** [comment]
Closing for lack of comm, happy to continue discussion on improving this doc.
