### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by kevmeister68** [MicrosoftDocs/sql-docs#8543]
[Enter feedback here]
Read intent applications should say read intensive applications.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 47fd1979-b6af-5ffc-fc7e-31e2b34fe207
* Version Independent ID: 33956f4f-e50c-94d3-b996-187bf71c1ec4
* Content: [Availability groups: a high-availability and disaster-recovery solution - SQL Server Always On](https://learn.microsoft.com/en-us/sql/database-engine/availability-groups/windows/always-on-availability-groups-sql-server?view=sql-server-ver16)
* Content Source: [docs/database-engine/availability-groups/windows/always-on-availability-groups-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/availability-groups/windows/always-on-availability-groups-sql-server.md)
* Service: **sql**
* Sub-service: **availability-groups**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by WilliamAntonRohm** [comment]
@kevmeister68 -- thank you for catching this.  I am updating the article.

**Comment by MashaMSFT** [comment]
@kevmeister68 , thanks for contacting Microsoft! I don't believe that's a typo as it's meant to say that applications that are offloading workloads with the intent: read-only to the secondary replica help performance of the primary replica. Although the implication is that it's for read-intensive workloads, the use of "read-intent" seems intentional to me as it's talking about the specification in the connection string. 

@kfarlee , would you be able to confirm please?

original: In addition, offloading read-intent applications and backup jobs to secondary replicas helps to improve performance on the primary replica.

corrected: In addition, offloading read-intent applications and backup jobs to secondary replicas helps to improve performance on the primary replica.

Thanks!
Masha from the SQL Docs team

**Comment by tarynpratt** [comment]
@kevmeister68, thanks so much for your feedback, the response from @MashaMSFT is correct. The language 'read-intent' is intentional. I'll go ahead and close out this Git Issue but please feel free to comment should you need anything further.

thanks again, 
#please-close
