### ISSUE TITLE
Some typos in the Slowly Changing Dimension topic.

### ISSUE THREAD

**Issue by mbarbieri77** [MicrosoftDocs/sql-docs#8575]
12 months in the code, but variable name is sixmonths, name of tables don't seem to match different parts of the text and code.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 16923b34-9fbb-86a2-071d-c4fa47e639ff
* Version Independent ID: 83127f7a-a6cd-0b63-a723-ee72f7511a6a
* Content: [Temporal Table Usage Scenarios - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/tables/temporal-table-usage-scenarios?view=sql-server-ver16)
* Content Source: [docs/relational-databases/tables/temporal-table-usage-scenarios.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/temporal-table-usage-scenarios.md)
* Service: **sql**
* Sub-service: **table-view-index**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by rwestMSFT** [comment]
@mbarbieri77 Thank you for your feedback. I would encourage you to submit a pull request to make the changes, as it is likely to get fixed sooner that way.

**Comment by WilliamAntonRohm** [comment]
@mbarbieri77 -- Marcelo, thank you for finding these discrepancies.  A very effective option that many customers like is to edit our documentation directly through a Pull Request (PR), instead of describing the fix in an Issue. If you are ever interested, you can click the Edit pencil icon at the top-right on the article's webpage, and then click the pencil icon on the GitHub webpage.

@rwestMSFT -- Randoph, thank you for your suggestion.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
