### ISSUE TITLE
What is the Provider Naming on a Connection String? 

### ISSUE THREAD

**Issue by nojetlag** [MicrosoftDocs/sql-docs#8610]
I looked at your release notes and 19.2.0 and 19.1.0 have a significant difference (TLS 1.3), when I install the driver it gets in "Add or remove programs" clearly identified. However when I try to make a connection lets say from an SSIS package in Visual Studio and I select the "Microsoft OLE DB Driver 19 for SQL Server" and later look at the generated connection string I get "MSOLEDBSQL19.1" For the 19.2.0 package I would have expected a string like "MSOLEDBSQL19.2" or did I misunderstand the naming concept. Where could I find more information about this behaviour in the documentation ? 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c317ca97-aeb0-47ad-32c1-96dac03228db
* Version Independent ID: 0a218c3e-da57-7e34-7bff-9c41fe5f4dc5
* Content: [Release notes for OLE DB Driver - OLE DB Driver for SQL Server](https://learn.microsoft.com/en-us/sql/connect/oledb/release-notes-for-oledb-driver-for-sql-server?view=sql-server-ver16)
* Content Source: [docs/connect/oledb/release-notes-for-oledb-driver-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/oledb/release-notes-for-oledb-driver-for-sql-server.md)
* Service: **sql**
* Sub-service: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by David-Engel** [comment]
@nojetlag The provider naming concept in OLE DB can be confusing.

The version-independent provider name is "MSOLEDBSQL19" for all versions of the Microsoft OLE DB Driver 19 for SQL Server. You can specify a version-specific ProgID of an OLE DB provider, **_if a provider implements different versions_**. The MSOLDDBSQL19 provider doesn't implement different versions, so the only ProgID available is "MSOLEDBSQL19.1". You can see that same behavior starting with version 19.0 of the driver. In practice, we found that implementing different ProgIDs just became a maintenance burden on the client side and we instead maintain backwards compatibility for all releases within a major version. If we introduce a breaking change, which is rare, the version-independent provider name is changed so that moving to a new version is very intentional.

TLS 1.3 support should be transparent to the application, as far as the OLE DB API goes.

Documentation about OLE DB provider names is found under the Windows docs:
https://learn.microsoft.com/en-us/previous-versions/windows/desktop/ms722656(v=vs.85)#the-provider-keyword
That link was surprisingly hard to find as the information is unfortunately not included in the latest versions of the docs. Probably because OLE DB is, in general, considered legacy.

Regards,
David

#please-close
