### ISSUE TITLE
Information on Backing up database is out of date and no longer works

### ISSUE THREAD

**Issue by rfernand2** [MicrosoftDocs/sql-docs#8689]
After reading this documentation page, I tried 2 of the ways to backup my database, using SQL Management Studio v19:
   - Right click on database | Tools | "Back up..." menu  (the "Back up..." menu item doesn't exist)
   - Running the Transact SQL code (the code issues the error: 
         **Msg 40510, Level 16, State 1, Line 3
         Statement 'BACKUP DATABASE' is not supported in this version of SQL Server.**

I am having trouble finding the updated info for v19 searching the web, but I figured that official Microsoft docs that were updated 3 days ago, would have the correct information.  But, as you can see, it did not.  

Please update this ASAP for users like me trying to backup their Azure hosted SQL database.  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c7044c28-1682-15db-6add-77d185262f3c
* Version Independent ID: e42f8fe5-da01-d793-a799-d7102bea5eec
* Content: [Create a Full Database Backup - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/backup-restore/create-a-full-database-backup-sql-server?view=sql-server-ver16)
* Content Source: [docs/relational-databases/backup-restore/create-a-full-database-backup-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/backup-restore/create-a-full-database-backup-sql-server.md)
* Service: **sql**
* Sub-service: **backup-restore**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by MashaMSFT** [comment]
Hi @rfernand2 , thanks so much for contacting Microsoft! My apologies for the confusion caused by the documentation. At the top of articles within the SQL Server documentation set, there is typically an **Applies to:** that defines the products the article is applicable to. 

The article in question is applicable to SQL Server and not Azure SQL Database, you can see that in the screenshot here: 
![image](https://user-images.githubusercontent.com/32783170/223310641-ed280b27-74ad-41ff-8028-0d9a49ecef21.png)

Articles applicable to Azure SQL Database will list Azure SQL Database in this applies to section. More information about the **Applies to** can be found in the [navigation tips](https://learn.microsoft.com/sql/sql-server/sql-docs-navigation-guide#applies-to). 

[Automated backups](https://learn.microsoft.com/azure/azure-sql/database/automated-backups-overview) has more information about backups with Azure SQL Database. 

I hope that helps! I'll go ahead and close out this Git Issue but please feel free to comment should you need anything further.

Thanks again for reaching out and I hope you have a wonderful rest of your day!
Masha from the SQL Docs team
#please-close
#assign:MashaMSFT

**Comment by MashaMSFT** [comment]
@rfernand2 , I forgot to add :) The BACKUP command isn't supported on Azure SQL Database. 
![image](https://user-images.githubusercontent.com/32783170/223312509-21d86d48-26a1-43ca-8e00-34af5b157b30.png)

You can find more information in the [feature comparison](https://learn.microsoft.com/azure/azure-sql/database/features-comparison) article. 

Thanks again! 
Masha from the SQL Docs team
