### ISSUE TITLE
consistency would be nice

### ISSUE THREAD

**Issue by mjl38** [MicrosoftDocs/sql-docs#8692]
[Enter feedback here]
For example to use "MultiSubnetFailover" you might have to pass true/false or Yes/No. Why make things difficult?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6dd3c01f-97c8-5e89-8234-fbdfe97b25fe
* Version Independent ID: af328d78-9373-62fa-3d90-b7efe6c00ad1
* Content: [Using Connection String Keywords with OLE DB Driver - OLE DB Driver for SQL Server](https://learn.microsoft.com/en-us/sql/connect/oledb/applications/using-connection-string-keywords-with-oledb-driver-for-sql-server?view=sql-server-ver16)
* Content Source: [docs/connect/oledb/applications/using-connection-string-keywords-with-oledb-driver-for-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/oledb/applications/using-connection-string-keywords-with-oledb-driver-for-sql-server.md)
* Service: **sql**
* Sub-service: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by David-Engel** [comment]
Thanks for the feedback. I agree it would be nice to be consistent. Unfortunately, depending on which OLE DB initialization interface is being used the connection string values are different between the two. Since this isn't a documentation issue, I'm going to close it now. But I'll note the feedback for consideration in the future.

Regards,
David

#please-close
