### ISSUE TITLE
No Examples of how to access Microsoft.Data.SqlClient  from PowerShell

### ISSUE THREAD

**Issue by Frankd4** [MicrosoftDocs/sql-docs#8730]
[Enter feedback here]
Could you please add some examples of how to consume the Microsoft.Data.SqlClient via PowerShell, any examples ?
How can we use AAD Authentication types.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 947b6a2f-66c5-821d-8c58-8798a48a9f3f
* Version Independent ID: 35874772-4b2c-7679-7fa3-57e77e02fbb0
* Content: [Connect to Azure SQL with Azure AD authentication and SqlClient - ADO.NET Provider for SQL Server](https://learn.microsoft.com/en-us/sql/connect/ado-net/sql/azure-active-directory-authentication?view=sql-server-ver16)
* Content Source: [docs/connect/ado-net/sql/azure-active-directory-authentication.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/ado-net/sql/azure-active-directory-authentication.md)
* Service: **sql**
* Sub-service: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by WilliamAntonRohm** [comment]
@Frankd4 -- Frank, thank you for your suggestions.  Please consider these resources:
- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server)

@David-Engel -- David, please look into this issue.

**Comment by Frankd4** [comment]
Thank you very much, William

**Comment by David-Engel** [comment]
Unfortunately the PowerShell experience with regards to automatic dependency downloads isn't up to par. Current attempts to `Install-Package -Name Microsoft.Data.SqlClient` results in a dependency loop error (not the fault of Microsoft.Data.SqlClient) unless you add the `-SkipDependencies` option.

Dependencies are critical to AAD authentication support in Microsoft.Data.SqlClient. We have an internal tracking item to occasionally revisit the PowerShell experience to see if the landscape has changed. Once the bugs are worked out on the PowerShell side, we'll look at adding PowerShell examples to the Microsoft.Data.SqlClient documentation.

Some related issues:
https://github.com/OneGet/oneget/issues/475
https://github.com/PowerShell/PowerShellGet/issues/491
https://github.com/dotnet/SqlClient/issues/161

Closing this issue since we are tracking it internally.

Thanks,
David

#please-close

**Comment by Frankd4** [comment]
Thank you @David-Engel 
Yes, that is my experience as well. I hope this will be fixed. How would I know when this is fixed please ?
any way to track ?

**Comment by David-Engel** [comment]
> How would I know when this is fixed please ? any way to track ?

I would subscribe to one, or both, of the first two GitHub issues I linked to.

Regards,
David

**Comment by Frankd4** [comment]
Thank you @David-Engel
