### ISSUE TITLE
This one is good. Should be more prominent

### ISSUE THREAD

**Issue by sderose** [MicrosoftDocs/sql-docs#8737]
[Enter feedback here]
It took forever to find this, though once found it does give useful and clear descriptions. I bet there are a lot of people who just want to run SQL (which they already know) over SQL Server running in docker -- without having to spend many days fighting with docker to try to talk to anything outside. I think you should make this page much more prominent and much easier to find; and have a similar page that walks through how to set up the whole stack: install ADS, install sql tools, create and populate a trivial db entirely via sqlcmd -i. 

I still haven't found any way to get Python APIs to talk to SQL Server when it's buried in a container. Simply not practical to try to install, code, and run Python inside the container; also very difficult to mod the container to have decent dev tools. Do I really have to talk to SQL Server only through sqlcmd or it's equivalents listed on the page?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 39bb4ba1-ae62-07a3-f79a-138f14cf2f10
* Version Independent ID: beaa4e7d-e771-cc96-0e59-34d9b1d5e8cc
* Content: [Install SQL Server command-line tools on Linux - SQL Server](https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-setup-tools?view=sql-server-ver16&tabs=redhat-install%2Credhat-offline)
* Content Source: [docs/linux/sql-server-linux-setup-tools.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/linux/sql-server-linux-setup-tools.md)
* Service: **sql**
* Sub-service: **linux**
* GitHub Login: @VanMSFT
* Microsoft Alias: **vanto**

**Comment by VanMSFT** [comment]
Hi @sderose - Thanks for your feedback. We're always looking for ways to improve the searchability of our docs. There are many ways to connect to SQL Server on Linux, but what we have in our documentation are the supported methods. As you referenced, you can also use Azure Data Studio to connect and query SQL Server on Linux container.

https://learn.microsoft.com/en-us/sql/azure-data-studio/quickstart-sql-server?view=sql-server-ver16

Since this is not a documentation issue, I will go ahead and close this, but feel free to comment further with any feedback.

@rwestMSFT - FYI
