### ISSUE TITLE
Table of Operator Descriptions almost - but not - in alphabetical order

### ISSUE THREAD

**Issue by Davi-Gray** [MicrosoftDocs/sql-docs#8925]
There are some odd placements of operators in the table. Yet overall it's clearly intended to be in alphabetical order. Either _actually_ putting it in alpha order (easiest), or reorganizing the whole thing to be ordered by functional areas, would make it easier to use.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 75244b49-10fe-f5f7-5f36-bdc5cce5ced1
* Version Independent ID: 24fb05e3-23cb-309a-59f4-1b654bc963eb
* Content: [Showplan Logical & Physical Operators Reference - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/showplan-logical-and-physical-operators-reference?view=sql-server-ver16)
* Content Source: [docs/relational-databases/showplan-logical-and-physical-operators-reference.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/showplan-logical-and-physical-operators-reference.md)
* Service: **sql**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by WilliamAntonRohm** [comment]
@Davi-Gray -- Davi, thank you for raising this.  I am updating the article.

**Comment by rwestMSFT** [comment]
@Davi-Gray I just wanted to let you know that we're closing this issue, but not because we're done. In fact, we discovered that the article is out of date, and therefore needs significant attention.

We will be tracking this internally (AB#70883). When we have something to share, I'll comment below.

Once again, thank you for your feedback, and helping us improve Database Docs content!

**Comment by Davi-Gray** [comment]
Thanks for letting me know!

**Comment by rwestMSFT** [comment]
@Davi-Gray We finally published the updated article. Thank you for giving us the push we needed.
