### ISSUE TITLE
OBJECT_ID doesn't remark about types not working

### ISSUE THREAD

**Issue by LarnuUK** [MicrosoftDocs/sql-docs#8998]
Document: [OBJECT\_ID (Transact-SQL)](https://learn.microsoft.com/en-us/sql/t-sql/functions/object-id-transact-sql?view=sql-server-ver16)

The linked document makes the following statements:
> Returns the database object identification number of a schema-scoped object.
> 
> > **Important**  
>> Objects that are not schema-scoped, such as DDL triggers, cannot be queried by using OBJECT_ID. For objects that are not found in the [sys.objects](https://learn.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-objects-transact-sql?view=sql-server-ver16)catalog view, obtain the object identification numbers by querying the appropriate catalog view. For example, to return the object identification number of a DDL trigger, use `SELECT OBJECT_ID FROM sys.triggers WHERE name = 'DatabaseTriggerLog``'`.

The definition for its parameters are also the following:
> **'** _object_name_ **'**  
> Is the object to be used. _object_name_ is either **varchar** or **nvarchar**. If _object_name_ is **varchar**, it is implicitly converted to **nvarchar**. Specifying the database and schema names is optional.
> 
> **'** _object_type_ **'**  
> Is the schema-scoped object type. _object_type_ is either **varchar** or **nvarchar**. If _object_type_ is **varchar**, it is implicitly converted to **nvarchar**. For a list of object types, see the **type** column in [sys.objects (Transact-SQL)](https://learn.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-objects-transact-sql?view=sql-server-ver16).

This all **strongly** implies that anything that appears in `sys.objects` and is schema qualified will work for `OBJECT_ID`, however, this is not true. Table `TYPE`s, for example, do not appear in when using `OBJECT_ID`. This can be proven with the following:
```sql
CREATE TYPE dbo.asdjklashgdlas AS table (I int);
GO
SELECT OBJECT_ID(N'dbo.asdjklashgdlas') AS ObjectID;
GO
DECLARE @ObjectName sysname;

SELECT @ObjectName = name
FROM sys.objects
WHERE name LIKE 'TT[_]asdjklashgdlas%'

SELECT OBJECT_ID(@ObjectName) AS ObjectID, @ObjectName AS ObjectName;
GO
DROP TYPE IF EXISTS dbo.asdjklashgdlas;
GO
```
For my test this brought back the following datasets:
```none
ObjectID
--------
NULL

ObjectID | ObjectName
---------|--------------------------
NULL     |TT_asdjklashgdlas_6F8A7843
```
Table `TYPE`s gain a prefix and suffix in the `name` column in the `sys.objects` table, but even if you pass that to the function, it's not found.

As such the documentation should be updated, likely in the "Remarks" section to denote what object types the function won't work for that *do* appear in `sys.objects`. For (table) `TYPE`s, `TYPE_ID` should be used, for example.

I openly admit that I don't know what other object types (that appear in `sys.objects`) this behaviour also occurs for.

**Comment by WilliamAntonRohm** [comment]
@LarnuUK -- Thom, thank you for your clarification.

**Comment by rwestMSFT** [comment]
@LarnuUK I've done some investigation of my own.

Once you create the object, you will see it in `sys.objects`, where it receives a value in the `object_id` column. You will also see it in `sys.types`, with a `user_type_id`, but no `object_id`.

Notwithstanding the confusion about naming things, I don't think there's a guarantee (stated or otherwise) that a value in the `object_id` column translates 1:1 to the ability to run the `OBJECT_ID` function against that object. I don't remember where I read it (it was a long time ago now), but as I recall, our advice is to use the system catalog views if you're looking for system object information.

This isn't to say that the article is entirely accurate. I agree that it could do with some rewording at the top, but as this isn't high on the priority list, it may take several months to be addressed. (Consider how long it took for us to get to this point.)

Therefore I am adding this to the backlog, and closing this issue for now. If we update the article, we will make a note here that it has been updated.

AB#70883
