### ISSUE TITLE
GENERATE_SERIES AND STRING_SPLIT not Recognized with Compatibility 160

### ISSUE THREAD

**Issue by JFKallen** [MicrosoftDocs/sql-docs#9016]
According to this page and other documentation, GENERATE_SERIES and STRING_SPLIT functions are available with compatibility Level 160.  Currently we are using a dedicated Azure SQL database (SQL Server 12.0.2000.8) with compatibility level 160, and these functions are not available.  Is there something I am missing?  I have confirmed that the database is at 160 both through the SSMS user interface and running the query directly.

SELECT compatibility_level  
FROM sys.databases WHERE name = 'xyz';

Thanks.

-JK
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2c2c7f50-c821-0a47-4855-85e2b03f1ccc
* Version Independent ID: c3f23dfe-c28e-7cd3-1038-e963d11f7647
* Content: [View or change the compatibility level of a database - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/databases/view-or-change-the-compatibility-level-of-a-database?view=azuresqldb-current)
* Content Source: [docs/relational-databases/databases/view-or-change-the-compatibility-level-of-a-database.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/databases/view-or-change-the-compatibility-level-of-a-database.md)
* Service: **sql**
* Sub-service: **supportability**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamAntonRohm** [comment]
@JFKallen -- J, thank you for your well-researched feedback.  Please consider these resources:
- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server)

@WilliamDAssafMSFT -- William, please look into this issue.

**Comment by thesqlsith** [comment]
Thank you @JFKallen for reporting this issue. 

Quick question for you. When you mentioned that you have a dedicated SQL Server, did you mean a dedicated SQL Pool (meaning a Synapse SQL Pool)? If so, the GENERATE_SERIES function is not yet available on that platform, and STRING_SPLIT without the recently added ordinal support should be there.

For Azure SQL Database, STRING_SPLIT was available under database compatibility 130, and we added the ordinal keyword support near the end of 2021 - https://learn.microsoft.com/sql/t-sql/functions/string-split-transact-sql?view=sql-server-ver16. GENERATE_SERIES - https://learn.microsoft.com/sql/t-sql/functions/generate-series-transact-sql?view=sql-server-ver16 was recently released (around November of 2022) and is also available in Azure SQL DB, however, that function is only available under database compat 160.

Would you be able to provide an error message or a few screenshots so that we may take a look at what you are seeing? Also, which version of SSMS are you using? Older versions will still allow you to use the functions, but they will not be able to be parsed correctly in the user interface and will show red "squiggly" lines underneath those function names which will look like a syntax error.

**Comment by WilliamDAssafMSFT** [comment]
Closing this issue for now. We have some doc updates in flight related to this. @JFKallen if you'd like to continue interaction on this topic, we can re-open the ticket.
