### ISSUE TITLE
SET DATEFORMAT

### ISSUE THREAD

**Issue by Mnior** [MicrosoftDocs/sql-docs#9095]
It is worth listing in detail all the combinations (there are not many of them) in which cases, when one sequence is explicitly specified, it is explicitly parsed in another.

There are also conflicting inaccuracies in the documentation regarding ISO 8601. That is. it is clearly stated that all dates in ISO 8601 format are parsed regardless of this setting, which is not always true.
For both formats (23 and 126 ) are positioned as ISO 8601, which is true, but 23 is parsed completely unpredictably for all 33 of the 34 languages.

`SET LANGUAGE English	; SELECT Convert(DateTime,'01-02-03'),Convert(DateTime,'01-02-2003'),Convert(DateTime,'2001-02-03'), date_format FROM sys.dm_exec_sessions WHERE session_id = @@SPID`

`SET LANGUAGE German	; SELECT Convert(DateTime,'01-02-03'),Convert(DateTime,'01-02-2003'),Convert(DateTime,'2001-02-03'), date_format FROM sys.dm_exec_sessions WHERE session_id = @@SPID`

`SET LANGUAGE Japanese	; SELECT Convert(DateTime,'01-02-03'),Convert(DateTime,'01-02-2003'),Convert(DateTime,'2001-02-03'), date_format FROM sys.dm_exec_sessions WHERE session_id = @@SPID`

**Comment by WilliamAntonRohm** [comment]
@Mnior -- thank you for your thorough feedback.  Are you following a particular learn.microsoft.com article?

**Comment by rwestMSFT** [comment]
I think it's this article: https://learn.microsoft.com/sql/t-sql/statements/set-dateformat-transact-sql

**Comment by WilliamAntonRohm** [comment]
@WilliamDAssafMSFT -- William, please look into this issue.

**Comment by WilliamDAssafMSFT** [comment]
This line does address the varied parsing: "[Some character string formats, for example ISO 8601, are interpreted independently of the DATEFORMAT setting.](https://learn.microsoft.com/en-us/sql/t-sql/statements/set-dateformat-transact-sql?view=sql-server-ver16#:~:text=Some%20character%20string%20formats%2C%20for%20example%20ISO%208601%2C%20are%20interpreted%20independently%20of%20the%20DATEFORMAT%20setting.)"

I am unclear though where "all dates in ISO 8601 format are parsed regardless of this setting." Help us out @Mnior, what Microsoft document are you referring to?

Might be easier for you to [create a Pull Request](https://docs.microsoft.com/sql/sql-server/sql-server-docs-contribute) and get the ball rolling on a specific change, instead of trying to describe it. By opening a pull request, you're collaborating with the author to add changes directly to the documentation. After your PR is merged, GitHub lists you as an article contributor. 

Either way, thanks for your feedback!

**Comment by rwestMSFT** [comment]
@Mnior I am closing this issue since we haven't heard from you for a while, and your concerns seem to have been addressed by my colleague. If you decide to respond, please feel free to continue the conversation below.
