### ISSUE TITLE
Ubuntu 18.04 is out of support

### ISSUE THREAD

**Issue by PwshPally** [MicrosoftDocs/sql-docs#9119]
The document says that Ubuntu 18.04 is required.  That OS is now out of support.  Will a newer version, like 22, work?

**Comment by rwestMSFT** [comment]
To which article is this question referring?

**Comment by PwshPally** [comment]
Fair question.  [Enable SQL Insights](https://learn.microsoft.com/en-us/azure/azure-sql/database/sql-insights-enable?view=azuresql#azure-virtual-machine-requirements).  In the Azure Virtual Machine Requirements section, first bullet point.

Sorry about leaving that out.

**Comment by rwestMSFT** [comment]
Thanks for your feedback, @PwshPally.

This issue is related to https://github.com/MicrosoftDocs/azure-docs/issues/110231, so I'm repeating my comments from there below.

---

Since SQL Insights is a **preview** feature, it may have "limited or restricted functionality". In this particular case, that is limited to Ubuntu 18.04 support.

As a reminder, preview features aren't meant for production use.

While this is not the answer you were asking for, that is all we can say from a Docs perspective.
