### ISSUE TITLE
Tutorial: Set up Azure Active Directory authentication for SQL Server

### ISSUE THREAD

**Issue by sommarskog** [MicrosoftDocs/sql-docs#9157]
I've read the topic https://learn.microsoft.com/en-us/sql/relational-databases/security/authentication-access/azure-ad-authentication-sql-server-setup-tutorial?view=sql-server-ver16 and I found it very useful. I have a few observations, though.

There is this passage that starts with "In the Azure portal, navigate to the Azure Key Vault instance where the certificate is stored, and select Access policies". However, access in Key Vault can also be done with Access Control (IAM), and this appears to be default and the recommended. I think the topic needs to discuss both. (I was able to set permissions from what is said in the topic, but I am not sure that I had the minimal permissions needed.)

Later there is a passage that starts "The Azure AD admin login is listed in sys.server_principals, but is not part of the sysadmin role. To grant the Azure AD admin the sysadmin role," and then it goes on to say how you should add the user to sysadmin, and with a command that is different from what is said in the previous paragraph. In any case, what I found is that the AD admin _is_ added to sysadmin, so the paragraph needs to be rewritten to reflect this, and also the Note that follows should be adapted to remove the clause "Once the Azure AD admin login is granted the sysadmin role".

(Since I also had the remark on Key-vault access, I did not want muddle waters by also making an edit to the text.)

**Comment by WilliamAntonRohm** [comment]
@sommarskog -- thank you for your detailed feedback.

@GithubMirek -- please look into this issue.

**Comment by VanMSFT** [comment]
Hi @sommarskog - Thanks for submitting this feedback.

There are many ways to manage Access Policies, and the tutorial focuses on one way. Since this is documentation for SQL, we don't want to convolute the content. There are other ways listed in Azure Key Vault documentation and we don't want to enforce recommendation in this article.

As for the Azure AD admin (now Microsoft Entra admin), we have fixed these passages, and hopefully they make more sense. Please let us know if there are any concerns.

@nofield FYI

**Comment by nofield** [comment]
Thanks for this feedback @sommarskog!

As Van mentioned, he's since updated the documentation to reflect the current behavior around sysadmin.

I think there's a good argument for including instructions for Key Vault access using IAM (if it's possible- need to confirm). There have been changes to AKV recently that require users to select either Access Policy *or* IAM initially on AKV configuration, and the recommendation is IAM:
![image](https://github.com/MicrosoftDocs/sql-docs/assets/58005768/eba46777-a0ce-4a6c-b35c-d6e927451fe6)

Key Vaults configured with IAM disallow the creation of certificates, which invalidates a lot of this content. Since these permission requirements are what SQL needs in order to access AKV, I think it makes sense for us to document both ways here (again, need to confirm with the Arc PG if IAM is even a valid option for this purpose, and which role(s) are appropriate).

**Comment by sommarskog** [comment]
It is soon six months since I played with this, but I recall I ran into exactly what you say: "There have been changes to AKV recently that require users to select either Access Policy or IAM initially on AKV configuration, and the recommendation is IAM:" (So it is not that recent. :--) I don't remember exactly, but I think I already set up my key vault for something else and picked IAM. I was able to figure out with help the docs in the shape they were at the time which permissions to set.

I think the best is to cover both, since some people may have older key vaults with Access Control. If you are only to cover one, that should be IAM. As for taking up space in the document, can you have one tab for each? I think I've seen that other topics.

**Comment by VanMSFT** [comment]
> Thanks for this feedback @sommarskog!
> 
> As Van mentioned, he's since updated the documentation to reflect the current behavior around sysadmin.
> 
> I think there's a good argument for including instructions for Key Vault access using IAM (if it's possible- need to confirm). There have been changes to AKV recently that require users to select either Access Policy _or_ IAM initially on AKV configuration, and the recommendation is IAM: ![image](https://private-user-images.githubusercontent.com/58005768/294322201-eba46777-a0ce-4a6c-b35c-d6e927451fe6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0OTAwODEsIm5iZiI6MTcwNDQ4OTc4MSwicGF0aCI6Ii81ODAwNTc2OC8yOTQzMjIyMDEtZWJhNDY3NzctYTBjZS00YTZjLWIzNWMtZDZlOTI3NDUxZmU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDIxMjMwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2Nzk4MGM0NmZiMWYzNWNiNTkzZjI3NDU3MWM3YzM1OWUzMDcyNWU2ZGQyZWZkYjQ2MzNiOWVjOGQ5YTQxMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5ITWzII99dB_5V9hc5JtxHMjMN3j3zxwBAhzYsdPnVA)
> 
> Key Vaults configured with IAM disallow the creation of certificates, which invalidates a lot of this content. Since these permission requirements are what SQL needs in order to access AKV, I think it makes sense for us to document both ways here (again, need to confirm with the Arc PG if IAM is even a valid option for this purpose, and which role(s) are appropriate).

@nofield - Thanks, Jordan! @MikeRayMSFT FYI

**Comment by rwestMSFT** [comment]
At the beginning of 2024 [we announced](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) that GitHub issues would be shut down, and this is happening at the end of April 2024.

If you would like to provide further feedback, you can use the Feedback option on the article in question. Otherwise, you are welcome to create a pull request, which will be reviewed by our team.

This issue is being tracked internally. AB#250648.
