### ISSUE TITLE
TDE with Customer Certificate is not supported in Azure SQL PASS ?

### ISSUE THREAD

**Issue by chaisen2006** [MicrosoftDocs/sql-docs#9214]
hi Article states at the top as Azure SQL PASS as applicable databases.
If I understand correctly customer certificate is not possible for Azure SQL PaaS and Managed Instance.

This is for SQL on Azure VM and on-prem SQL setups - option with customer Certificate as TDE protector.

Please clarify and confirm.

thanks

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 20953c9f-c769-7849-420a-dac77f917d4a
* Version Independent ID: dfd9ad27-844c-c3c8-58a3-5d4a0c92fbba
* Content: [Transparent data encryption (TDE) - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/security/encryption/transparent-data-encryption?view=sql-server-ver16)
* Content Source: [docs/relational-databases/security/encryption/transparent-data-encryption.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/security/encryption/transparent-data-encryption.md)
* Service: **sql**
* Sub-service: **security**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by TimShererWithAquent** [comment]
@chaisen2006  -- thank you for your feedback. This seems to be a product question, rather than a documentation issue. Please consider these resources:

- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server)

I'm going to keep this issue open as an enhancement request, in case there's clarification needed for the article.

**Comment by rwestMSFT** [comment]
Both Azure SQL Database and Azure SQL Managed Instance are supported, as noted in the "Applies to" section.

**Comment by chaisen2006** [comment]
@rwestMSFT - Thanks for getting back. If I read it correctly in the article - 
https://learn.microsoft.com/en-us/azure/azure-sql/database/transparent-data-encryption-tde-overview?view=azuresql-mi&tabs=azure-portal 

 It states that TDE protector can be a service managed certificate and NOT a customer managed certificate. So I was under the impression that Customer managed certificate as TDE protector is only applicable for SQL on prem and SQL on Azure VM set ups.

But from your inputs you mean to suggest that Customer Managed certificate is supported as TDE protector in Azure SQL PASS as well ? Do I understand you correctly. thanks!

**Comment by rwestMSFT** [comment]
@chaisen2006 TDE on Azure SQL Database and Azure SQL Managed Instance is supported for customer certificates (also known as BYOK, or "bring your own key), as long as you use Azure Key Vault. To get this to work, you need to transfer your certificate to a key vault, and allow permission from Azure SQL to access that vault.

This is outlined here: https://learn.microsoft.com/en-us/azure/azure-sql/database/transparent-data-encryption-tde-overview#customer-managed-transparent-data-encryption---bring-your-own-key

> The TDE Protector can be [generated by the key vault or transferred to the key vault](https://learn.microsoft.com/en-us/azure/key-vault/keys/hsm-protected-keys) from an on-premises hardware security module (HSM) device. SQL Database, SQL Managed Instance, and Azure Synapse need to be granted permissions to the customer-owned key vault to decrypt and encrypt the DEK.

*Note:* I think you meant to write "PaaS", not "PASS".

**Comment by chaisen2006** [comment]
@rwestMSFT that is correct but Certificates and Keys are 2 different ways TDE protector can be used. Your explanation is w.r.t to Keys stored in Azure Key Vault but I am looking at Customer custom certificate. ( not azure Managed Service Certificate )

Customer Custom in house certificate SQL commands I see in the above page ( where I posted this feedback ) is possible in SQL on VM setup and not PaaS as per my understanding?

Thanks for taking time out!

**Comment by rwestMSFT** [comment]
Clearly I don't understand your question, so I'm going to summarize what I think you're asking.

The TDE protector, also known as the master key, is protected by one of the following options:

- a certificate in the `master` database, itself protected by a server certificate
- a key in an EKM (or Azure Key Vault)

You get to pick which one you want, bearing in mind that Azure SQL handles some of this for you, because you don't have access to the instance level on SQL Database. By default, the DEK is protected by a built-in server certificate, so you don't have to do anything to [set up TDE](https://learn.microsoft.com/en-us/azure/azure-sql/database/transparent-data-encryption-tde-overview?view=azuresql-mi&tabs=azure-portal#manage-transparent-data-encryption).

The Transact-SQL code in the section [Enable TDE](https://learn.microsoft.com/en-us/sql/relational-databases/security/encryption/transparent-data-encryption?view=sql-server-ver16#enable-tde) applies only to SQL Server (on-premises and in VMs), which it does state.

> **Applies to:** SQL Server.

Does this answer your question? Is the documentation clear about what is needed?

**Comment by chaisen2006** [comment]
@rwestMSFT  - yes that is correct. In the [Enable TDE] article at the top of the page it states to SQL PAAS as well so I wanted to get is clarified. thank you

**Comment by rwestMSFT** [comment]
Then we're clear that the "Enable TDE" section in question only applies to SQL Server.
