### ISSUE TITLE
What is the behavior of Azure Sql MI/DB when it comes to implicit use of indexed views?

### ISSUE THREAD

**Issue by AndrewMorris-scsu** [MicrosoftDocs/sql-docs#9253]
Please clarify the behavior of Azure SQL database and Azure SQL Managed in the examples below. Does Azure SQL DB/MI always follow the behavior of enterprise when it comes to implicitly leveraging indexed views? Are there caveats on the different models (Basic DTU vs. Standard vCore vs. BC vs. Premium)?

Specifically, do Azure sql db/mi users need to use the "WITH (NOEXPAND)" hint, or will it implicitly use this like the enterprise edition? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0a452207-5ac2-1a41-c5b1-3baf085a79b4
* Version Independent ID: a590e66c-ed9f-4d80-1511-1864128d2e8e
* Content: [Create Indexed Views - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/views/create-indexed-views?view=sql-server-ver16)
* Content Source: [docs/relational-databases/views/create-indexed-views.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/views/create-indexed-views.md)
* Service: **sql**
* Sub-service: **table-view-index**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by WilliamDAssafMSFT** [comment]
Great question @AndrewMorris-scsu, we can bring clarity to this in more places. This answer is documented elsewhere. Prior to SQL Server 2016 (13.x) Service Pack 1, [automatic use of an indexed view by the query optimizer is supported only in specific editions of SQL Server](https://learn.microsoft.com/sql/t-sql/queries/hints-transact-sql-table?view=sql-server-ver16#using-noexpand). Since, all editions support this. 

[Azure SQL Database supports automatic use of indexed views without specifying the NOEXPAND hint.](https://learn.microsoft.com/en-us/sql/t-sql/queries/hints-transact-sql-table#using-noexpand)

Azure SQL Managed Instance runs the latest version of SQL Server. Azure SQL Managed Instance has near 100% compatibility with the latest Enterprise Edition SQL Server database engine.

**Comment by AndrewMorris-scsu** [comment]
Thank you for clarifying!!!
