### ISSUE TITLE
?? 

### ISSUE THREAD

**Issue by palestalo** [MicrosoftDocs/sql-docs#9298]
--
Important
In addition to enabling the common criteria compliance enabled option, you also must download and run a script that finishes configuring SQL Server to comply with Common Criteria Evaluation Assurance Level 4+ (EAL4+). You can download this script from the [Microsoft SQL Server Common Criteria](https://go.microsoft.com/fwlink/?LinkId=616319) site.
--

Cant find any script , link opens PDF document.
Where is script ? Cant enable wo. running script ?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 48909bd6-c8bf-85ec-c32c-5a5068fc841f
* Version Independent ID: a13c699f-ba22-272f-7115-26dadf46c5cb
* Content: [Common Criteria Compliance Enabled Configuration - SQL Server](https://learn.microsoft.com/en-us/sql/database-engine/configure-windows/common-criteria-compliance-enabled-server-configuration-option?view=sql-server-ver16)
* Content Source: [docs/database-engine/configure-windows/common-criteria-compliance-enabled-server-configuration-option.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/database-engine/configure-windows/common-criteria-compliance-enabled-server-configuration-option.md)
* Service: **sql**
* Sub-service: **configuration**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**
*

**Comment by rwestMSFT** [comment]
The PDF you downloaded contains links to the appropriate script, which depends on the version of SQL Server in question.

For example, this extract from the document references **Downloads for Microsoft SQL Server 2019 CU13 @ EAL4** on page 2:

> Please perform the following steps in order to ensure the integrity of the downloads from this website:
> - The following steps assume that the “CertUtil” tool is available for calculating the SHA-256 hash sum (which should be pre-installed on Microsoft Windows). Alternatively, any other tool capable of calculating the SHA256 sum of a file can be used instead.
> - Download the “CC Guidance Addendum”, open a command prompt and change to the download directory.
> - Run “CertUtil -hashfile SQL19_EAL4-W_AGD_ADD_1.3.pdf SHA256” on the command prompt and verify that the SHA-256 output is identical to 893CDAF7310DAE93836FC2B91156E9FABE73682ED97B7CD2695B04F3DA1018A4

There follows a series of links for you to follow, verifying each file as required. The final file in the list is a Transact-SQL script, which is the file you're seeking.

> - Security Target
> - CC Guidance Addendum
> - SQL Server Technical Documentation ➔ Integrity Check Validation Data
> - Permissions Poster
> - Install Triggers Script

You must use the PDF to get there, because this provides a valid "chain of evidence" to download the correct file, or in the words of the PDF: "to ensure the integrity of the downloads".
