### ISSUE TITLE
TOC links seem to be crossed

### ISSUE THREAD

**Issue by DWalker07** [MicrosoftDocs/sql-docs#9322]
[Enter feedback here]
If you navigate to https://learn.microsoft.com/en-us/sql/relational-databases/in-memory-oltp/a-guide-to-query-processing-for-memory-optimized-tables?view=sql-server-ver16, the highlighted link in the left-side table of contents says "Natively compiled" (under "Natively compiled").  That's the wrong TOC item for this topic.

Then, in the TOC on the left, if you click just below Natively Compiled, on the topic Performance of In-Memory, and then click on the first subtopic "Performance of in-memory", the topic you get is titled "Natively Compiled Stored Procedures and Execution Set Options".  

It looks like there are some table of contents labels that are slightly messed up here.  Thanks.

David Walker

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 33e49268-9863-3be2-218c-c472fe6f3711
* Version Independent ID: b104aa79-5b21-cd77-f24e-71a9fd93cf36
* Content: [Query processing for memory-optimized tables - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/in-memory-oltp/a-guide-to-query-processing-for-memory-optimized-tables?view=sql-server-ver16)
* Content Source: [docs/relational-databases/in-memory-oltp/a-guide-to-query-processing-for-memory-optimized-tables.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/in-memory-oltp/a-guide-to-query-processing-for-memory-optimized-tables.md)
* Service: **sql**
* Sub-service: **in-memory-oltp**
* GitHub Login: @WilliamDAssafMSFT
* Microsoft Alias: **wiassaf**

**Comment by DWalker07** [comment]
Also, under "Performance of In-Memory" in the TOC, if you click on "In-Memory on Azure SQL Database", the TOC switches to a different place (and the TOC label then says "In-memory OLTP").  Is that intended?  The TOC is now in a completely different place, and other than using the Back button, I can't find the content I was browsing through.

**Comment by WilliamAntonRohm** [comment]
@DWalker07 -- thank you for your feedback.  I am looking into this issue.

**Comment by WilliamDAssafMSFT** [comment]
@DWalker07 thanks for pointing this out, nice catch! A doc update is in flight to fix the swapped TOC entries. Thanks for taking the time to point this out! The whole community will benefit from this doc improvement.

re: the TOC switch, this is intentional! Notice the version switcher in the dropdown. The article "Optimize performance by using in-memory technologies in Azure SQL Database and Azure SQL Managed Instance" is in the context of the Azure SQL products, not SQL Server products. Each product has articles that do and do not apply to it. The content of a TOC varies by product. For more information, see [our navigation guide](https://learn.microsoft.com/sql/sql-server/sql-docs-navigation-guide#version-filter).

**Comment by DWalker07** [comment]
Thanks for that info.
