### ISSUE TITLE
SQLSpecialColumns buffer_length

### ISSUE THREAD

**Issue by therealjbschueler** [MicrosoftDocs/sql-docs#9328]
Why is BUFFER_LENGTH described differently here than it is for SQLColumns?

In particular,  it states "This value is the same as the COLUMN_SIZE column for character or binary data" which disagrees with SQLColumns which states "This value might differ from COLUMN_SIZE column for character data".  The SQLColumns version makes sense. 

-Jack

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 813f2ecd-74cf-c78d-789d-d5969b8a92b6
* Version Independent ID: b623b998-df96-3b18-fc60-691e23455b73
* Content: [SQLSpecialColumns Function - ODBC API Reference](https://learn.microsoft.com/en-us/sql/odbc/reference/syntax/sqlspecialcolumns-function?view=sql-server-ver16)
* Content Source: [docs/odbc/reference/syntax/sqlspecialcolumns-function.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/odbc/reference/syntax/sqlspecialcolumns-function.md)
* Service: **sql**
* Sub-service: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by WilliamAntonRohm** [comment]
@therealjbschueler -- Jack, thank you for your clear feedback.

@David-Engel -- David, please look into this issue.

**Comment by David-Engel** [comment]
> Content: [SQLSpecialColumns Function - ODBC API Reference](https://learn.microsoft.com/en-us/sql/odbc/reference/syntax/sqlspecialcolumns-function?view=sql-server-ver16)

> Why is BUFFER_LENGTH described differently here than it is for SQLColumns?
> 
> In particular, it states "This value is the same as the COLUMN_SIZE column for character or binary data" which disagrees with SQLColumns which states "This value might differ from COLUMN_SIZE column for character data". The SQLColumns version makes sense.

@v-chojas Can you answer the above question?

**Comment by v-chojas** [comment]
They are different functions, so it doesn't necessarily have to be the same ,but as the continuation of the description says, the details are in the linked document:
https://learn.microsoft.com/en-us/sql/odbc/reference/appendixes/column-size-decimal-digits-transfer-octet-length-and-display-size?view=sql-server-ver16
...which then leads to these:
https://learn.microsoft.com/en-us/sql/odbc/reference/appendixes/column-size?view=sql-server-ver16
https://learn.microsoft.com/en-us/sql/odbc/reference/appendixes/transfer-octet-length?view=sql-server-ver16

It is possible that due to character encoding and the like, COLUMN_SIZE and BUFFER_LENGTH may be different, but perhaps when the documentation was originally written, this wasn't the case, and later only SQLColumns doc was changed.

**Comment by rwestMSFT** [comment]
@v-chojas Do you think this requires a note in the main article to address this incongruity?

**Comment by v-chojas** [comment]
@rwestMSFT it may be better to change the SQLSpecialColumns doc to also say "This value might differ from COLUMN_SIZE column for character data" like the SQLColumns one.

**Comment by rwestMSFT** [comment]
@v-chojas @David-Engel Thanks, I'll stage an internal PR.

@therealjbschueler Thanks for your feedback.

**Comment by therealjbschueler** [comment]
Thank you for addressing this issue.
