### ISSUE TITLE
Upgrading from pre-2012 SQL server

### ISSUE THREAD

**Issue by Tarjei-stavanger** [MicrosoftDocs/sql-docs#9400]
It would be nice if there was some words on the upgrade path from pre-2012 SQL servers to something more modern.

E.g.  We have a SQL server 2008 which I'm about to upgrade to at least something which can create files that can be read by our more modern SQL servers. Possibly a SQL 2022 server.

I seem to remember that the OS have to be upgraded to 2012 R2 before upgrading the SQL server to SQL server 2012.

It would be nice to be certain about the upgrade path.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 89223ae2-d21a-20df-90f1-75d6a7ef2600
* Version Independent ID: 89223ae2-d21a-20df-90f1-75d6a7ef2600
* Content: [End of support options - SQL Server](https://learn.microsoft.com/en-us/sql/sql-server/end-of-support/sql-server-end-of-support-overview?view=sql-server-ver16)
* Content Source: [docs/sql-server/end-of-support/sql-server-end-of-support-overview.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/sql-server/end-of-support/sql-server-end-of-support-overview.md)
* Service: **sql**
* Sub-service: **install**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by WilliamAntonRohm** [comment]
@Tarjei-stavanger -- Tarjei, thank you for your feedback.  SQL Server 2008 is no longer supported; please see:
- [Announcing new options for SQL Server 2008 and Windows Server 2008 End of Support](https://azure.microsoft.com/en-us/blog/announcing-new-options-for-sql-server-2008-and-windows-server-2008-end-of-support/)

Also, consider these resources:
- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server)

cc @rwestMSFT for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by Tarjei-stavanger** [comment]
That is unhelpful. I already know that the old versions are not supported.

What is needed is information about how to get away from the unsupported MS SQL servers and onto a supported version.

**Comment by rwestMSFT** [comment]
Hi @Tarjei-stavanger, whether you think it helpful or not, our content only covers supported content.

That being said, we have lots of content that discusses options for migrating away from SQL Server 2005 and later versions. Specifically, I can think of this section, which discusses migrating to a new SQL Server instance (the recommended method): https://learn.microsoft.com/en-us/sql/database-engine/install-windows/supported-version-and-edition-upgrades-2022?view=sql-server-ver16#migrate-to-sql-server-2022.

Since SQL Server 2016, you can attach or restore a SQL Server database from 2005 and later versions and it will just work. The only provision is that 2005 database compatibility level will be upgraded to 2008 (100).

Upgrading an existing instance of SQL Server from before SQL Server 2016 is not recommended, for many reasons, but for migrating, it's quite easy, and you'll be able to keep your database in the old compatibility level as long as you need it.

**Comment by WilliamAntonRohm** [comment]
@Tarjei-stavanger -- Tarjei, thank you for your follow-up.

@rwestMSFT -- Randolph, thank you for those clarifications.
