### ISSUE TITLE
Documentation of FOR JSON AUTO does not match actual query results

### ISSUE THREAD

**Issue by ot-jim-elphick** [MicrosoftDocs/sql-docs#9492]
Page title states:   Format Query Results as JSON
Examples show neatly formatted json using the FOR JSON AUTO.  

Actual results using SSMS 18.12.1 and SQL Server 2022 do not match the documentation

FOR JSON AUTO returns correct json syntax.  But the "format" does not include the line feeds and tabs shown in the documentation.  

Actual query results for FOR JSON AUTO are a single string of syntactically correct json.  No carriage returns.  No tabs.

Example:
[{"Id":1,"v1":1,"v2":"un      ","flag":false},{"Id":2,"v1":2,"v2":"deux    ","flag":false},{"Id":3,"v1":3,"v2":"trois   ","flag":false}]

Is there an internal flag in SSMS or other method of returning formatted json that matches documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ffb5c17b-c567-303f-00b8-0c8a0ad15fb5
* Version Independent ID: a4ccc766-4a61-5b7a-e5dd-692e3cebb503
* Content: [Format Query Results as JSON with FOR JSON - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/json/format-query-results-as-json-with-for-json-sql-server?view=sql-server-ver16)
* Content Source: [docs/relational-databases/json/format-query-results-as-json-with-for-json-sql-server.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/json/format-query-results-as-json-with-for-json-sql-server.md)
* Service: **sql**
* GitHub Login: @jovanpop-msft
* Microsoft Alias: **jovanpop**

**Comment by WilliamAntonRohm** [comment]
@ot-jim-elphick -- Jim, thank you for your feedback.  Please consider these resources:
- [SQL Server on Microsoft Q&A](https://docs.microsoft.com/answers/products/sql-server)
- [DBA Stack Exchange](https://dba.stackexchange.com/questions/tagged/sql-server)
- [Stack Overflow](https://stackoverflow.com/questions/tagged/sql-server)

@jovanpop-msft -- Jovan, please look into this issue.

**Comment by jovanpop-msft** [comment]
@ot-jim-elphick thanks for the feedback.

This page doesn't show the results for SSMS. It shows a "logical structure" of the results. It is formatted for readability purposes, but it is specific for SSMS. 
When you click on the cell, SSMS will show the JSON in a new window, but it is not pretty formatted. ADS also show concatenated results, but when you client on JSON and show it in new window it shows formatted results.

<img width="553" alt="image" src="https://github.com/MicrosoftDocs/sql-docs/assets/20593304/ff5d4e29-b72d-4dd1-a419-8820f778d29f">

Every client tool might handle presentation differently and this changes independently of FOR JSON clause.

@WilliamAntonRohm - do we have other pages that describe how client tools present results? I would not add this to this page because the presentation will be changed depending on the tool versions.

**Comment by jovanpop-msft** [comment]
@ot-jim-elphick thanks for the feedback.

This page doesn't show the results for SSMS. It shows a "logical structure" of the results. It is formatted for readability purposes, but it is specific for SSMS. 
When you click on the cell, SSMS will show the JSON in a new window, but it is not pretty formatted. ADS also show concatenated results, but when you client on JSON and show it in new window it shows formatted results.

<img width="553" alt="image" src="https://github.com/MicrosoftDocs/sql-docs/assets/20593304/ff5d4e29-b72d-4dd1-a419-8820f778d29f">

Every client tool might handle presentation differently and this changes independently of FOR JSON clause.

@WilliamAntonRohm - do we have other pages that describe how client tools present results? I would not add this to this page because presentation will be changed depending on the tool versions.

**Comment by rwestMSFT** [comment]
We have staged an update to this article that makes it clearer in the NOTE at the top of the article that SSMS outputs JSON as an unformatted string.

> **Note**  
> Azure Data Studio is the recommended query editor for JSON queries because it auto-formats the JSON results, as shown in this article. SQL Server Management Studio displays an unformatted string.

When that internal PR is merged, which will take a few days because of the holiday season, this issue will automatically close.

Thank you for your feedback, @ot-jim-elphick.
