### ISSUE TITLE
SSMS: Does the support table on this page need updated?

### ISSUE THREAD

**Issue by Mcateer-ctrl** [MicrosoftDocs/sql-docs#9544]
I see version 19.1 is shown as 'Full support' on the support table. As SSMS is under [Modern Lifecycle Policy announcement](https://learn.microsoft.com/en-us/lifecycle/announcements/modern-policy) and 19.2 is out, does this table need updated? to show 19.2 in 'Full support' and 19.1 shown as 'Upgrade'

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0343b0b9-368c-ff89-f707-47da7d8a7c01
* Version Independent ID: d215b9e8-aab5-81e5-ba71-796d6c97f441
* Content: [SQL Server Management Studio (SSMS) support policy - SQL Server Management Studio (SSMS)](https://learn.microsoft.com/en-us/sql/ssms/support-policy?view=sql-server-ver16)
* Content Source: [docs/ssms/support-policy.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/support-policy.md)
* Service: **sql**
* Sub-service: **ssms**
* GitHub Login: @erinstellato-ms
* Microsoft Alias: **erinstellato**

**Comment by erinstellato-ms** [comment]
@Mcateer-ctrl Thanks for the catch!  I'll get that page updated in the next day or two to list 19.2 as Full support.

**Comment by erinstellato-ms** [comment]
#please-close

**Comment by Mcateer-ctrl** [comment]
Hi, from looking at this table update, does this mean 19.1 is still supported?

**Comment by erinstellato-ms** [comment]
@Mcateer-ctrl I'm slightly confused.  Initially you asked if the table needed to be updated to reflect the 19.2 release, which it did, and it's been updated.  Now you're asking if 19.1 is still supported?  As noted in the article, "The latest current branch version is always in the Full support servicing phase. This support statement means that if you encounter a code defect that warrants a critical update, you must have the latest current branch version installed in order to receive a fix."

So, you can use 19.1, but if you an encounter an issue, the recommendation is to upgrade to 19.2.  If you find an issue in 19.2, we will work to fix it in the next release, but we would not "backport" a fix to 19.2.

Hope that clarifies things.

**Comment by Mcateer-ctrl** [comment]
Hi, I was questioning if 19.1 was still supported as it wasn't added to the table on the SSMS support policy page, stating 'upgrade'. Was slightly confused.
