### ISSUE TITLE
Where is the registered server list stored? I keep saving "trust server certificate" but it is never saved and always fails connection due to the certificate.

### ISSUE THREAD

**Issue by ben9tamu** [MicrosoftDocs/sql-docs#9595]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 24fc57a8-b76c-7c1c-87d4-e9d8364572cc
* Version Independent ID: 12c95704-ea0f-17ce-b6b1-5feb3a7b04f1
* Content: [View Registered Servers - SQL Server Management Studio (SSMS)](https://learn.microsoft.com/en-us/sql/ssms/register-servers/view-registered-servers-in-sql-server-management-studio?view=sql-server-ver16)
* Content Source: [docs/ssms/register-servers/view-registered-servers-in-sql-server-management-studio.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/ssms/register-servers/view-registered-servers-in-sql-server-management-studio.md)
* Service: **sql**
* Sub-service: **ssms**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by ben9tamu** [comment]
SQL Server Management Studio	19.2.56.2
Operating System	10.0.19045
Microsoft .NET Framework	4.0.30319.42000

**Comment by erinstellato-ms** [comment]
Hi @ben9tamu - This is a known limitation with registered servers and there's a feedback item already that folks can upvote (
[Get SSMS to save the Registered Servers - Trust Server Certificate setting](https://feedback.azure.com/d365community/idea/329a3193-0a98-ee11-a81c-0022484c92b1)
).  When using Central Management Servers (CMS), that information is stored in msdb.  Registered server information (not CMS) is stored locally.  We are planning to address this for registered servers in SSMS 20 with the new connection dialog, but note that changing behavior in CMS is separate, and requires engine work because of where the information is stored.

**Comment by rwestMSFT** [comment]
Thanks, @erinstellato-ms.

I'm closing this issue as resolved.

**Comment by ben9tamu** [comment]
Hi I am using a central management server, but the information is still not saved.

>> When using Central Management Servers (CMS), that information is stored in msdb.
Can you tell me where that information is saved in msdb?

Thanks,
Ben Kim | Database Administrator III
Technology Services
Texas A&M University
3602 TAMU | College Station, TX 77843-3602
***@***.******@***.***>
------------------------------------------------------
IT.tamu.edu

**Comment by erinstellato-ms** [comment]
@ben9tamu You'll find information in dbo.sysmanagement_shared_registered_servers and msdb.dbo.sysmanagement_shared_server_groups.  Depending on permissions for your login, you may not be able to view information in those tables.

**Comment by ben9tamu** [comment]
thanks

Ben Kim | Database Administrator III
Technology Services
Texas A&M University
3602 TAMU | College Station, TX 77843-3602
***@***.******@***.***>
------------------------------------------------------
IT.tamu.edu
