### ISSUE TITLE
pyodbc connection to database cannot use UID and PWD, results in error

### ISSUE THREAD

**Issue by parHaddox** [MicrosoftDocs/sql-docs#9622]
Azure Functions App using Python 3.11 (linux) V2, extension bundle v4. Connecting to serverless Azure SQL database using UID and PWD results in the error: 

[fa005] [microsoft][odbc driver 18 for sql server]cannot use access token with any of the following options: authentication, integrated security, user, password. (0) (sqldriverconnect)

To mitigate the issue, you must omit UID and PWD in the connection string as is suggested in the pyodbc documentation here: https://github.com/mkleehammer/pyodbc/wiki/Connecting-to-SQL-Server-from-Linux#connecting-to-servers-with-access-tokens

This required me to register an app, create a secret, add the secrets to my app settings, logging into my database with my admin Entra ID, creating a login in with SQL and assigning it db_owner of my database. I believe these additional steps would be helpful to those learning from this walkthrough.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3b978274-097f-4726-c612-86103c6e13da
* Version Independent ID: 8d6410fe-9a7d-78d0-a034-83c3836907bb
* Content: [Step 3 - Connecting to SQL using pyodbc - Python driver for SQL Server](https://learn.microsoft.com/en-us/sql/connect/python/pyodbc/step-3-proof-of-concept-connecting-to-sql-using-pyodbc?view=sql-server-ver16)
* Content Source: [docs/connect/python/pyodbc/step-3-proof-of-concept-connecting-to-sql-using-pyodbc.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/python/pyodbc/step-3-proof-of-concept-connecting-to-sql-using-pyodbc.md)
* Service: **sql**
* Sub-service: **connectivity**
* GitHub Login: @David-Engel
* Microsoft Alias: **v-davidengel**

**Comment by David-Engel** [comment]
The doc example uses SQL authentication in the sample code. The only way you would get that error is if you are passing an access token as described in [that pyODBC wiki page](https://github.com/mkleehammer/pyodbc/wiki/Connecting-to-SQL-Server-from-Linux#connecting-to-servers-with-access-tokens). Since SQL auth is being used in the example, access token acquisition and the associated prerequisites that you described are not part of this walkthrough. Those details are well documented [elsewhere](https://learn.microsoft.com/en-us/azure/azure-monitor/logs/api/register-app-for-token?tabs=portal).

Regards,
David

**Comment by rwestMSFT** [comment]
Thank you for your feedback, @David-Engel.

I am closing this issue as resolved.

**Comment by parHaddox** [comment]
OK, that makes sense. I did have the application settings with tenant id,
client ID and secret in the application settings from using sql_input and
sql_output from azure.functions. I will prove it out on my side by removing
those to verify that's all it was on my side. I appreciate your feedback!

-Chris
