### ISSUE TITLE
Database Mirroring and Replication (SQL Server) Missing Details

### ISSUE THREAD

**Issue by kenjmartinii** [MicrosoftDocs/sql-docs#9625]
Affected docs:

https://learn.microsoft.com/en-us/sql/database-engine/database-mirroring/database-mirroring-and-replication-sql-server?view=sql-server-ver16

Link to affected line:

https://github.com/MicrosoftDocs/sql-docs/blob/4512c328751bfc9f09c6c8b713df07b2754704d6/docs/database-engine/database-mirroring/database-mirroring-and-replication-sql-server.md?plain=1#L18

The SQL Server documentation for combining Database Mirroring with Replication states the following within the second paragraph. Emphasis on the last part about subscription databases by me:

> Replication failover to a mirror is fully supported for publication databases, **with limited support for subscription databases.**

While the documentation states that subscription databases have "limited support" for Mirroring & Replication, it doesn't elaborate further.

We're in luck here since there is a whitepaper originally published in 2008 on this exact topic which _does_ go into much greater detail about what "limited support" truly means for subscription databases when Database Mirroring is in play.

https://download.microsoft.com/download/d/9/4/d948f981-926e-40fa-a026-5bfcf076d9b9/replicationanddbm.docx

It would be beneficial to take the detailed info related to subscription databases from this whitepaper, specifically section 'Mirroring the Subscription Database' starting on page 14, and incorporate portions of that into the main SQL Server docs for the same topic.

**Comment by rwestMSFT** [comment]
@kenjmartinii Thank you for your feedback. Since database mirroring is no longer under active development, and was replaced with availability groups several versions ago, we aren't going to invest any time into the documentation for database mirroring. The whitepaper was written for SQL Server 2008 R2, which was released 14 years ago, and the technology landscape has changed dramatically in that time.

I trust you understand this decision.
