### ISSUE TITLE
Create Index statement missing from Create Index page

### ISSUE THREAD

**Issue by davimack** [MicrosoftDocs/sql-docs#9632]
Where's the bit where you create an index?  You tell us how to alter an index, but there's no create in there, I don't believe.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4f616e6e-0d3b-6bc8-00e6-29fae2b8c76e
* Version Independent ID: 44a3d3de-b042-fe8c-fd1c-105440bc1e73
* Content: [Specify Fill Factor for an Index - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/indexes/specify-fill-factor-for-an-index?view=sql-server-ver16)
* Content Source: [docs/relational-databases/indexes/specify-fill-factor-for-an-index.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/indexes/specify-fill-factor-for-an-index.md)
* Service: **sql**
* Sub-service: **table-view-index**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by WilliamAntonRohm** [comment]
@davimack -- David, thank you for your feedback.  The article referenced in this issue is [Specify Fill Factor for an Index - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/indexes/specify-fill-factor-for-an-index?view=sql-server-ver16).

See [Create a clustered index](https://learn.microsoft.com/en-us/sql/relational-databases/indexes/create-clustered-indexes?view=sql-server-ver16) and the subsequent articles.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
