### ISSUE TITLE
Wrong description in the table's "Qualifying Rows"

### ISSUE THREAD

**Issue by JParkACR** [MicrosoftDocs/sql-docs#9662]
[Enter feedback here]

In the table, the "Qualifying Rows" descriptions are wrong.
Please correct them.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2f9c244b-870b-737f-6f6d-db9675179427
* Version Independent ID: 3dde09ff-88b5-f6f3-1120-3bf8a90a395e
* Content: [Temporal Tables - SQL Server](https://learn.microsoft.com/en-us/sql/relational-databases/tables/temporal-tables?view=sql-server-2016)
* Content Source: [docs/relational-databases/tables/temporal-tables.md](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/relational-databases/tables/temporal-tables.md)
* Service: **sql**
* Sub-service: **table-view-index**
* GitHub Login: @rwestMSFT
* Microsoft Alias: **randolphwest**

**Comment by WilliamAntonRohm** [comment]
@JParkACR -- Jay, thank you for catching these.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
@JParkACR -- Jay, the descriptions are correct as written.

**Comment by rwestMSFT** [comment]
@JParkACR You are incorrect in your assumption.

Let's take a look at a table containing a row with the following information:

- `ValidFrom`: 2024-02-02 10:49:23 AM
- `ValidTo`: 9999-12-31 11:59:59 PM

Let's say I want to see the data for a specific point in time, so we'll set `date_value` to some point in the future, or `2024-02-12 11:55:03 AM`.

If I run a `SELECT ... AS AT 2024-02-12 11:55:03 AM`, the `AS AT` requires that all rows that are valid at that point in time are returned. In other words, return all rows where `date_value` is between `ValidFrom` and `ValidTo`. Therefore, the `ValidFrom` column is `<= date_value`, and the `ValidTo` column is `> date_value`.

Using your logic, my row will never be returned, because you're ignoring all rows that have a `ValidFrom` time in the past.

**Comment by rwestMSFT** [comment]
AS AT is a point in time. It's not relevant whether it's in the future or the past in terms of the date you supply. The AS AT feature is asking for all rows that are valid at that specific point in time you provide. That means it must include all rows where the ValidFrom was before or the same as (<=) that point in time, and the ValidTo is after (>) that point in time.

**Comment by rwestMSFT** [comment]
It's my mistake, I meant AS OF. But my point remains.
